Repository input-output-hk/daedalus, pull requests merged in 2018-06, with the labels that each got.

#948 [DDW-292] use correct daedalus version in bug requests
  CHANGELOG.md
  source/renderer/app/api/ada/sendAdaBugReport.js
  source/renderer/app/api/etc/sendEtcBugReport.js
Labels: bug

#949 [DDW-283] properly wait for node update
  CHANGELOG.md
  source/renderer/app/stores/ada/NodeUpdateStore.js
Labels: bug

#956 [DDW-299] upgrade webpack-stream package to fix crashes in dev mode
  package-lock.json
  package.json
  yarn.lock
Labels: chore

#958 [DDW-300] Increase wallets limit to 50
  CHANGELOG.md
  source/renderer/app/api/ada/getAdaWallets.js
  source/renderer/app/components/wallet/WalletAdd.js
  source/renderer/app/components/wallet/WalletAdd.scss
  source/renderer/app/config/numbersConfig.js
  source/renderer/app/containers/wallet/WalletAddPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/ada/AdaWalletsStore.js
Labels: bug, release-0.10.1

#959 [DEVOPS-796] fix cp interactive in nix scripts
  CHANGELOG.md
  installers/nix/linux.nix
  yarn2nix.nix
Labels: bug, release-0.10.1

#963 [DEVOPS-888] set a logs prefix for launcher
  CHANGELOG.md
  installers/dhall/launcher.dhall
Labels: bug, release-0.10.1

#953 [DEVOPS-872] disable allow skip files and adds a launcher lock file
  CHANGELOG.md
  cardano-sl-src.json
  installers/WindowsInstaller.hs
  installers/dhall/linux64.dhall
  installers/dhall/macos64.dhall
  installers/dhall/os.type
  installers/dhall/win64.dhall
Labels: bug, release-0.10.1

#931 [DEVOPS-846] shellcheck compliance of all scripts
  .gitignore
  default.nix
  installers/build-certificates-unix.sh
  scripts/build-installer-nix.sh
  scripts/build-installer-unix.sh
  scripts/nix-shell.sh
  tests/shellcheck.nix
Labels: chore

#966 [DDW-309] Limit maximum number of wallets to 20
  CHANGELOG.md
  source/renderer/app/api/ada/getAdaWallets.js
  source/renderer/app/config/numbersConfig.js
Labels: bug, release-0.10.1

#968 Cardano 1.2.1 release bump
  cardano-sl-src.json
Labels: release-0.10.1

#969 [DEVOPS-900] Bump version to 0.10.1-cardano-sl-1.2.1
  .buildkite/pipeline.yml
  appveyor.yml
  installers/WindowsInstaller.hs
  release.nix
  scripts/build-installer-unix.sh
  scripts/build-installer-win64.bat
Labels: release-0.10.1

#957 [DDW-286] Create hide show used addresses acceptance test
  CHANGELOG.md
  features/hide-show-used-addresses.feature
  features/step_definitions/receive-steps.js
  features/support/helpers/shared-helpers.js
Labels: chore

#965 [DDW-303] refactor about window to modal dialog
  CHANGELOG.md
  source/common/ipc-api/open-about-dialog.js
  source/main/index.js
  source/main/windows/about.js
  source/renderer/app/About.js
  source/renderer/app/App.js
  source/renderer/app/actions/app-actions.js
  source/renderer/app/actions/index.js
  source/renderer/app/components/static/About.js
  source/renderer/app/containers/static/AboutDialog.js
  source/renderer/app/containers/static/AboutDialog.scss
  source/renderer/app/containers/static/AboutPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/index.js
  source/renderer/app/stores/AppStore.js
  source/renderer/app/themes/daedalus/dark-blue.js
Labels: bug

#972 [DDW-285] Removes redemption from the 'app bar' menu and add it to sy…
  CHANGELOG.md
  features/navigate-sidebar-categories.feature
  features/step_definitions/settings-steps.js
  features/step_definitions/wallets-steps.js
  features/support/helpers/shared-helpers.js
  source/common/ipc-api/go-to-ada-redemption-screen.js
  source/main/index.js
  source/main/menus/osx.js
  source/main/menus/win-linux.js
  source/renderer/app/config/ada/sidebarConfig.js
  source/renderer/app/stores/AppStore.js
  source/renderer/app/stores/SidebarStore.js
Labels: feature, release-0.11.0

#973 [DDW-317] Font display improvements
  CHANGELOG.md
  source/renderer/app/components/wallet/backup-recovery/WalletRecoveryPhraseMnemonic.scss
  source/renderer/app/components/wallet/paper-wallet-certificate/SecuringPasswordDialog.scss
  source/renderer/app/components/widgets/Dialog.scss
  source/renderer/app/themes/index.global.scss
Labels: chore, release-0.11.0

#954 Release/0.10.1
  .buildkite/pipeline.yml
  CHANGELOG.md
  appveyor.yml
  cardano-sl-src.json
  installers/WindowsInstaller.hs
  installers/dhall/launcher.dhall
  installers/dhall/linux64.dhall
  installers/dhall/macos64.dhall
  installers/dhall/os.type
  installers/dhall/win64.dhall
  installers/nix/linux.nix
  package-lock.json
  package.json
  release.nix
  scripts/build-installer-unix.sh
  scripts/build-installer-win64.bat
  source/renderer/app/api/ada/getAdaWallets.js
  source/renderer/app/assets/pdf/paper-wallet-certificate-page-1.inline.svg
  source/renderer/app/assets/pdf/paper-wallet-certificate-page-1.png
  source/renderer/app/assets/pdf/paper-wallet-certificate-page-2.inline.svg
  source/renderer/app/assets/pdf/paper-wallet-certificate-page-2.png
  source/renderer/app/components/wallet/WalletAdd.js
  source/renderer/app/components/wallet/WalletAdd.scss
  source/renderer/app/config/numbersConfig.js
  source/renderer/app/containers/wallet/WalletAddPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/ada/AdaWalletsStore.js
  source/renderer/app/utils/paperWalletPdfGenerator.js
  yarn.lock
  yarn2nix.nix
Labels: release-0.10.1

#974 [DDW-297] Merge release/0.10.1 branch into develop - FORK
  CHANGELOG.md
  installers/common/WindowsInstaller.hs
  installers/dhall/linux64.dhall
  installers/dhall/macos64.dhall
  installers/dhall/os.type
  installers/dhall/win64.dhall
  installers/nix/linux.nix
  package-lock.json
  package.json
  source/renderer/app/api/ada/getAdaWallets.js
  source/renderer/app/assets/pdf/paper-wallet-certificate-page-1.inline.svg
  source/renderer/app/assets/pdf/paper-wallet-certificate-page-1.png
  source/renderer/app/assets/pdf/paper-wallet-certificate-page-2.inline.svg
  source/renderer/app/assets/pdf/paper-wallet-certificate-page-2.png
  source/renderer/app/components/wallet/WalletAdd.js
  source/renderer/app/components/wallet/WalletAdd.scss
  source/renderer/app/config/numbersConfig.js
  source/renderer/app/containers/wallet/WalletAddPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/ada/AdaWalletsStore.js
  source/renderer/app/utils/paperWalletPdfGenerator.js
  storybook/stories/AddWallet.stories.js
  yarn.lock
  yarn2nix.nix
Labels: chore, release-0.11.0

#970 [DDW-289] Properly handle Ada redemption screen in case there are no wallets
  CHANGELOG.md
  source/renderer/app/assets/images/attention-big-thin.inline.svg
  source/renderer/app/components/notifications/NodeUpdateNotification.scss
  source/renderer/app/components/notifications/RestoreNotification.scss
  source/renderer/app/components/wallet/ada-redemption/AdaRedemptionNoWallets.js
  source/renderer/app/components/wallet/ada-redemption/AdaRedemptionNoWallets.scss
  source/renderer/app/containers/wallet/AdaRedemptionPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/AppStore.js
  source/renderer/app/stores/WalletStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
Labels: feature, release-0.11.0

#975 [DDW-310] Add acceptance tests for about dialog
  CHANGELOG.md
  features/about-dialog.feature
  features/step_definitions/about-dialog.js
Labels: chore

#980 [DDW-320] Bump Daedalus and Cardano versions
  CHANGELOG.md
  package-lock.json
  package.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: chore, release-0.11.0

#983 [DEVOPS-906] Update cardano-sl to tip of release/1.3.0
  cardano-sl-src.json
Labels: release-0.11.0

#979 [DDW-302] Add acceptance tests for maximum wallets limit
  CHANGELOG.md
  features/step_definitions/wallets-limit.js
  features/step_definitions/wallets-steps.js
  features/support/helpers/wallets-helpers.js
  features/wallets-limit.feature
Labels: chore

#984 [DDW-324] Improved documentation info section
  README.md
  features/README.md
  tls/README.md
Labels: chore

#977 [DDW-298] Add acceptance tests for update mechanism
  CHANGELOG.md
  features/node-update-notification.feature
  features/step_definitions/node-update-notification-steps.js
  features/support/electron.js
  package-lock.json
  source/main/ipc-api/kill-process.js
  source/renderer/app/api/ada/mocks/patchAdaApi.js
Labels: chore

#987 [DDW-326] Restore deleted package-lock.json file
  package-lock.json
Labels: bug

#981 [DDW-173] Submit forms on Enter key
  CHANGELOG.md
  source/renderer/app/components/profile/bug-report/BugReportDialog.js
  source/renderer/app/components/profile/language-selection/LanguageSelectionForm.js
  source/renderer/app/components/profile/terms-of-use/TermsOfUseForm.js
  source/renderer/app/components/wallet/WalletCreateDialog.js
  source/renderer/app/components/wallet/WalletReceive.js
  source/renderer/app/components/wallet/WalletRestoreDialog.js
  source/renderer/app/components/wallet/WalletSendConfirmationDialog.js
  source/renderer/app/components/wallet/WalletSendForm.js
  source/renderer/app/components/wallet/ada-redemption/AdaRedemptionForm.js
  source/renderer/app/components/wallet/etc/WalletSendForm.js
  source/renderer/app/components/wallet/settings/ChangeWalletPasswordDialog.js
  source/renderer/app/components/wallet/settings/DeleteWalletConfirmationDialog.js
  source/renderer/app/components/wallet/settings/export-to-file/WalletExportToFileDialog.js
  source/renderer/app/components/widgets/Dialog.js
  source/renderer/app/components/widgets/Dialog.scss
  source/renderer/app/components/widgets/DialogCloseButton.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/simple/SimpleButton.scss
  source/renderer/app/utils/form.js
Labels: feature

#985 [DEVOPS-919] installers: provide BUILD_NUMBER and API_VERSION
  .eslintrc
  default.nix
  installers/Spec.hs
  installers/common/MacInstaller.hs
  installers/common/Util.hs
  installers/common/WindowsInstaller.hs
  release.nix
  scripts/build-installer-nix.sh
  scripts/build-installer-win64.bat
  source/common/environment.js
  source/main/webpack.config.js
  source/renderer/app/components/static/About.js
  source/renderer/app/i18n/global-messages.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/webpack.config.js
  yarn2nix.nix
Labels: release-0.11.0

#989 Chore/ddw 325 switch from npm to yarn
  .flowconfig
  .github/pull_request_template.md
  README.md
  features/README.md
  package-lock.json
  package.json
  yarn.lock
Labels: chore

#723 [DDW-81] Improve redirecting logic of network store
  CHANGELOG.md
  source/renderer/app/Routes.js
  source/renderer/app/components/loading/Loading.js
  source/renderer/app/containers/LoadingPage.js
  source/renderer/app/containers/Root.js
  source/renderer/app/containers/etc/LoadingPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/stores/AppStore.js
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/ProfileStore.js
  source/renderer/app/stores/WalletStore.js
  source/renderer/app/stores/ada/AdaRedemptionStore.js
Labels: chore

#990 [DDW-329] Fix button outline color on special buttons
  CHANGELOG.md
  source/renderer/app/components/loading/SystemTimeErrorOverlay.js
  source/renderer/app/components/loading/SystemTimeErrorOverlay.scss
  source/renderer/app/components/sidebar/wallets/SidebarWalletsMenu.scss
  source/renderer/app/components/wallet/ada-redemption/AdaRedemptionDisclaimer.js
  source/renderer/app/components/wallet/ada-redemption/AdaRedemptionDisclaimer.scss
  source/renderer/app/components/wallet/paper-wallet-certificate/ConfirmationDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/ConfirmationDialog.scss
  source/renderer/app/components/wallet/settings/ChangeWalletPasswordDialog.js
  source/renderer/app/components/wallet/settings/ChangeWalletPasswordDialog.scss
  source/renderer/app/components/wallet/settings/DeleteWalletButton.scss
  source/renderer/app/components/wallet/settings/DeleteWalletConfirmationDialog.js
  source/renderer/app/components/wallet/settings/DeleteWalletConfirmationDialog.scss
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/mixins/buttons.scss
  source/renderer/app/themes/simple/SimpleButton.scss
Labels: bug

#978 [DEVOPS-398] installers: Add config for public testnet
  cardano-sl-src.json
  installers/README.md
  installers/common/Config.hs
  installers/dhall/linux64.dhall
  installers/dhall/testnet.dhall
  installers/nix/linux.nix
  scripts/build-installer-unix.sh
Labels: DO NOT MERGE

#976 [DDW-39] Acceptance tests for wallets, transactions and addresses ordering
  CHANGELOG.md
  features/hide-show-used-addresses.feature
  features/receive-money.feature
  features/step_definitions/receive-steps.js
  features/step_definitions/wallets-steps.js
  features/support/helpers/wallets-helpers.js
  features/transactions-grouping.feature
  features/wallets-ordering.feature
Labels: chore

#991 [DEVOPS-398] Installers: Add config for public testnet
  CHANGELOG.md
  installers/dhall/linux64.dhall
  installers/dhall/testnet.dhall
  installers/nix/linux.nix
Labels: feature, release-0.11.1

#992 [DEVOPS-922] Different ports for mainnet/staging/testnet
  CHANGELOG.md
  installers/Spec.hs
  installers/common/Config.hs
  installers/common/MacInstaller.hs
  installers/common/Types.hs
  installers/common/Util.hs
  installers/common/WindowsInstaller.hs
  installers/dhall/cluster.type
  installers/dhall/installer.dhall
  installers/dhall/launcher.dhall
  installers/dhall/mainnet.dhall
  installers/dhall/staging.dhall
  installers/dhall/testnet.dhall
  source/common/environment.js
  source/main/webpack.config.js
  source/renderer/app/api/ada/adaTestReset.js
  source/renderer/app/api/ada/adaTxFee.js
  source/renderer/app/api/ada/applyAdaUpdate.js
  source/renderer/app/api/ada/changeAdaWalletPassphrase.js
  source/renderer/app/api/ada/deleteAdaWallet.js
  source/renderer/app/api/ada/exportAdaBackupJSON.js
  source/renderer/app/api/ada/getAdaAccounts.js
  source/renderer/app/api/ada/getAdaAddressHistory.js
  source/renderer/app/api/ada/getAdaHistory.js
  source/renderer/app/api/ada/getAdaHistoryByAccount.js
  source/renderer/app/api/ada/getAdaHistoryByWallet.js
  source/renderer/app/api/ada/getAdaLocalTimeDifference.js
  source/renderer/app/api/ada/getAdaSyncProgress.js
  source/renderer/app/api/ada/getAdaWalletAccounts.js
  source/renderer/app/api/ada/getAdaWallets.js
  source/renderer/app/api/ada/importAdaBackupJSON.js
  source/renderer/app/api/ada/importAdaWallet.js
  source/renderer/app/api/ada/isValidAdaAddress.js
  source/renderer/app/api/ada/newAdaAccount.js
  source/renderer/app/api/ada/newAdaPayment.js
  source/renderer/app/api/ada/newAdaWallet.js
  source/renderer/app/api/ada/newAdaWalletAddress.js
  source/renderer/app/api/ada/nextAdaUpdate.js
  source/renderer/app/api/ada/postponeAdaUpdate.js
  source/renderer/app/api/ada/redeemAda.js
  source/renderer/app/api/ada/redeemAdaPaperVend.js
  source/renderer/app/api/ada/restoreAdaWallet.js
  source/renderer/app/api/ada/updateAdaWallet.js
  source/renderer/webpack.config.js
  yarn2nix.nix
Labels: feature, release-0.11.1

#988 [DEVOPS-814] Show different banners for testnet and staging RC
  CHANGELOG.md
  installers/common/Types.hs
  source/common/environment.js
  source/renderer/app/components/widgets/WalletTestEnvironmentLabel.js
  source/renderer/app/containers/TopBarContainer.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/types/networkTypes.js
  yarn2nix.nix
Labels: chore, release-0.11.1

#993 [DEVOPS-919] installers: fix missing backend in filenames
  installers/Spec.hs
  installers/common/Config.hs
  installers/common/MacInstaller.hs
  installers/common/Types.hs
  installers/common/WindowsInstaller.hs
Labels: bug, release-0.11.0
