Repository input-output-hk/daedalus, pull requests merged in 2018-02, with the labels that each got.

#719 Fix/DDW-93 Poll local time difference every 1 hour when connected
  .nonsense
  CHANGELOG.md
  app/stores/NetworkStatusStore.js
Labels: bug

#721 Chore/ddw 101 Run acceptance tests on release/0.9.0 branch in demo mode
  features/step_definitions/local-time-difference-steps.js
Labels: bug

#629 [DEVOPS-529] Buildkite migration
  .buildkite/pipeline.yml
  .travis.yml
  appveyor.yml
  default.nix
  fetch-nixpkgs.nix
  installers/Installer.hs
  installers/MacInstaller.hs
  installers/README.md
  installers/cardano-installer.cabal
  installers/cardano-installer.nix
  installers/load-certificate.hs
  installers/shell.nix
  nixpkgs-src.json
  scripts/build-installer-unix.sh
  scripts/nix-shell.sh
Labels: Infrastructure

#735 Fix/ddw 119 Fix wallet restore reactions configuration
  CHANGELOG.md
  app/stores/WalletStore.js
  app/stores/ada/AdaWalletsStore.js
Labels: bug

#691 Feature/ddw 5 Send bug reports with logs from Daedalus
  CHANGELOG.md
  app/actions/profile-actions.js
  app/api/ada/index.js
  app/api/ada/sendAdaBugReport.js
  app/api/common.js
  app/api/etc/index.js
  app/api/etc/sendEtcBugReport.js
  app/api/lib/reportRequest.js
  app/assets/images/sidebar/bug-report-ic.inline.svg
  app/components/layout/SidebarLayout.js
  app/components/loading/Loading.js
  app/components/loading/Loading.scss
  app/components/profile/bug-report/BugReportDialog.js
  app/components/profile/bug-report/BugReportDialog.scss
  app/components/sidebar/Sidebar.js
  app/components/sidebar/SidebarCategory.js
  app/components/sidebar/SidebarCategory.scss
  app/containers/LoadingPage.js
  app/containers/MainLayout.js
  app/containers/etc/LoadingPage.js
  app/containers/etc/MainLayout.js
  app/containers/profile/dialogs/BugReportDialogContainer.js
  app/containers/wallet/WalletSupportRequestPage.js
  app/environment.js
  app/i18n/errors.js
  app/i18n/locales/de-DE.json
  app/i18n/locales/defaultMessages.json
  app/i18n/locales/en-US.json
  app/i18n/locales/hr-HR.json
  app/i18n/locales/ja-JP.json
  app/i18n/locales/ko-KR.json
  app/i18n/locales/zh-CN.json
  app/stores/NetworkStatusStore.js
  app/stores/ProfileStore.js
  app/themes/daedalus/cardano.js
  app/themes/daedalus/dark-blue.js
  app/themes/daedalus/light-blue.js
  app/types/LogTypes.js
  electron/config.js
  electron/ipc-api/compress-logs.js
  electron/ipc-api/delete-compressed-logs.js
  electron/ipc-api/download-logs.js
  electron/ipc-api/get-logs.js
  electron/ipc-api/index.js
  electron/main.development.js
  package.json
Labels: feature

#738 [DDW-124] dont show validation error after clearing spending password field
  CHANGELOG.md
  app/components/wallet/WalletReceive.js
Labels: bug

#742 Fix/ddw 125 fix broken get logs function on windows
  electron/ipc-api/get-logs.js
Labels: bug

#752 Fix/ddw 139 Show time sync error even if the syncing has not started
  CHANGELOG.md
  app/components/loading/Loading.js
Labels: bug

#731 Chore/ddw 114 port ddw 101 to fork (FORK)
  features/step_definitions/local-time-difference-steps.js
Labels: chore

#754 [DDW-113] port ddw-93 to FORK
  CHANGELOG.md
  source/renderer/app/stores/NetworkStatusStore.js
Labels: chore

#755 [DDW-120] port ddw-119 to FORK
  CHANGELOG.md
  source/renderer/app/stores/WalletStore.js
  source/renderer/app/stores/ada/AdaWalletsStore.js
Labels: chore

#753 [DDW-116] port ddw-5 to fork
  CHANGELOG.md
  package-lock.json
  package.json
  source/common/environment.js
  source/main/config.js
  source/main/ipc-api/compress-logs.js
  source/main/ipc-api/delete-compressed-logs.js
  source/main/ipc-api/download-logs.js
  source/main/ipc-api/get-logs.js
  source/main/ipc-api/index.js
  source/main/utils/setupLogging.js
  source/renderer/app/actions/profile-actions.js
  source/renderer/app/api/ada/index.js
  source/renderer/app/api/ada/sendAdaBugReport.js
  source/renderer/app/api/common.js
  source/renderer/app/api/etc/index.js
  source/renderer/app/api/etc/sendEtcBugReport.js
  source/renderer/app/api/lib/reportRequest.js
  source/renderer/app/assets/images/sidebar/bug-report-ic.inline.svg
  source/renderer/app/components/layout/SidebarLayout.js
  source/renderer/app/components/loading/Loading.js
  source/renderer/app/components/loading/Loading.scss
  source/renderer/app/components/profile/bug-report/BugReportDialog.js
  source/renderer/app/components/profile/bug-report/BugReportDialog.scss
  source/renderer/app/components/sidebar/Sidebar.js
  source/renderer/app/components/sidebar/SidebarCategory.js
  source/renderer/app/components/sidebar/SidebarCategory.scss
  source/renderer/app/containers/LoadingPage.js
  source/renderer/app/containers/MainLayout.js
  source/renderer/app/containers/etc/LoadingPage.js
  source/renderer/app/containers/etc/MainLayout.js
  source/renderer/app/containers/profile/dialogs/BugReportDialogContainer.js
  source/renderer/app/containers/wallet/WalletSupportRequestPage.js
  source/renderer/app/i18n/errors.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/ProfileStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/types/LogTypes.js
Labels: chore

#756 [DDW-141] port ddw-124 to fork
  CHANGELOG.md
  source/renderer/app/components/wallet/WalletReceive.js
Labels: chore

#758 [DDW-140] port ddw-139 to fork
  CHANGELOG.md
  source/renderer/app/components/loading/Loading.js
Labels: chore

#759 [DDW-115] port DEVOPS-676 to fork
  package.json
  source/renderer/webpack.config.js
Labels: chore
