Repository input-output-hk/daedalus, pull requests merged in 2018-09, with the labels that each got.

#1073 [DDW-351] Improve transaction details text selection
  source/renderer/app/assets/images/collapse-arrow.inline.svg
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/components/wallet/transactions/Transaction.scss
  source/renderer/app/i18n/locales/defaultMessages.json
Labels: feature

#1076 [DDW-360] Missing V1 Api endpoints integration - 1 and 2
  features/support/helpers/wallets-helpers.js
  source/renderer/app/actions/ada/wallets-actions.js
  source/renderer/app/api/ada/importAdaBackupJSON.js
  source/renderer/app/api/ada/importAdaWallet.js
  source/renderer/app/api/ada/index.js
  source/renderer/app/api/ada/types.js
  source/renderer/app/components/wallet/file-import/WalletFileImportDialog.js
  source/renderer/app/components/wallet/file-import/WalletFileImportDialog.scss
  source/renderer/app/containers/wallet/dialogs/WalletFileImportDialogContainer.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/ada/AdaWalletsStore.js
Labels: feature

#1079 [DDW-360] missing v1 api endpoints integration 6-9
  CHANGELOG.md
  source/renderer/app/api/ada/adaTestReset.js
  source/renderer/app/api/ada/applyAdaUpdate.js
  source/renderer/app/api/ada/index.js
  source/renderer/app/api/ada/lib/v1/request.js
  source/renderer/app/api/ada/nextAdaUpdate.js
  source/renderer/app/api/ada/postponeAdaUpdate.js
  source/renderer/app/api/ada/types.js
  source/renderer/app/stores/ada/NodeUpdateStore.js
Labels: feature

#1083 [DDW-403] Log GPU-crash events
  source/main/utils/mainErrorHandler.js
Labels: feature

#1080 [DDW-360] V1 API Ada Redemption, Missing Endpoints 3-4
  CHANGELOG.md
  source/common/redemption-key-validation.js
  source/renderer/app/actions/ada/ada-redemption-actions.js
  source/renderer/app/api/ada/index.js
  source/renderer/app/api/ada/mocks/patchAdaApi.js
  source/renderer/app/api/ada/redeemAda.js
  source/renderer/app/api/ada/redeemAdaPaperVend.js
  source/renderer/app/api/ada/types.js
  source/renderer/app/components/wallet/ada-redemption/AdaRedemptionForm.js
  source/renderer/app/containers/wallet/AdaRedemptionPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/stores/ada/AdaRedemptionStore.js
Labels: feature

#1078 [DDW-360] Transactions paging
  source/renderer/app/api/ada/getAdaHistoryByWallet.js
  source/renderer/app/api/ada/index.js
  source/renderer/app/api/ada/lib/v1/request.js
  source/renderer/app/api/ada/types.js
  source/renderer/app/config/numbersConfig.js
  source/renderer/app/containers/wallet/WalletTransactionsPage.js
  source/renderer/app/stores/TransactionsStore.js
Labels: feature

#1081 [DDW-406] V1 API Improve Network Store
  CHANGELOG.md
  source/renderer/app/api/ada/index.js
  source/renderer/app/api/ada/types.js
  source/renderer/app/api/common.js
  source/renderer/app/stores/NetworkStatusStore.js
Labels: feature

#1086 [DDW-275] Improve NTP check handling
  features/step_definitions/local-time-difference-steps.js
  source/common/ipc-api/go-to-network-status-screen.js
  source/main/index.js
  source/main/menus/osx.js
  source/main/menus/win-linux.js
  source/renderer/app/Routes.js
  source/renderer/app/actions/ada/ada-redemption-actions.js
  source/renderer/app/api/ada/getNodeInfo.js
  source/renderer/app/api/ada/index.js
  source/renderer/app/api/ada/mocks/patchAdaApi.js
  source/renderer/app/api/ada/types.js
  source/renderer/app/api/common.js
  source/renderer/app/components/loading/Loading.js
  source/renderer/app/components/loading/SystemTimeErrorOverlay.js
  source/renderer/app/components/loading/SystemTimeErrorOverlay.scss
  source/renderer/app/components/status/NetworkStatus.js
  source/renderer/app/components/status/NetworkStatus.scss
  source/renderer/app/config/cryptoConfig.js
  source/renderer/app/config/formattingConfig.js
  source/renderer/app/config/numbersConfig.js
  source/renderer/app/config/timingConfig.js
  source/renderer/app/config/urlsConfig.js
  source/renderer/app/containers/LoadingPage.js
  source/renderer/app/containers/Root.js
  source/renderer/app/containers/status/NetworkStatusPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/routes-config.js
  source/renderer/app/stores/AppStore.js
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/ada/AdaRedemptionStore.js
Labels: feature

#1090 [DDW-411] Implement design review fixes and improvements
  source/renderer/app/assets/images/ada-symbol-big-dark.inline.svg
  source/renderer/app/components/profile/bug-report/BugReportDialog.scss
  source/renderer/app/components/profile/language-selection/LanguageSelectionForm.scss
  source/renderer/app/components/profile/terms-of-use/TermsOfUseForm.scss
  source/renderer/app/components/profile/terms-of-use/TermsOfUseText.scss
  source/renderer/app/components/settings/categories/SupportSettings.scss
  source/renderer/app/components/sidebar/Sidebar.js
  source/renderer/app/components/sidebar/SidebarCategory.js
  source/renderer/app/components/sidebar/SidebarCategory.scss
  source/renderer/app/components/sidebar/wallets/SidebarWalletsMenu.js
  source/renderer/app/components/sidebar/wallets/SidebarWalletsMenu.scss
  source/renderer/app/components/wallet/WalletCreateDialog.scss
  source/renderer/app/components/wallet/WalletReceive.js
  source/renderer/app/components/wallet/WalletReceive.scss
  source/renderer/app/components/wallet/WalletRestoreDialog.scss
  source/renderer/app/components/wallet/WalletSendConfirmationDialog.scss
  source/renderer/app/components/wallet/ada-redemption/AdaRedemptionForm.scss
  source/renderer/app/components/wallet/backup-recovery/WalletRecoveryPhraseEntryDialog.scss
  source/renderer/app/components/wallet/file-import/WalletFileImportDialog.scss
  source/renderer/app/components/wallet/paper-wallet-certificate/CompletionDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/CompletionDialog.scss
  source/renderer/app/components/wallet/paper-wallet-certificate/InstructionsDialog.scss
  source/renderer/app/components/wallet/paper-wallet-certificate/VerificationDialog.js
  source/renderer/app/components/wallet/settings/ChangeWalletPasswordDialog.scss
  source/renderer/app/components/wallet/settings/DeleteWalletConfirmationDialog.scss
  source/renderer/app/components/wallet/settings/ExportWalletToFileDialog.scss
  source/renderer/app/components/wallet/skins/AmountInputSkin.scss
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/components/wallet/transactions/Transaction.scss
  source/renderer/app/components/widgets/BigButtonForDialogs.scss
  source/renderer/app/components/widgets/InlineNotification.js
  source/renderer/app/components/widgets/InlineNotification.scss
  source/renderer/app/components/widgets/forms/InlineEditingInput.scss
  source/renderer/app/components/widgets/forms/ReadOnlyInput.scss
  source/renderer/app/config/timingConfig.js
  source/renderer/app/containers/MainLayout.js
  source/renderer/app/containers/wallet/WalletReceivePage.js
  source/renderer/app/containers/wallet/dialogs/paper-wallet-certificate/CompletionDialogContainer.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/simple/SimpleInput.scss
  source/renderer/app/utils/strings.js
  storybook/stories/PaperWallets.stories.js
  storybook/stories/Sidebar.stories.js
  storybook/stories/SidebarWalletsMenu.stories.js
  storybook/stories/WalletScreens.stories.js
  storybook/stories/support/StoryLayout.js
Labels: bug

#1093 [DDW-318] Handle forbidden mnemonics Api error, Fix handled error mes…
  source/renderer/app/api/api.js
  source/renderer/app/api/common/errors.js
  source/renderer/app/api/utils/request.js
  source/renderer/app/components/sidebar/SidebarCategory.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
Labels: bug

#1094 [DDW-416] Add Daedalus and Cardano version to Daedalus logs
  source/main/index.js
Labels: feature

#1095 [DDW-411] Transaction toggle arrow colors
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
Labels: bug

#1097 [DDW-419] Implement Japanese Terms of use for Testnet network
  CHANGELOG.md
  source/renderer/app/i18n/locales/terms-of-use/ada/other/ja-JP.md
Labels: feature

#1060 [DEVOPS-398] Update to cardano-sl 1.3.1
  cardano-sl-src.json
Labels: release-0.11.1
