Repository input-output-hk/daedalus, pull requests merged in 2018-10, with the labels that each got.

#1105 [DDW-389] Update Generic Api error message
  source/renderer/app/api/common.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
Labels: bug, release-0.11.1

#1100 [DDW-418] Improve 'Forbidden mnemonic' error message
  source/renderer/app/api/common/errors.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
Labels: chore

#1106 [DDW-422] Merge release/0.11.1 into develop
  source/renderer/app/api/common/errors.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
Labels: chore, release-0.11.1

#1103 [DDW-421] Record screenshots of failed acceptance tests
  .gitignore
  CHANGELOG.md
  features/step_definitions/helper-steps.js
  features/support/electron.js
  features/support/helpers/screenshot.js
Labels: chore, release-0.12.0

#1092 [DDW-413] Update support request feature node logs handling
  cardano-sl-src.json
  source/main/config.js
  source/main/ipc-api/get-logs.js
Labels: feature, release-0.12.0

#1104 [DEVOPS-998] [CO-354] Update cardano-sl to PR branch
  cardano-sl-src.json
Labels: release-0.11.1

#1107 [DDW-274] Refactor IPC channels logic
  .eslintrc
  features/node-update-notification.feature
  features/receive-money.feature
  features/send-money-to-receiver.feature
  features/transactions-display.feature
  package.json
  source/common/ipc-api.js
  source/common/ipc-api/tls-config.js
  source/common/ipc/cardano.ipc.js
  source/common/ipc/go-to-ada-redemption-screen.js
  source/common/ipc/go-to-network-status-screen.js
  source/common/ipc/lib/IpcChannel.js
  source/common/ipc/load-asset.js
  source/common/ipc/open-about-dialog.js
  source/common/logging.js
  source/common/types/cardanoNode.types.js
  source/main/cardano/CardanoNode.js
  source/main/cardano/config.js
  source/main/cardano/setup.js
  source/main/cardano/utils.js
  source/main/config.js
  source/main/index.js
  source/main/ipc-api/cardanoIpcApi.js
  source/main/ipc-api/load-asset.js
  source/main/ipc/cardano.ipc.js
  source/main/ipc/compress-logs.js
  source/main/ipc/download-logs.js
  source/main/ipc/get-gpu-status.js
  source/main/ipc/get-logs.js
  source/main/ipc/index.js
  source/main/ipc/lib/MainIpcChannel.js
  source/main/ipc/load-asset.js
  source/main/ipc/parse-redemption-code-from-pdf.js
  source/main/ipc/resize-window.js
  source/main/utils/loadTlsConfig.js
  source/main/windows/main.js
  source/renderer/app/api/api.js
  source/renderer/app/config/timingConfig.js
  source/renderer/app/ipc/awaitUpdateChannel.js
  source/renderer/app/ipc/cardano.ipc.js
  source/renderer/app/ipc/cardanoNodeChannels.js
  source/renderer/app/ipc/cardanoNodeStateChangeChannel.js
  source/renderer/app/ipc/lib/IpcChannel.js
  source/renderer/app/ipc/lib/RendererIpcChannel.js
  source/renderer/app/ipc/loadAsset.js
  source/renderer/app/ipc/tlsConfigChannel.js
  source/renderer/app/stores/AppStore.js
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/SidebarStore.js
  source/renderer/app/types/gpuStatus.js
  source/renderer/app/utils/paperWalletPdfGenerator.js
  yarn.lock
Labels: chore, release-0.12.0

#1101 [DDW-420] Fix failing acceptance tests, Improve code style
  features/add-wallet-via-sidebar.feature
  features/generate-wallet-address.feature
  features/import-wallet-via-sidebar.feature
  features/node-update-notification.feature
  features/receive-money.feature
  features/restore-wallet-via-sidebar.feature
  features/step_definitions/receive-steps.js
  features/step_definitions/settings-steps.js
  features/step_definitions/wallets-steps.js
  features/support/helpers/wallets-helpers.js
  features/switching-between-wallets.feature
  features/transactions-display.feature
  features/wallet-settings.feature
  features/wallets-ordering.feature
  source/renderer/app/actions/ada/addresses-actions.js
  source/renderer/app/actions/ada/wallet-settings-actions.js
  source/renderer/app/actions/ada/wallets-actions.js
  source/renderer/app/api/addresses/types.js
  source/renderer/app/api/api.js
  source/renderer/app/api/common/errors.js
  source/renderer/app/api/transactions/requests/createTransaction.js
  source/renderer/app/api/transactions/requests/redeemAda.js
  source/renderer/app/api/transactions/requests/redeemPaperVendedAda.js
  source/renderer/app/api/wallets/requests/createWallet.js
  source/renderer/app/api/wallets/requests/importWalletAsKey.js
  source/renderer/app/api/wallets/types.js
  source/renderer/app/components/wallet/WalletCreateDialog.js
  source/renderer/app/components/wallet/WalletCreateDialog.scss
  source/renderer/app/components/wallet/WalletRestoreDialog.js
  source/renderer/app/components/wallet/WalletRestoreDialog.scss
  source/renderer/app/components/wallet/WalletSendConfirmationDialog.js
  source/renderer/app/components/wallet/WalletSendConfirmationDialog.scss
  source/renderer/app/components/wallet/WalletSettings.js
  source/renderer/app/components/wallet/ada-redemption/AdaRedemptionForm.js
  source/renderer/app/components/wallet/file-import/WalletFileImportDialog.js
  source/renderer/app/components/wallet/file-import/WalletFileImportDialog.scss
  source/renderer/app/components/wallet/settings/ChangeSpendingPasswordDialog.js
  source/renderer/app/components/wallet/settings/ChangeSpendingPasswordDialog.scss
  source/renderer/app/containers/wallet/WalletReceivePage.js
  source/renderer/app/containers/wallet/WalletSettingsPage.js
  source/renderer/app/containers/wallet/dialogs/WalletRestoreDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/WalletSendConfirmationDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/settings/ChangeSpendingPasswordDialogContainer.js
  source/renderer/app/i18n/global-messages.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/WalletStore.js
  source/renderer/app/stores/ada/AdaWalletSettingsStore.js
  source/renderer/app/stores/ada/AdaWalletsStore.js
  source/renderer/app/stores/ada/AddressesStore.js
  source/renderer/app/utils/validations.js
  storybook/stories/WalletScreens.stories.js
Labels: chore, release-0.12.0

#1096 [DDW-417] Implement new data layer migration screen
  CHANGELOG.md
  features/data-layer-migration.feature
  features/receive-money.feature
  features/send-money-to-receiver.feature
  features/step_definitions/data-layer-migration.js
  features/step_definitions/helper-steps.js
  features/step_definitions/setup-steps.js
  features/step_definitions/wallets-steps.js
  features/support/helpers/data-layer-migration-helpers.js
  features/support/helpers/wallets-helpers.js
  source/renderer/app/Routes.js
  source/renderer/app/actions/profile-actions.js
  source/renderer/app/api/utils/localStorage.js
  source/renderer/app/components/profile/data-layer-migration/DataLayerMigrationForm.js
  source/renderer/app/components/profile/data-layer-migration/DataLayerMigrationForm.scss
  source/renderer/app/containers/profile/DataLayerMigrationPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/routes-config.js
  source/renderer/app/stores/ProfileStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
Labels: feature, release-0.12.0

#1008 [DEVOPS-779] remove nix-shell.sh in favor of buildkite hooks
  .buildkite/hooks/pre-command
  .buildkite/pipeline.yml
  scripts/nix-shell.sh
Labels: Infrastructure, release-0.12.0

#1109 [DDW-429] Add Network Prefix to Node IPC Local Storage Keys and Process Names
  CHANGELOG.md
  source/common/types/cardanoNode.types.js
  source/main/cardano/CardanoNode.js
  source/main/cardano/utils.js
Labels: chore, release-0.12.0

#1113 [DDW-431] Prevent multiple Daedalus instances per state dir
  CHANGELOG.md
  README.md
  package.json
  source/common/environment.js
  source/main/cardano/config.js
  source/main/cardano/setup.js
  source/main/config.js
  source/main/index.js
  source/main/utils/config.js
  source/main/utils/getRuntimeFolderPath.js
  source/main/utils/loadTlsConfig.js
  source/main/utils/lockFiles.js
  source/main/utils/safeExitWithCode.js
  source/main/webpack.config.js
  source/renderer/webpack.config.js
  yarn.lock
Labels: feature, release-0.12.0

#1114 [DEVOPS-1073] Unique productName for each installed Daedalus
  installers/Spec.hs
  installers/common/MacInstaller.hs
  installers/common/Util.hs
  installers/common/WindowsInstaller.hs
  installers/daedalus-installer.cabal
  installers/daedalus-installer.nix
  installers/nix/linux.nix
  yarn2nix.nix
Labels: bug, release-0.12.0

#1112 [DDW-426] Fix Having Trouble Connecting Notification
  CHANGELOG.md
  source/renderer/app/components/loading/Loading.js
Labels: bug, release-0.12.0

#1116 [DEVOPS-1084] fix unicode in uninstaller
  installers/common/WindowsInstaller.hs
Labels: bug, release-0.12.0

#1111 [DDW-427] Handle new transaction fee calculation error messages
  CHANGELOG.md
  cardano-sl-src.json
  source/renderer/app/api/api.js
  source/renderer/app/api/transactions/errors.js
  source/renderer/app/api/transactions/types.js
  source/renderer/app/components/wallet/WalletSendForm.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/TransactionsStore.js
Labels: bug, release-0.12.0

#1115 [DDW-432] Implement NodeIPC improvements
  README.md
  package.json
  source/common/ipc/lib/IpcChannel.js
  source/main/cardano/CardanoNode.js
  source/main/cardano/setup.js
  source/main/cardano/utils.js
  source/main/ipc/cardano.ipc.js
  source/main/ipc/lib/MainIpcChannel.js
  source/main/ipc/load-asset.js
  source/renderer/app/api/api.js
  source/renderer/app/components/profile/data-layer-migration/DataLayerMigrationForm.scss
  source/renderer/app/components/status/NetworkStatus.js
  source/renderer/app/config/timingConfig.js
  source/renderer/app/containers/status/NetworkStatusPage.js
  source/renderer/app/ipc/cardano.ipc.js
  source/renderer/app/ipc/lib/RendererIpcChannel.js
  source/renderer/app/ipc/loadAsset.js
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
Labels: bug, release-0.12.0

#1120 main window on Linux: icon relative to process.env.DAEDALUS_INSTALL_DIRECTORY
  .gitignore
  default.nix
  shell.nix
  source/main/windows/main.js
Labels: bug, release-0.12.0

#1117 [DDW-434] Clean up and proof-read CHANGELOG
  CHANGELOG.md
Labels: chore, release-0.12.0

#1121 [DDW 436] Improve Daedalus lock file handling
  package.json
  source/main/cardano/CardanoNode.js
  source/main/index.js
  source/main/utils/lockFiles.js
  source/main/utils/processes.js
Labels: bug, release-0.12.0

#1122 [DDW-438] Fix missing Cardano node pub logs
  .gitignore
  shell.nix
  source/main/cardano/config.js
  source/main/config.js
Labels: bug, release-0.12.0

#1123 [DDW-439] Add all release items to the CHANGELOG
  CHANGELOG.md
Labels: chore, release-0.12.0

#1126 [DDW-441] Fix broken sequential creation of test wallets
  features/support/helpers/wallets-helpers.js
Labels: chore, release-0.12.0

#1118 [DDW-433] Expose Cardano Node states to the UI
  CHANGELOG.md
  cardano-sl-src.json
  package.json
  source/common/types/cardanoNode.types.js
  source/main/cardano/CardanoNode.js
  source/main/cardano/setup.js
  source/renderer/app/components/loading/Loading.js
  source/renderer/app/components/loading/Loading.scss
  source/renderer/app/components/profile/bug-report/BugReportDialog.js
  source/renderer/app/components/status/NetworkStatus.js
  source/renderer/app/containers/LoadingPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/NetworkStatusStore.js
Labels: feature, release-0.12.0

#1131 [DDW-443] Fix Antivirus Notification Close Button Hover Color
  CHANGELOG.md
  source/renderer/app/components/notifications/AntivirusRestaurationSlowdownNotification.scss
Labels: bug, release-0.12.0

#1132 [DDW-443] Fix Antivirus Notification Close Button Hover Color
  CHANGELOG.md
  source/renderer/app/components/notifications/AntivirusRestaurationSlowdownNotification.scss
Labels: bug, release-0.12.0

#1133 [DEVOPS-1096] Fix Daedalus icon on Linux
  source/main/windows/main.js
Labels: bug, release-0.12.0

#1135 [DEVOPS-1095] allow opening links when in the sandbox
  default.nix
  installers/nix/nix-installer.nix
Labels: bug, release-0.12.0

#1136 [DEVOPS-1095] allow opening links when in the sandbox
  default.nix
  installers/nix/nix-installer.nix
Labels: bug, release-0.12.0

#1137 [DDW-445] Add Daedalus and Cardano version to Daedalus logs
  CHANGELOG.md
  source/main/index.js
Labels: bug, release-0.12.0

#1144 [DEVOPS-1109] cli argument to inhibit console log: --log-console-off
  cardano-sl-src.json
  installers/dhall/launcher.dhall
Labels: bug, release-0.12.0

#1142 [DEVOPS-1110] shell.nix/README doc updates for demo cluster
  README.md
  shell.nix
Labels: chore, release-0.12.0

#1145 [DDW-447] Fix yarn test in nix shell
  shell.nix
Labels: bug, release-0.12.0

#1143 [DDW-448] Fix lockfile logic
  package.json
  source/main/cardano/setup.js
  source/main/index.js
  source/main/utils/lock-files/adapter.js
  source/main/utils/lock-files/index.js
  source/main/utils/lock-files/lockfile.js
  source/main/utils/lockFiles.js
  source/main/webpack.config.js
  yarn.lock
Labels: bug, release-0.12.0

#1148 [DDW-451] fix startup errors for start:dev
  package.json
  source/common/environment.js
  source/main/index.js
  source/main/webpack.config.js
Labels: chore

#1140 [DDW-450] Bump Cardano version
  cardano-sl-src.json
Labels: chore, release-0.12.0

#1151 [DEVOPS-1112] Update cardano-sl to release/2.0.0 branch
  cardano-sl-src.json
Labels: chore, release-0.12.0

#1153 [DEVOPS-1112] Update cardano-sl to latest release/2.0.0 branch
  cardano-sl-src.json
Labels: chore, release-0.12.0

#1155 Merge release/0.12.0 into develop branch
  CHANGELOG.md
  README.md
  cardano-sl-src.json
  installers/dhall/launcher.dhall
  package.json
  shell.nix
  source/main/cardano/setup.js
  source/main/index.js
  source/main/utils/lock-files/adapter.js
  source/main/utils/lock-files/index.js
  source/main/utils/lock-files/lockfile.js
  source/main/utils/lockFiles.js
  source/main/webpack.config.js
  source/main/windows/main.js
  source/renderer/app/components/loading/Loading.js
  source/renderer/app/components/loading/SystemTimeErrorOverlay.js
  source/renderer/app/components/loading/SystemTimeErrorOverlay.scss
  source/renderer/app/components/settings/categories/SupportSettings.js
  source/renderer/app/components/status/NetworkStatus.js
  source/renderer/app/containers/LoadingPage.js
  source/renderer/app/containers/status/NetworkStatusPage.js
  source/renderer/app/i18n/global-messages.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/NetworkStatusStore.js
  yarn.lock
Labels: chore
