Repository input-output-hk/daedalus, pull requests merged in 2018-05, with the labels that each got.

#895 [R120-4] Update cardano-sl-src.json to latest release/1.2.0
  cardano-sl-src.json
Labels: bug, release-0.10.0

#899 [R120-4] Update cardano-sl-src.json to latest release/1.2.0
  cardano-sl-src.json
Labels: bug, release-0.10.0

#901 Chore/ddw 258 Add owner info to all Daedalus GitHub documents
  CHANGELOG.md
  README.md
  features/README.md
Labels: chore

#892 Chore/ddw 218 Improve request body params length calculation
  CHANGELOG.md
  source/renderer/app/api/ada/lib/request.js
  source/renderer/app/api/ada/lib/v1/request.js
  source/renderer/app/api/etc/lib/request.js
  source/renderer/app/api/lib/utils.js
Labels: chore

#910 Fix/ddw 257 Prevent dragging of images within the application
  CHANGELOG.md
  source/renderer/app/components/settings/categories/DisplaySettings.js
  source/renderer/app/components/wallet/paper-wallet-certificate/SecuringPasswordDialog.scss
  source/renderer/app/components/widgets/NodeSyncStatusIcon.scss
Labels: bug

#913 [DEVOPS-771] AppVeyor: remove 1.0. prefix from build version
  appveyor.yml
Labels: chore

#917 Merge Release/0.10.0 back into develop
  installers/dhall/macos64.dhall
Labels: chore

#916 [DDW-231] log expected errors as debug messages only
  CHANGELOG.md
  source/renderer/app/api/ada/index.js
  source/renderer/app/api/etc/index.js
Labels: chore

#920 [DDW-265] installers: fix network setting of staging build
  .buildkite/pipeline.yml
  appveyor.yml
  installers/Installer.hs
  installers/Types.hs
Labels: bug

#921 [DEVOPS-842] hydra CI tests for flow and eslint
  cardano-sl-src.json
  default.nix
  release.nix
  tests/flow.nix
  tests/lint.nix
  yarn2nix.nix
Labels: Infrastructure

#927 Fix/ddw 266 About dialog mentioned Alexander Vieth twice
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: bug, release-0.10.0

#929 [DEVOPS-855] just use the variable as-is
  .buildkite/pipeline.yml
  scripts/build-installer-nix.sh
Labels: bug

#934 Update the `applicationVersion`s embedded in the 1.2 RC6 installers
  cardano-sl-src.json
Labels: chore, release-0.10.0

#933 Feature/ddw 271 Ada redemption options update - 1.2.0
  CHANGELOG.md
  features/ada-redemption.feature
  features/step_definitions/ada-redemption-steps.js
  source/common/decrypt.js
  source/main/ipc-api/parse-redemption-code-from-pdf.js
  source/renderer/app/actions/ada/ada-redemption-actions.js
  source/renderer/app/components/wallet/ada-redemption/AdaRedemptionChoices.js
  source/renderer/app/components/wallet/ada-redemption/AdaRedemptionChoices.scss
  source/renderer/app/components/wallet/ada-redemption/AdaRedemptionForm.js
  source/renderer/app/components/wallet/ada-redemption/AdaRedemptionForm.scss
  source/renderer/app/containers/wallet/AdaRedemptionPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/ada/AdaRedemptionStore.js
  source/renderer/app/types/redemptionTypes.js
Labels: feature, release-0.10.0

#930 Fix/ddw 277 Fix broken translation on create wallet dialog
  CHANGELOG.md
  source/renderer/app/components/wallet/backup-recovery/WalletBackupPrivacyWarningDialog.js
  source/renderer/app/containers/wallet/WalletReceivePage.js
Labels: bug

#928 Fix/ddw 276 Fix Storybook
  CHANGELOG.md
  storybook/webpack.config.js
Labels: bug

#915 Chore/ddw 249 improve build time
  CHANGELOG.md
  gulpfile.js
  package-lock.json
  package.json
  source/main/webpack.config.js
  source/renderer/app/containers/wallet/dialogs/paper-wallet-certificate/SecuringPasswordDialogContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/webpack.config.js
  storybook/stories/PaperWallets.stories.js
  yarn.lock
  yarn2nix.nix
Labels: chore

#938 [DDW-159] Check for linting and flow-type errors in storybook directory
  CHANGELOG.md
  package.json
  source/renderer/app/components/wallet/settings/export-to-file/WalletExportToFileDialog.js
  storybook/config.js
  storybook/stories/AdaRedemptionDialog.stories.js
  storybook/stories/AddWallet.stories.js
  storybook/stories/LanguageSelectionForm.stories.js
  storybook/stories/PaperWallets.stories.js
  storybook/stories/Sidebar.stories.js
  storybook/stories/SidebarCategory.stories.js
  storybook/stories/SidebarWalletsMenu.stories.js
  storybook/stories/Staking.stories.js
  storybook/stories/StakingChart.stories.js
  storybook/stories/TopBar.stories.js
  storybook/stories/WalletDeleteConfirmationDialog.stories.js
  storybook/stories/WalletExportToFileDialog.stories.js
  storybook/stories/WalletSummary.stories.js
  storybook/stories/WalletTransactionsList.stories.js
  storybook/stories/Widgets.stories.js
  storybook/stories/index.js
Labels: chore

#944 [DDW-268] fix npm audit issues by upgrading dependencies
  CHANGELOG.md
  package-lock.json
  package.json
  yarn.lock
Labels: chore

#941 [DDW-284] Merge release 0.10.0 branch into develop - FORK
  CHANGELOG.md
  cardano-sl-src.json
  features/ada-redemption.feature
  features/step_definitions/ada-redemption-steps.js
  installers/common/WindowsInstaller.hs
  package.json
  source/common/decrypt.js
  source/main/ipc-api/parse-redemption-code-from-pdf.js
  source/renderer/app/actions/ada/ada-redemption-actions.js
  source/renderer/app/components/wallet/WalletRestoreDialog.js
  source/renderer/app/components/wallet/ada-redemption/AdaRedemptionChoices.js
  source/renderer/app/components/wallet/ada-redemption/AdaRedemptionChoices.scss
  source/renderer/app/components/wallet/ada-redemption/AdaRedemptionForm.js
  source/renderer/app/components/wallet/ada-redemption/AdaRedemptionForm.scss
  source/renderer/app/containers/wallet/AdaRedemptionPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/ada/AdaRedemptionStore.js
  source/renderer/app/types/redemptionTypes.js
  storybook/stories/AdaRedemptionDialog.stories.js
Labels: DO NOT MERGE, chore

#935 [DDW-222] Use a switch instead a link for 'hide used' addresses on th…
  CHANGELOG.md
  package-lock.json
  source/renderer/app/components/wallet/WalletReceive.js
  source/renderer/app/components/wallet/WalletReceive.scss
  source/renderer/app/components/widgets/forms/TinySwitch.js
  source/renderer/app/components/widgets/forms/TinySwitch.scss
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  storybook/stories/Widgets.stories.js
  storybook/stories/support/StoryDecorator.js
Labels: feature

#946 [DDW-270] disable webview tags to avoid xss attack
  CHANGELOG.md
  source/main/windows/about.js
  source/main/windows/main.js
Labels: bug

#951 [DDW-296] Fix paper wallet certificate PDF printing issues
  CHANGELOG.md
  package-lock.json
  package.json
  source/renderer/app/assets/pdf/paper-wallet-certificate-page-1.inline.svg
  source/renderer/app/assets/pdf/paper-wallet-certificate-page-1.png
  source/renderer/app/assets/pdf/paper-wallet-certificate-page-2.inline.svg
  source/renderer/app/assets/pdf/paper-wallet-certificate-page-2.png
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/utils/paperWalletPdfGenerator.js
  yarn.lock
Labels: bug

#947 [DDW-288] ports ddw-70 to target latest develop
  CHANGELOG.md
  source/renderer/app/components/wallet/transactions/WalletTransactionsList.js
Labels: bug
