Repository input-output-hk/daedalus, pull requests merged in 2018-08, with the labels that each got.

#1032 [DDW-372] Fix double window bug when running in dev without backend
  source/main/index.js
Labels: bug

#1049 Merges master into release/0.11.1
  CHANGELOG.md
  installers/Spec.hs
  installers/common/Config.hs
  installers/common/MacInstaller.hs
  installers/common/Types.hs
  installers/common/WindowsInstaller.hs
  installers/dhall/linux64.dhall
  installers/dhall/macos64.dhall
  installers/dhall/os.type
  installers/dhall/win64.dhall
  package-lock.json
  release.nix
  source/common/environment.js
  source/main/windows/main.js
  source/renderer/app/actions/ada/wallets-actions.js
  source/renderer/app/api/ada/sendAdaBugReport.js
  source/renderer/app/api/etc/sendEtcBugReport.js
  source/renderer/app/components/notifications/AntivirusRestaurationSlowdownNotification.js
  source/renderer/app/components/notifications/AntivirusRestaurationSlowdownNotification.scss
  source/renderer/app/components/settings/categories/SupportSettings.js
  source/renderer/app/components/static/About.js
  source/renderer/app/components/static/About.scss
  source/renderer/app/containers/static/AboutDialog.js
  source/renderer/app/containers/wallet/Wallet.js
  source/renderer/app/i18n/global-messages.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/WalletStore.js
  source/renderer/app/utils/paperWalletPdfGenerator.js
  storybook/stories/AntivirusRestaurationSlowdownNotification.stories.js
  storybook/stories/index.js
Labels: chore, release-0.11.1

#1050 [DDW-386] Bump Daedalus version to 0.11.1
  CHANGELOG.md
  package-lock.json
  package.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: chore, release-0.11.1

#1051 [DDW-385] use testnet explorer links in testnet build
  CHANGELOG.md
  source/common/environment.js
  source/renderer/app/components/wallet/paper-wallet-certificate/CompletionDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/InstructionsDialog.js
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/config/urlsConfig.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/utils/ada/network.js
Labels: chore, release-0.11.1

#1055 [DDW-346] Show Testnet label on paper wallet certificate
  CHANGELOG.md
  source/renderer/app/assets/pdf/paper-wallet-certificate-page-1-testnet.png
  source/renderer/app/assets/pdf/paper-wallet-certificate-page-2-testnet.png
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/utils/paperWalletPdfGenerator.js
Labels: chore, release-0.11.1

#1056 [DEVOPS-922] Choose backend ports for staging and testnet which don't conflict
  installers/Spec.hs
  installers/dhall/staging.dhall
  installers/dhall/testnet.dhall
  yarn2nix.nix
Labels: release-0.11.1

#1054 [DDW-388] Detect if Daedalus was launched using Launcher
  CHANGELOG.md
  source/main/index.js
Labels: bug, release-0.11.1

#1053 [DDW-380] Unable to open Daedalus in safe mode in TestNet
  cardano-sl-src.json
  installers/dhall/linux64.dhall
  installers/nix/linux.nix
  source/main/index.js
  source/main/menus/osx.js
  source/main/menus/win-linux.js
  source/main/windows/main.js
Labels: bug, release-0.11.1

#1041 [DDW-378] fix broken storybook
  CHANGELOG.md
  source/common/environment.js
  source/renderer/app/components/sidebar/Sidebar.js
  source/renderer/app/components/sidebar/wallets/SidebarWalletsMenu.js
  source/renderer/app/stores/SidebarStore.js
  source/renderer/app/types/sidebarTypes.js
  storybook/stories/SidebarCategory.stories.js
  storybook/stories/WalletScreens.stories.js
  storybook/stories/support/StoryDecorator.js
  storybook/stories/support/StoryLayout.js
Labels: chore

#1037 [DDW-356] V1 API endpoints integration 2/5
  CHANGELOG.md
  source/renderer/app/actions/ada/addresses-actions.js
  source/renderer/app/api/ada/adaTxFee.js
  source/renderer/app/api/ada/getAdaAddress.js
  source/renderer/app/api/ada/getAdaWalletAccounts.js
  source/renderer/app/api/ada/index.js
  source/renderer/app/api/ada/isValidAdaAddress.js
  source/renderer/app/api/ada/lib/v1/request.js
  source/renderer/app/api/ada/newAdaWalletAddress.js
  source/renderer/app/api/ada/types.js
  source/renderer/app/api/common.js
  source/renderer/app/components/wallet/WalletReceive.js
  source/renderer/app/components/wallet/WalletSendForm.js
  source/renderer/app/containers/wallet/Wallet.js
  source/renderer/app/containers/wallet/WalletReceivePage.js
  source/renderer/app/domains/WalletAddress.js
  source/renderer/app/stores/ada/AdaTransactionsStore.js
  source/renderer/app/stores/ada/AddressesStore.js
Labels: feature

#1031 [DDW-337] V1 Api endpoints integration 3/5 - Ada payments
  CHANGELOG.md
  features/receive-money.feature
  features/step_definitions/transactions-steps.js
  features/transactions-display.feature
  source/renderer/app/api/ada/adaTxFee.js
  source/renderer/app/api/ada/getAdaHistoryByWallet.js
  source/renderer/app/api/ada/getAdaWalletAccountsV1.js
  source/renderer/app/api/ada/index.js
  source/renderer/app/api/ada/lib/utils.js
  source/renderer/app/api/ada/newAdaPayment.js
  source/renderer/app/api/ada/types.js
  source/renderer/app/components/wallet/WalletSendForm.js
  source/renderer/app/containers/wallet/Wallet.js
  source/renderer/app/containers/wallet/WalletSendPage.js
  source/renderer/app/stores/ada/AdaTransactionsStore.js
  source/renderer/app/stores/ada/AdaWalletsStore.js
  source/renderer/app/stores/ada/AddressesStore.js
  source/renderer/app/utils/formatters.js
Labels: feature

#1036 [DDW-374] Submit network and software versions to reporting server
  CHANGELOG.md
  source/common/environment.js
  source/renderer/app/api/ada/index.js
  source/renderer/app/api/ada/sendAdaBugReport.js
  source/renderer/app/api/etc/sendEtcBugReport.js
Labels: chore, release-0.11.1

#1052 [DEVOPS-998] bump cardano-sl to HEAD of 1.3.1
  cardano-sl-src.json
Labels: chore, release-0.11.1

#1062 [DDW-396] Debug NODE_ENV issues on CI builds
  source/renderer/webpack.config.js
Labels: bug, release-0.11.1

#1061 [DEVOPS-1020] add logs in dev mode and nix improvements
  .gitignore
  shell.nix
  source/main/utils/getRuntimeFolderPath.js
Labels: chore, release-0.11.1

#1042 [DDW-358] V1 API endpoints integration 4/5
  CHANGELOG.md
  source/renderer/app/api/ada/changeAdaWalletPassphrase.js
  source/renderer/app/api/ada/deleteAdaWallet.js
  source/renderer/app/api/ada/index.js
  source/renderer/app/api/ada/lib/encryptPassphrase.js
  source/renderer/app/api/ada/lib/v1/request.js
  source/renderer/app/api/ada/nextAdaUpdate.js
  source/renderer/app/api/ada/types.js
  source/renderer/app/api/ada/updateAdaWallet.js
  source/renderer/app/api/common.js
  source/renderer/app/api/etc/etcLocalStorage.js
  source/renderer/app/domains/Wallet.js
  source/renderer/app/stores/ada/AdaWalletSettingsStore.js
  source/renderer/app/types/transactionAssuranceTypes.js
Labels: feature

#1045 [DDW-359] V1 API endpoints integration 5/5
  source/renderer/app/api/ada/getAdaLocalTimeDifference.js
  source/renderer/app/api/ada/getAdaSyncProgress.js
  source/renderer/app/api/ada/getNodeInfo.js
  source/renderer/app/api/ada/index.js
  source/renderer/app/api/ada/types.js
  source/renderer/app/api/common.js
  source/renderer/app/stores/NetworkStatusStore.js
Labels: feature

#1067 [DDW-400] Dynamic Api port
  CHANGELOG.md
  source/renderer/app/api/ada/adaTestReset.js
  source/renderer/app/api/ada/adaTxFee.js
  source/renderer/app/api/ada/applyAdaUpdate.js
  source/renderer/app/api/ada/changeAdaWalletPassphrase.js
  source/renderer/app/api/ada/deleteAdaWallet.js
  source/renderer/app/api/ada/exportAdaBackupJSON.js
  source/renderer/app/api/ada/getAdaAccounts.js
  source/renderer/app/api/ada/getAdaAddressHistory.js
  source/renderer/app/api/ada/getAdaHistory.js
  source/renderer/app/api/ada/getAdaHistoryByAccount.js
  source/renderer/app/api/ada/getAdaHistoryByWallet.js
  source/renderer/app/api/ada/getAdaLocalTimeDifference.js
  source/renderer/app/api/ada/getAdaSyncProgress.js
  source/renderer/app/api/ada/getAdaWalletAccounts.js
  source/renderer/app/api/ada/getAdaWallets.js
  source/renderer/app/api/ada/importAdaBackupJSON.js
  source/renderer/app/api/ada/importAdaWallet.js
  source/renderer/app/api/ada/index.js
  source/renderer/app/api/ada/isValidAdaAddress.js
  source/renderer/app/api/ada/lib/request.js
  source/renderer/app/api/ada/lib/v1/request.js
  source/renderer/app/api/ada/newAdaAccount.js
  source/renderer/app/api/ada/newAdaPayment.js
  source/renderer/app/api/ada/newAdaWallet.js
  source/renderer/app/api/ada/newAdaWalletAddress.js
  source/renderer/app/api/ada/nextAdaUpdate.js
  source/renderer/app/api/ada/postponeAdaUpdate.js
  source/renderer/app/api/ada/redeemAda.js
  source/renderer/app/api/ada/redeemAdaPaperVend.js
  source/renderer/app/api/ada/restoreAdaWallet.js
  source/renderer/app/api/ada/types.js
  source/renderer/app/api/ada/updateAdaWallet.js
  source/renderer/app/api/index.js
Labels: chore

#1072 [DDW-405] add tls-auth params to api config
  CHANGELOG.md
  source/main/utils/setupTls.js
  source/renderer/app/api/ada/adaTestReset.js
  source/renderer/app/api/ada/adaTxFee.js
  source/renderer/app/api/ada/applyAdaUpdate.js
  source/renderer/app/api/ada/changeAdaWalletPassphrase.js
  source/renderer/app/api/ada/deleteAdaWallet.js
  source/renderer/app/api/ada/exportAdaBackupJSON.js
  source/renderer/app/api/ada/getAdaAccounts.js
  source/renderer/app/api/ada/getAdaAddressHistory.js
  source/renderer/app/api/ada/getAdaHistory.js
  source/renderer/app/api/ada/getAdaHistoryByAccount.js
  source/renderer/app/api/ada/getAdaHistoryByWallet.js
  source/renderer/app/api/ada/getAdaLocalTimeDifference.js
  source/renderer/app/api/ada/getAdaSyncProgress.js
  source/renderer/app/api/ada/getAdaWalletAccounts.js
  source/renderer/app/api/ada/getAdaWallets.js
  source/renderer/app/api/ada/importAdaBackupJSON.js
  source/renderer/app/api/ada/importAdaWallet.js
  source/renderer/app/api/ada/isValidAdaAddress.js
  source/renderer/app/api/ada/lib/request.js
  source/renderer/app/api/ada/lib/v1/request.js
  source/renderer/app/api/ada/newAdaAccount.js
  source/renderer/app/api/ada/newAdaPayment.js
  source/renderer/app/api/ada/newAdaWallet.js
  source/renderer/app/api/ada/newAdaWalletAddress.js
  source/renderer/app/api/ada/nextAdaUpdate.js
  source/renderer/app/api/ada/postponeAdaUpdate.js
  source/renderer/app/api/ada/redeemAda.js
  source/renderer/app/api/ada/redeemAdaPaperVend.js
  source/renderer/app/api/ada/restoreAdaWallet.js
  source/renderer/app/api/ada/types.js
  source/renderer/app/api/ada/updateAdaWallet.js
  source/renderer/app/api/index.js
Labels: feature
