Repository input-output-hk/daedalus, pull requests merged in 2018-04, with the labels that each got.

#818 Chore/DDW-205 Remove remote logging
  CHANGELOG.md
  features/agree-to-send-logs.feature
  features/local-time-difference.feature
  features/navigate-general-settings-menu.feature
  features/step_definitions/agree-to-send-logs.js
  features/step_definitions/general-settings-steps.js
  features/step_definitions/setup-steps.js
  features/support/helpers/send-logs-choice-helpers.js
  features/transactions-grouping.feature
  package-lock.json
  package.json
  source/common/logging.js
  source/main/utils/remoteLog.js
  source/main/utils/setupLogging.js
  source/renderer/app/Routes.js
  source/renderer/app/actions/profile-actions.js
  source/renderer/app/api/localStorage/index.js
  source/renderer/app/components/profile/send-logs-choice-form/SendLogsChoiceForm.js
  source/renderer/app/components/profile/send-logs-choice-form/SendLogsChoiceForm.scss
  source/renderer/app/components/settings/categories/SupportSettings.js
  source/renderer/app/components/settings/categories/SupportSettings.scss
  source/renderer/app/containers/profile/SendLogsChoicePage.js
  source/renderer/app/containers/profile/dialogs/BugReportDialogContainer.js
  source/renderer/app/containers/settings/categories/SupportSettingsPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/routes-config.js
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/ProfileStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  yarn.lock
Labels: chore

#835 Fix/ddw 212 Fix missing application menu on Windows build
  electron/menus/win-linux.js
Labels: bug

#837 [DEVOPS-775] create the shortcut on the desktop after copying the binaries and creating certs
  installers/WindowsInstaller.hs
Labels: bug

#833 Chore/ddw 165 Daedalus logs should be in UTC instead of local time
  CHANGELOG.md
  source/main/utils/setupLogging.js
Labels: chore

#832 Chore/ddw 156 Clicking outside of the dialogs should not close them during wallet creation
  source/renderer/app/components/wallet/backup-recovery/WalletBackupPrivacyWarningDialog.js
  source/renderer/app/components/wallet/backup-recovery/WalletRecoveryPhraseDisplayDialog.js
  source/renderer/app/components/wallet/backup-recovery/WalletRecoveryPhraseEntryDialog.js
Labels: chore

#830 Chore/ddw 193 About dialog micro issue
  source/renderer/app/components/static/About.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: chore

#827 Chore/ddw 175 Improve Dark blue theme styling of update and restoration notifications
  source/renderer/app/components/layout/SidebarLayout.scss
  source/renderer/app/components/notifications/NodeUpdateNotification.scss
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
Labels: chore

#826 Chore/ddw 171 Print Daedalus version in application title
  source/common/environment.js
  source/main/windows/main.js
  source/renderer/app/components/static/About.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
Labels: chore

#824 Fix/ddw 150 Send manual bug report wrong text color in Dark blue theme
  source/renderer/app/components/profile/bug-report/BugReportDialog.scss
Labels: bug

#825 Fix/ddw 155 Transaction with 0 confirmations should be in pending
  source/renderer/app/components/wallet/transactions/Transaction.js
Labels: bug

#828 Chore/ddw 126 Bug report dialog logs alphabetical ordering
  source/main/ipc-api/get-logs.js
  source/renderer/app/themes/daedalus/dark-blue.js
Labels: chore

#829 Chore/ddw 146 "Attach logs" should be on by default for support requests
  source/renderer/app/actions/profile-actions.js
  source/renderer/app/components/profile/bug-report/BugReportDialog.js
  source/renderer/app/containers/profile/dialogs/BugReportDialogContainer.js
  source/renderer/app/stores/ProfileStore.js
Labels: chore

#840 [CSL-2435] Use 'TextEncoder' to measure correct length of UTF-8 strings
  CHANGELOG.md
  app/api/ada/lib/request.js
  features/wallet-settings.feature
Labels: bug

#839 [CSL-2435] Use 'TextEncoder' to measure correct length of UTF-8 strings
  CHANGELOG.md
  features/wallet-settings.feature
  source/renderer/app/api/ada/lib/request.js
Labels: bug

#843 Merge master into develop after release/0.9.1
  .buildkite/pipeline.yml
  .travis.yml
  CHANGELOG.md
  app/api/ada/lib/request.js
  app/i18n/locales/en-US.json
  app/i18n/locales/ja-JP.json
  app/stores/TransactionsStore.js
  appveyor.yml
  electron/main.development.js
  electron/menus/osx.js
  electron/menus/win-linux.js
  features/wallet-settings.feature
  installers/WindowsInstaller.hs
  package.json
Labels: chore

#846 Feature/ddw 176 change add wallet dialog to render in page
  features/add-wallet-via-sidebar.feature
  features/import-wallet-via-sidebar.feature
  features/paper-wallets-certificate.feature
  features/restore-wallet-via-sidebar.feature
  features/step_definitions/wallets-steps.js
  features/support/helpers/add-wallet-page-helpers.js
  features/support/helpers/dialogs/add-wallet-dialog-helpers.js
  source/common/environment.js
  source/renderer/app/Routes.js
  source/renderer/app/actions/network-status-actions.js
  source/renderer/app/actions/sidebar-actions.js
  source/renderer/app/components/layout/TopBar.js
  source/renderer/app/components/sidebar/Sidebar.js
  source/renderer/app/components/wallet/WalletAdd.js
  source/renderer/app/components/wallet/WalletAdd.scss
  source/renderer/app/components/wallet/WalletAddDialog.scss
  source/renderer/app/components/wallet/WalletRestoreDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/CompletionDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/InstructionsDialog.js
  source/renderer/app/components/widgets/BigButtonForDialogs.js
  source/renderer/app/containers/MainLayout.js
  source/renderer/app/containers/TopBarContainer.js
  source/renderer/app/containers/etc/MainLayout.js
  source/renderer/app/containers/profile/LanguageSelectionPage.js
  source/renderer/app/containers/profile/TermsOfUsePage.js
  source/renderer/app/containers/wallet/NoWalletsPage.js
  source/renderer/app/containers/wallet/WalletAddPage.js
  source/renderer/app/containers/wallet/dialogs/WalletAddDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/paper-wallet-certificate/CompletionDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/paper-wallet-certificate/InstructionsDialogContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/routes-config.js
  source/renderer/app/stores/AppStore.js
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/SidebarStore.js
  source/renderer/app/stores/WalletStore.js
  source/renderer/app/stores/ada/AdaWalletsStore.js
  source/renderer/webpack.config.js
  storybook/stories/AddWallet.stories.js
  storybook/stories/PaperWallets.stories.js
  storybook/stories/Sidebar.stories.js
  storybook/stories/WalletTransactionsList.stories.js
Labels: feature

#848 Feature/ddw 209 Add "Show more transactions" button on summary screen
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/components/wallet/transactions/WalletTransactionsList.js
  source/renderer/app/components/wallet/transactions/WalletTransactionsList.scss
  source/renderer/app/containers/wallet/WalletSummaryPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
Labels: feature

#852 Chore/ddw 204 Update NTP Api endpoint handling
  CHANGELOG.md
  source/renderer/app/api/ada/index.js
  source/renderer/app/components/loading/Loading.js
  source/renderer/app/components/loading/SystemTimeErrorOverlay.js
  source/renderer/app/containers/LoadingPage.js
  source/renderer/app/containers/etc/LoadingPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/NetworkStatusStore.js
Labels: chore

#855 [DDW-213] updated to electron 1.7.13
  package-lock.json
  package.json
  yarn.lock
Labels: bug

#850 Fix/ddw 202 UI improvements
  CHANGELOG.md
  source/common/environment.js
  source/main/ipc-api/get-logs.js
  source/main/windows/main.js
  source/renderer/app/actions/profile-actions.js
  source/renderer/app/assets/images/ada-logo.inline.svg
  source/renderer/app/components/layout/SidebarLayout.scss
  source/renderer/app/components/notifications/NodeUpdateNotification.scss
  source/renderer/app/components/profile/bug-report/BugReportDialog.js
  source/renderer/app/components/profile/bug-report/BugReportDialog.scss
  source/renderer/app/components/settings/categories/SupportSettings.scss
  source/renderer/app/components/static/About.js
  source/renderer/app/components/wallet/WalletReceive.js
  source/renderer/app/components/wallet/WalletReceive.scss
  source/renderer/app/components/wallet/backup-recovery/WalletBackupPrivacyWarningDialog.js
  source/renderer/app/components/wallet/backup-recovery/WalletRecoveryPhraseDisplayDialog.js
  source/renderer/app/components/wallet/backup-recovery/WalletRecoveryPhraseEntryDialog.js
  source/renderer/app/components/wallet/etc/WalletReceive.js
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/components/wallet/transactions/Transaction.scss
  source/renderer/app/components/wallet/transactions/WalletTransactionsList.js
  source/renderer/app/components/wallet/transactions/WalletTransactionsList.scss
  source/renderer/app/components/widgets/forms/AdaCertificateUploadWidget.scss
  source/renderer/app/containers/profile/dialogs/BugReportDialogContainer.js
  source/renderer/app/containers/wallet/WalletSummaryPage.js
  source/renderer/app/containers/wallet/WalletTransactionsPage.js
  source/renderer/app/containers/wallet/etc/WalletTransactionsPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/ProfileStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
Labels: bug, chore

#856 Feature/ddw 181 Setting "spending password" should be on by default
  CHANGELOG.md
  features/add-wallet-via-sidebar.feature
  features/restore-wallet-via-sidebar.feature
  features/step_definitions/wallets-steps.js
  source/renderer/app/components/wallet/WalletCreateDialog.js
  source/renderer/app/components/wallet/WalletRestoreDialog.js
  source/renderer/app/components/wallet/settings/ChangeWalletPasswordDialog.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
Labels: feature

#859 Chore/ddw 215 Bug reporting feature should display support page
  CHANGELOG.md
  source/renderer/app/components/settings/categories/SupportSettings.scss
  source/renderer/app/components/sidebar/Sidebar.js
  source/renderer/app/containers/MainLayout.js
  source/renderer/app/containers/etc/MainLayout.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
Labels: chore

#860 Chore/ddw 163 Improve timers setup on Loading screen
  CHANGELOG.md
  source/renderer/app/components/loading/Loading.js
Labels: chore

#862 Feature/ddw 228 Wallet restore indicator in sidebar
  CHANGELOG.md
  source/renderer/app/components/sidebar/wallets/SidebarWalletMenuItem.js
  source/renderer/app/components/sidebar/wallets/SidebarWalletMenuItem.scss
  source/renderer/app/components/sidebar/wallets/SidebarWalletsMenu.js
  source/renderer/app/components/widgets/ProgressBar.js
  source/renderer/app/components/widgets/ProgressBar.scss
  source/renderer/app/stores/SidebarStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
Labels: feature

#861 Chore/ddw 229 Tell user that only one wallet can be restored at the same time
  CHANGELOG.md
  source/renderer/app/components/loading/Loading.js
  source/renderer/app/components/notifications/RestoreNotification.scss
  source/renderer/app/components/wallet/WalletAdd.js
  source/renderer/app/components/wallet/WalletAdd.scss
  source/renderer/app/components/wallet/transactions/WalletTransactionsList.js
  source/renderer/app/containers/wallet/WalletAddPage.js
  source/renderer/app/containers/wallet/dialogs/WalletFileImportDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/WalletRestoreDialogContainer.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
Labels: chore

#806 [DEVOPS-13] Dhall configs derived
  .nonsense
  appveyor.yml
  cardano-sl-src.json
  default.nix
  installers/Config.hs
  installers/Installer.hs
  installers/MacInstaller.hs
  installers/README.md
  installers/Types.hs
  installers/WindowsInstaller.hs
  installers/daedalus-installer.cabal
  installers/dhall/cluster.type
  installers/dhall/launcher.dhall
  installers/dhall/linux.dhall
  installers/dhall/linux64.dhall
  installers/dhall/macos64.dhall
  installers/dhall/mainnet.dhall
  installers/dhall/os.type
  installers/dhall/staging.dhall
  installers/dhall/win64.dhall
  installers/nix/linux.nix
  scripts/build-installer-nix.sh
  scripts/build-installer-unix.sh
  scripts/build-installer-win64.bat
  source/main/webpack.config.js
  source/renderer/webpack.config.js
  yarn2nix.nix
Labels: release-0.10.0

#867 Fix/ddw 224 Dark blue theme UI improvements and fix for missing launcher-config.yaml in local development
  launcher-config.yaml
  source/renderer/app/components/layout/SidebarLayout.scss
  source/renderer/app/components/layout/TopBar.scss
  source/renderer/app/components/layout/TopBarLayout.scss
  source/renderer/app/components/notifications/NodeUpdateNotification.scss
  source/renderer/app/components/notifications/RestoreNotification.scss
  source/renderer/app/components/settings/menu/SettingsMenuItem.scss
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
Labels: bug, release-0.10.0

#865 [CSL-2472] detect a lack of SSE4 during the install
  default.nix
  installers/nix/nix-installer.nix
Labels: release-0.10.0

#844 [DEVOPS-13] changes based on feedback from the community
  default.nix
Labels: release-0.10.0

#871 Fix/ddw 237 Update paper wallet certificate generation to use more random bits
  CHANGELOG.md
  features/import-wallet-via-sidebar.feature
  features/paper-wallets-certificate.feature
  features/restore-wallet-via-sidebar.feature
  features/step_definitions/paper-wallets-certificate-steps.js
  package-lock.json
  package.json
  source/renderer/app/api/ada/getAdaWalletRecoveryPhraseFromCertificate.js
  source/renderer/app/api/ada/index.js
  source/renderer/app/assets/images/paper-wallet-certificate/certificate.png
  source/renderer/app/assets/pdf/paper-wallet-certificate-page-2.inline.svg
  source/renderer/app/components/wallet/WalletRestoreDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/InstructionsDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/PrintDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/VerificationDialog.js
  source/renderer/app/config/paperWalletsConfig.js
  source/renderer/app/containers/wallet/PaperWalletCreateCertificatePage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/ada/AdaWalletsStore.js
  source/renderer/app/utils/crypto.js
  source/renderer/app/utils/paperWalletPdfGenerator.js
  yarn.lock
Labels: bug, release-0.10.0

#872 Chore/ddw 240 Update teams on About dialog
  CHANGELOG.md
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: chore, release-0.10.0

#875 Chore/merge release into develop
  CHANGELOG.md
  appveyor.yml
  cardano-sl-src.json
  default.nix
  installers/AppVeyor.hs
  installers/nix/nix-installer.nix
  package.json
  source/renderer/app/components/layout/SidebarLayout.scss
  source/renderer/app/components/layout/TopBar.scss
  source/renderer/app/components/layout/TopBarLayout.scss
  source/renderer/app/components/notifications/NodeUpdateNotification.scss
  source/renderer/app/components/notifications/RestoreNotification.scss
  source/renderer/app/components/settings/menu/SettingsMenuItem.scss
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
Labels: chore

#880 Fix/ddw 241 Extend About dialog height to accommodate increased team members list
  CHANGELOG.md
  source/main/windows/about.js
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: bug, release-0.10.0

#878 [DEVOPS-807] Installer filename consistency and bump version 1.1 -> 1.2.0
  .buildkite/pipeline.yml
  appveyor.yml
  installers/WindowsInstaller.hs
  release.nix
  scripts/build-installer-nix.sh
  scripts/build-installer-unix.sh
  scripts/build-installer-win64.bat
Labels: release-0.10.0

#881 Chore/ddw 239 Refactor magic numbers into constants
  CHANGELOG.md
  source/renderer/app/api/ada/getAdaWalletCertificateAdditionalMnemonics.js
  source/renderer/app/api/ada/index.js
  source/renderer/app/api/ada/types.js
  source/renderer/app/components/loading/Loading.js
  source/renderer/app/components/profile/bug-report/BugReportDialog.js
  source/renderer/app/components/sidebar/Sidebar.js
  source/renderer/app/components/wallet/WalletBackupDialog.js
  source/renderer/app/components/wallet/WalletCreateDialog.js
  source/renderer/app/components/wallet/WalletRestoreDialog.js
  source/renderer/app/components/wallet/WalletSendConfirmationDialog.js
  source/renderer/app/components/wallet/WalletSendForm.js
  source/renderer/app/components/wallet/ada-redemption/AdaRedemptionChoices.js
  source/renderer/app/components/wallet/ada-redemption/AdaRedemptionForm.js
  source/renderer/app/components/wallet/etc/WalletSendConfirmationDialog.js
  source/renderer/app/components/wallet/etc/WalletSendForm.js
  source/renderer/app/components/wallet/file-import/WalletFileImportDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/InstructionsDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/PrintDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/SecuringPasswordDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/VerificationDialog.js
  source/renderer/app/components/wallet/settings/ChangeWalletPasswordDialog.js
  source/renderer/app/components/wallet/settings/DeleteWalletConfirmationDialog.js
  source/renderer/app/components/wallet/settings/export-to-file/WalletExportToFileDialog.js
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/components/wallet/transactions/TransactionTypeIcon.js
  source/renderer/app/components/widgets/forms/InlineEditingInput.js
  source/renderer/app/config.js
  source/renderer/app/config/ada/sidebarConfig.js
  source/renderer/app/config/cryptoConfig.js
  source/renderer/app/config/formattingConfig.js
  source/renderer/app/config/numbersConfig.js
  source/renderer/app/config/paperWalletsConfig.js
  source/renderer/app/config/sidebarConfig.js
  source/renderer/app/config/timingConfig.js
  source/renderer/app/config/transactionAssuranceConfig.js
  source/renderer/app/config/urlsConfig.js
  source/renderer/app/containers/wallet/AdaRedemptionPage.js
  source/renderer/app/containers/wallet/WalletReceivePage.js
  source/renderer/app/containers/wallet/etc/WalletReceivePage.js
  source/renderer/app/domains/Wallet.js
  source/renderer/app/domains/WalletTransaction.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/WalletBackupStore.js
  source/renderer/app/stores/WalletSettingsStore.js
  source/renderer/app/stores/WalletStore.js
  source/renderer/app/stores/ada/AdaRedemptionStore.js
  source/renderer/app/stores/ada/AdaWalletsStore.js
  source/renderer/app/stores/ada/NodeUpdateStore.js
  source/renderer/app/stores/etc/EtcWalletsStore.js
  source/renderer/app/types/redemptionTypes.js
  source/renderer/app/types/transactionAssuranceTypes.js
  source/renderer/app/types/walletBackupTypes.js
Labels: chore

#870 Chore/ddw 219 Add acceptance tests for transactions display
  CHANGELOG.md
  features/import-wallet-via-sidebar.feature
  features/paper-wallets-certificate.feature
  features/send-money-to-receiver.feature
  features/step_definitions/transactions-steps.js
  features/step_definitions/wallets-steps.js
  features/support/helpers/shared-helpers.js
  features/transactions-display.feature
  features/transactions-grouping.feature
  source/renderer/app/api/ada/index.js
  source/renderer/app/components/wallet/WalletSendForm.js
  source/renderer/app/components/wallet/etc/WalletSendConfirmationDialog.js
  source/renderer/app/components/wallet/etc/WalletSendForm.js
  source/renderer/app/components/wallet/skins/AmountInputSkin.js
  source/renderer/app/components/wallet/skins/etc/AmountInputSkin.js
  source/renderer/app/containers/wallet/dialogs/WalletSendConfirmationDialogContainer.js
  source/renderer/app/domains/Wallet.js
  source/renderer/app/stores/ada/AdaRedemptionStore.js
  source/renderer/app/stores/ada/AdaTransactionsStore.js
  source/renderer/app/stores/ada/AdaWalletsStore.js
  source/renderer/app/stores/ada/AddressesStore.js
Labels: chore

#885 Fix/ddw 242 Step for active restore notification is too fragile
  CHANGELOG.md
  features/step_definitions/wallets-steps.js
  features/support/helpers/notifications-helpers.js
Labels: chore

#884 Chore/ddw 206 Create PR template with review checklist
  .github/pull_request_template.md
  CHANGELOG.md
Labels: chore

#888 Fix/ddw 247 Fix paper wallet QR code issues on Confirmation dialog
  source/renderer/app/components/wallet/paper-wallet-certificate/CompletionDialog.js
Labels: bug, release-0.10.0

#887 Fix/ddw 244 Delete logs.zip on support dialog mount
  source/renderer/app/actions/profile-actions.js
  source/renderer/app/components/profile/bug-report/BugReportDialog.js
  source/renderer/app/containers/profile/dialogs/BugReportDialogContainer.js
  source/renderer/app/containers/settings/categories/SupportSettingsPage.js
  source/renderer/app/stores/ProfileStore.js
Labels: bug, release-0.10.0

#889 Fix/ddw 251 Fix broken Ada redemption
  source/renderer/app/stores/ada/AdaRedemptionStore.js
Labels: bug
