Repository input-output-hk/daedalus, pull requests merged in 2018-07, with the labels that each got.

#1000 [DDW-345] Add Cardano version to Daedalus titlebar
  source/common/environment.js
  source/main/windows/main.js
  source/renderer/app/api/ada/sendAdaBugReport.js
  source/renderer/app/api/etc/sendEtcBugReport.js
  source/renderer/app/components/static/About.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/utils/paperWalletPdfGenerator.js
Labels: bug, release-0.11.0

#1001 [DDW-345] Add Cardano version to Daedalus titlebar - Code style improvements
  source/common/environment.js
  source/main/windows/main.js
  source/renderer/app/i18n/locales/defaultMessages.json
Labels: chore, release-0.11.0

#996 [DDW-221] Prevent wallet data polling during wallet deletion
  CHANGELOG.md
  source/renderer/app/stores/ada/AdaWalletsStore.js
Labels: bug

#999 [DDW-341] Improve paper wallet certificate QR code compatibility
  CHANGELOG.md
  source/renderer/app/utils/paperWalletPdfGenerator.js
Labels: bug, release-0.11.1

#998 [DDW-340] Fix wallet export feature
  CHANGELOG.md
  source/main/webpack.config.js
  source/renderer/app/components/wallet/WalletSettings.js
  source/renderer/app/components/wallet/etc/WalletSettings.js
  source/renderer/app/components/wallet/settings/DeleteWalletConfirmationDialog.scss
  source/renderer/app/components/wallet/settings/ExportWalletToFileDialog.js
  source/renderer/app/components/wallet/settings/ExportWalletToFileDialog.scss
  source/renderer/app/containers/wallet/WalletSettingsPage.js
  source/renderer/app/containers/wallet/dialogs/settings/ChangeWalletPasswordDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/settings/DeleteWalletDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/settings/ExportWalletToFileDialogContainer.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/webpack.config.js
  storybook/stories/DeleteWalletConfirmationDialog.stories.js
  storybook/stories/ExportWalletToFileDialog.stories.js
  storybook/stories/WalletScreens.stories.js
  storybook/stories/index.js
Labels: bug

#1003 [DDW-349] Open About dialog links in a new browser window
  source/renderer/app/components/static/About.js
  source/renderer/app/components/static/About.scss
  source/renderer/app/containers/static/AboutDialog.js
Labels: bug, release-0.11.0

#1004 [DEVOPS-943] release.nix: pass buildNum to installer
  release.nix
Labels: release-0.11.0

#1002 [DDW-347] Fix send form validation and improve restore dialog UX
  source/renderer/app/components/wallet/WalletSendConfirmationDialog.js
  source/renderer/app/components/wallet/WalletSendForm.js
  source/renderer/app/components/widgets/Dialog.js
Labels: bug

#995 [DDW-248] Refactor compress/download logs handling
  CHANGELOG.md
  source/common/fileName.js
  source/common/ipc-api.js
  source/main/ipc-api/compress-logs.js
  source/main/ipc-api/delete-compressed-logs.js
  source/main/ipc-api/index.js
  source/main/utils/setupLogging.js
  source/renderer/app/actions/profile-actions.js
  source/renderer/app/api/ada/sendAdaBugReport.js
  source/renderer/app/api/etc/sendEtcBugReport.js
  source/renderer/app/api/lib/reportRequest.js
  source/renderer/app/components/profile/bug-report/BugReportDialog.js
  source/renderer/app/components/settings/categories/SupportSettings.scss
  source/renderer/app/components/widgets/DialogCloseButton.js
  source/renderer/app/components/widgets/DialogCloseButton.scss
  source/renderer/app/containers/profile/dialogs/BugReportDialogContainer.js
  source/renderer/app/containers/settings/categories/SupportSettingsPage.js
  source/renderer/app/stores/ProfileStore.js
  source/renderer/app/types/LogTypes.js
Labels: chore

#1014 [DDW-362] Fixate all npm dependencies and update script names
  gulpfile.js
  package.json
  yarn.lock
Labels: chore

#1011 [DDW-354] Merge release/0.11.0 into develop branch
  .eslintrc
  CHANGELOG.md
  cardano-sl-src.json
  default.nix
  installers/Spec.hs
  installers/common/Config.hs
  installers/common/MacInstaller.hs
  installers/common/Types.hs
  installers/common/Util.hs
  installers/common/WindowsInstaller.hs
  package.json
  release.nix
  scripts/build-installer-nix.sh
  scripts/build-installer-win64.bat
  source/common/environment.js
  source/main/webpack.config.js
  source/main/windows/main.js
  source/renderer/app/api/ada/sendAdaBugReport.js
  source/renderer/app/api/etc/sendEtcBugReport.js
  source/renderer/app/api/lib/reportRequest.js
  source/renderer/app/components/static/About.js
  source/renderer/app/components/static/About.scss
  source/renderer/app/containers/static/AboutDialog.js
  source/renderer/app/i18n/global-messages.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/utils/paperWalletPdfGenerator.js
  source/renderer/webpack.config.js
  yarn2nix.nix
Labels: DO NOT MERGE, chore

#1017 [DDW-353] pin eslint-scope version via the yarn resolutions feature
  package.json
  yarn.lock
Labels: bug

#1019 [DDW-342] fix white screen rendering bug
  CHANGELOG.md
  package-lock.json
  package.json
  source/common/ipc-api.js
  source/main/index.js
  source/main/ipc-api/get-gpu-status.js
  source/main/ipc-api/index.js
  source/main/menus/osx.js
  source/main/menus/win-linux.js
  source/main/utils/mainErrorHandler.js
  source/main/utils/rendererErrorHandler.js
  source/main/windows/main.js
  source/renderer/app/actions/app-actions.js
  source/renderer/app/stores/AppStore.js
  source/renderer/app/types/gpuStatus.js
  yarn.lock
Labels: bug, release-0.11.1

#1027 [DDW-369] Disable nodeLogPath in dhall files
  installers/dhall/linux64.dhall
  installers/dhall/macos64.dhall
  installers/dhall/os.type
  installers/dhall/win64.dhall
Labels: release-0.11.0

#1020 [DDW-370] add antivirus restoration slowdown notification component t…
  CHANGELOG.md
  source/common/environment.js
  source/renderer/app/actions/ada/wallets-actions.js
  source/renderer/app/components/notifications/AntivirusRestaurationSlowdownNotification.js
  source/renderer/app/components/notifications/AntivirusRestaurationSlowdownNotification.scss
  source/renderer/app/components/settings/categories/SupportSettings.js
  source/renderer/app/containers/wallet/Wallet.js
  source/renderer/app/i18n/global-messages.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/WalletStore.js
  storybook/stories/AntivirusRestaurationSlowdownNotification.stories.js
  storybook/stories/index.js
Labels: feature

#1007 [DDW-342] fix white screen rendering bug
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  shell.nix
  source/common/environment.js
  source/common/ipc-api.js
  source/main/index.js
  source/main/ipc-api/get-gpu-status.js
  source/main/ipc-api/index.js
  source/main/menus/osx.js
  source/main/menus/win-linux.js
  source/main/utils/mainErrorHandler.js
  source/main/utils/rendererErrorHandler.js
  source/main/windows/main.js
  source/renderer/app/actions/app-actions.js
  source/renderer/app/stores/AppStore.js
  source/renderer/app/types/gpuStatus.js
  yarn.lock
Labels: WIP, bug
