Repository input-output-hk/daedalus, pull requests merged in 2018-11, with the labels that each got.

#1159 [DDW-453] Inject missing Japanese translations
  CHANGELOG.md
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
Labels: chore, release-0.12.0

#1154 [DEVOPS-1086] fault injection to develop
  README.md
  features/data-layer-migration.feature
  features/node-update-exit.feature
  features/node-update-notification.feature
  features/quit-app.feature
  features/step_definitions/app-steps.js
  features/step_definitions/cardano-steps.js
  features/step_definitions/helper-steps.js
  features/support/electron.js
  features/support/global-types.js
  features/support/helpers/app-helpers.js
  features/support/helpers/cardano-node-helpers.js
  package.json
  source/common/ipc/cardano.ipc.js
  source/common/types/cardanoNode.types.js
  source/main/cardano/CardanoNode.js
  source/main/cardano/setup.js
  source/main/cardano/utils.js
  source/main/ipc/cardano.ipc.js
  source/main/utils/processes.js
  source/main/windows/main.js
  source/renderer/app/actions/window-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/ipc/cardano.ipc.js
  source/renderer/app/stores/WindowStore.js
  source/renderer/app/utils/index.js
  yarn.lock
Labels: chore, release-0.13.0

#1160 Merge release/0.12.0 into develop branch
  CHANGELOG.md
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
Labels: chore

#1162 [DDW-462] Use "taskkill" to kill processes with pid on Windows
  CHANGELOG.md
  source/main/cardano/CardanoNode.js
  source/main/cardano/setup.js
Labels: bug, release-0.12.0

#1163 Merge release/0.12.0 into develop branch
  CHANGELOG.md
  cardano-sl-src.json
  source/main/cardano/CardanoNode.js
  source/main/cardano/setup.js
Labels: chore

#1166 [DDW-483, DDW-485] Fix missing launcher config error message and prevent orphan processes after app quit
  CHANGELOG.md
  source/main/config.js
  source/main/index.js
Labels: bug, release-0.12.0

#1164 [DDW-464] Removes Antivirus notification
  CHANGELOG.md
  source/main/index.js
  source/renderer/app/actions/wallets-actions.js
  source/renderer/app/components/notifications/AntivirusRestaurationSlowdownNotification.js
  source/renderer/app/components/notifications/AntivirusRestaurationSlowdownNotification.scss
  source/renderer/app/containers/wallet/Wallet.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/WalletsStore.js
  storybook/stories/AntivirusRestaurationSlowdownNotification.stories.js
  storybook/stories/index.js
Labels: bug, release-0.13.0

#1165 [DDW-484] Change Daedalus fullscreen mode to maximize, on Linux, to keep the menus usable
  source/main/menus/win-linux.js
Labels: feature, release-0.12.0

#1168 [DDW-486] Wallet Import & Export functionality is not implemented but UI is exposed in TestNet build.
  CHANGELOG.md
  source/renderer/app/components/wallet/WalletAdd.js
  source/renderer/app/components/wallet/WalletSettings.js
Labels: chore, release-0.12.0

#1170 [DDW-490] Use a small icon for the window and a large icon for the desktop
  CHANGELOG.md
  default.nix
  shell.nix
Labels: bug, release-0.12.0

#1169 [DDW-489] Fix an edge-case error message when Daedalus is not started…
  CHANGELOG.md
  source/main/config.js
Labels: bug, release-0.12.0

#1173 [DDW-488] Amount field minor malfunction
  CHANGELOG.md
  package.json
  yarn.lock
Labels: bug, release-0.12.0

#1175 Merge release/0.12.0 into develop branch
  CHANGELOG.md
  default.nix
  package.json
  shell.nix
  source/common/environment.js
  source/main/config.js
  source/main/index.js
  source/main/menus/win-linux.js
  source/renderer/app/components/wallet/WalletAdd.js
  source/renderer/app/components/wallet/WalletSettings.js
  yarn.lock
Labels: chore

#1139 [DDW-376] Cleanup SimpleTheme Config in Daedalus
  CHANGELOG.md
  features/step_definitions/paper-wallets-certificate-steps.js
  features/step_definitions/wallets-steps.js
  package.json
  source/renderer/app/App.js
  source/renderer/app/themes/daedalus.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/mixins/error-message.scss
  source/renderer/app/themes/overrides/AutocompleteOverrides.scss
  source/renderer/app/themes/overrides/ButtonOverrides.scss
  source/renderer/app/themes/overrides/ModalOverrides.scss
  source/renderer/app/themes/overrides/SwitchOverrides.scss
  source/renderer/app/themes/overrides/index.js
  source/renderer/app/themes/simple/SimpleBubble.scss
  source/renderer/app/themes/simple/SimpleCheckbox.scss
  source/renderer/app/themes/simple/SimpleFormField.scss
  source/renderer/app/themes/simple/SimpleInput.scss
  source/renderer/app/themes/simple/SimpleOptions.scss
  source/renderer/app/themes/simple/SimpleSelect.scss
  source/renderer/app/themes/simple/SimpleSwitch.scss
  source/renderer/app/themes/simple/SimpleTextArea.scss
  source/renderer/app/themes/simple/_config.scss
  yarn.lock
Labels: chore, release-0.13.0

#1176 [DDW-494] Fixes send bug report form after downloading logs
  CHANGELOG.md
  source/renderer/app/stores/ProfileStore.js
Labels: bug, release-0.12.0

#1178 [DDW-496] cache cardano node status between page reloads
  source/common/ipc/cardano.ipc.js
  source/common/ipc/lib/IpcChannel.js
  source/common/types/cardanoNode.types.js
  source/main/cardano/CardanoNode.js
  source/main/cardano/setup.js
  source/main/ipc/cardano.ipc.js
  source/main/ipc/lib/MainIpcChannel.js
  source/renderer/app/ipc/cardano.ipc.js
  source/renderer/app/ipc/lib/RendererIpcChannel.js
  source/renderer/app/stores/NetworkStatusStore.js
Labels: chore, release-0.13.0

#1182 [DEVOPS-1112] Update cardano-sl to latest release/2.0.0 branch
  cardano-sl-src.json
Labels: release-0.12.0

#1183 [DDW-498] Use info instead of debug logger for API calls
  CHANGELOG.md
  source/main/index.js
  source/main/ipc/compress-logs.js
  source/main/utils/setupLogging.js
Labels: chore, release-0.13.0

#1187 [DDW-499] Enable Cardano Wallet API documentation server in development mode
  CHANGELOG.md
  README.md
  source/main/cardano/config.js
Labels: chore, release-0.13.0

#1186 [DDW-501] Prepare Daedalus 0.11.2 release
  CHANGELOG.md
  package.json
Labels: chore, release-0.11.2

#1190 Release/0.11.2
  CHANGELOG.md
  cardano-sl-src.json
  package.json
Labels: release-0.11.2

#1193 Merge master into release/0.12.0 branch
  CHANGELOG.md
Labels: chore, release-0.12.0

#1188 [DDW-502] Enable EKG server for non-mainnet networks
  CHANGELOG.md
  cardano-sl-src.json
  installers/dhall/cluster.type
  installers/dhall/demo.dhall
  installers/dhall/launcher.dhall
  installers/dhall/mainnet.dhall
  installers/dhall/staging.dhall
  installers/dhall/testnet.dhall
  shell.nix
  source/renderer/app/components/status/NetworkStatus.js
  source/renderer/app/config/urlsConfig.js
  source/renderer/app/containers/status/NetworkStatusPage.js
  source/renderer/app/utils/network.js
Labels: feature, release-0.12.0

#1156 [DDW-442] Fix failing apply-node-update test
  .gitignore
  CHANGELOG.md
  features/node-update-exit.feature
  features/support/electron.js
  features/wallet-address-generate.feature
  logs/.keep
  source/main/cardano/setup.js
  source/main/config.js
  source/main/utils/lockFiles.js
Labels: bug, release-0.13.0

#1194 [DDW-504] Daedalus start with time offset to the past
  CHANGELOG.md
  source/renderer/app/components/loading/Loading.js
Labels: bug, release-0.12.0

#1195 Merge release/0.12.0 into develop branch
  CHANGELOG.md
  cardano-sl-src.json
  installers/dhall/cluster.type
  installers/dhall/demo.dhall
  installers/dhall/launcher.dhall
  installers/dhall/mainnet.dhall
  installers/dhall/staging.dhall
  installers/dhall/testnet.dhall
  shell.nix
  source/renderer/app/components/loading/Loading.js
  source/renderer/app/components/status/NetworkStatus.js
  source/renderer/app/components/wallet/summary/WalletSummary.js
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/components/wallet/transactions/WalletTransactionsList.js
  source/renderer/app/config/urlsConfig.js
  source/renderer/app/containers/status/NetworkStatusPage.js
  source/renderer/app/containers/wallet/WalletSummaryPage.js
  source/renderer/app/stores/ProfileStore.js
  source/renderer/app/utils/network.js
  storybook/stories/WalletScreens.stories.js
  storybook/stories/WalletSummary.stories.js
  storybook/stories/WalletTransactionsList.stories.js
Labels: chore, release-0.12.0

#1197 [DDW-497] Adds support for non-Latin characters in spending password
  CHANGELOG.md
  features/wallet-settings.feature
  source/renderer/app/utils/validations.js
Labels: bug, release-0.12.0

#1198 Merge release/0.12.0 into develop branch
  CHANGELOG.md
  features/wallet-settings.feature
Labels: chore, release-0.12.0
