Repository input-output-hk/daedalus, pull requests merged in 2018-12, with the labels that each got.

#1185 [DDW-502] Bump Cardano revision
  cardano-sl-src.json
Labels: chore, release-0.12.0

#1201 [DDW-457] Update flow and mobx dependencies
  .eslintrc
  .flowconfig
  package.json
  source/renderer/app/components/sidebar/wallets/SidebarWalletMenuItem.js
  source/renderer/app/components/wallet/WalletBackupDialog.js
  source/renderer/app/components/widgets/forms/MnemonicInputWidget.js
  source/renderer/app/containers/wallet/WalletReceivePage.js
  source/renderer/app/containers/wallet/dialogs/paper-wallet-certificate/CompletionDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/paper-wallet-certificate/SecuringPasswordDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/paper-wallet-certificate/VerificationDialogContainer.js
  source/renderer/app/index.js
  source/renderer/app/stores/TransactionsStore.js
  source/renderer/app/stores/UiDialogsStore.js
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/stores/index.js
  source/renderer/app/stores/lib/Store.js
  source/renderer/app/types/sidebarTypes.js
  yarn.lock
Labels: chore, release-0.13.0

#1204 [DEVOPS-1166] --metrics is also needed to start EKG
  installers/dhall/demo.dhall
  installers/dhall/staging.dhall
  installers/dhall/testnet.dhall
Labels: bug, release-0.12.0

#1208 [DDW-512] Fix and improve menu code for Windows and Linux
  source/main/menus/MenuActions.types.js
  source/main/menus/osx.js
  source/main/menus/win-linux.js
Labels: bug, release-0.13.0

#1206 [DDW-461] Fix flickering issue on Network Status screen syncing chart
  CHANGELOG.md
  source/renderer/app/components/status/NetworkStatus.scss
Labels: bug, release-0.13.0

#1211 Release 0.12 cardano bump
  cardano-sl-src.json
Labels: chore, release-0.12.0

#1210 Merge release/0.12.0 into develop branch
  cardano-sl-src.json
  installers/dhall/demo.dhall
  installers/dhall/staging.dhall
  installers/dhall/testnet.dhall
Labels: chore, release-0.12.0

#1213 [DDW-518, DDW-519, DDW-520, DDW-521] Improve NTP check handling on system wake-up event
  CHANGELOG.md
  source/renderer/app/components/status/NetworkStatus.js
  source/renderer/app/config/timingConfig.js
  source/renderer/app/containers/status/NetworkStatusPage.js
  source/renderer/app/stores/NetworkStatusStore.js
Labels: bug, release-0.12.0

#1215 [DDW-522] Fix the Cardano setup steps in README file
  CHANGELOG.md
  README.md
Labels: bug, release-0.13.0

#1209 [DDW-508] Design implementation fixes
  CHANGELOG.md
  source/main/windows/main.js
  source/renderer/app/components/loading/SystemTimeErrorOverlay.scss
  source/renderer/app/components/profile/data-layer-migration/DataLayerMigrationForm.scss
  source/renderer/app/components/wallet/WalletRestoreDialog.scss
  source/renderer/app/components/wallet/paper-wallet-certificate/CompletionDialog.scss
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/components/widgets/Dialog.scss
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/overrides/SelectOverrides.scss
  source/renderer/app/themes/overrides/index.js
Labels: bug, release-0.13.0

#1218 Merge release/0.12.0 into develop branch
  CHANGELOG.md
  cardano-sl-src.json
  source/renderer/app/components/status/NetworkStatus.js
  source/renderer/app/config/timingConfig.js
  source/renderer/app/containers/status/NetworkStatusPage.js
  source/renderer/app/stores/NetworkStatusStore.js
Labels: chore, release-0.12.0

#1217 [DDW-523] Ada Redemption page reloading issues
  CHANGELOG.md
  source/renderer/app/components/wallet/settings/ExportWalletToFileDialog.js
  source/renderer/app/containers/Root.js
  source/renderer/app/containers/wallet/AdaRedemptionPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/stores/SidebarStore.js
Labels: bug, release-0.13.0

#1220 [DDW-526] ADA redemption failing on Daedalus 0.12.0 with Cardano 2.0.0
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/stores/AdaRedemptionStore.js
Labels: bug, release-0.12.0

#1222 Merge release/0.12.0 into develop branch
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/stores/AdaRedemptionStore.js
Labels: chore, release-0.12.0

#1223 [DEVOPS-1112] Bump cardano-sl to latest release/2.0.0
  cardano-sl-src.json
Labels: release-0.12.0

#1216 [DDW-457] Update Webpack to version 4
  .babelrc
  .eslintrc
  .nvmrc
  .storybook/webpack.config.js
  CHANGELOG.md
  features/support/electron.js
  package.json
  scripts/package.js
  source/main/ipc/index.js
  source/main/preload.js
  source/main/webpack.config.js
  source/renderer/app/App.js
  source/renderer/app/ThemeManager.js
  source/renderer/app/api/api.js
  source/renderer/app/api/transactions/types.js
  source/renderer/app/components/profile/language-selection/LanguageSelectionForm.js
  source/renderer/app/components/profile/language-selection/LanguageSelectionForm.scss
  source/renderer/app/components/status/NetworkStatus.js
  source/renderer/app/components/wallet/WalletCreateDialog.js
  source/renderer/app/components/wallet/WalletReceive.js
  source/renderer/app/components/wallet/WalletRestoreDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/VerificationDialog.js
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/components/wallet/transactions/WalletTransactionsList.js
  source/renderer/app/components/widgets/forms/InlineEditingInput.js
  source/renderer/app/containers/status/NetworkStatusPage.js
  source/renderer/app/domains/WalletTransaction.js
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/index.js
  source/renderer/app/stores/AdaRedemptionStore.js
  source/renderer/app/stores/TransactionsStore.js
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/themes/daedalus.js
  source/renderer/app/themes/index.global.scss
  source/renderer/app/themes/index.js
  source/renderer/app/utils/network.js
  source/renderer/index.html
  source/renderer/webpack.config.js
  storybook/stories/AdaRedemptionDialog.stories.js
  storybook/stories/DeleteWalletConfirmationDialog.stories.js
  storybook/stories/ExportWalletToFileDialog.stories.js
  storybook/stories/LanguageSelectionForm.stories.js
  storybook/stories/SidebarCategory.stories.js
  storybook/stories/SidebarWalletsMenu.stories.js
  storybook/stories/WalletScreens.stories.js
  storybook/stories/support/StoryDecorator.js
  storybook/stories/support/utils.js
  storybook/webpack.config.js
  yarn.lock
  yarn2nix.nix
Labels: chore, release-0.13.0

#1225 [DDW-530] Remove SVG title tags added by image software
  source/renderer/app/assets/images/ada-logo.inline.svg
  source/renderer/app/assets/images/ada-symbol-big-dark.inline.svg
  source/renderer/app/assets/images/ada-symbol-smallest-dark.inline.svg
  source/renderer/app/assets/images/ada-symbol.inline.svg
  source/renderer/app/assets/images/arrow.inline.svg
  source/renderer/app/assets/images/attach-ic.inline.svg
  source/renderer/app/assets/images/back-arrow-ic_old.svg
  source/renderer/app/assets/images/card-payment-ic.svg
  source/renderer/app/assets/images/cardano-logo-white.inline.svg
  source/renderer/app/assets/images/cardano-logo.inline.svg
  source/renderer/app/assets/images/cert-bad-ic.inline.svg
  source/renderer/app/assets/images/cert-ic.inline.svg
  source/renderer/app/assets/images/cert-locked-ic.inline.svg
  source/renderer/app/assets/images/clipboard-ic.inline.svg
  source/renderer/app/assets/images/close-cross-white.inline.svg
  source/renderer/app/assets/images/close-cross.inline.svg
  source/renderer/app/assets/images/create-ic.inline.svg
  source/renderer/app/assets/images/daedalus-logo-header-nologo.svg
  source/renderer/app/assets/images/daedalus-logo-header.svg
  source/renderer/app/assets/images/exchange-ic.inline.svg
  source/renderer/app/assets/images/expand-arrow.svg
  source/renderer/app/assets/images/ic-check.svg
  source/renderer/app/assets/images/import-ic.inline.svg
  source/renderer/app/assets/images/receive-white-ic.svg
  source/renderer/app/assets/images/restore-ic.inline.svg
  source/renderer/app/assets/images/search-ic-dark.svg
  source/renderer/app/assets/images/search-ic.svg
  source/renderer/app/assets/images/send-white-ic.svg
  source/renderer/app/assets/images/sidebar/add-wallet-ic.inline.svg
  source/renderer/app/assets/images/sidebar/checked-light.svg
  source/renderer/app/assets/images/sidebar/spinner-light.svg
  source/renderer/app/assets/images/sidebar/staking-ic.svg
  source/renderer/app/assets/images/spinner-dark.inline.svg
  source/renderer/app/assets/images/spinner-dark.svg
  source/renderer/app/assets/images/spinner-light.svg
  source/renderer/app/assets/images/success-big.inline.svg
  source/renderer/app/assets/images/top-bar/sticker.svg
Labels: bug, release-0.13.0

#1230 [DDW-527] Disable wallet export in any production environment
  source/renderer/app/containers/wallet/WalletSettingsPage.js
Labels: bug, release-0.13.0

#1231 [DDW-528] Focus inline editing field on mouse up
  BESTPRACTICES.md
  CHANGELOG.md
Labels: feature, release-0.13.0

#1235 [DEVOPS-1192] Eval variables in statePath for nix-shell
  BESTPRACTICES.md
  CHANGELOG.md
Labels: bug, release-0.13.0

#1199 [DDW-459] Replace in-app support request with links to support page
  CHANGELOG.md
  source/renderer/app/actions/profile-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/api/common/requests/sendBugReport.js
  source/renderer/app/api/common/types.js
  source/renderer/app/assets/images/link-ic.inline.svg
  source/renderer/app/components/loading/Loading.js
  source/renderer/app/components/loading/Loading.scss
  source/renderer/app/components/loading/SystemTimeErrorOverlay.js
  source/renderer/app/components/profile/bug-report/BugReportDialog.js
  source/renderer/app/components/profile/bug-report/BugReportDialog.scss
  source/renderer/app/components/settings/categories/SupportSettings.js
  source/renderer/app/containers/LoadingPage.js
  source/renderer/app/containers/MainLayout.js
  source/renderer/app/containers/profile/dialogs/BugReportDialogContainer.js
  source/renderer/app/containers/settings/categories/SupportSettingsPage.js
  source/renderer/app/containers/wallet/WalletSupportRequestPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/ProfileStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/utils/network.js
  source/renderer/app/utils/serialize.js
Labels: feature, release-0.13.0

#1236 [DDW-537] Remove node version check
  .nvmrc
  CHANGELOG.md
  package.json
  yarn.lock
Labels: chore, release-0.13.0

#1219 [DDW-457] Update Electron
  package.json
  source/renderer/app/components/loading/SystemTimeErrorOverlay.js
  source/renderer/app/components/settings/categories/SupportSettings.js
  source/renderer/app/stores/AppStore.js
  source/renderer/index.html
  yarn.lock
Labels: chore, release-0.13.0

#1227 [DDW-531] Update minor dependencies
  .eslintrc
  CHANGELOG.md
  features/step_definitions/data-layer-migration.js
  features/support/electron.js
  features/support/i18n.js
  features/support/webdriver.js
  gulpfile.js
  package.json
  source/common/utils/files.js
  source/main/cardano/utils.js
  source/main/ipc/get-logs.js
  source/main/ipc/lib/MainIpcChannel.js
  source/renderer/app/api/api.js
  source/renderer/app/api/utils/request.js
  source/renderer/app/api/utils/requestV0.js
  source/renderer/app/components/loading/Loading.js
  source/renderer/app/components/status/NetworkStatus.js
  source/renderer/app/components/wallet/WalletBackupDialog.js
  source/renderer/app/components/wallet/WalletReceive.js
  source/renderer/app/components/wallet/paper-wallet-certificate/CompletionDialog.js
  source/renderer/app/components/wallet/summary/WalletSummary.js
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/components/wallet/transactions/WalletTransactionsList.js
  source/renderer/app/components/widgets/Dialog.js
  source/renderer/app/containers/Root.js
  source/renderer/app/containers/wallet/WalletAddPage.js
  source/renderer/app/domains/WalletTransaction.js
  source/renderer/app/stores/AppStore.js
  source/renderer/app/stores/ProfileStore.js
  source/renderer/app/stores/UiNotificationsStore.js
  source/renderer/app/stores/lib/Store.js
  source/renderer/app/utils/network.js
  source/renderer/app/utils/serialize.js
  storybook/stories/AddWallet.stories.js
  storybook/stories/DeleteWalletConfirmationDialog.stories.js
  storybook/stories/PaperWallets.stories.js
  storybook/stories/WalletScreens.stories.js
  storybook/stories/Widgets.stories.js
  storybook/stories/support/utils.js
  yarn.lock
Labels: chore, release-0.13.0
