Repository input-output-hk/daedalus, pull requests merged in 2018-03, with the labels that each got.

#761 [DDW-148] fix merge conflicts with release/0.9.0
  .buildkite/pipeline.yml
  .nonsense
  .storybook/webpack.config.js
  .travis.yml
  CHANGELOG.md
  README.md
  appveyor.yml
  default.nix
  fetch-nixpkgs.nix
  gulpfile.js
  installers/Installer.hs
  installers/Launcher.hs
  installers/MacInstaller.hs
  installers/README.md
  installers/RewriteLibs.hs
  installers/WindowsInstaller.hs
  installers/build-certificates-win64.bat
  installers/cardano-installer.cabal
  installers/cardano-installer.nix
  installers/launcher-config-mac.yaml
  installers/launcher-config-windows.yaml
  installers/load-certificate.hs
  installers/shell.nix
  installers/stack.yaml
  nixpkgs-src.json
  package-lock.json
  package.json
  scripts/build-installer-unix.sh
  scripts/build-installer-win64.bat
  scripts/nix-shell.sh
  source/main/index.js
  source/main/utils/installChromeExtensions.js
  source/main/windows/about.js
  source/renderer/app/components/layout/SidebarLayout.js
  source/renderer/app/components/profile/bug-report/BugReportDialog.js
  source/renderer/app/components/sidebar/Sidebar.js
  source/renderer/app/components/wallet/WalletReceive.js
  source/renderer/app/components/wallet/settings/paper-wallet-export-dialogs/ExportPaperWalletMnemonicVerificationDialog.scss
  source/renderer/app/components/widgets/forms/InlineEditingInput.scss
  source/renderer/app/components/widgets/forms/ReadOnlyInput.scss
  source/renderer/app/containers/wallet/WalletSummaryPage.js
  source/renderer/app/containers/wallet/etc/WalletSummaryPage.js
  source/renderer/app/i18n/global-messages.js
  source/renderer/app/index.html
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/themes/daedalus.js
  source/renderer/app/themes/simple/SimpleBubble.scss
  source/renderer/app/themes/simple/SimpleInput.scss
  source/renderer/app/themes/simple/_config.scss
  source/renderer/index.html
  storybook/stories/TopBar.stories.js
  storybook/webpack.config.js
  yarn.lock
Labels: chore

#767 Fix/ddw 154 Show 'Having trouble syncing?' message only if syncing has stalled for 5 minutes
  app/components/loading/Loading.js
Labels: bug

#709 Fix/ddw 91 fix broken options component styles (FORK)
  package-lock.json
  source/renderer/app/components/wallet/WalletAddDialog.scss
  source/renderer/app/components/widgets/forms/ReadOnlyInput.scss
  source/renderer/index.html
Labels: bug

#771 Chore/ddw 158 Port DDW-154 to fork
  source/renderer/app/components/loading/Loading.js
Labels: chore

#775 Merge master into develop
  .buildkite/pipeline.yml
  appveyor.yml
  installers/launcher-config-mac.yaml
  installers/launcher-config-windows.yaml
Labels: chore

#778 Fix/ddw 166 Remove 5 transactions limit from transactions screen
  CHANGELOG.md
  app/stores/TransactionsStore.js
Labels: bug

#783 Chore/ddw 169 finish fork
  .eslintrc
  CHANGELOG.md
  README.md
  appveyor.yml
  gulpfile.js
  installers/MacInstaller.hs
  installers/RewriteLibs.hs
  scripts/build-installer-unix.sh
  scripts/build-installer-win64.bat
  scripts/nix-shell.sh
  scripts/package.js
  source/renderer/app/api/common.js
  tls/ca/ca.crt
  yarn.lock
Labels: DO NOT MERGE, chore

#791 [DDW-169] Run npm install and package from MacInstaller.hs
  installers/MacInstaller.hs
  scripts/build-installer-unix.sh
Labels: bug

#792 Chore/ddw 183 Port DDW-166 to fork
  CHANGELOG.md
  source/renderer/app/stores/TransactionsStore.js
Labels: chore

#793 Chore/ddw 182 port DDW-168 to fork
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore

#802 Chore/ddw 192 Port DEVOPS-727 to fork
  appveyor.yml
Labels: chore

#803 Fix/ddw 196 Add About window icon for Linux build
  package-lock.json
  source/main/windows/about.js
Labels: bug

#804 Fix/ddw 194 fix missing icons in webpack fork branch
  package-lock.json
  package.json
  source/renderer/app/components/layout/TopBar.js
  source/renderer/app/components/loading/Loading.js
  source/renderer/app/components/loading/SystemTimeErrorOverlay.js
  source/renderer/app/components/notifications/NodeUpdateNotification.js
  source/renderer/app/components/notifications/StatusMessagesNotification.js
  source/renderer/app/components/sidebar/SidebarCategory.js
  source/renderer/app/components/sidebar/wallets/SidebarWalletsMenu.js
  source/renderer/app/components/static/About.js
  source/renderer/app/components/wallet/WalletReceive.js
  source/renderer/app/components/wallet/ada-redemption/AdaRedemptionDisclaimer.js
  source/renderer/app/components/wallet/ada-redemption/AdaRedemptionSuccessOverlay.js
  source/renderer/app/components/wallet/etc/WalletReceive.js
  source/renderer/app/components/wallet/navigation/WalletNavButton.js
  source/renderer/app/components/wallet/navigation/WalletNavButton.scss
  source/renderer/app/components/wallet/summary/WalletSummary.js
  source/renderer/app/components/wallet/summary/etc/WalletSummary.js
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/components/wallet/transactions/TransactionTypeIcon.js
  source/renderer/app/components/widgets/BigButtonForDialogs.js
  source/renderer/app/components/widgets/DialogBackButton.js
  source/renderer/app/components/widgets/DialogCloseButton.js
  source/renderer/app/components/widgets/NotificationMessage.js
  source/renderer/app/components/widgets/forms/AdaCertificateUploadWidget.js
  source/renderer/app/components/widgets/forms/FileUploadWidget.js
  yarn.lock
Labels: bug

#805 Fix/ddw 199 fix disabled form-fields background color
  source/renderer/app/components/widgets/forms/InlineEditingInput.scss
  source/renderer/app/components/widgets/forms/ReadOnlyInput.scss
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/simple/SimpleFormField.scss
  source/renderer/app/themes/simple/SimpleInput.scss
  source/renderer/app/themes/simple/_config.scss
Labels: bug

#807 Feature/ddw 133 Paper wallets certificate generation: Acceptance tests implementation
  CHANGELOG.md
  features/paper-wallets-certificate.feature
  features/step_definitions/paper-wallets-certificate-steps.js
  features/support/paper_wallet_certificates/paper-wallet-certificate.pdf
  source/renderer/app/actions/ada/wallets-actions.js
  source/renderer/app/components/wallet/WalletRestoreDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/CompletionDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/InstructionsDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/PasswordChoiceDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/PrintDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/SecuringPasswordDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/TemplateChoiceDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/VerificationDialog.js
  source/renderer/app/containers/wallet/dialogs/WalletRestoreDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/paper-wallet-certificate/PasswordChoiceDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/paper-wallet-certificate/VerificationDialogContainer.js
  source/renderer/app/stores/ada/AdaWalletsStore.js
  source/renderer/app/utils/i18nContext.js
Labels: feature

#794 Feature/ddw 164 Wallet restoration from a paper wallet certificate
  CHANGELOG.md
  features/paper-wallets-certificate.feature
  features/step_definitions/paper-wallets-certificate-steps.js
  features/support/paper_wallet_certificates/paper-wallet-certificate.pdf
  package-lock.json
  package.json
  source/renderer/app/actions/ada/wallets-actions.js
  source/renderer/app/api/ada/getAdaWalletCertificateRecoveryPhrase.js
  source/renderer/app/api/ada/getAdaWalletRecoveryPhraseFromCertificate.js
  source/renderer/app/api/ada/index.js
  source/renderer/app/api/ada/types.js
  source/renderer/app/api/common.js
  source/renderer/app/components/wallet/WalletAddDialog.js
  source/renderer/app/components/wallet/WalletRestoreDialog.js
  source/renderer/app/components/wallet/WalletRestoreDialog.scss
  source/renderer/app/components/wallet/ada-redemption/AdaRedemptionChoices.scss
  source/renderer/app/components/wallet/ada-redemption/AdaRedemptionForm.js
  source/renderer/app/components/wallet/paper-wallet-certificate/CompletionDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/InstructionsDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/PasswordChoiceDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/PrintDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/SecuringPasswordDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/TemplateChoiceDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/VerificationDialog.js
  source/renderer/app/containers/wallet/dialogs/WalletRestoreDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/paper-wallet-certificate/PasswordChoiceDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/paper-wallet-certificate/VerificationDialogContainer.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/ada/AdaWalletsStore.js
  source/renderer/app/utils/crypto.js
  source/renderer/app/utils/i18nContext.js
  yarn.lock
Labels: feature

#817 Fix/ddw 160 Debug context menu copy & paste actions on Windows [HOTFIX]
  CHANGELOG.md
  electron/main.development.js
  electron/menus/osx.js
  electron/menus/win-linux.js
Labels: bug

#816 Fix/ddw 160 Debug context menu copy & paste actions on Windows
  CHANGELOG.md
  source/main/menus/osx.js
  source/main/menus/win-linux.js
  source/main/windows/main.js
Labels: bug

#821 Chore/ddw 207 Bump Daedalus version to 0.9.1 and Cardano version to 1.1.1
  CHANGELOG.md
  app/i18n/locales/en-US.json
  app/i18n/locales/ja-JP.json
  package.json
Labels: chore
