Repository input-output-hk/daedalus, pull requests merged in 2019-02, with the labels that each got.

#1300 [DEVOPS-1232] Fix macOS and AppVeyor CI
  installers/common/MacInstaller.hs
  installers/overlays/add-test-stubs.nix
  scripts/build-installer-win64.bat
Labels: chore, release-0.13.0

#1295 [DEVOPS] Provide a shell.nix for testing the dhall files
  default.nix
  installers/default.nix
  installers/dhall/shell.nix
Labels: chore, release-0.13.0

#1302 [DDW-556] Fix Chrome Dev-Tools errors
  CHANGELOG.md
  source/main/windows/main.js
Labels: bug, release-0.13.0

#1276 [DDW-565] Improve performance of rendering huge lists
  CHANGELOG.md
  features/step_definitions/paper-wallets-certificate-steps.js
  features/step_definitions/receive-steps.js
  features/step_definitions/wallets-steps.js
  package.json
  source/main/index.js
  source/main/locales/en-US.json
  source/main/locales/ja-JP.json
  source/main/menus/win-linux.js
  source/main/preload.js
  source/main/utils/ensureDirectoryExists.js
  source/main/utils/installChromeExtensions.js
  source/main/windows/main.js
  source/renderer/app/api/api.js
  source/renderer/app/api/transactions/requests/getTransactionHistory.js
  source/renderer/app/api/transactions/types.js
  source/renderer/app/assets/fonts/SFMono-Light.otf
  source/renderer/app/assets/fonts/SFMono-Light.ttf
  source/renderer/app/components/wallet/receive/Address.js
  source/renderer/app/components/wallet/receive/Address.scss
  source/renderer/app/components/wallet/receive/VirtualAddressesList.js
  source/renderer/app/components/wallet/receive/VirtualAddressesList.scss
  source/renderer/app/components/wallet/receive/WalletReceive.js
  source/renderer/app/components/wallet/receive/WalletReceive.scss
  source/renderer/app/components/wallet/summary/WalletSummary.js
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/components/wallet/transactions/Transaction.scss
  source/renderer/app/components/wallet/transactions/WalletTransactionsList.js
  source/renderer/app/components/wallet/transactions/WalletTransactionsList.scss
  source/renderer/app/components/wallet/transactions/render-strategies/SimpleTransactionList.js
  source/renderer/app/components/wallet/transactions/render-strategies/SimpleTransactionList.scss
  source/renderer/app/components/wallet/transactions/render-strategies/VirtualTransactionList.js
  source/renderer/app/components/wallet/transactions/render-strategies/VirtualTransactionList.scss
  source/renderer/app/components/wallet/transactions/types.js
  source/renderer/app/components/widgets/BorderedBox.js
  source/renderer/app/components/widgets/BorderedBox.scss
  source/renderer/app/config/numbersConfig.js
  source/renderer/app/config/timingConfig.js
  source/renderer/app/containers/wallet/WalletReceivePage.js
  source/renderer/app/containers/wallet/WalletSummaryPage.js
  source/renderer/app/containers/wallet/WalletTransactionsPage.js
  source/renderer/app/domains/Wallet.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/TransactionsStore.js
  source/renderer/app/stores/WalletSettingsStore.js
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/index.global.scss
  source/renderer/index.html
  source/renderer/webpack.config.js
  storybook/stories/WalletScreens.stories.js
  storybook/stories/WalletSummary.stories.js
  storybook/stories/WalletTransactionsList.stories.js
  storybook/stories/support/utils.js
  storybook/webpack.config.js
  yarn.lock
Labels: feature, release-0.13.0

#1303 [DWW-565] Revert simplified virtual tx height calculations
  CHANGELOG.md
  source/renderer/app/components/wallet/transactions/WalletTransactionsList.js
  source/renderer/app/components/wallet/transactions/render-strategies/VirtualTransactionList.js
Labels: bug, release-0.13.0

#1305 [DDW-565] Improve 'Receive' screen UX
  CHANGELOG.md
  source/renderer/app/components/wallet/receive/WalletReceive.scss
Labels: bug, release-0.13.0

#1306 [DDW-565] Fixes scrollbar over notification
  CHANGELOG.md
  source/renderer/app/components/wallet/layouts/WalletWithNavigation.scss
  source/renderer/app/components/widgets/NotificationMessage.js
  source/renderer/app/containers/wallet/WalletReceivePage.js
Labels: bug, release-0.13.0

#1307 [DDW-574] Bump Cardano-sl version to the tip of develop branch
  cardano-sl-src.json
Labels: chore, release-0.13.0

#1309 [DDW-576] Implement extra explanation for Create Paper Wallet Certificate
  CHANGELOG.md
  source/renderer/app/components/wallet/paper-wallet-certificate/InstructionsDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/InstructionsDialog.scss
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
Labels: feature, release-0.13.0

#1299 [DDW-517] Implement Structured Logging for Daedalus Logs
  CHANGELOG.md
  source/common/types/environment.types.js
  source/common/types/logging.types.js
  source/common/utils/logging.js
  source/main/cardano/CardanoNode.js
  source/main/cardano/setupCardanoNodeMode.js
  source/main/cardano/setupFrontendOnlyMode.js
  source/main/config.js
  source/main/environment.js
  source/main/index.js
  source/main/ipc/compress-logs.js
  source/main/ipc/parse-redemption-code-from-pdf.js
  source/main/ipc/reportRequestChannel.js
  source/main/utils/buildAppMenus.js
  source/main/utils/handleDiskSpace.js
  source/main/utils/logging.js
  source/main/utils/mainErrorHandler.js
  source/main/utils/processes.js
  source/main/utils/rendererErrorHandler.js
  source/main/utils/setupLogging.js
  source/renderer/app/api/api.js
  source/renderer/app/api/transactions/requests/redeemPaperVendedAda.js
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/stores/AdaRedemptionStore.js
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/utils/logging.js
Labels: feature, release-0.13.0

#1310 [DDW-578] Bump Daedalus version
  CHANGELOG.md
  package.json
Labels: chore, release-0.13.0

#1308 [DDW-575] Handle 'transaction is too big' transaction error
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/api/transactions/errors.js
  source/renderer/app/components/wallet/WalletSendConfirmationDialog.js
  source/renderer/app/components/wallet/WalletSendForm.js
  source/renderer/app/components/wallet/WalletSendForm.scss
  source/renderer/app/components/wallet/ada-redemption/AdaRedemptionForm.js
  source/renderer/app/components/widgets/FormattedHTMLMessageWithLink.js
  source/renderer/app/containers/wallet/WalletSendPage.js
  source/renderer/app/containers/wallet/dialogs/WalletSendConfirmationDialogContainer.js
  source/renderer/app/i18n/LocalizableError.js
  source/renderer/app/i18n/errors.js
  source/renderer/app/i18n/global-messages.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/terms-of-use/mainnet/en-US.md
  source/renderer/app/i18n/locales/terms-of-use/mainnet/ja-JP.md
  source/renderer/app/i18n/locales/terms-of-use/other/en-US.md
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/i18n/types.js
  source/renderer/app/themes/mixins/error-message.scss
Labels: feature, release-0.13.0

#1313 [DDW-579] Implement ellipsis when loading the number of transactions
  CHANGELOG.md
  source/renderer/app/components/wallet/summary/WalletSummary.js
  source/renderer/app/components/wallet/summary/WalletSummary.scss
  source/renderer/app/containers/wallet/WalletSummaryPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  storybook/stories/WalletScreens.stories.js
  storybook/stories/WalletSummary.stories.js
Labels: feature, release-0.13.0

#1298 [DEVOPS-970] Build Windows installers on Linux
  .buildkite/pipeline.yml
  CHANGELOG.md
  ConfigMutator.hs
  cardano-sl-src.json
  default.nix
  dummy-certs/authenticode.pvk
  dummy-certs/authenticode.spc
  installers/Installer.hs
  installers/common/Config.hs
  installers/common/WindowsInstaller.hs
  installers/overlays/required.nix
  installers/stack.yaml
  nsis-inner.nix
  nsis.nix
  release.nix
  scripts/build-cross-windows.sh
  scripts/package.js
  shell.nix
  utils/windows/gen-cert
  yarn2nix.nix
Labels: chore, release-0.13.0

#1312 [DDW-565] Fix expanded rows and blank screen issues
  CHANGELOG.md
  source/renderer/app/components/wallet/receive/VirtualAddressesList.js
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/components/wallet/transactions/WalletTransactionsList.js
  source/renderer/app/components/wallet/transactions/render-strategies/VirtualTransactionList.js
  source/renderer/app/components/wallet/transactions/render-strategies/VirtualTransactionList.scss
  source/renderer/app/containers/wallet/WalletTransactionsPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
Labels: bug, release-0.13.0

#1317 [DDW-581] Replace ada symbol images with unicode character
  CHANGELOG.md
  features/step_definitions/wallets-steps.js
  source/renderer/app/assets/images/ada-symbol-smallest-dark.inline.svg
  source/renderer/app/assets/images/ada-symbol.inline.svg
  source/renderer/app/components/wallet/ada-redemption/AdaRedemptionSuccessOverlay.js
  source/renderer/app/components/wallet/ada-redemption/AdaRedemptionSuccessOverlay.scss
  source/renderer/app/components/wallet/summary/WalletSummary.js
  source/renderer/app/components/wallet/summary/WalletSummary.scss
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/components/wallet/transactions/Transaction.scss
  source/renderer/app/i18n/global-messages.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/utils/formatters.js
Labels: feature, release-0.14.0

#1319 [DDW-585] Update NTP API response handling
  CHANGELOG.md
  cardano-sl-src.json
  source/renderer/app/api/api.js
  source/renderer/app/api/nodes/types.js
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/config/timingConfig.js
  source/renderer/app/stores/NetworkStatusStore.js
Labels: bug, release-0.13.0
