Repository input-output-hk/daedalus, pull requests merged in 2019-08, with the labels that each got.

#1514 Nix dependency fix
  package.json
  source/renderer/app/components/staking/stake-pools/StakePoolsSearch.scss
  yarn.lock
Labels: bug

#1499 [DDW-792] New Wallet Creation - base files
  source/renderer/app/actions/wallets-actions.js
  source/renderer/app/components/wallet/WalletCreateDialog.js
  source/renderer/app/components/wallet/wallet-create/ConfigDialog.js
  source/renderer/app/components/wallet/wallet-create/HashDialog.js
  source/renderer/app/components/wallet/wallet-create/InstructionsDialog.js
  source/renderer/app/components/wallet/wallet-create/MnemonicsDialog.js
  source/renderer/app/components/wallet/wallet-create/TemplateDialog.js
  source/renderer/app/components/wallet/wallet-create/ValidateDialog.js
  source/renderer/app/components/wallet/wallet-create/WalletCreateDialog.js
  source/renderer/app/components/wallet/wallet-create/WalletCreateDialog.scss
  source/renderer/app/components/wallet/wallet-create/WalletCreateSteps.js
  source/renderer/app/components/wallet/wallet-create/WalletCreateSteps.scss
  source/renderer/app/components/wallet/wallet-create/WalletCreateStyles.scss
  source/renderer/app/config/walletsConfig.js
  source/renderer/app/containers/wallet/WalletAddPage.js
  source/renderer/app/containers/wallet/dialogs/WalletCreateDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/wallet-create/ConfigDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/wallet-create/HashDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/wallet-create/InstructionsDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/wallet-create/MnemonicsDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/wallet-create/TemplateDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/wallet-create/ValidateDialogContainer.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/types/injectedPropsType.js
  storybook/stories/WalletScreens-Create-Wallet.stories.js
  storybook/stories/WalletScreens.stories.js
Labels: feature, release-vNext

#1516 [DDW-815] Remove "Realtime statistics monitor" link in Testnet builds
  CHANGELOG.md
  source/renderer/app/components/status/DaedalusDiagnostics.js
Labels: chore, release-0.14.0

#1517 [DDW-812] Fix application dialog close button colour
  CHANGELOG.md
  source/renderer/app/components/status/BlockConsolidationStatus.js
  source/renderer/app/components/status/BlockConsolidationStatus.scss
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/components/status/DaedalusDiagnostics.scss
  source/renderer/app/i18n/locales/defaultMessages.json
Labels: bug, release-0.14.0

#1518 [DDW-813] Adds a link to the 'Safety Tips' Support portal article
  CHANGELOG.md
  features/tests/e2e/steps/general-settings-steps.js
  source/main/locales/en-US.json
  source/main/locales/ja-JP.json
  source/main/menus/osx.js
  source/main/menus/win-linux.js
Labels: feature, release-0.14.0

#1520 Merge release/0.14.0 into develop branch
  CHANGELOG.md
  cardano-sl-src.json
  features/tests/e2e/steps/general-settings-steps.js
  scripts/build-cross-windows.sh
  source/main/locales/en-US.json
  source/main/locales/ja-JP.json
  source/main/menus/osx.js
  source/main/menus/win-linux.js
  source/renderer/app/components/status/BlockConsolidationStatus.js
  source/renderer/app/components/status/BlockConsolidationStatus.scss
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/components/status/DaedalusDiagnostics.scss
  source/renderer/app/i18n/locales/defaultMessages.json
Labels: chore, release-0.14.0

#1521 [DDW-812] Fix notification z-index issue on Daedalus Diagnostics screen
  CHANGELOG.md
  source/renderer/app/containers/Root.js
  source/renderer/app/containers/status/DaedalusDiagnosticsDialog.js
Labels: bug, release-0.14.0

#1519 [DEVOPS] RC3 cardano-sl application version bump
  cardano-sl-src.json
Labels: chore, release-0.14.0

#1515 [DDW-811] Re-enable the old wallet creation process
  CHANGELOG.md
  source/renderer/app/components/wallet/WalletCreateDialog.js
  source/renderer/app/components/wallet/WalletCreateDialog.scss
  source/renderer/app/containers/wallet/WalletAddPage.js
  source/renderer/app/containers/wallet/dialogs/WalletCreateDialogContainerOld.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/WalletsStore.js
Labels: bug, release-vNext

#1522 Merge release/0.14.0 into develop branch
  CHANGELOG.md
  cardano-sl-src.json
  source/renderer/app/containers/Root.js
  source/renderer/app/containers/status/DaedalusDiagnosticsDialog.js
Labels: chore, release-0.14.0

#1509 [DDW-800] Fix Netlify builds
  CHANGELOG.md
  package.json
  storybook/webpack.config.js
  yarn.lock
Labels: chore, release-vNext

#1523 [DDW-810] Replace "[GPU Safe Mode]" window titlebar text
  CHANGELOG.md
  source/common/types/environment.types.js
  source/common/types/logging.types.js
  source/main/environment.js
  source/main/index.js
  source/main/locales/en-US.json
  source/main/locales/ja-JP.json
  source/main/menus/MenuActions.types.js
  source/main/menus/osx.js
  source/main/menus/win-linux.js
  source/main/utils/buildAppMenus.js
  source/main/utils/setupLogging.js
  source/main/windows/main.js
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/components/status/DaedalusDiagnostics.scss
  source/renderer/app/containers/status/DaedalusDiagnosticsDialog.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/ProfileStore.js
  source/renderer/app/types/coreSystemInfoTypes.js
  storybook/stories/Diagnostics.stories.js
Labels: bug, release-0.14.0

#1524 Merge release/0.14.0 into develop branch
  CHANGELOG.md
  source/common/types/environment.types.js
  source/common/types/logging.types.js
  source/main/environment.js
  source/main/index.js
  source/main/locales/en-US.json
  source/main/locales/ja-JP.json
  source/main/menus/MenuActions.types.js
  source/main/menus/osx.js
  source/main/menus/win-linux.js
  source/main/utils/buildAppMenus.js
  source/main/utils/setupLogging.js
  source/main/windows/main.js
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/components/status/DaedalusDiagnostics.scss
  source/renderer/app/containers/status/DaedalusDiagnosticsDialog.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/ProfileStore.js
  source/renderer/app/types/coreSystemInfoTypes.js
  storybook/stories/Diagnostics.stories.js
Labels: chore, release-0.14.0

#1525 [DDW-805] Create Tutorial Series for Theme Management
  CHANGELOG.md
  gulpfile.js
  package.json
  source/renderer/app/themes/README.md
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/index.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/scripts/update.js
  source/renderer/app/themes/types.js
  source/renderer/app/themes/utils/checkCreateTheme.js
  source/renderer/app/themes/utils/constants.js
  source/renderer/app/themes/utils/createTheme.js
  source/renderer/app/themes/utils/findUpdates.js
  source/renderer/app/themes/utils/updateThemes.js
  source/renderer/app/themes/utils/updateThemesCLI.js
  source/renderer/app/themes/utils/writeThemeUpdate.js
Labels: chore, release-vNext

#1502 [DDW-760] Theme Management Optimization
  CHANGELOG.md
  source/renderer/app/themes/daedalus/white.js
Labels: chore, release-vNext

#1503 [DDW-744]: Delegation setup wizard optimization
  CHANGELOG.md
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationSteps.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsActivationDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsActivationDialog.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsConfirmationDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsConfirmationDialog.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsIntroDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsIntroDialog.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsNotAvailableDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsNotAvailableDialog.scss
  source/renderer/app/i18n/locales/defaultMessages.json
Labels: feature, release-vNext

#1526 [DDW-783] Link to support portal article explaining UTXO distribution
  CHANGELOG.md
  source/renderer/app/components/wallet/utxo/WalletUtxo.js
  source/renderer/app/components/wallet/utxo/WalletUtxo.scss
  source/renderer/app/containers/wallet/WalletUtxoPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  storybook/stories/WalletScreens-Utxo.stories.js
Labels: bug, release-0.14.0

#1527 Merge release/0.14.0 into develop branch
  CHANGELOG.md
  source/main/utils/buildAppMenus.js
  source/renderer/app/components/wallet/utxo/WalletUtxo.js
  source/renderer/app/components/wallet/utxo/WalletUtxo.scss
  source/renderer/app/containers/wallet/WalletUtxoPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  storybook/stories/WalletScreens-Utxo.stories.js
Labels: chore, release-0.14.0

#1512 [DDW-797]: Fix external and copy icons inconsistencies
  CHANGELOG.md
  source/renderer/app/components/settings/categories/SupportSettings.js
  source/renderer/app/components/settings/categories/SupportSettings.scss
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.js
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.scss
  source/renderer/app/components/wallet/paper-wallet-certificate/CompletionDialog.scss
  source/renderer/app/config/timingConfig.js
Labels: bug, release-vNext

#1530 [DDW-818] Create Wallet Screen missing Japanese translations
  CHANGELOG.md
  source/renderer/app/i18n/locales/ja-JP.json
Labels: bug, release-vNext

#1533 [DDW-826] Fix 'Feature Request' item menu in Japanese
  CHANGELOG.md
  source/main/locales/ja-JP.json
Labels: bug, release-vNext

#1485 [DDW-690] Fix minimum window height on Windows and Linux
  CHANGELOG.md
  source/main/config.js
  source/main/utils/getContentMinimumSize.js
  source/main/windows/main.js
Labels: chore, release-vNext

#1531 [DDW-798] "1 confirmations" is displayed on Transaction Assurance Level
  CHANGELOG.md
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
Labels: bug, release-vNext

#1534 Merge release/0.14.0 into develop branch
  bors.toml
  cardano-sl-src.json
  features/tests/e2e/documents/paper_wallet_certificates/paper-wallet-certificate.pdf
  release-build.nix
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
Labels: chore, release-0.14.0

#1536 [DDW-830] Fix dialog content issues in the latest version of Chrome
  CHANGELOG.md
  source/renderer/app/themes/overrides/ModalOverrides.scss
Labels: bug, release-vNext

#1494 [DDW-765]: Change behavior of system dialogs
  CHANGELOG.md
  features/tests/e2e/setup/electron.js
  features/tests/e2e/steps/wallets-steps.js
  flow/declarations/File.js
  package.json
  source/common/ipc/api.js
  source/common/types/file-meta-request.types.js
  source/main/ipc/generateFileMetaChannel.js
  source/main/ipc/index.js
  source/main/preload.js
  source/renderer/app/components/wallet/file-import/WalletFileImportDialog.js
  source/renderer/app/components/widgets/forms/FileUploadWidget.js
  source/renderer/app/components/widgets/forms/FileUploadWidget.scss
  source/renderer/app/ipc/generateFileMetaChannel.js
  source/renderer/app/utils/fileMetaGenerator.js
  source/renderer/webpack.config.js
  yarn.lock
Labels: feature, release-vNext

#1535 [DDW-751] Diagnostic screen empty tooltip
  CHANGELOG.md
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/components/status/DaedalusDiagnostics.scss
Labels: bug, release-vNext

#1532 [DDW-814] White theme styling adjustments
  CHANGELOG.md
  source/renderer/app/components/layout/SidebarLayout.scss
  source/renderer/app/components/loading/syncing-connecting/LogosDisplay.scss
  source/renderer/app/components/notifications/NodeUpdateNotification.scss
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/Settings.stories.js
  storybook/stories/index.js
Labels: bug, release-vNext

#1543 [DDW-838] Improve stake pools dummy data
  source/renderer/app/config/generateStakePoolFakeData.js
  source/renderer/app/config/stakingCurrentEpoch.dummy.json
  source/renderer/app/config/stakingPreviousEpoch.dummy.json
  source/renderer/app/config/stakingRewards.dummy.json
  source/renderer/app/config/stakingStakePools.dummy.json
Labels: bug, release-vNext

#1545 [DDW-839] Delegation setup improvements
  CHANGELOG.md
  source/renderer/app/components/staking/delegation-center/DelegationCenterHeader.js
  source/renderer/app/components/staking/delegation-center/DonutRing.js
  source/renderer/app/components/staking/delegation-center/helpers.js
  source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  storybook/stories/Staking-DelegationCenter.stories.js
  storybook/stories/Staking.stories.js
Labels: bug, release-vNext

#1491 [DDW-680] Unify automated and manual update flows
  CHANGELOG.md
  features/node-update-notification.feature
  features/tests/e2e/steps/helper-steps.js
  features/tests/e2e/steps/node-update-notification-steps.js
  source/common/ipc/api.js
  source/main/index.js
  source/main/ipc/rebuild-application-menu.js
  source/main/menus/osx.js
  source/main/menus/win-linux.js
  source/main/utils/buildAppMenus.js
  source/renderer/app/App.js
  source/renderer/app/actions/node-update-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/api/nodes/types.js
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/components/loading/manual-update/ManualUpdate.scss
  source/renderer/app/components/notifications/AutomaticUpdateNotification.js
  source/renderer/app/components/notifications/AutomaticUpdateNotification.scss
  source/renderer/app/components/notifications/NodeUpdateNotification.js
  source/renderer/app/components/notifications/NodeUpdateNotification.scss
  source/renderer/app/containers/MainLayout.js
  source/renderer/app/containers/loading/LoadingPage.js
  source/renderer/app/containers/notifications/AutomaticUpdateNotificationDialog.js
  source/renderer/app/containers/notifications/NodeUpdatePage.js
  source/renderer/app/containers/profile/LanguageSelectionPage.js
  source/renderer/app/containers/settings/categories/GeneralSettingsPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/NodeUpdateStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/Notifications.stories.js
  storybook/stories/Widgets.stories.js
  storybook/stories/index.js
Labels: feature, release-vNext
