Repository input-output-hk/daedalus, pull requests merged in 2019-11, with the labels that each got.

#1632 [DEVOPS] Enable macOS builds signing
  .buildkite/pipeline.yml
Labels: Infrastructure, release/0.14.AR

#1631 [DDW-895] Spending password should be always required
  CHANGELOG.md
  features/data-layer-migration.feature
  features/import-wallet-via-sidebar.feature
  features/paper-wallets-certificate.feature
  features/tests/e2e/steps/paper-wallets-certificate-steps.js
  features/tests/e2e/steps/settings-steps.js
  features/tests/e2e/steps/wallets-limit.js
  features/tests/e2e/steps/wallets-steps.js
  features/wallet-settings.feature
  source/renderer/app/actions/wallet-settings-actions.js
  source/renderer/app/actions/wallets-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/api/utils/index.js
  source/renderer/app/api/wallets/requests/changeSpendingPassword.js
  source/renderer/app/api/wallets/requests/importWalletAsKey.js
  source/renderer/app/api/wallets/types.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationSetupWizardDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsActivationDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsConfirmationDialog.js
  source/renderer/app/components/wallet/WalletCreateDialog.js
  source/renderer/app/components/wallet/WalletCreateDialog.scss
  source/renderer/app/components/wallet/WalletRestoreDialog.js
  source/renderer/app/components/wallet/WalletRestoreDialog.scss
  source/renderer/app/components/wallet/file-import/WalletFileImportDialog.js
  source/renderer/app/components/wallet/file-import/WalletFileImportDialog.scss
  source/renderer/app/components/wallet/settings/ChangeSpendingPasswordDialog.js
  source/renderer/app/components/wallet/settings/ChangeSpendingPasswordDialog.scss
  source/renderer/app/components/wallet/settings/ExportWalletToFileDialog.js
  source/renderer/app/components/wallet/settings/WalletSettings.js
  source/renderer/app/components/widgets/forms/ReadOnlyInput.js
  source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
  source/renderer/app/containers/wallet/WalletSettingsPage.js
  source/renderer/app/containers/wallet/dialogs/WalletCreateDialogContainerOld.js
  source/renderer/app/containers/wallet/dialogs/WalletFileImportDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/WalletRestoreDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/settings/ChangeSpendingPasswordDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/settings/ExportWalletToFileDialogContainer.js
  source/renderer/app/domains/Wallet.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/WalletSettingsStore.js
  source/renderer/app/stores/WalletsStore.js
  storybook/stories/AddWallet.stories.js
  storybook/stories/ExportWalletToFileDialog.stories.js
  storybook/stories/Staking.stories.js
  storybook/stories/WalletScreens-Settings.stories.js
Labels: V2-API, feature, release-vNext

#1622 [DDW-1007] Replace sidebar "Bug-report" icon with a "Network" badge
  CHANGELOG.md
  source/renderer/app/assets/images/sidebar/bug-report-ic-dark.inline.svg
  source/renderer/app/assets/images/sidebar/bug-report-ic.inline.svg
  source/renderer/app/assets/images/sidebar/network-info-logo-cardano-ic.inline.svg
  source/renderer/app/components/sidebar/Sidebar.js
  source/renderer/app/components/sidebar/Sidebar.scss
  source/renderer/app/components/sidebar/SidebarCategory.js
  source/renderer/app/components/sidebar/SidebarCategory.scss
  source/renderer/app/components/sidebar/SidebarCategoryNetworkInfo.js
  source/renderer/app/components/sidebar/SidebarCategoryNetworkInfo.scss
  source/renderer/app/config/sidebarConfig.js
  source/renderer/app/containers/MainLayout.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/routes-config.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/Sidebar.stories.js
  storybook/stories/SidebarCategory.stories.js
  storybook/stories/support/StoryLayout.js
Labels: V2-API, feature, release-vNext

#1629 [DDW-925] Implement restoration of both 12 and 15 mnemonic words phrases
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/api/wallets/requests/restoreLegacyWallet.js
  source/renderer/app/api/wallets/types.js
  source/renderer/app/components/staking/delegation-center/DropdownMenu.scss
  source/renderer/app/components/staking/epochs/StakingEpochs.scss
  source/renderer/app/components/status/DaedalusDiagnostics.scss
  source/renderer/app/components/wallet/WalletRestoreDialog.js
  source/renderer/app/components/widgets/NewsFeedIcon.scss
  source/renderer/app/components/widgets/RadioOverride.scss
  source/renderer/app/components/widgets/RadioSet.js
  source/renderer/app/components/widgets/RadioSet.scss
  source/renderer/app/config/cryptoConfig.js
  source/renderer/app/config/walletsConfig.js
  source/renderer/app/containers/wallet/dialogs/WalletRestoreDialogContainer.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/themes/daedalus.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/overrides/CheckboxOverrides.scss
  source/renderer/app/themes/overrides/RadioOverrides.scss
  source/renderer/app/themes/overrides/SelectOverrides.scss
  source/renderer/app/themes/overrides/index.js
  source/renderer/app/themes/utils/createTheme.js
Labels: V2-API, feature, release-vNext

#1637 [DDW-998] Introduce Legacy Wallet list API V2 endpoint
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/api/wallets/requests/getLegacyWallets.js
  source/renderer/app/api/wallets/types.js
  source/renderer/app/stores/WalletsStore.js
Labels: V2-API, feature, release-vNext

#1636 [DDW-979] JS cleanup and selfnode cluster support
  nix/launcher-config.nix
  package.json
  shell.nix
  source/common/types/cardano-node.types.js
  source/main/cardano/CardanoNode.js
  source/main/cardano/CardanoWalletLauncher.js
  source/main/cardano/config.js
  source/main/cardano/nodes/http-bridge.js
  source/main/cardano/nodes/index.js
  source/main/cardano/nodes/jormungandr.js
  source/main/config.js
  source/renderer/app/stores/NetworkStatusStore.js
  yarn2nix.nix
Labels: V2-API, infrastructure, release-vNext

#1640 [DDW-997] Disable create a paper wallet certificate feature
  CHANGELOG.md
  source/renderer/app/components/sidebar/Sidebar.js
  source/renderer/app/containers/MainLayout.js
  storybook/stories/Sidebar.stories.js
  storybook/stories/support/StoryLayout.js
Labels: V2-API, chore, release-vNext

#1638 [DDW-1023] Remove parallel wallet restoration limitation
  CHANGELOG.md
  source/renderer/app/api/transactions/types.js
  source/renderer/app/api/wallets/types.js
  source/renderer/app/components/wallet/WalletAdd.js
  source/renderer/app/containers/wallet/WalletAddPage.js
  source/renderer/app/domains/Wallet.js
  source/renderer/app/stores/SidebarStore.js
  source/renderer/app/stores/TransactionsStore.js
  source/renderer/app/stores/WalletsStore.js
Labels: V2-API, chore, release-vNext

#1644 [DDW-1041] Update wallet restoration notification
  CHANGELOG.md
  source/renderer/app/components/notifications/RestoreNotification.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
Labels: V2-API, chore, release-vNext

#1648 Remove check-hydra script from CI
  .buildkite/pipeline.yml
Labels: V2-API, chore, infrastructure

#1643 [DDW-1004]: Rewards screen update for incentivized testnet
  CHANGELOG.md
  package.json
  source/common/ipc/api.js
  source/common/types/rewards-csv-request.types.js
  source/main/ipc/generateRewardsCsvChannel.js
  source/main/ipc/index.js
  source/renderer/app/actions/wallets-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/api/staking/types.js
  source/renderer/app/api/wallets/types.js
  source/renderer/app/assets/images/download-ic.inline.svg
  source/renderer/app/components/staking/layouts/StakingWithNavigation.js
  source/renderer/app/components/staking/rewards/StakingRewards.js
  source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.js
  source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.scss
  source/renderer/app/components/widgets/BorderedBox.scss
  source/renderer/app/config/stakingRewards.dummy.json
  source/renderer/app/containers/staking/StakingRewardsPage.js
  source/renderer/app/domains/Wallet.js
  source/renderer/app/i18n/errors.js
  source/renderer/app/i18n/global-messages.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/ipc/generateRewardsCsvChannel.js
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  source/renderer/app/utils/rewardsCsvGenerator.js
  storybook/stories/Staking-DelegationCenter.stories.js
  storybook/stories/support/utils.js
  yarn.lock
Labels: V2-API, feature, release-vNext

#1641 [DDW-1000] Integrate legacy wallet transactions list V2 API endpoint
  CHANGELOG.md
  source/renderer/app/api/addresses/types.js
  source/renderer/app/api/api.js
  source/renderer/app/api/transactions/requests/getLegacyWalletTransactionHistory.js
  source/renderer/app/api/transactions/types.js
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/components/wallet/transactions/Transaction.scss
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/AddressesStore.js
  source/renderer/app/stores/TransactionsStore.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  storybook/stories/WalletTransactionsList.stories.js
  storybook/stories/support/utils.js
Labels: V2-API, feature, release-vNext

#1645 [DDW-1043] Disable/hide wallet recovery phrase verification feature
  CHANGELOG.md
  source/renderer/app/components/sidebar/Sidebar.js
  source/renderer/app/components/sidebar/wallets/SidebarWalletMenuItem.js
  source/renderer/app/components/sidebar/wallets/SidebarWalletsMenu.js
  source/renderer/app/components/wallet/settings/WalletSettings.js
  source/renderer/app/containers/wallet/Wallet.js
  source/renderer/app/containers/wallet/WalletSettingsPage.js
  storybook/stories/SidebarWalletsMenu.stories.js
  storybook/stories/WalletScreens-Settings.stories.js
Labels: V2-API, chore, release-vNext

#1647 [DDW-999] Legacy wallets UI
  CHANGELOG.md
  source/renderer/app/components/navigation/NavDropdown.js
  source/renderer/app/components/navigation/Navigation.js
  source/renderer/app/components/wallet/layouts/WalletWithNavigation.js
  source/renderer/app/components/wallet/navigation/WalletNavigation.js
  source/renderer/app/components/wallet/settings/WalletSettings.js
  source/renderer/app/components/wallet/settings/WalletSettings.scss
  source/renderer/app/containers/wallet/Wallet.js
  source/renderer/app/containers/wallet/WalletSettingsPage.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/WalletScreens-Settings.stories.js
  storybook/stories/WalletScreens.stories.js
Labels: V2-API, chore, release-vNext

#1649 [DDW-1055] Fix paper wallet certificate restoration
  CHANGELOG.md
  source/renderer/app/stores/WalletsStore.js
Labels: V2-API, bug, release-vNext

#1652 [DDW-1044] Disable manual update notification for Incentivized Testnet
  CHANGELOG.md
  features/node-update-notification.feature
  source/renderer/app/App.js
  source/renderer/app/components/loading/syncing-connecting/SyncingConnecting.js
  source/renderer/app/containers/loading/LoadingPage.js
  source/renderer/app/containers/loading/SyncingConnectingPage.js
  source/renderer/app/stores/NodeUpdateStore.js
  storybook/stories/Loading-SyncingConnecting.stories.js
Labels: V2-API, feature, release-vNext

#1654 [DEVOPS] Daedalus applicationVersion: bump all environments
  installers/cardano-configuration.yaml
  package.json
Labels: chore, release-0.15.1

#1653 [DDW-1056] Newsfeed content loading issue
  CHANGELOG.md
  source/renderer/app/api/utils/externalRequest.js
Labels: bug, release-0.15.1

#1658 [DDW-1057] Update cardano-wallet revision
  README.md
  nix/sources.json
Labels: V2-API, chore, release-vNext

#1655 [DDW-1042]: Implement network splash screen
  CHANGELOG.md
  source/renderer/app/actions/network-status-actions.js
  source/renderer/app/assets/images/splash-network-bg-faded.inline.svg
  source/renderer/app/components/sidebar/Sidebar.js
  source/renderer/app/components/splash/Network.js
  source/renderer/app/components/splash/Network.scss
  source/renderer/app/containers/MainLayout.js
  source/renderer/app/containers/Root.js
  source/renderer/app/containers/splash/NetworkPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/Splash-Network.stories.js
  storybook/stories/Splash.stories.js
  storybook/stories/index.js
Labels: V2-API, feature, release-vNext

#1646 [DDW-979] Replace the var substitution logic
  README.md
  source/main/utils/config.js
Labels: V2-API, infrastructure, release-vNext

#1634 [DDW-983] Implement transfer funds wizard for Incentivized Testnet
  CHANGELOG.md
  README.md
  package.json
  source/renderer/app/actions/wallets-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/api/wallets/requests/transferFunds.js
  source/renderer/app/api/wallets/requests/transferFundsCalculateFee.js
  source/renderer/app/api/wallets/types.js
  source/renderer/app/components/layout/TopBar.js
  source/renderer/app/components/notifications/LegacyNotification.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationSetupWizardDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.scss
  source/renderer/app/components/wallet/transfer-funds/TransferFundsStep1Dialog.js
  source/renderer/app/components/wallet/transfer-funds/TransferFundsStep1Dialog.scss
  source/renderer/app/components/wallet/transfer-funds/TransferFundsStep2Dialog.js
  source/renderer/app/components/wallet/transfer-funds/TransferFundsStep2Dialog.scss
  source/renderer/app/components/widgets/forms/WalletsDropdown.js
  source/renderer/app/components/widgets/forms/WalletsDropdownOption.js
  source/renderer/app/components/widgets/forms/WalletsDropdownOption.scss
  source/renderer/app/containers/MainLayout.js
  source/renderer/app/containers/TopBarContainer.js
  source/renderer/app/containers/staking/DelegationCenterPage.js
  source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
  source/renderer/app/containers/wallet/TransferFundsPage.js
  source/renderer/app/containers/wallet/WalletAddPage.js
  source/renderer/app/containers/wallet/dialogs/WalletTransferFundsContainer.js
  source/renderer/app/containers/wallet/dialogs/transfer-funds/TransferFundsStep1Container.js
  source/renderer/app/containers/wallet/dialogs/transfer-funds/TransferFundsStep2Container.js
  source/renderer/app/domains/Wallet.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/AddressesStore.js
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/stores/TransactionsStore.js
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  storybook/stories/Staking.stories.js
  storybook/stories/WalletTransferFunds.stories.js
  storybook/stories/index.js
  storybook/stories/support/StoryLayout.js
  storybook/stories/support/StoryProvider.js
  utils/jormungandr/selfnode/genesis.yaml
  utils/v2-api-importer/legacy.js
  yarn.lock
Labels: V2-API, feature, release-vNext

#1659 [DDW-983] Implement transfer funds wizard for Incentivized Testnet
  CHANGELOG.md
  source/renderer/app/components/layout/TopBar.js
  source/renderer/app/components/notifications/LegacyNotification.js
  source/renderer/app/containers/TopBarContainer.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
Labels: V2-API, feature, release-vNext

#1656 Release/0.15.1
  CHANGELOG.md
  installers/cardano-configuration.yaml
  package.json
  source/renderer/app/api/utils/externalRequest.js
Labels: release-0.15.1

#1660 [DDW-983] Revert yarn.lock changes
  CHANGELOG.md
  yarn.lock
Labels: V2-API, bug, release-vNext

#1661 Merge master into develop branch
  CHANGELOG.md
  installers/cardano-configuration.yaml
  package.json
  source/renderer/app/api/utils/externalRequest.js
Labels: chore, release-0.15.1

#1663 [DDW-979] Fix icons for SelfNode, QA, and Nightly Testnet networks builds
  default.nix
Labels: V2-API, bug, release-vNext

#1651 [DDW-1038] Integrate Delete Pending Transaction V2 API Endpoint for Legacy Wallets
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/api/transactions/requests/deleteLegacyTransaction.js
  source/renderer/app/api/transactions/requests/deleteTransaction.js
  source/renderer/app/api/transactions/types.js
  source/renderer/app/assets/images/spinner-dark.svg
  source/renderer/app/assets/images/wallet-nav/pending.inline.svg
  source/renderer/app/components/splash/Network.scss
  source/renderer/app/components/wallet/transactions/CancelTransactionButton.js
  source/renderer/app/components/wallet/transactions/CancelTransactionButton.scss
  source/renderer/app/components/wallet/transactions/CancelTransactionConfirmationDialog.js
  source/renderer/app/components/wallet/transactions/CancelTransactionConfirmationDialog.scss
  source/renderer/app/components/wallet/transactions/SpinnerOverrides.scss
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/components/wallet/transactions/Transaction.scss
  source/renderer/app/components/wallet/transactions/TransactionTypeIcon.js
  source/renderer/app/components/wallet/transactions/TransactionTypeIcon.scss
  source/renderer/app/components/wallet/transactions/WalletTransactionsList.js
  source/renderer/app/config/txnsConfig.js
  source/renderer/app/containers/TopBarContainer.js
  source/renderer/app/containers/wallet/WalletSummaryPage.js
  source/renderer/app/containers/wallet/WalletTransactionsPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/TransactionsStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/WalletScreens.stories.js
  storybook/stories/WalletTransactionsList.stories.js
Labels: V2-API, feature, release-vNext

#1657 [DDW-1053] Handle Incentivized Testnet network UI
  CHANGELOG.md
  README.md
  package.json
  source/common/types/environment.types.js
  source/main/environment.js
  source/main/menus/osx.js
  source/main/menus/win-linux.js
  source/renderer/app/api/api.js
  source/renderer/app/components/sidebar/SidebarCategory.scss
  source/renderer/app/components/sidebar/SidebarCategoryNetworkInfo.js
  source/renderer/app/components/widgets/WalletTestEnvironmentLabel.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/ProfileStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  storybook/stories/Sidebar.stories.js
  storybook/stories/TopBar.stories.js
Labels: V2-API, feature, release-vNext

#1613 [DDW-977] Integrate network information V2 API endpoint
  CHANGELOG.md
  features/tests/e2e/steps/app-steps.js
  source/main/config.js
  source/renderer/app/api/api.js
  source/renderer/app/api/network/errors.js
  source/renderer/app/api/network/requests/getNetworkInfo.js
  source/renderer/app/api/network/types.js
  source/renderer/app/api/nodes/types.js
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/components/loading/syncing-connecting/StatusIcons.js
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/components/status/DaedalusDiagnostics.scss
  source/renderer/app/config/timingConfig.js
  source/renderer/app/containers/status/DaedalusDiagnosticsDialog.js
  source/renderer/app/domains/Wallet.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/NodeUpdateStore.js
  source/renderer/app/stores/ProfileStore.js
  source/renderer/app/stores/WalletSettingsStore.js
  source/renderer/app/stores/WalletsStore.js
  storybook/stories/Diagnostics.stories.js
Labels: V2-API, feature, release-vNext

#1664 [DDW-905] Add "Terms and conditions" for Incentivized Testnet
  CHANGELOG.md
  source/renderer/app/components/profile/terms-of-use/TermsOfUseText.scss
  source/renderer/app/i18n/locales/terms-of-use/itn-balance-check/en-US.md
  source/renderer/app/i18n/locales/terms-of-use/itn-balance-check/ja-JP.md
  source/renderer/app/stores/ProfileStore.js
Labels: V2-API, chore, release-vNext

#1665 [DDW-1051] Update Cardano Explorer links
  source/common/types/environment.types.js
  source/main/environment.js
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/components/wallet/transactions/WalletTransactionsList.js
  source/renderer/app/config/urlsConfig.js
  source/renderer/app/containers/status/DaedalusDiagnosticsDialog.js
  source/renderer/app/containers/wallet/WalletSummaryPage.js
  source/renderer/app/containers/wallet/WalletTransactionsPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/utils/network.js
  storybook/stories/WalletScreens.stories.js
  storybook/stories/WalletTransactionsList.stories.js
Labels: V2-API, feature, release-vNext

#1668 [DDW-1065] Hide legacy wallet notification during wallet restoration/syncing
  CHANGELOG.md
  source/renderer/app/components/layout/TopBar.js
  source/renderer/app/components/notifications/LegacyNotification.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: V2-API, feature, release-vNext

#1671 [DDW-1054] Make links for incentivised testnet theme consistent color
  source/renderer/app/components/notifications/LegacyNotification.js
  source/renderer/app/components/staking/delegation-center/DelegationCenterHeader.scss
  source/renderer/app/components/staking/delegation-center/WalletRow.scss
  source/renderer/app/components/staking/rewards/StakingRewards.scss
  source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.scss
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.scss
  source/renderer/app/i18n/locales/defaultMessages.json
Labels: V2-API, chore, release-vNext

#1669 [DDW-1061] Fix cardano-node process name
  CHANGELOG.md
  source/common/types/cardano-node.types.js
  source/main/cardano/utils.js
Labels: V2-API, bug, release-vNext

#1666 [DDW-977] Add sync-tolerance parameter for jormungandr wallet
  nix/launcher-config.nix
  nix/sources.json
  source/common/types/cardano-node.types.js
  source/common/types/logging.types.js
  source/renderer/app/api/api.js
  source/renderer/app/api/network/requests/getNetworkInfo.js
  source/renderer/app/api/network/types.js
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/components/loading/syncing-connecting/SyncingConnecting.js
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/config/numbersConfig.js
  source/renderer/app/config/timingConfig.js
  source/renderer/app/containers/Root.js
  source/renderer/app/containers/loading/LoadingPage.js
  source/renderer/app/containers/loading/SyncingConnectingPage.js
  source/renderer/app/containers/loading/SystemTimeErrorPage.js
  source/renderer/app/containers/status/DaedalusDiagnosticsDialog.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/ProfileStore.js
Labels: V2-API, chore, release-vNext

#1673 [DDW-1064]: Implement connecting and syncing screens for incentivized testnet
  CHANGELOG.md
  features/tests/e2e/steps/app-steps.js
  features/tests/e2e/steps/trouble-syncing-notification-steps.js
  source/renderer/app/assets/images/circle-bg-faded.inline.svg
  source/renderer/app/components/loading/syncing-connecting/ReportIssue.scss
  source/renderer/app/components/loading/syncing-connecting/StatusIcons.scss
  source/renderer/app/components/loading/syncing-connecting/SyncingConnecting.js
  source/renderer/app/components/loading/syncing-connecting/SyncingConnecting.scss
  source/renderer/app/components/loading/syncing-connecting/SyncingConnectingBackground.js
  source/renderer/app/components/loading/syncing-connecting/SyncingConnectingBackground.scss
  source/renderer/app/components/loading/syncing-connecting/SyncingConnectingStatus.js
  source/renderer/app/components/loading/syncing-connecting/SyncingConnectingStatus.scss
  source/renderer/app/components/loading/syncing-connecting/SyncingConnectingTitle.js
  source/renderer/app/components/loading/syncing-connecting/SyncingConnectingTitle.scss
  source/renderer/app/components/splash/Network.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/Loading-SyncingConnecting.stories.js
  storybook/stories/Loading.stories.js
Labels: V2-API, feature, release-vNext

#1674 [DDW-1068] Use production Cardano Explorer URL
  CHANGELOG.md
  source/common/utils/environmentCheckers.js
  source/main/environment.js
  source/renderer/app/api/api.js
  source/renderer/app/api/transactions/types.js
  source/renderer/app/components/wallet/paper-wallet-certificate/CompletionDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/InstructionsDialog.js
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/components/wallet/transactions/WalletTransactionsList.js
  source/renderer/app/config/urlsConfig.js
  source/renderer/app/containers/wallet/WalletSummaryPage.js
  source/renderer/app/containers/wallet/WalletTransactionsPage.js
  source/renderer/app/containers/wallet/dialogs/paper-wallet-certificate/CompletionDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/paper-wallet-certificate/InstructionsDialogContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/utils/network.js
Labels: V2-API, feature, release-vNext

#1676 [DDW-1070]: Update incentivized testnet splash screen priority
  CHANGELOG.md
  source/renderer/app/containers/Root.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: V2-API, feature, release-vNext

#1677 [DDW-1071] Incentivized Testnet Theme Fixes
  CHANGELOG.md
  source/common/utils/environmentCheckers.js
  source/renderer/app/components/news/AlertsOverlay.scss
  source/renderer/app/components/news/IncidentOverlay.scss
  source/renderer/app/components/notifications/LegacyNotification.js
  source/renderer/app/components/notifications/LegacyNotification.scss
  source/renderer/app/components/sidebar/SidebarCategory.scss
  source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.scss
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
Labels: V2-API, bug, release-vNext

#1678 [DDW-1069] Rotating logs
  package.json
  source/main/cardano/CardanoNode.js
  source/main/cardano/CardanoWalletLauncher.js
  source/main/cardano/setupCardanoNodeMode.js
  source/main/config.js
  yarn.lock
Labels: V2-API, chore, release-vNext

#1675 [DDW-1059|1060] Fix Daedalus lock file path and Daedalus state directory structure
  default.nix
  lib.nix
  nix/launcher-config.nix
  nix/sources.json
  shell.nix
Labels: V2-API, bug, release-vNext

#1679 Incentivized Testnet Balance Check
  default.nix
  installer-clusters.cfg
  installers/Installer.hs
  installers/common/Types.hs
  installers/icons/itn_balance_check.iconset/icon_1024x1024.png
  installers/icons/itn_balance_check.iconset/icon_1024x1024@2x.png
  installers/icons/itn_balance_check.iconset/icon_128x128.png
  installers/icons/itn_balance_check.iconset/icon_128x128@2x.png
  installers/icons/itn_balance_check.iconset/icon_16x16.png
  installers/icons/itn_balance_check.iconset/icon_16x16@2x.png
  installers/icons/itn_balance_check.iconset/icon_18x18.png
  installers/icons/itn_balance_check.iconset/icon_18x18@2x.png
  installers/icons/itn_balance_check.iconset/icon_19x19.png
  installers/icons/itn_balance_check.iconset/icon_19x19@2x.png
  installers/icons/itn_balance_check.iconset/icon_22x22.png
  installers/icons/itn_balance_check.iconset/icon_22x22@2x.png
  installers/icons/itn_balance_check.iconset/icon_24x24.png
  installers/icons/itn_balance_check.iconset/icon_24x24@2x.png
  installers/icons/itn_balance_check.iconset/icon_256x256.png
  installers/icons/itn_balance_check.iconset/icon_256x256@2x.png
  installers/icons/itn_balance_check.iconset/icon_32x32.png
  installers/icons/itn_balance_check.iconset/icon_32x32@2x.png
  installers/icons/itn_balance_check.iconset/icon_40x40.png
  installers/icons/itn_balance_check.iconset/icon_40x40@2x.png
  installers/icons/itn_balance_check.iconset/icon_48x48.png
  installers/icons/itn_balance_check.iconset/icon_48x48@2x.png
  installers/icons/itn_balance_check.iconset/icon_512x512.png
  installers/icons/itn_balance_check.iconset/icon_512x512@2x.png
  installers/icons/itn_balance_check.iconset/icon_64x64.png
  installers/icons/itn_balance_check.iconset/icon_64x64@2x.png
  installers/icons/itn_balance_check/1024x1024.png
  installers/icons/itn_balance_check/128x128.ico
  installers/icons/itn_balance_check/128x128.png
  installers/icons/itn_balance_check/16x16.ico
  installers/icons/itn_balance_check/16x16.png
  installers/icons/itn_balance_check/18x18.ico
  installers/icons/itn_balance_check/18x18.png
  installers/icons/itn_balance_check/19x19.ico
  installers/icons/itn_balance_check/19x19.png
  installers/icons/itn_balance_check/22x22.ico
  installers/icons/itn_balance_check/22x22.png
  installers/icons/itn_balance_check/24x24.ico
  installers/icons/itn_balance_check/24x24.png
  installers/icons/itn_balance_check/256x256.ico
  installers/icons/itn_balance_check/256x256.png
  installers/icons/itn_balance_check/32x32.ico
  installers/icons/itn_balance_check/32x32.png
  installers/icons/itn_balance_check/40x40.ico
  installers/icons/itn_balance_check/40x40.png
  installers/icons/itn_balance_check/48x48.ico
  installers/icons/itn_balance_check/48x48.png
  installers/icons/itn_balance_check/512x512.png
  installers/icons/itn_balance_check/64x64.ico
  installers/icons/itn_balance_check/64x64.png
  installers/icons/itn_balance_check/itn_balance_check.ico
  installers/icons/update_icons
  nix/launcher-config.nix
  nix/sources.json
  release-build.nix
  yarn2nix.nix
Labels: V2-API, feature, release-vNext

#1680 [DDW-1073] Daedalus copy updates for Incentivized Testnet - Balance check
  CHANGELOG.md
  source/renderer/app/components/layout/TopBar.js
  source/renderer/app/components/loading/syncing-connecting/StatusIcons.js
  source/renderer/app/components/notifications/LegacyBadge.js
  source/renderer/app/components/notifications/LegacyNotification.js
  source/renderer/app/components/notifications/LegacyNotification.scss
  source/renderer/app/components/wallet/WalletAdd.js
  source/renderer/app/components/wallet/WalletRestoreDialog.js
  source/renderer/app/components/wallet/settings/WalletSettings.js
  source/renderer/app/components/wallet/settings/WalletSettings.scss
  source/renderer/app/components/wallet/transfer-funds/TransferFundsStep1Dialog.js
  source/renderer/app/components/wallet/transfer-funds/TransferFundsStep2Dialog.js
  source/renderer/app/components/widgets/RadioSet.scss
  source/renderer/app/components/widgets/forms/InlineEditingInput.js
  source/renderer/app/components/widgets/forms/WalletsDropdownOption.scss
  source/renderer/app/config/profileConfig.js
  source/renderer/app/containers/wallet/WalletAddPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/themes/mixins/buttons.scss
  storybook/stories/_support/config.js
  storybook/stories/wallets/addWallet/Add.stories.js
  tests/wallets/e2e/features/restore-wallet-via-sidebar.feature
  tests/wallets/e2e/steps/wallets.js
Labels: V2-API, chore, release-vNext

#1684 [DDW-1071] Incentivized Testnet Theme Fixes
  CHANGELOG.md
  source/renderer/app/components/sidebar/SidebarCategory.scss
  source/renderer/app/components/wallet/settings/DeleteWalletButton.scss
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
Labels: V2-API, bug, release-vNext

#1688 cardano-wallet: update to release 2019-11-14
  nix/sources.json
Labels: V2-API, chore, release-vNext

#1685 [DDW-1073] Daedalus copy updates for Incentivized Testnet - Balance check
  source/renderer/app/components/sidebar/SidebarCategory.scss
Labels: V2-API, chore, release-vNext

#1691 [DDW-1079] Add Japanese Terms of Use
  CHANGELOG.md
  source/renderer/app/i18n/locales/terms-of-use/itn-balance-check/ja-JP.md
Labels: chore, release-vNext-ITN0

#1693 [DDW-993]: Button text is not well vertically centered
  CHANGELOG.md
  source/renderer/app/components/wallet/settings/WalletRecoveryPhrase.scss
Labels: bug, release-vNext-ITN0

#1690 [DDW-1083] Prevent latest version check and fix wallet ordering
  CHANGELOG.md
  source/renderer/app/components/loading/syncing-connecting/SyncingConnecting.js
  source/renderer/app/stores/NodeUpdateStore.js
  source/renderer/app/stores/WalletsStore.js
Labels: bug, release-vNext-ITN0

#1695 [DDW-1084] Bump Daedalus version to 1.1.0-ITN0
  CHANGELOG.md
  package.json
Labels: chore, release-1.1.0-ITN0

#1696 [DEVOPS] Remove wallet and jormungandr binaries from devops shell
  shell.nix
Labels: bug, release-1.1.0-ITN0

#1694 Bumps cardano-wallet version
  nix/sources.json
Labels: bug, release-1.1.0-ITN0

#1692 [DDW-1082] On the restore dialog when i click first tab it changes selection to 15 word recovery phrase
  CHANGELOG.md
  source/renderer/app/components/wallet/WalletRestoreDialog.js
  source/renderer/app/i18n/locales/defaultMessages.json
Labels: bug, release-1.1.0-ITN0

#1697 [DDW-1085] Bump sync report issue timer threshold to 10 mins
  CHANGELOG.md
  nix/launcher-config.nix
  nix/sources.json
  source/renderer/app/config/timingConfig.js
Labels: chore, release-1.1.0-ITN0

#1689 [DDW-1076] Wallet name update feature issues
  CHANGELOG.md
  source/renderer/app/components/layout/TopBar.scss
  source/renderer/app/components/sidebar/wallets/SidebarWalletMenuItem.scss
  source/renderer/app/components/wallet/WalletSendConfirmationDialog.js
  source/renderer/app/components/wallet/settings/WalletSettings.js
  source/renderer/app/components/wallet/settings/WalletSettings.scss
  source/renderer/app/components/widgets/forms/InlineEditingInput.js
  source/renderer/app/containers/wallet/WalletSettingsPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  storybook/stories/wallets/settings/WalletSettingsScreen.stories.js
Labels: bug, release-1.1.0-ITN0

#1699 [DDW-992] Yellow frame displayed around the Diagnostics Dialog
  CHANGELOG.md
  source/renderer/app/components/status/DaedalusDiagnostics.scss
Labels: :hourglass_flowing_sand:release-vNext-ITN0, bug

#1703 [DDW-1086]: Fix incorrect wallet password change issue
  CHANGELOG.md
  source/renderer/app/api/api.js
Labels: :hourglass_flowing_sand:release-vNext-ITN0, chore

#1702 [DDW-1017] Fix Select Language Tests
  CHANGELOG.md
  tests/navigation/e2e/features/navigate-general-settings-menu.feature
  tests/settings/e2e/features/select-language.feature
  tests/settings/e2e/steps/general-settings.js
Labels: :hourglass_flowing_sand:release-vNext-ITN0, bug

#1704 Merge latest develop into v2 integration
  default.nix
Labels: :hourglass_flowing_sand:release-vNext-ITN0, chore

#1705 [DDW-932] Unconfirmed transactions calculation
  CHANGELOG.md
  source/renderer/app/components/wallet/summary/WalletSummary.js
  source/renderer/app/components/wallet/summary/WalletSummary.scss
  source/renderer/app/config/numbersConfig.js
  source/renderer/app/containers/wallet/WalletSummaryPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/TransactionsStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  source/renderer/app/types/unconfirmedAmountType.js
  storybook/stories/wallets/summary/WalletSummary.stories.js
Labels: :hourglass_flowing_sand:release-vNext-ITN0, feature

#1707 [DDW-970] Fix disabled red button color
  CHANGELOG.md
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
Labels: :hourglass_flowing_sand:release-vNext-ITN0, bug

#1706 [DDW-786]: Remove unused dependencies
  CHANGELOG.md
  package.json
  source/renderer/webpack.config.js
  storybook/webpack.config.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext-ITN0, chore

#1709 [DDW-1088] Fix themes:check:createTheme Script
  CHANGELOG.md
  gulpfile.js
  source/renderer/app/themes/utils/constants.js
  source/renderer/app/themes/utils/createTheme.js
Labels: :hourglass_flowing_sand:release-vNext-ITN0, bug

#1710 [DDW-1091] Fix storing duplicated "Newsfeed" ID's when marked as read
  CHANGELOG.md
  source/renderer/app/api/utils/localStorage.js
  source/renderer/app/components/news/AlertsOverlay.js
Labels: :hourglass_flowing_sand:release-vNext-ITN0, bug

#1708 [DDW-1058] - Apply proper styles to "network info" screen's button
  CHANGELOG.md
  source/renderer/app/components/loading/syncing-connecting/SyncingConnecting.js
  source/renderer/app/components/loading/syncing-connecting/SyncingConnectingBackground.js
  source/renderer/app/components/loading/syncing-connecting/SyncingConnectingBackground.scss
  source/renderer/app/components/loading/syncing-connecting/SyncingConnectingTitle.js
  source/renderer/app/components/splash/Network.js
  source/renderer/app/components/splash/Network.scss
  source/renderer/app/containers/staking/StakingRewardsPage.js
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  storybook/stories/_support/StoryLayout.js
  storybook/stories/_support/StoryWrapper.js
  storybook/stories/_support/utils.js
  storybook/stories/navigation/Sidebar.stories.js
  storybook/stories/navigation/SidebarWalletsMenu.stories.js
  storybook/stories/nodes/environment/TopBarEnvironment.stories.js
  storybook/stories/nodes/index.js
  storybook/stories/nodes/splash/Splash.stories.js
  storybook/stories/nodes/syncing/Syncing.stories.js
  storybook/stories/nodes/syncing/SyncingConnecting.stories.js
  storybook/stories/settings/utils/SettingsWrapper.js
  storybook/stories/staking/DelegationSteps.stories.js
  storybook/stories/staking/StakePools.stories.js
  storybook/stories/staking/Staking.stories.js
  storybook/stories/staking/StakingWrapper.js
  storybook/stories/wallets/_utils/WalletsWrapper.js
  storybook/stories/wallets/addWallet/Add.stories.js
  storybook/stories/wallets/settings/WalletSettings.stories.js
  storybook/stories/wallets/settings/WalletSettingsScreen.stories.js
Labels: :hourglass_flowing_sand:release-vNext-ITN0, bug

#1718 Merge latest develop into v2 integration
  CHANGELOG.md
Labels: :hourglass_flowing_sand:release-vNext-ITN0, chore

#1719 [DDW-1081] Adjust Stake pool logic for ranking color
  CHANGELOG.md
  source/renderer/app/components/staking/delegation-center/DelegationCenter.js
  source/renderer/app/components/staking/delegation-center/DelegationCenterBody.js
  source/renderer/app/components/staking/delegation-center/WalletRow.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.js
  source/renderer/app/components/staking/stake-pools/StakePoolThumbnail.js
  source/renderer/app/components/staking/stake-pools/StakePools.js
  source/renderer/app/components/staking/stake-pools/StakePoolsList.js
  source/renderer/app/containers/staking/DelegationCenterPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/utils/colors.js
  storybook/stories/staking/DelegationCenter.stories.js
Labels: :hourglass_flowing_sand:release-vNext-ITN0, bug

#1723 [DDW-841] - Instead of node in status icon tooltips we should say Cardano node
  CHANGELOG.md
  source/renderer/app/components/loading/syncing-connecting/StatusIcons.js
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
Labels: :hourglass_flowing_sand:release-vNext-ITN0, bug

#1714 [DDW-961] Reorganize Storybook and Add Missing Stories, Updates, and Improvements
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.js
  source/renderer/app/components/widgets/forms/WalletsDropdown.js
  storybook/stories/nodes/status/Diagnostics.stories.js
  storybook/stories/staking/DelegationSteps.stories.js
  storybook/stories/staking/Epochs.stories.js
  storybook/stories/wallets/settings/WalletDelete.stories.js
Labels: :hourglass_flowing_sand:release-vNext-ITN0, chore

#1713 [DDW-1080] Wallet ada displays in several lines when number format is selected without any separators
  source/renderer/app/components/layout/TopBar.js
  source/renderer/app/components/notifications/LegacyBadge.scss
  source/renderer/app/components/sidebar/wallets/SidebarWalletMenuItem.js
  source/renderer/app/components/sidebar/wallets/SidebarWalletMenuItem.scss
  source/renderer/app/config/profileConfig.js
  source/renderer/app/stores/ProfileStore.js
  source/renderer/app/stores/SidebarStore.js
  source/renderer/app/utils/formatters.js
  tests/paper-wallets/e2e/features/paper-wallets-certificate.feature
  tests/transactions/e2e/features/send-money-to-receiver.feature
Labels: :hourglass_flowing_sand:release-vNext-ITN0, bug

#1712 [DDW-1093] Update cardano-js to v0.2.2 and address validator improvement
  CHANGELOG.md
  package.json
  source/renderer/app/stores/WalletsStore.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext-ITN0, chore

#1715 [DDW-1089] Add a script which checks for "integrity" lines in yarn.lock file
  CHANGELOG.md
  package.json
  utils/create-news-verification-hashes/index.js
  utils/js-launcher/index.js
  utils/lockfile-checker/index.js
  utils/v2-api-importer/index.js
  utils/v2-api-importer/legacy.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext-ITN0, feature

#1726 [DDW-1104] Fix transaction amount handling with new number formats
  CHANGELOG.md
  source/renderer/app/App.js
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/stores/ProfileStore.js
  source/renderer/app/utils/formatters.js
  tests/nodes/e2e/features/data-layer-migration.feature
  tests/wallets/e2e/features/restore-wallet-via-sidebar.feature
Labels: :hourglass_flowing_sand:release-vNext-ITN0, bug

#1727 [DDW-1025] External link icon on menu items
  CHANGELOG.md
  source/main/locales/en-US.json
  source/main/locales/ja-JP.json
Labels: :hourglass_flowing_sand:release-vNext-ITN0, chore

#1728 [DDW-1025] Adds link icon to the 'Safety Tips' menu item
  CHANGELOG.md
  source/main/locales/en-US.json
  source/main/locales/ja-JP.json
Labels: :hourglass_flowing_sand:release-vNext-ITN0, chore

#1724 [DDW-1101] Improve send screen error messages
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/api/transactions/types.js
  source/renderer/app/api/wallets/types.js
  source/renderer/app/components/wallet/WalletSendConfirmationDialog.js
  source/renderer/app/components/wallet/WalletSendForm.js
  source/renderer/app/domains/Wallet.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/stores/TransactionsStore.js
  source/renderer/app/stores/WalletsStore.js
  storybook/stories/_support/utils.js
  storybook/stories/staking/DelegationCenter.stories.js
Labels: :hourglass_flowing_sand:release-vNext-ITN0, chore

#1730 [DDW-1106] Missing hamburger icon
  CHANGELOG.md
  source/renderer/app/containers/TopBarContainer.js
Labels: bug, release-2.0.0-ITN1
