Repository input-output-hk/daedalus, pull requests merged in 2019-05, with the labels that each got.

#1384 [DDW-633] Fork electron-log and fix issues
  CHANGELOG.md
  package.json
  source/main/config.js
  source/main/ipc/compress-logs.js
  source/main/preload.js
  source/main/utils/logging.js
  source/main/utils/safeExitWithCode.js
  source/main/utils/setupLogging.js
  source/renderer/app/i18n/locales/defaultMessages.json
  yarn.lock
Labels: bug, release-0.14.0

#1388 [DDW-661] Linux Daedalus localtime fix
  default.nix
  installers/nix/nix-installer.nix
Labels: bug, release-0.14.0

#1389 Reduce the closure size of node-modules by ~1600 items
  yarn2nix.nix
Labels: chore, release-0.14.0

#1391 [DDW-662] Setup automatic storybook builds on netlify
  CHANGELOG.md
  package.json
Labels: chore, release-0.14.0

#1393 [DDW-666] Fixed EKG server port collision in development mode
  CHANGELOG.md
  installers/dhall/demo.dhall
  source/renderer/app/config/urlsConfig.js
Labels: bug, release-0.14.0

#1392 [DDW-643] Spending password is asked when clicking on 'Copy address' link
  CHANGELOG.md
  source/renderer/app/components/wallet/receive/WalletReceive.js
Labels: bug, release-0.14.0

#1385 [DDW-637] Add timestamp for Paper wallet
  CHANGELOG.md
  features/generate-filename-with-timestamp.feature
  features/tests/e2e/helpers/screenshot.js
  features/tests/unit/steps/generate-filename-with-timestamp-steps.js
  source/common/types/paper-wallet-request.types.js
  source/common/utils/files.js
  source/main/ipc/generatePaperWalletChannel.js
  source/renderer/app/actions/network-status-actions.js
  source/renderer/app/components/status/NetworkStatus.js
  source/renderer/app/components/wallet/paper-wallet-certificate/InstructionsDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/InstructionsDialog.scss
  source/renderer/app/components/wallet/utxo/WalletUtxo.js
  source/renderer/app/containers/status/NetworkStatusDialog.js
  source/renderer/app/containers/wallet/dialogs/paper-wallet-certificate/InstructionsDialogContainer.js
  source/renderer/app/i18n/errors.js
  source/renderer/app/i18n/global-messages.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/utils/paperWalletPdfGenerator.js
Labels: feature, release-0.14.0

#1370 [DDW-611] Implement new Network status dialog design
  CHANGELOG.md
  features/support/paper_wallet_certificates/paper-wallet-certificate.pdf
  source/common/types/cardano-node.types.js
  source/common/types/environment.types.js
  source/common/types/logging.types.js
  source/common/types/no-disk-space.types.js
  source/main/cardano/CardanoNode.js
  source/main/cardano/utils.js
  source/main/config.js
  source/main/environment.js
  source/main/index.js
  source/main/menus/osx.js
  source/main/menus/win-linux.js
  source/main/utils/buildAppMenus.js
  source/main/utils/handleDiskSpace.js
  source/main/utils/processes.js
  source/main/windows/main.js
  source/renderer/app/components/status/NetworkStatus.js
  source/renderer/app/components/status/NetworkStatus.scss
  source/renderer/app/containers/status/NetworkStatusDialog.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/stores/BlockConsolidationStore.js
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/types/coreSystemInfoTypes.js
  source/renderer/app/types/systemInfoTypes.js
Labels: chore, release-0.14.0

#1399 [DDW 622] Remove legacy npm references
  CHANGELOG.md
  installers/common/Util.hs
  installers/common/WindowsInstaller.hs
  package.json
  scripts/package.js
  tests/lint.nix
  yarn.lock
Labels: chore, release-0.14.0

#1402 [DDW-675] Fix broken Storybook
  CHANGELOG.md
  package.json
  source/main/environment.js
  source/renderer/app/containers/status/NetworkStatusDialog.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/i18n/translations.js
  yarn.lock
Labels: bug, release-0.14.0

#1404 [DDW-676] Improve network status dialog
  CHANGELOG.md
  source/common/ipc/api.js
  source/common/types/environment.types.js
  source/common/types/stateDirectoryPath.types.js
  source/main/environment.js
  source/main/index.js
  source/main/ipc/getStateDirectoryPathChannel.js
  source/renderer/app/components/status/NetworkStatus.js
  source/renderer/app/components/status/NetworkStatus.scss
  source/renderer/app/components/wallet/navigation/WalletNavigation.js
  source/renderer/app/containers/status/NetworkStatusDialog.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/ipc/getStateDirectoryPathChannel.js
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/types/coreSystemInfoTypes.js
Labels: bug, release-0.14.0

#1394 [DDW-647] Decentralization progress
  CHANGELOG.md
  source/renderer/app/Routes.js
  source/renderer/app/actions/index.js
  source/renderer/app/actions/staking-actions.js
  source/renderer/app/assets/images/sidebar/delegation-progress-ic.inline.svg
  source/renderer/app/components/sidebar/Sidebar.scss
  source/renderer/app/components/sidebar/SidebarCategory.js
  source/renderer/app/components/sidebar/SidebarCategory.scss
  source/renderer/app/components/staking/_stakingConfig.scss
  source/renderer/app/components/staking/delegation-countdown/DelegationCountDownInfo.js
  source/renderer/app/components/staking/delegation-countdown/DelegationCountDownInfo.scss
  source/renderer/app/components/staking/delegation-countdown/DelegationCountdownCounter.js
  source/renderer/app/components/staking/delegation-countdown/DelegationCountdownCounter.scss
  source/renderer/app/components/staking/delegation-countdown/StakingDelegationCountdown.js
  source/renderer/app/components/staking/delegation-countdown/StakingDelegationCountdown.scss
  source/renderer/app/components/staking/info/StakingInfo.js
  source/renderer/app/components/staking/info/StakingInfo.scss
  source/renderer/app/config/sidebarConfig.js
  source/renderer/app/containers/Root.js
  source/renderer/app/containers/staking/Staking.js
  source/renderer/app/containers/staking/StakingDelegationCenterPage.js
  source/renderer/app/containers/staking/StakingDelegationCountdownPage.js
  source/renderer/app/containers/staking/StakingEpochsPage.js
  source/renderer/app/containers/staking/StakingInfoPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/AppStore.js
  source/renderer/app/stores/SidebarStore.js
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  storybook/stories/Sidebar.stories.js
  storybook/stories/Staking-Legacy.stories.js
  storybook/stories/Staking.stories.js
  storybook/stories/StakingDelegationCountdown.stories.js
  storybook/stories/support/StoryLayout.js
Labels: feature, release-0.14.0

#1403 [DDW-650] UI - Staking rewards
  CHANGELOG.md
  source/renderer/app/assets/images/ascending.inline.svg
  source/renderer/app/components/staking/rewards/StakingRewards.js
  source/renderer/app/components/staking/rewards/StakingRewards.scss
  source/renderer/app/containers/staking/Staking.js
  source/renderer/app/containers/staking/StakingRewardsPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  storybook/stories/Staking-Rewards.stories.js
  storybook/stories/Staking.stories.js
Labels: feature, release-0.14.0

#1405 [DDW-674] Truncated "Add Wallet" screen while wallet is restored
  CHANGELOG.md
  source/renderer/app/components/wallet/WalletAdd.scss
Labels: bug, release-0.14.0

#1401 [DDW-655] Log Daedalus version
  package.json
  source/main/cardano/CardanoNode.js
  source/main/config.js
  source/main/index.js
  source/main/utils/logUsedVersion.js
  yarn.lock
Labels: chore, release-0.14.0

#1407 [DDW-678] Addresses are not visible on Receive screen
  CHANGELOG.md
  source/renderer/app/components/wallet/receive/WalletReceive.scss
Labels: WIP, bug, release-0.14.0
