Repository input-output-hk/daedalus, pull requests merged in 2019-07, with the labels that each got.

#1445 [DDW-731] Remove non-formatted files
  CHANGELOG.md
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/utils/createTheme.js
Labels: bug, release-0.14.0

#1440 [DDW-651]: UI - Delegation Center
  CHANGELOG.md
  source/renderer/app/assets/images/link-ic-colored.inline.svg
  source/renderer/app/assets/images/settings-ic.inline.svg
  source/renderer/app/components/staking/_stakingConfig.scss
  source/renderer/app/components/staking/delegation-center/DelegationCenter.js
  source/renderer/app/components/staking/delegation-center/DelegationCenter.scss
  source/renderer/app/components/staking/delegation-center/DelegationCenterBody.js
  source/renderer/app/components/staking/delegation-center/DelegationCenterBody.scss
  source/renderer/app/components/staking/delegation-center/DelegationCenterHeader.js
  source/renderer/app/components/staking/delegation-center/DelegationCenterHeader.scss
  source/renderer/app/components/staking/delegation-center/DonutRing.js
  source/renderer/app/components/staking/delegation-center/DonutRing.scss
  source/renderer/app/components/staking/delegation-center/DropdownMenu.js
  source/renderer/app/components/staking/delegation-center/DropdownMenu.scss
  source/renderer/app/components/staking/delegation-center/WalletRow.js
  source/renderer/app/components/staking/delegation-center/WalletRow.scss
  source/renderer/app/config/numbersConfig.js
  source/renderer/app/containers/staking/DelegationCenterPage.js
  source/renderer/app/domains/Wallet.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/utils/colors.js
  storybook/stories/Staking-DelegationCenter.stories.js
  storybook/stories/Staking-StakePools.stories.js
  storybook/stories/Staking.stories.js
Labels: feature, release-0.14.0

#1449 [DEVOPS] OSX Mojave build fix
  README.md
  installers/common/MacInstaller.hs
  release.nix
Labels: bug, release-0.14.0

#1450 [DDW-681] Update 'About' screen Daedalus contributors
  CHANGELOG.md
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: chore, release-0.14.0

#1444 [DDW-702] Fix screen loading logic
  CHANGELOG.md
  source/renderer/app/stores/NetworkStatusStore.js
Labels: bug, release-0.14.0

#1447 [DDW-698] Introduce external links icon
  CHANGELOG.md
  source/renderer/app/components/loading/Loading.scss
  source/renderer/app/components/loading/ManualUpdateOverlay.scss
  source/renderer/app/components/loading/SystemTimeErrorOverlay.js
  source/renderer/app/components/loading/SystemTimeErrorOverlay.scss
  source/renderer/app/components/settings/categories/SupportSettings.js
  source/renderer/app/components/settings/categories/SupportSettings.scss
  source/renderer/app/components/staking/countdown/StakingCountdown.js
  source/renderer/app/components/staking/countdown/StakingCountdown.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsIntroDialog.scss
  source/renderer/app/components/staking/epochs/StakingEpochs.scss
  source/renderer/app/components/staking/info/StakingInfo.js
  source/renderer/app/components/staking/info/StakingInfo.scss
  source/renderer/app/components/staking/rewards/StakingRewards.js
  source/renderer/app/components/staking/rewards/StakingRewards.scss
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.js
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.scss
  source/renderer/app/components/static/About.js
  source/renderer/app/components/static/About.scss
  source/renderer/app/components/status/BlockConsolidationStatus.js
  source/renderer/app/components/status/BlockConsolidationStatus.scss
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/components/status/DaedalusDiagnostics.scss
  source/renderer/app/components/wallet/paper-wallet-certificate/CompletionDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/CompletionDialog.scss
  source/renderer/app/components/wallet/paper-wallet-certificate/InstructionsDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/InstructionsDialog.scss
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/components/wallet/transactions/Transaction.scss
  source/renderer/app/containers/settings/categories/SupportSettingsPage.js
  source/renderer/app/containers/staking/StakingCountdownPage.js
  source/renderer/app/containers/staking/StakingInfoPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/mixins/link.scss
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/Staking.stories.js
Labels: feature, release-0.14.0

#1452 [DDW-722]: Loading screen icons UX improvement
  CHANGELOG.md
  source/renderer/app/components/loading/Loading.js
  source/renderer/app/components/loading/StatusIcons.js
  source/renderer/app/components/loading/StatusIcons.scss
  source/renderer/app/containers/LoadingPage.js
  storybook/stories/Diagnostics.stories.js
  storybook/stories/Loading.stories.js
  storybook/stories/index.js
Labels: feature, release-0.14.0

#1438 [DDW-600] Implement button to open the local database directory
  CHANGELOG.md
  source/common/ipc/api.js
  source/main/ipc/index.js
  source/main/ipc/open-local-directory.js
  source/renderer/app/components/notifications/GenericNotification.js
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/components/status/DaedalusDiagnostics.scss
  source/renderer/app/components/widgets/NotificationMessage.js
  source/renderer/app/components/widgets/NotificationMessage.scss
  source/renderer/app/config/timingConfig.js
  source/renderer/app/containers/status/DaedalusDiagnosticsDialog.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/ipc/open-local-directory.js
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/Diagnostics.stories.js
Labels: chore, release-0.14.0

#1430 [DDW-659] UI - Delegation setup wizard step 2
  CHANGELOG.md
  source/renderer/app/api/staking/types.js
  source/renderer/app/assets/images/check-w.inline.svg
  source/renderer/app/assets/images/stake-pool-placeholder.inline.svg
  source/renderer/app/components/staking/delegation-center/DelegationCenter.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationSetupWizardDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsIntroDialog.scss
  source/renderer/app/components/staking/stake-pools/StakePoolThumbnail.js
  source/renderer/app/components/staking/stake-pools/StakePoolThumbnail.scss
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.js
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.scss
  source/renderer/app/components/staking/stake-pools/StakePools.js
  source/renderer/app/components/staking/stake-pools/StakePools.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsList.js
  source/renderer/app/components/staking/stake-pools/StakePoolsSearch.js
  source/renderer/app/components/staking/stake-pools/StakePoolsSearch.scss
  source/renderer/app/components/widgets/Dialog.js
  source/renderer/app/components/widgets/Dialog.scss
  source/renderer/app/config/timingConfig.js
  source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/overrides/ModalOverrides.scss
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/Staking-DelegationCenter.stories.js
  storybook/stories/Staking.stories.js
Labels: feature, release-0.14.0

#1453 [DDW-695]: Improve "having trouble connecting/syncing" notifications
  CHANGELOG.md
  source/renderer/app/components/loading/Loading.js
  source/renderer/app/components/loading/Loading.scss
  source/renderer/app/containers/LoadingPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  storybook/stories/Loading.stories.js
Labels: feature, release-0.14.0

#1439 [DDW-660] UI - Delegation setup wizard steps 3 & 4
  CHANGELOG.md
  source/renderer/app/components/staking/countdown/StakingCountdown.scss
  source/renderer/app/components/staking/delegation-center/DelegationCenter.js
  source/renderer/app/components/staking/delegation-center/DelegationCenterBody.js
  source/renderer/app/components/staking/delegation-center/DelegationCenterHeader.scss
  source/renderer/app/components/staking/delegation-center/WalletRow.js
  source/renderer/app/components/staking/delegation-center/WalletRow.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationSetupWizardDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsActivationDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsActivationDialog.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsConfirmationDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsConfirmationDialog.scss
  source/renderer/app/components/staking/epochs/StakingEpochs.scss
  source/renderer/app/components/staking/info/StakingInfo.scss
  source/renderer/app/components/staking/layouts/StakingWithNavigation.scss
  source/renderer/app/components/staking/legacy/Staking.scss
  source/renderer/app/components/staking/rewards/StakingRewards.scss
  source/renderer/app/containers/staking/DelegationCenterPage.js
  source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/Staking-DelegationCenter.stories.js
  storybook/stories/Staking.stories.js
Labels: feature, release-0.14.0

#1437 [DDW-694] Improve UTXO screen
  CHANGELOG.md
  source/renderer/app/components/navigation/NavDropdown.scss
  source/renderer/app/components/navigation/NavOptionsStyles.scss
  source/renderer/app/components/navigation/Navigation.js
  source/renderer/app/components/staking/delegation-center/DropdownMenu.scss
  source/renderer/app/components/wallet/utxo/WalletUtxo.js
  source/renderer/app/components/wallet/utxo/WalletUtxo.scss
  source/renderer/app/components/wallet/utxo/WalletUtxoCursor.js
  source/renderer/app/components/wallet/utxo/WalletUtxoTick.scss
  source/renderer/app/containers/wallet/Wallet.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/utils/createTheme.js
Labels: chore, release-0.14.0

#1446 [DDW-683] Refactor the Loading screen
  CHANGELOG.md
  features/tests/e2e/steps/app-steps.js
  features/tests/e2e/steps/app-version-difference.js
  features/tests/e2e/steps/local-time-difference-steps.js
  features/tests/e2e/steps/no-disk-space.js
  features/tests/e2e/steps/trouble-connecting-notification-steps.js
  features/tests/e2e/steps/trouble-syncing-notification-steps.js
  source/renderer/app/components/loading/Loading.js
  source/renderer/app/components/loading/Loading.scss
  source/renderer/app/components/loading/manual-update/ManualUpdate.js
  source/renderer/app/components/loading/manual-update/ManualUpdate.scss
  source/renderer/app/components/loading/no-disk-space-error/NoDiskSpaceError.js
  source/renderer/app/components/loading/no-disk-space-error/NoDiskSpaceError.scss
  source/renderer/app/components/loading/syncing-connecting/LogosDisplay.js
  source/renderer/app/components/loading/syncing-connecting/LogosDisplay.scss
  source/renderer/app/components/loading/syncing-connecting/ReportIssue.js
  source/renderer/app/components/loading/syncing-connecting/ReportIssue.scss
  source/renderer/app/components/loading/syncing-connecting/StatusIcons-tooltip.scss
  source/renderer/app/components/loading/syncing-connecting/StatusIcons.js
  source/renderer/app/components/loading/syncing-connecting/StatusIcons.scss
  source/renderer/app/components/loading/syncing-connecting/SyncingConnecting.js
  source/renderer/app/components/loading/syncing-connecting/SyncingConnecting.scss
  source/renderer/app/components/loading/syncing-connecting/SyncingConnectingTitle.js
  source/renderer/app/components/loading/syncing-connecting/SyncingConnectingTitle.scss
  source/renderer/app/components/loading/system-time-error/SystemTimeError.js
  source/renderer/app/components/loading/system-time-error/SystemTimeError.scss
  source/renderer/app/containers/LoadingPage.js
  source/renderer/app/containers/Root.js
  source/renderer/app/containers/loading/Loading.js
  source/renderer/app/containers/loading/ManualUpdatePage.js
  source/renderer/app/containers/loading/NoDiskSpaceErrorPage.js
  source/renderer/app/containers/loading/SyncingConnectingPage.js
  source/renderer/app/containers/loading/SystemTimeErrorPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/types/injectedPropsType.js
  storybook/stories/Loading-ManualUpdate.stories.js
  storybook/stories/Loading-NoDiskSpaceError.stories.js
  storybook/stories/Loading-SyncingConnecting.stories.js
  storybook/stories/Loading-SystemTimeError.stories.js
  storybook/stories/Loading.stories.js
  storybook/stories/ManualUpdateOverlay.stories.js
  storybook/stories/index.js
Labels: feature, release-0.14.0

#1455 [DDW-739] Fix the position of the external link icon
  CHANGELOG.md
  source/renderer/app/components/loading/manual-update/ManualUpdate.js
  source/renderer/app/components/loading/manual-update/ManualUpdate.scss
  source/renderer/app/components/loading/syncing-connecting/ReportIssue.scss
  source/renderer/app/components/staking/countdown/StakingCountdown.js
  source/renderer/app/components/staking/countdown/StakingCountdown.scss
  source/renderer/app/components/staking/info/StakingInfo.js
  source/renderer/app/components/staking/info/StakingInfo.scss
  source/renderer/app/components/status/BlockConsolidationStatus.js
  source/renderer/app/components/status/BlockConsolidationStatus.scss
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/utils/createTheme.js
Labels: bug, release-0.14.0

#1428 [DDW-635] Shutting down Screen top Priority
  CHANGELOG.md
  source/renderer/app/containers/Root.js
  source/renderer/app/containers/loading/LoadingPage.js
  source/renderer/app/stores/NetworkStatusStore.js
Labels: bug, release-0.14.0

#1457 [DDW-736] Implement animated logo on the "Loading" screens
  CHANGELOG.md
  package.json
  source/renderer/app/components/loading/syncing-connecting/LogosDisplay.js
  source/renderer/app/components/loading/syncing-connecting/LogosDisplay.scss
  source/renderer/app/components/loading/syncing-connecting/logo-animation-data.json
  yarn.lock
Labels: feature, release-0.14.0

#1424 [DDW-696] Update createTheme Definitions
  CHANGELOG.md
  gulpfile.js
  package.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/types.js
  source/renderer/app/themes/utils/checkCreateTheme.js
  source/renderer/app/themes/utils/constants.js
  source/renderer/app/themes/utils/createTheme.js
  source/renderer/app/themes/utils/index.js
  yarn.lock
Labels: chore, release-0.14.0

#1458 [DDW-748] Ada redemption application menu item UX
  CHANGELOG.md
  source/main/menus/osx.js
  source/main/menus/win-linux.js
  source/main/utils/buildAppMenus.js
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/components/status/DaedalusDiagnostics.scss
  source/renderer/app/stores/NetworkStatusStore.js
Labels: chore, release-0.14.0

#1459 [DDW-746] Small UI and copy improvements
  CHANGELOG.md
  source/main/locales/en-US.json
  source/main/locales/ja-JP.json
  source/main/menus/osx.js
  source/main/menus/win-linux.js
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: bug, release-0.14.0

#1461 [DDW-745] Staking screen improvements
  CHANGELOG.md
  source/renderer/app/api/staking/types.js
  source/renderer/app/components/staking/delegation-center/DelegationCenter.js
  source/renderer/app/components/staking/delegation-center/WalletRow.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationSetupWizardDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.js
  source/renderer/app/components/staking/epochs/StakingEpochs.js
  source/renderer/app/components/staking/epochs/StakingEpochs.scss
  source/renderer/app/components/staking/epochs/StakingEpochsCurrentEpochData.js
  source/renderer/app/components/staking/epochs/StakingEpochsDataTable.js
  source/renderer/app/components/staking/epochs/StakingEpochsPreviousEpochData.js
  source/renderer/app/components/staking/epochs/helpers.js
  source/renderer/app/components/staking/layouts/StakingWithNavigation.js
  source/renderer/app/components/staking/navigation/StakingNavigation.js
  source/renderer/app/components/staking/rewards/StakingRewards.js
  source/renderer/app/components/staking/rewards/StakingRewards.scss
  source/renderer/app/components/staking/stake-pools/StakePools.js
  source/renderer/app/components/staking/stake-pools/StakePoolsSearch.scss
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/components/wallet/ada-redemption/AdaRedemptionDisclaimer.scss
  source/renderer/app/components/wallet/ada-redemption/AdaRedemptionSuccessOverlay.scss
  source/renderer/app/components/widgets/Dialog.scss
  source/renderer/app/config/sidebarConfig.js
  source/renderer/app/config/stakingCurrentEpoch.dummy.json
  source/renderer/app/config/stakingPreviousEpoch.dummy.json
  source/renderer/app/config/stakingRewards.dummy.json
  source/renderer/app/containers/staking/DelegationCenterPage.js
  source/renderer/app/containers/staking/StakePoolsListPage.js
  source/renderer/app/containers/staking/Staking.js
  source/renderer/app/containers/staking/StakingEpochsPage.js
  source/renderer/app/containers/staking/StakingRewardsPage.js
  source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/overrides/ButtonOverrides.scss
  source/renderer/app/themes/overrides/ModalOverrides.scss
  source/renderer/app/themes/overrides/SelectOverrides.scss
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/Sidebar.stories.js
  storybook/stories/Staking-Epochs.stories.js
  storybook/stories/Staking-Rewards.stories.js
  storybook/stories/Staking-StakePools.stories.js
  storybook/stories/Staking.stories.js
Labels: bug, release-0.14.0

#1463 [DDW-747] Handle no-wallets case on the Delegation Center screen
  CHANGELOG.md
  source/renderer/app/components/staking/delegation-center/DelegationCenterNoWallets.js
  source/renderer/app/components/staking/delegation-center/DelegationCenterNoWallets.scss
  source/renderer/app/containers/staking/DelegationCenterPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/Staking.stories.js
Labels: feature, release-0.14.0

#1467 [DDW-752] Fix dependency vulnerabilities
  .eslintrc
  CHANGELOG.md
  package.json
  yarn.lock
Labels: bug, release-0.14.0

#1448 [DDW-701]: Improve Daedalus log rotation
  CHANGELOG.md
  package.json
  source/main/ipc/get-logs.js
  source/main/utils/setupLogging.js
  yarn.lock
Labels: feature, release-0.14.0

#1462 [DDW-684] Improve NTP handling
  CHANGELOG.md
  features/local-time-difference.feature
  features/tests/e2e/steps/local-time-difference-steps.js
  source/renderer/app/components/loading/system-time-error/SystemTimeError.js
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/config/numbersConfig.js
  source/renderer/app/config/timingConfig.js
  source/renderer/app/stores/NetworkStatusStore.js
Labels: bug, release-0.14.0

#1469 [DDW-753] Licensing update
  LICENSE
  LICENSE NOTICE
  source/renderer/app/components/static/About.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: chore, release-0.14.0

#1456 [DDW-656] Log Daedalus state snapshot
  CHANGELOG.md
  source/common/ipc/api.js
  source/common/types/logging.types.js
  source/main/config.js
  source/main/index.js
  source/main/ipc/set-log-state-snapshot.js
  source/main/utils/setupLogging.js
  source/renderer/app/containers/status/DaedalusDiagnosticsDialog.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/ipc/setStateSnapshotLogChannel.js
  source/renderer/app/stores/ProfileStore.js
  source/renderer/app/utils/formatters.js
Labels: feature, release-0.14.0

#1466 [DDW-750] Prepare CHANGELOG for the 1.6.0 release
  CHANGELOG.md
Labels: chore, release-0.14.0

#1471 [DDW-758] Fix app name typos
  CHANGELOG.md
  source/renderer/app/i18n/locales/en-US.json
Labels: bug, release-0.14.0

#1464 [DDW-697] Automate Theme Management
  CHANGELOG.md
  gulpfile.js
  package.json
  source/renderer/app/ThemeManager.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/scripts/check.js
  source/renderer/app/themes/scripts/update.js
  source/renderer/app/themes/types.js
  source/renderer/app/themes/utils/constants.js
  source/renderer/app/themes/utils/createTheme.js
  source/renderer/app/themes/utils/findUpdates.js
  source/renderer/app/themes/utils/index.js
  source/renderer/app/themes/utils/updateThemes.js
  source/renderer/app/themes/utils/updateThemesCLI.js
  source/renderer/app/themes/utils/writeThemeUpdate.js
Labels: DO NOT MERGE, chore, release-0.14.0

#1476 [DDW-761] Fix 'To addresses' in the same line
  CHANGELOG.md
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/components/wallet/transactions/Transaction.scss
  storybook/stories/support/utils.js
Labels: bug, release-0.14.0

#1479 [DDW-762] Fix broken 'Read the Article' button
  CHANGELOG.md
  source/renderer/app/components/loading/syncing-connecting/ReportIssue.js
Labels: bug, release-0.14.0

#1482 [DDW-764] Fix timestamp date format handling
  CHANGELOG.md
  source/renderer/app/containers/wallet/dialogs/paper-wallet-certificate/InstructionsDialogContainer.js
Labels: bug, release-0.14.0

#1484 [DDW-776] Fix wrong styling of the Stake Pool in the Dark Blue theme
  CHANGELOG.md
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.scss
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
Labels: bug, release-0.14.0

#1487 [DDW-777] Implement link to feature requests
  CHANGELOG.md
  source/main/locales/en-US.json
  source/main/locales/ja-JP.json
  source/main/menus/osx.js
  source/main/menus/win-linux.js
Labels: feature, release-0.14.0

#1489 [DDW-785] Reverse the order of buttons on Having trouble connecting/syncing notification
  CHANGELOG.md
  source/renderer/app/components/loading/syncing-connecting/ReportIssue.js
Labels: bug, release-0.14.0

#1490 [DDW-780] Truncated third Loading Dot
  source/renderer/app/components/loading/syncing-connecting/SyncingConnectingTitle.scss
  source/renderer/app/themes/mixins/animations.scss
  storybook/stories/WalletScreens.stories.js
Labels: bug, release-0.14.0

#1488 [DDW-781] Blank Screen Fix - Default Selection.
  CHANGELOG.md
  source/main/locales/en-US.json
  source/main/locales/ja-JP.json
  source/main/menus/MenuActions.types.js
  source/main/menus/osx.js
  source/main/menus/win-linux.js
  source/main/utils/buildAppMenus.js
Labels: bug, release-0.14.0

#1493 [DDW-789] Fix focused button of the 'Blank Screen fix' prompt on Windows
  CHANGELOG.md
  source/main/utils/buildAppMenus.js
Labels: bug, release-0.14.0

#1477 [DDW-775] Cardano SL 3.0.3 integration
  appveyor.yml
  cardano-sl-src.json
  default.nix
  installers/daedalus-installer.nix
  lib.nix
  release-build.nix
  release.nix
  scripts/build-cross-windows.sh
  shell.nix
  yarn2nix.nix
Labels: DO NOT MERGE

#1478 [DDW-727] Implement process management for decoupled cardano-wallet and node
  .gitignore
  README.md
  installers/dhall/demo.dhall
  installers/dhall/linux64.dhall
  installers/dhall/macos64.dhall
  installers/dhall/mainnet.dhall
  installers/dhall/staging.dhall
  installers/dhall/testnet.dhall
  installers/dhall/win64.dhall
  lib.nix
  package.json
  shell.nix
  source/main/cardano/CardanoNode.js
  source/main/cardano/CardanoWalletLauncher.js
  source/main/cardano/setupCardanoNodeMode.js
  source/renderer/app/api/addresses/requests/createAddress.js
  source/renderer/app/api/addresses/requests/getAddresses.js
  source/renderer/app/api/addresses/types.js
  source/renderer/app/api/api.js
  source/renderer/app/api/transactions/requests/getTransactionHistory.js
  source/renderer/app/api/utils/request.js
  source/renderer/app/api/wallets/requests/getWallets.js
  source/renderer/app/api/wallets/types.js
  source/renderer/app/components/wallet/receive/Address.js
  source/renderer/app/components/wallet/receive/WalletReceive.js
  source/renderer/app/containers/wallet/WalletReceivePage.js
  source/renderer/app/domains/WalletAddress.js
  source/renderer/app/stores/NetworkStatusStore.js
  storybook/stories/support/utils.js
  utils/configurations/cardano-wallet-genesis.yaml
  utils/v2-api-importer/faucet-txt.b64
  utils/v2-api-importer/index.js
  utils/v2-api-importer/mnemonics.txt
  yarn.lock
Labels: DO NOT MERGE, feature, release-vNext

#1426 [DDW-711] Update Storybook to the latest version
  CHANGELOG.md
  package.json
  source/renderer/app/components/staking/stake-pools/StakePoolsList.js
  storybook/addons.js
  storybook/addons/DaedalusMenu/DaedalusMenu.css
  storybook/addons/DaedalusMenu/DaedalusMenu.js
  storybook/addons/DaedalusMenu/DaedalusMenuStyles.js
  storybook/addons/DaedalusMenu/index.js
  storybook/addons/DaedalusMenu/register.js
  storybook/stories/Sidebar.stories.js
  storybook/stories/Staking-StakePools.stories.js
  storybook/stories/Staking.stories.js
  storybook/stories/support/DaedalusMenu.js
  storybook/stories/support/DaedalusMenu.scss
  storybook/stories/support/StoryLayout.js
  storybook/stories/support/StoryWrapper.js
  storybook/webpack.config.js
  yarn.lock
Labels: Approved, DO NOT MERGE, chore, release-vNext

#1468 [DDW-712] Stake Pools - Search and Filter
  CHANGELOG.md
  source/renderer/app/api/staking/types.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.js
  source/renderer/app/components/staking/layouts/StakingWithNavigation.scss
  source/renderer/app/components/staking/stake-pools/StakePoolThumbnail.js
  source/renderer/app/components/staking/stake-pools/StakePoolThumbnail.scss
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.scss
  source/renderer/app/components/staking/stake-pools/StakePools.js
  source/renderer/app/components/staking/stake-pools/StakePoolsSearch.js
  source/renderer/app/components/staking/stake-pools/StakePoolsSearch.scss
  source/renderer/app/components/staking/stake-pools/helpers.js
  source/renderer/app/components/widgets/BackToTopButton.js
  source/renderer/app/components/widgets/BackToTopButton.scss
  source/renderer/app/components/widgets/Dialog.scss
  source/renderer/app/config/stakingStakePools.dummy old.json
  source/renderer/app/config/stakingStakePools.dummy.json
  source/renderer/app/config/timingConfig.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  source/renderer/app/utils/domManipulation.js
  storybook/stories/Staking-StakePools.stories.js
Labels: Approved, feature, release-vNext

#1472 [DDW-689] Unify support request data handling
  CHANGELOG.md
  source/common/types/support-requests.types.js
  source/common/utils/reporting.js
  source/main/menus/osx.js
  source/main/menus/win-linux.js
  source/main/utils/buildAppMenus.js
  source/renderer/app/containers/loading/SyncingConnectingPage.js
  source/renderer/app/containers/settings/categories/SupportSettingsPage.js
  source/renderer/app/utils/network.js
Labels: Approved, chore, release-vNext
