Repository input-output-hk/daedalus, pull requests merged in 2019-06, with the labels that each got.

#1410 [DDW-677] Implement alternative update path for manual updates
  CHANGELOG.md
  appveyor.yml
  features/app-version-difference.feature
  features/step_definitions/app-version-difference.js
  package.json
  source/renderer/app/actions/node-update-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/api/nodes/requests/getLatestAppVersionInfo.js
  source/renderer/app/api/nodes/types.js
  source/renderer/app/api/utils/externalRequest.js
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/components/loading/Loading.js
  source/renderer/app/components/loading/ManualUpdateOverlay.js
  source/renderer/app/components/loading/ManualUpdateOverlay.scss
  source/renderer/app/config/urlsConfig.js
  source/renderer/app/containers/LoadingPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/AppStore.js
  source/renderer/app/stores/NodeUpdateStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/utils/network.js
  storybook/stories/ManualUpdateOverlay.stories.js
  storybook/stories/index.js
Labels: feature, release-0.13.2

#1371 [DDW-604] Unify and Optimize Themeing Colors
  CHANGELOG.md
  package.json
  source/renderer/app/components/profile/terms-of-use/TermsOfUseText.scss
  source/renderer/app/components/staking/delegation-countdown/StakingDelegationCountdown.scss
  source/renderer/app/components/staking/info/StakingInfo.scss
  source/renderer/app/components/staking/legacy/BlockGenerationInfo.scss
  source/renderer/app/components/staking/legacy/StakingSwitch.scss
  source/renderer/app/components/staking/stake-pools/StakePool.scss
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.js
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.scss
  source/renderer/app/components/staking/stake-pools/StakingStakePools.js
  source/renderer/app/components/staking/stake-pools/StakingStakePools.scss
  source/renderer/app/components/status/NetworkStatus.scss
  source/renderer/app/components/wallet/WalletCreateDialog.scss
  source/renderer/app/components/wallet/WalletRestoreDialog.scss
  source/renderer/app/components/wallet/backup-recovery/WalletRecoveryInstructions.scss
  source/renderer/app/components/wallet/backup-recovery/WalletRecoveryPhraseMnemonic.scss
  source/renderer/app/components/wallet/file-import/WalletFileImportDialog.scss
  source/renderer/app/components/wallet/paper-wallet-certificate/CompletionDialog.scss
  source/renderer/app/components/wallet/paper-wallet-certificate/ConfirmationDialog.scss
  source/renderer/app/components/wallet/paper-wallet-certificate/InstructionsDialog.scss
  source/renderer/app/components/wallet/paper-wallet-certificate/PrintDialog.scss
  source/renderer/app/components/wallet/paper-wallet-certificate/SecuringPasswordDialog.scss
  source/renderer/app/components/wallet/paper-wallet-certificate/VerificationDialog.scss
  source/renderer/app/components/wallet/receive/VirtualAddressesList.scss
  source/renderer/app/components/wallet/settings/ChangeSpendingPasswordDialog.scss
  source/renderer/app/components/wallet/transactions/Transaction.scss
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/mixins/buttons.scss
  source/renderer/app/themes/types.js
  source/renderer/app/themes/utils/createShades.js
  source/renderer/app/themes/utils/createTheme.js
  yarn.lock
Labels: chore, release-0.14.0

#1396 [DDW-642] Update to latest react-polymorph
  CHANGELOG.md
  package.json
  yarn.lock
Labels: chore, release-0.14.0

#1414 [DDW-686] Fix vulnerability warning
  CHANGELOG.md
  package.json
  yarn.lock
Labels: bug, release-0.14.0

#1413 [DDW-654] Network status screen renaming
  CHANGELOG.md
  features/tests/e2e/documents/paper_wallet_certificates/paper-wallet-certificate.pdf
  features/tests/e2e/steps/block-consolidation-page-steps.js
  source/common/ipc/constants.js
  source/main/locales/en-US.json
  source/main/locales/ja-JP.json
  source/main/menus/MenuActions.types.js
  source/main/menus/osx.js
  source/main/menus/win-linux.js
  source/main/utils/buildAppMenus.js
  source/renderer/app/App.js
  source/renderer/app/actions/app-actions.js
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/assets/images/cardano-logo-white.inline.svg
  source/renderer/app/assets/images/cardano-logo.inline.svg
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/components/status/DaedalusDiagnostics.scss
  source/renderer/app/containers/static/AboutDialog.scss
  source/renderer/app/containers/status/BlockConsolidationStatusDialog.scss
  source/renderer/app/containers/status/DaedalusDiagnosticsDialog.js
  source/renderer/app/containers/status/DaedalusDiagnosticsDialog.scss
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/AppStore.js
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/index.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
Labels: chore, release-0.14.0

#1416 [DDW-671] Block consolidation status screen is not fully shown
  CHANGELOG.md
  source/renderer/app/components/status/BlockConsolidationStatus.scss
Labels: bug, release-0.14.0

#1409 [DDW-648] Move funds from legacy wallet CTA
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/components/layout/SidebarLayout.scss
  source/renderer/app/components/layout/TopBar.js
  source/renderer/app/components/layout/TopBar.scss
  source/renderer/app/components/layout/TopBarLayout.scss
  source/renderer/app/components/notifications/LegacyBadge.js
  source/renderer/app/components/notifications/LegacyBadge.scss
  source/renderer/app/components/notifications/LegacyNotification.js
  source/renderer/app/components/notifications/LegacyNotification.scss
  source/renderer/app/components/sidebar/wallets/SidebarWalletMenuItem.js
  source/renderer/app/components/sidebar/wallets/SidebarWalletMenuItem.scss
  source/renderer/app/components/sidebar/wallets/SidebarWalletsMenu.js
  source/renderer/app/containers/TopBarContainer.js
  source/renderer/app/domains/Wallet.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/SidebarStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/types/sidebarTypes.js
  storybook/stories/Sidebar.stories.js
  storybook/stories/SidebarWalletsMenu.stories.js
  storybook/stories/support/StoryLayout.js
  storybook/stories/support/StoryProvider.js
  storybook/stories/support/utils.js
Labels: feature, release-0.14.0

#1382 [DDW-615] Move the GPU Safe Mode under "Help and Support" submenu and add a confirmation dialog
  CHANGELOG.md
  source/common/ipc/constants.js
  source/common/types/support-requests.types.js
  source/main/locales/en-US.json
  source/main/locales/ja-JP.json
  source/main/menus/osx.js
  source/main/menus/win-linux.js
  source/main/utils/buildAppMenus.js
  source/renderer/app/App.js
  source/renderer/app/actions/app-actions.js
  source/renderer/app/components/layout/TopBarLayout.scss
  source/renderer/app/components/wallet/utxo/WalletUtxo.scss
  source/renderer/app/containers/LoadingPage.js
  source/renderer/app/containers/notifications/GenericNotificationContainer.js
  source/renderer/app/containers/settings/Settings.js
  source/renderer/app/containers/settings/categories/SupportSettingsPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/AppStore.js
  source/renderer/app/stores/ProfileStore.js
Labels: chore, release-0.14.0

#1423 [DDW-677] Implement alternative update path for manual updates - Improvements
  CHANGELOG.md
  features/app-version-difference.feature
  features/step_definitions/app-version-difference.js
  features/support/electron.js
  source/renderer/app/api/api.js
  source/renderer/app/api/nodes/requests/getLatestAppVersion.js
  source/renderer/app/api/nodes/requests/getLatestAppVersionInfo.js
  source/renderer/app/api/nodes/types.js
  source/renderer/app/api/utils/externalRequest.js
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/components/loading/Loading.js
  source/renderer/app/config/timingConfig.js
  source/renderer/app/config/urlsConfig.js
  source/renderer/app/containers/LoadingPage.js
  source/renderer/app/stores/NodeUpdateStore.js
  source/renderer/app/utils/network.js
Labels: chore, release-0.13.2

#1421 Merge release/0.13.2 into develop branch
  CHANGELOG.md
  features/app-version-difference.feature
  features/support/paper_wallet_certificates/paper-wallet-certificate.pdf
  features/tests/e2e/documents/paper_wallet_certificates/paper-wallet-certificate.pdf
  features/tests/e2e/setup/electron.js
  features/tests/e2e/steps/app-version-difference.js
  features/tests/e2e/steps/trouble-connecting-notification-steps.js
  package.json
  source/renderer/app/actions/node-update-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/api/nodes/requests/getCurrentEpoch.js
  source/renderer/app/api/nodes/requests/getLatestAppVersion.js
  source/renderer/app/api/nodes/types.js
  source/renderer/app/api/utils/externalRequest.js
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/components/loading/Loading.js
  source/renderer/app/components/loading/ManualUpdateOverlay.js
  source/renderer/app/components/loading/ManualUpdateOverlay.scss
  source/renderer/app/config/urlsConfig.js
  source/renderer/app/containers/LoadingPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/NodeUpdateStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/utils/network.js
  storybook/stories/ManualUpdateOverlay.stories.js
  storybook/stories/index.js
Labels: chore, release-0.13.2

#1425 [DDW 713] Remove legacy references to report server
  CHANGELOG.md
  installers/Spec.hs
  installers/dhall/cluster.type
  installers/dhall/demo.dhall
  installers/dhall/launcher.dhall
  installers/dhall/mainnet.dhall
  installers/dhall/staging.dhall
  installers/dhall/testnet.dhall
  launcher-config.yaml
  source/main/cardano/config.js
  source/main/config.js
Labels: chore, release-0.14.0

#1419 [DDW-634] Improve switching application menu screens
  CHANGELOG.md
  features/block-consolidation-page.feature
  features/tests/e2e/steps/block-consolidation-page-steps.js
  source/common/ipc/constants.js
  source/main/menus/MenuActions.types.js
  source/main/menus/osx.js
  source/main/menus/win-linux.js
  source/main/utils/buildAppMenus.js
  source/renderer/app/App.js
  source/renderer/app/Routes.js
  source/renderer/app/actions/app-actions.js
  source/renderer/app/containers/Root.js
  source/renderer/app/containers/status/BlockConsolidationStatusDialog.js
  source/renderer/app/containers/status/DaedalusDiagnosticsDialog.js
  source/renderer/app/routes-config.js
  source/renderer/app/stores/AppStore.js
  source/renderer/app/types/applicationDialogTypes.js
Labels: chore, release-0.14.0

#1418 [DDW-652]: UI - Current and previous epoch
  CHANGELOG.md
  package.json
  source/renderer/app/components/staking/epochs/StakingEpochs.js
  source/renderer/app/components/staking/epochs/StakingEpochs.scss
  source/renderer/app/components/staking/epochs/StakingEpochsCurrentEpochData.js
  source/renderer/app/components/staking/epochs/StakingEpochsDataTable.js
  source/renderer/app/components/staking/epochs/StakingEpochsNoData.js
  source/renderer/app/components/staking/epochs/StakingEpochsPreviousEpochData.js
  source/renderer/app/components/staking/epochs/helpers.js
  source/renderer/app/components/staking/info/StakingInfo.scss
  source/renderer/app/containers/staking/StakingEpochsPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/overrides/SelectOverrides.scss
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/Staking-Epochs.stories.js
  storybook/stories/Staking.stories.js
  yarn.lock
Labels: feature, release-0.14.0

#1431 [DDW-716] Move Stake Pool Tooltip logic into StakePoolsList
  CHANGELOG.md
  source/renderer/app/components/staking/stake-pools/StakePoolThumbnail.js
  source/renderer/app/components/staking/stake-pools/StakePools.js
  source/renderer/app/components/staking/stake-pools/StakePoolsList.js
  source/renderer/app/i18n/locales/defaultMessages.json
Labels: bug, release-0.14.0

#1427 [DDW-708] Fix Loading Screen icons
  source/renderer/app/components/loading/Loading.scss
  source/renderer/app/components/loading/StatusIcons.js
  source/renderer/app/components/loading/StatusIcons.scss
  storybook/stories/Loading.stories.js
  storybook/stories/index.js
Labels: bug, release-0.14.0

#1436 [DDW-708] fix loading screen icons
  storybook/stories/index.js
Labels: bug, release-0.14.0

#1417 [DDW-658] UI - Delegation setup wizard steps 0 & 1
  CHANGELOG.md
  source/renderer/app/assets/images/attention-dark.inline.svg
  source/renderer/app/assets/images/back-arrow-ic.inline.svg
  source/renderer/app/assets/images/back-arrow-ic_old.inline.svg
  source/renderer/app/assets/images/back-arrow-ic_old.svg
  source/renderer/app/assets/images/link-ic.inline.svg
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationSetupWizardDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsIntroDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsIntroDialog.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsNotAvailableDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsNotAvailableDialog.scss
  source/renderer/app/components/widgets/DialogBackButton.scss
  source/renderer/app/config/stakingConfig.js
  source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/themes/daedalus.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/overrides/SelectOverrides.scss
  source/renderer/app/themes/overrides/StepperOverrides.scss
  source/renderer/app/themes/overrides/index.js
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/Staking.stories.js
  yarn.lock
Labels: feature, release-0.14.0

#1441 [DDW-720] Remove 0.13.2 version from CHANGELOG
  CHANGELOG.md
  package.json
Labels: chore, release-0.14.0

#1443 [DDW-721] Bump Cardano-SL revision
  cardano-sl-src.json
Labels: chore, release-0.14.0

#1429 [DDW-693] Improve Stake Pool tooltip positioning
  CHANGELOG.md
  source/renderer/app/api/staking/types.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsIntroDialog.js
  source/renderer/app/components/staking/stake-pools/StakePoolThumbnail.js
  source/renderer/app/components/staking/stake-pools/StakePoolThumbnail.scss
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.js
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsList.js
  source/renderer/app/components/staking/stake-pools/StakePoolsList.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsSearch.js
  source/renderer/app/config/stakingConfig.js
  source/renderer/app/config/stakingStakePools.dummy old.json
  source/renderer/app/config/stakingStakePools.dummy.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/Staking-StakePoolsStory.js
  storybook/stories/Staking.stories.js
Labels: bug, release-0.14.0

#1442 [DDW-658] UI - Delegation setup wizard steps 0 & 1 - Fixes
  CHANGELOG.md
  source/renderer/app/components/staking/delegation-center/DelegationCenter.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsIntroDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsNotAvailableDialog.js
  source/renderer/app/components/staking/epochs/StakingEpochsCurrentEpochData.js
  source/renderer/app/components/staking/epochs/StakingEpochsPreviousEpochData.js
  source/renderer/app/components/staking/stake-pools/StakePoolsSearch.js
  source/renderer/app/containers/staking/DelegationCenterPage.js
  source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/utils/createTheme.js
Labels: bug, release-0.14.0
