Repository input-output-hk/daedalus, pull requests merged in 2019-12, with the labels that each got.

#1725 [DDW-1026] Add Delegation Status of Wallets in Delegation Setup Wizard
  source/renderer/app/api/api.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationSetupWizardDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.js
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/components/wallet/transfer-funds/TransferFundsStep1Dialog.js
  source/renderer/app/components/widgets/forms/WalletsDropdown.js
  source/renderer/app/components/widgets/forms/WalletsDropdownOption.js
  source/renderer/app/components/widgets/forms/WalletsDropdownOption.scss
  source/renderer/app/containers/wallet/dialogs/transfer-funds/TransferFundsStep1Container.js
  source/renderer/app/domains/Wallet.js
  source/renderer/app/i18n/global-messages.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  storybook/stories/_support/StoryProvider.js
  storybook/stories/_support/utils.js
  storybook/stories/staking/DelegationSteps.stories.js
  storybook/stories/wallets/transferFunds/TransferFunds.stories.js
Labels: chore, release-2.0.0-ITN1

#1593 [DDW-755] Refactor wallet nav to use new Dropdown
  CHANGELOG.md
  package.json
  source/renderer/app/App.js
  source/renderer/app/components/navigation/NavDropdown.js
  source/renderer/app/components/navigation/NavDropdown.scss
  source/renderer/app/components/navigation/NavOptionsStyles.scss
  source/renderer/app/components/navigation/NavSelectSkin.js
  source/renderer/app/components/navigation/NavSelectStyles.scss
  source/renderer/app/components/wallet/layouts/WalletWithNavigation.scss
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/themes/daedalus.js
  source/renderer/app/themes/overrides/OptionsOverrides.scss
  source/renderer/app/themes/overrides/SelectOverrides.scss
  storybook/stories/_support/StoryDecorator.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext, chore

#1734 Merge latest develop into v2 integration
  CHANGELOG.md
  README.md
  package.json
  source/renderer/app/App.js
  source/renderer/app/components/navigation/NavDropdown.js
  source/renderer/app/components/navigation/NavDropdown.scss
  source/renderer/app/components/navigation/NavOptionsStyles.scss
  source/renderer/app/components/navigation/NavSelectSkin.js
  source/renderer/app/components/navigation/NavSelectStyles.scss
  source/renderer/app/components/wallet/layouts/WalletWithNavigation.scss
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/themes/daedalus.js
  source/renderer/app/themes/overrides/OptionsOverrides.scss
  source/renderer/app/themes/overrides/SelectOverrides.scss
  storybook/stories/_support/StoryDecorator.js
  yarn.lock
Labels: chore, release-2.0.0-ITN1

#1735 [DDW-1018] Configure numeric input number formats
  CHANGELOG.md
  package.json
  source/renderer/app/components/wallet/WalletSendForm.js
  source/renderer/app/containers/wallet/WalletSendPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/utils/formatters.js
  storybook/stories/wallets/send/WalletSend.stories.js
  yarn.lock
Labels: feature, release-2.0.0-ITN1

#1733 [DDW-1094] Integrate stake pools list V2 API endpoint
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/api/staking/requests/getStakePools.js
  source/renderer/app/api/staking/types.js
  source/renderer/app/components/staking/delegation-center/WalletRow.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationSetupWizardDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.scss
  source/renderer/app/components/staking/epochs/StakingEpochsCurrentEpochData.js
  source/renderer/app/components/staking/epochs/StakingEpochsPreviousEpochData.js
  source/renderer/app/components/staking/rewards/StakingRewards.js
  source/renderer/app/components/staking/stake-pools/StakePoolThumbnail.js
  source/renderer/app/components/staking/stake-pools/StakePoolThumbnail.scss
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.js
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.scss
  source/renderer/app/components/staking/stake-pools/StakePools.js
  source/renderer/app/components/staking/stake-pools/StakePoolsList.js
  source/renderer/app/components/staking/stake-pools/helpers.js
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/components/wallet/transactions/WalletTransactionsList.js
  source/renderer/app/components/widgets/forms/WalletsDropdown.js
  source/renderer/app/components/widgets/forms/WalletsDropdownOption.js
  source/renderer/app/components/widgets/forms/WalletsDropdownOption.scss
  source/renderer/app/config/generateStakePoolFakeData.js
  source/renderer/app/config/stakingStakePools.dummy.json
  source/renderer/app/config/stakingStakePoolsMissingApiData.dummy.json
  source/renderer/app/containers/staking/StakePoolsListPage.js
  source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
  source/renderer/app/containers/wallet/WalletSummaryPage.js
  source/renderer/app/containers/wallet/WalletTransactionsPage.js
  source/renderer/app/domains/StakePool.js
  source/renderer/app/domains/Wallet.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  source/renderer/app/utils/network.js
  storybook/stories/staking/DelegationSteps.stories.js
  storybook/stories/staking/StakePools.stories.js
  storybook/stories/wallets/transactions/TransactionsList.stories.js
Labels: feature, release-2.0.0-ITN1

#1738 DDW-1109 Remove StakePool from Wallet domain
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/components/staking/delegation-center/DelegationCenter.js
  source/renderer/app/components/staking/delegation-center/DelegationCenterBody.js
  source/renderer/app/components/staking/delegation-center/WalletRow.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationSetupWizardDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.js
  source/renderer/app/components/staking/epochs/StakingEpochsCurrentEpochData.js
  source/renderer/app/components/staking/epochs/StakingEpochsPreviousEpochData.js
  source/renderer/app/components/staking/rewards/StakingRewards.js
  source/renderer/app/components/wallet/transfer-funds/TransferFundsStep1Dialog.js
  source/renderer/app/components/widgets/forms/WalletsDropdown.js
  source/renderer/app/components/widgets/forms/WalletsDropdownOption.js
  source/renderer/app/config/stakingCurrentEpoch.dummy.json
  source/renderer/app/config/stakingPreviousEpoch.dummy.json
  source/renderer/app/config/stakingRewards.dummy.json
  source/renderer/app/containers/staking/DelegationCenterPage.js
  source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/transfer-funds/TransferFundsStep1Container.js
  source/renderer/app/domains/Wallet.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/stores/WalletsStore.js
  storybook/stories/_support/StoryProvider.js
  storybook/stories/staking/DelegationCenter.stories.js
  storybook/stories/staking/DelegationSteps.stories.js
  storybook/stories/wallets/transferFunds/TransferFunds.stories.js
Labels: bug, release-2.0.0-ITN1

#1729 [DDW-1098] Inspect wallet rewards display and remove actively delegated stake info
  CHANGELOG.md
  source/common/types/cardano-node.types.js
  source/renderer/app/api/api.js
  source/renderer/app/api/network/types.js
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/assets/images/delimeter-slash.inline.svg
  source/renderer/app/components/sidebar/wallets/SidebarWalletsMenu.js
  source/renderer/app/components/sidebar/wallets/SidebarWalletsMenu.scss
  source/renderer/app/components/staking/countdown/StakingCountdown.js
  source/renderer/app/components/staking/delegation-center/DelegationCenter.js
  source/renderer/app/components/staking/delegation-center/DelegationCenterHeader.js
  source/renderer/app/components/staking/delegation-center/DelegationCenterHeader.scss
  source/renderer/app/components/staking/delegation-center/WalletRow.js
  source/renderer/app/components/staking/delegation-center/helpers.js
  source/renderer/app/components/widgets/CountdownWidget.js
  source/renderer/app/components/widgets/CountdownWidget.scss
  source/renderer/app/config/epochsConfig.js
  source/renderer/app/containers/staking/DelegationCenterPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/StakingStore.js
  storybook/stories/staking/DelegationCenter.stories.js
  storybook/stories/staking/Staking.stories.js
Labels: chore, release-2.0.0-ITN1

#1739 [DDW-1110] Updates cardano-wallet and fixes wallet and stake pool types
  CHANGELOG.md
  nix/sources.json
  source/main/cardano/nodes/jormungandr.js
  source/renderer/app/api/api.js
  source/renderer/app/api/staking/types.js
  source/renderer/app/api/wallets/types.js
  source/renderer/app/config/stakingStakePoolsMissingApiData.dummy.json
  source/renderer/app/domains/StakePool.js
  source/renderer/app/domains/Wallet.js
  utils/jormungandr/selfnode/genesis.yaml
Labels: chore, release-2.0.0-ITN1

#1742 [DDW-1031] Add theme var for Checkbox icon color
  CHANGELOG.md
  package.json
  source/renderer/app/themes/overrides/CheckboxOverrides.scss
  source/renderer/app/themes/overrides/index.js
  yarn.lock
Labels: chore, release-2.0.0-ITN1

#1743 [DDW-982] Distinguish unit and e2e test setup
  CHANGELOG.md
  package.json
  tests/setup-common.js
  tests/setup-e2e.js
Labels: chore, release-2.0.0-ITN1

#1744 [DDW-1095] Integrate stake pool join V2 API endpoint and update "Delegation" wizard
  CHANGELOG.md
  source/renderer/app/actions/staking-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/api/staking/requests/joinStakePool.js
  source/renderer/app/api/staking/types.js
  source/renderer/app/assets/images/questionmark.inline.svg
  source/renderer/app/assets/images/tada-ic.inline.svg
  source/renderer/app/components/staking/delegation-center/DelegationCenterBody.js
  source/renderer/app/components/staking/delegation-center/WalletRow.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationSetupWizardDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationSteps.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsActivationDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsActivationDialog.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsConfirmationDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsConfirmationDialog.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsIntroDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsIntroDialog.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsNotAvailableDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsNotAvailableDialog.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsSuccessDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsSuccessDialog.scss
  source/renderer/app/components/staking/stake-pools/StakePoolThumbnail.js
  source/renderer/app/components/staking/stake-pools/StakePoolThumbnail.scss
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.js
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.scss
  source/renderer/app/components/staking/stake-pools/StakePools.js
  source/renderer/app/components/staking/stake-pools/StakePoolsList.js
  source/renderer/app/components/wallet/transfer-funds/TransferFundsStep1Dialog.js
  source/renderer/app/components/widgets/forms/WalletsDropdown.js
  source/renderer/app/components/widgets/forms/WalletsDropdownOption.scss
  source/renderer/app/config/stakingConfig.js
  source/renderer/app/containers/staking/DelegationCenterPage.js
  source/renderer/app/containers/staking/StakePoolsListPage.js
  source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
  source/renderer/app/domains/StakePool.js
  source/renderer/app/domains/Wallet.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/_support/utils.js
  storybook/stories/staking/DelegationCenter.stories.js
  storybook/stories/staking/DelegationSteps.stories.js
  storybook/stories/staking/Staking.stories.js
Labels: feature, release-2.0.0-ITN1

#1737 [DDW-1096]: Integrate stake pool quit V2 API add confirmation dialog
  CHANGELOG.md
  source/renderer/app/actions/wallets-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/api/staking/types.js
  source/renderer/app/api/wallets/requests/quitStakePool.js
  source/renderer/app/api/wallets/types.js
  source/renderer/app/assets/images/untada.inline.svg
  source/renderer/app/components/staking/delegation-center/DelegationCenter.js
  source/renderer/app/components/staking/delegation-center/DelegationCenterBody.js
  source/renderer/app/components/staking/delegation-center/UndelegateConfirmationDialog.js
  source/renderer/app/components/staking/delegation-center/UndelegateConfirmationDialog.scss
  source/renderer/app/components/staking/delegation-center/UndelegateConfirmationResultDialog.js
  source/renderer/app/components/staking/delegation-center/UndelegateConfirmationResultDialog.scss
  source/renderer/app/components/staking/delegation-center/WalletRow.js
  source/renderer/app/components/staking/rewards/StakingRewards.js
  source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.js
  source/renderer/app/config/numbersConfig.js
  source/renderer/app/containers/staking/DelegationCenterPage.js
  source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
  source/renderer/app/containers/staking/dialogs/UndelegateDialogContainer.js
  source/renderer/app/i18n/global-messages.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/overrides/SelectOverrides.scss
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/staking/DelegationCenter.stories.js
  storybook/stories/staking/Staking.stories.js
  storybook/stories/staking/Undelegate.stories.js
Labels: feature, release-2.0.0-ITN1

#1749 [DDW-1117] Update cardano-wallet to latest master
  CHANGELOG.md
  nix/sources.json
  utils/jormungandr/selfnode/genesis.yaml
Labels: chore, release-2.0.0-ITN1

#1750 [DDW-1123] Enable Delegation UI in Daedalus builds
  CHANGELOG.md
  source/renderer/app/stores/SidebarStore.js
Labels: chore, release-2.0.0-ITN1

#1752 [DDW-1116] Integrate stake pool join/quit fee estimation API endpoint
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/api/staking/requests/getDelegationFee.js
  source/renderer/app/api/staking/types.js
  source/renderer/app/containers/staking/DelegationCenterPage.js
  source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
  source/renderer/app/stores/StakingStore.js
Labels: feature, release-2.0.0-ITN1

#1753 [DDW-1111] Update minimum amount of ada for delegation to be available
  CHANGELOG.md
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.js
  source/renderer/app/config/stakingConfig.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  storybook/stories/staking/DelegationSteps.stories.js
Labels: chore, release-2.0.0-ITN1

#1746 [DDW-1108] Fix middle ellipsis for addresses - Character width calculation version
  CHANGELOG.md
  source/renderer/app/components/wallet/receive/Address.js
  source/renderer/app/components/wallet/receive/Address.scss
  source/renderer/app/components/wallet/receive/WalletReceive.js
  source/renderer/app/containers/wallet/WalletReceivePage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  storybook/stories/wallets/receive/WalletReceive.stories.js
Labels: bug, release-2.0.0-ITN1

#1757 [DDW-1115]: Update stake pool ranking logic
  CHANGELOG.md
  source/renderer/app/api/api.js
Labels: feature, release-2.0.0-ITN1

#1756 [DDW-1120]: Update serialize-javascript dependency
  CHANGELOG.md
  package.json
  yarn.lock
Labels: chore, release-2.0.0-ITN1

#1759 [DDW-1122] Implement Support portal articles placeholder links
  CHANGELOG.md
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
Labels: chore, release-2.0.0-ITN1

#1758 [DDW-1114] Message for current stake pool being selected again
  CHANGELOG.md
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.scss
  source/renderer/app/containers/staking/DelegationCenterPage.js
  source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  storybook/stories/staking/DelegationSteps.stories.js
Labels: chore, release-2.0.0-ITN1

#1754 [DDW-1124] Delegated drop down displayed Truncated in Minimized mode
  source/renderer/app/components/staking/delegation-center/DropdownMenu.js
  source/renderer/app/components/staking/delegation-center/DropdownMenu.scss
  source/renderer/app/components/staking/delegation-center/WalletRow.js
  source/renderer/app/components/wallet/receive/WalletReceive.js
  source/renderer/app/components/widgets/BackToTopButton.js
  source/renderer/app/stores/SidebarStore.js
Labels: bug, release-2.0.0-ITN1

#1761 [DDW-1126] Fix legacy wallet migration notification
  CHANGELOG.md
  source/renderer/app/components/layout/TopBar.js
  source/renderer/app/components/notifications/LegacyNotification.js
  source/renderer/app/containers/TopBarContainer.js
  source/renderer/app/stores/WalletsStore.js
  storybook/stories/_support/StoryLayout.js
Labels: bug, release-2.0.0-ITN1

#1760 [DDW-1119]: Update rewards note and learn more button style
  CHANGELOG.md
  source/renderer/app/components/staking/rewards/StakingRewards.js
  source/renderer/app/components/staking/rewards/StakingRewards.scss
  source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.js
  source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.scss
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
Labels: chore, release-2.0.0-ITN1

#1764 [DDW-1127] Updates cardano-wallet to latest master
  CHANGELOG.md
  nix/sources.json
  utils/jormungandr/selfnode/genesis.yaml
Labels: chore, release-2.0.0-ITN1

#1751 [DDW-1118] Use next epoch info from the Api
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/api/network/types.js
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/components/staking/delegation-center/DelegationCenterHeader.js
  source/renderer/app/components/staking/delegation-center/helpers.js
  source/renderer/app/components/widgets/CountdownWidget.js
  source/renderer/app/components/widgets/CountdownWidget.scss
  source/renderer/app/config/epochsConfig.js
Labels: chore, release-2.0.0-ITN1

#1741 [DDW-1112] Implement new "Terms of use" for the "Rewards" network
  CHANGELOG.md
  source/renderer/app/components/profile/terms-of-use/TermsOfUseForm.js
  source/renderer/app/components/profile/terms-of-use/TermsOfUseText.js
  source/renderer/app/components/profile/terms-of-use/TermsOfUseText.scss
  source/renderer/app/components/settings/categories/TermsOfUseSettings.js
  source/renderer/app/components/settings/menu/SettingsMenu.js
  source/renderer/app/containers/profile/TermsOfUsePage.js
  source/renderer/app/containers/settings/categories/TermsOfUseSettingsPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/terms-of-use/itn-rewards-v1/en-US.md
  source/renderer/app/i18n/locales/terms-of-use/itn-rewards-v1/ja-JP.md
  source/renderer/app/i18n/locales/terms-of-use/mainnet/en-US.md
  source/renderer/app/i18n/locales/terms-of-use/mainnet/ja-JP.md
  source/renderer/app/i18n/locales/terms-of-use/other/en-US.md
  source/renderer/app/i18n/locales/terms-of-use/other/ja-JP.md
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/routes-config.js
  storybook/stories/settings/general/General.stories.js
  storybook/stories/settings/utils/SettingsWrapper.js
  tests/navigation/e2e/features/navigate-general-settings-menu.feature
  tests/settings/e2e/features/accept-terms-of-use.feature
  tests/settings/e2e/steps/terms-of-use.js
Labels: feature, release-2.0.0-ITN1

#1762 [DDW-1121] Update delegation copy
  source/common/types/environment.types.js
  source/common/types/locales.types.js
  source/common/utils/environmentCheckers.js
  source/main/environment.js
  source/renderer/app/api/api.js
  source/renderer/app/api/network/types.js
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/components/loading/system-time-error/SystemTimeError.js
  source/renderer/app/components/settings/categories/SupportSettings.js
  source/renderer/app/components/staking/countdown/StakingCountdown.js
  source/renderer/app/components/staking/delegation-center/DelegationCenter.js
  source/renderer/app/components/staking/delegation-center/DelegationCenterHeader.js
  source/renderer/app/components/staking/delegation-center/UndelegateConfirmationResultDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationSetupWizardDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsSuccessDialog.js
  source/renderer/app/components/widgets/CountdownWidget.js
  source/renderer/app/components/widgets/CountdownWidget.scss
  source/renderer/app/config/epochsConfig.js
  source/renderer/app/containers/staking/DelegationCenterPage.js
  source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
  source/renderer/app/containers/staking/dialogs/UndelegateDialogContainer.js
  source/renderer/app/i18n/global-messages.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/utils/humanizeDurationByLocale.js
  storybook/stories/nodes/errors/SystemTimeError.stories.js
  storybook/stories/nodes/status/Diagnostics.stories.js
  storybook/stories/settings/language/Language.stories.js
  storybook/stories/staking/DelegationCenter.stories.js
  storybook/stories/staking/DelegationSteps.stories.js
  storybook/stories/staking/Undelegate.stories.js
  storybook/stories/wallets/receive/WalletReceive.stories.js
  storybook/stories/wallets/settings/WalletSettingsScreen.stories.js
  storybook/stories/wallets/transactions/TransactionsList.stories.js
  utils/jormungandr/selfnode/genesis.yaml
Labels: feature, release-2.0.0-ITN1

#1765 [DDW-1125] Handle list stake pools API endpoint errors
  CHANGELOG.md
  source/renderer/app/components/staking/delegation-center/DelegationCenter.js
  source/renderer/app/components/staking/delegation-center/DelegationCenterBody.js
  source/renderer/app/components/staking/delegation-center/DelegationCenterBody.scss
  source/renderer/app/components/staking/delegation-center/UndelegateConfirmationDialog.js
  source/renderer/app/components/staking/delegation-center/WalletRow.js
  source/renderer/app/components/staking/delegation-center/WalletRow.scss
  source/renderer/app/components/staking/layouts/StakingWithNavigation.scss
  source/renderer/app/components/staking/stake-pools/StakePools.js
  source/renderer/app/components/staking/stake-pools/StakePools.scss
  source/renderer/app/components/widgets/forms/WalletsDropdown.js
  source/renderer/app/config/stakingConfig.js
  source/renderer/app/containers/staking/DelegationCenterPage.js
  source/renderer/app/containers/staking/StakePoolsListPage.js
  source/renderer/app/containers/staking/dialogs/UndelegateDialogContainer.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/StakingStore.js
  storybook/stories/staking/DelegationCenter.stories.js
  storybook/stories/staking/StakePools.stories.js
  storybook/stories/staking/Staking.stories.js
  storybook/stories/staking/Undelegate.stories.js
Labels: feature, release-2.0.0-ITN1

#1767 [DDW-1132] Improve spending password error handling
  CHANGELOG.md
  source/renderer/app/api/api.js
Labels: bug, release-2.0.0-ITN1

#1769 [DDW-1133]: Update package dependencies
  CHANGELOG.md
  package.json
  yarn.lock
Labels: chore, release-2.0.0-ITN1

#1768 [DDW-1129] Stake pool data presentation
  source/renderer/app/api/api.js
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.js
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.scss
  source/renderer/app/components/staking/stake-pools/StakePools.js
  source/renderer/app/config/generateStakePoolFakeData.js
  source/renderer/app/config/stakingStakePools.dummy.json
  source/renderer/app/containers/staking/StakePoolsListPage.js
  source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
  source/renderer/app/domains/StakePool.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  source/renderer/app/utils/formatters.js
Labels: feature, release-2.0.0-ITN1

#1766 [DDW-1130] Improve wallet delegation / undelegation
  CHANGELOG.md
  source/renderer/app/actions/staking-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/api/staking/requests/quitStakePool.js
  source/renderer/app/api/staking/types.js
  source/renderer/app/api/wallets/types.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsConfirmationDialog.js
  source/renderer/app/config/stakingConfig.js
  source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
  source/renderer/app/containers/staking/dialogs/UndelegateDialogContainer.js
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/stores/WalletsStore.js
Labels: chore, release-2.0.0-ITN1

#1770 [DDW-1134] Improve font rendering on Network splash screen
  CHANGELOG.md
  source/renderer/app/components/splash/Network.scss
Labels: bug, release-2.0.0-ITN1

#1772 [DDW-1128] React-polymorph Error is showed after app resizing
  CHANGELOG.md
  package.json
  source/renderer/app/components/loading/syncing-connecting/SyncingConnectingTitle.scss
  yarn.lock
Labels: bug, release-2.0.0-ITN1

#1771 [DDW-1131] Enable providing stake pool registry cardano-wallet argument
  CHANGELOG.md
  source/main/cardano/CardanoWalletLauncher.js
  source/main/config.js
  source/renderer/app/api/api.js
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.js
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.scss
Labels: chore, release-2.0.0-ITN1

#1773 [DDW-1136] - Add cost and profit margin to stake pool details
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/api/staking/types.js
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.js
  source/renderer/app/config/stakingStakePools.dummy.json
  source/renderer/app/domains/StakePool.js
  source/renderer/app/i18n/locales/defaultMessages.json
Labels: chore, release-2.0.0-ITN1

#1774 [DDW-1137] Fix undelegation issue
  CHANGELOG.md
  source/renderer/app/containers/staking/dialogs/UndelegateDialogContainer.js
Labels: bug, release-2.0.0-ITN1

#1779 [DDW-1142, DDW-1144, DDW-1140] Small updates for ITN launch
  CHANGELOG.md
  nix/sources.json
  source/renderer/app/actions/wallet-backup-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/components/staking/delegation-center/DelegationCenterHeader.js
  source/renderer/app/components/staking/delegation-center/UndelegateConfirmationResultDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsSuccessDialog.js
  source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.js
  source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.scss
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.js
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.scss
  source/renderer/app/components/wallet/WalletAdd.js
  source/renderer/app/components/wallet/WalletBackupDialog.js
  source/renderer/app/components/wallet/WalletCreateDialog.js
  source/renderer/app/components/wallet/backup-recovery/MnemonicWord.scss
  source/renderer/app/components/wallet/backup-recovery/WalletBackupPrivacyWarningDialog.js
  source/renderer/app/components/wallet/backup-recovery/WalletRecoveryInstructions.scss
  source/renderer/app/components/wallet/backup-recovery/WalletRecoveryPhraseDisplayDialog.js
  source/renderer/app/components/wallet/backup-recovery/WalletRecoveryPhraseEntryDialog.js
  source/renderer/app/components/wallet/backup-recovery/WalletRecoveryPhraseEntryDialog.scss
  source/renderer/app/components/widgets/BigButtonForDialogs.scss
  source/renderer/app/components/widgets/forms/WalletsDropdownOption.scss
  source/renderer/app/config/stakingConfig.js
  source/renderer/app/containers/wallet/dialogs/WalletBackupDialogContainer.js
  source/renderer/app/domains/StakePool.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/WalletBackupStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/overrides/CheckboxOverrides.scss
  source/renderer/app/themes/overrides/index.js
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/staking/RewardsForIncentivizedTestnet.stories.js
  storybook/stories/staking/Staking.stories.js
Labels: chore, release-2.0.0-ITN1

#1781 Cardano wallet version bump
  CHANGELOG.md
  nix/sources.json
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsIntroDialog.js
  source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.js
Labels: chore, release-2.0.0-ITN1

#1748 [DDW-1092] Make all notification UI/UX the same
  CHANGELOG.md
  source/renderer/app/App.js
  source/renderer/app/actions/app-actions.js
  source/renderer/app/actions/network-status-actions.js
  source/renderer/app/actions/notifications-actions.js
  source/renderer/app/actions/wallets-actions.js
  source/renderer/app/components/notifications/GenericNotification.js
  source/renderer/app/components/notifications/GenericNotification.scss
  source/renderer/app/components/notifications/InlineNotification.js
  source/renderer/app/components/notifications/InlineNotification.scss
  source/renderer/app/components/notifications/Notification.js
  source/renderer/app/components/notifications/Notification.scss
  source/renderer/app/components/notifications/NotificationTransitions.scss
  source/renderer/app/components/settings/categories/SupportSettings.scss
  source/renderer/app/components/wallet/paper-wallet-certificate/CompletionDialog.js
  source/renderer/app/components/widgets/NotificationMessage.js
  source/renderer/app/config/formattingConfig.js
  source/renderer/app/config/timingConfig.js
  source/renderer/app/containers/loading/SyncingConnectingPage.js
  source/renderer/app/containers/notifications/GenericNotificationContainer.js
  source/renderer/app/containers/notifications/NotificationsContainer.js
  source/renderer/app/containers/settings/categories/SupportSettingsPage.js
  source/renderer/app/containers/status/DaedalusDiagnosticsDialog.js
  source/renderer/app/containers/wallet/WalletReceivePage.js
  source/renderer/app/i18n/global-messages.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/AppStore.js
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/ProfileStore.js
  source/renderer/app/stores/UiNotificationsStore.js
  source/renderer/app/stores/index.js
  source/renderer/app/types/notificationType.js
  source/renderer/app/types/notificationTypes.js
  storybook/stories/common/Widgets.stories.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext-ITN1, feature

#1780 [DDW-996] Add more hotkeys to the Daedalus
  CHANGELOG.md
  source/common/ipc/constants.js
  source/main/locales/en-US.json
  source/main/locales/ja-JP.json
  source/main/menus/MenuActions.types.js
  source/main/menus/osx.js
  source/main/menus/win-linux.js
  source/main/utils/buildAppMenus.js
  source/renderer/app/stores/AppStore.js
Labels: :hourglass_flowing_sand:release-vNext-ITN1, feature

#1797 [DDW-1155] - Network info screen should be responsive
  CHANGELOG.md
  source/renderer/app/components/splash/Network.scss
Labels: :hourglass_flowing_sand:release-vNext-ITN1, chore

#1740 [DDW-1100] Implement Yoroi wallets restoration
  CHANGELOG.md
  nix/sources.json
  source/renderer/app/components/wallet/WalletRestoreDialog.js
  source/renderer/app/components/wallet/WalletRestoreDialog.scss
  source/renderer/app/config/cryptoConfig.js
  source/renderer/app/config/walletsConfig.js
  source/renderer/app/i18n/global-messages.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  utils/jormungandr/selfnode/genesis.yaml
Labels: :hourglass_flowing_sand:release-vNext-ITN1, DO NOT MERGE, feature

#1805 [DDW-1160] Add wallet type to route path
  CHANGELOG.md
  nix/sources.json
  source/renderer/app/api/api.js
  source/renderer/app/api/transactions/requests/deleteLegacyTransaction.js
  source/renderer/app/api/transactions/requests/getLegacyWalletTransactionHistory.js
  source/renderer/app/api/utils/index.js
  source/renderer/app/api/wallets/requests/deleteLegacyWallet.js
  source/renderer/app/api/wallets/requests/transferFunds.js
  source/renderer/app/api/wallets/requests/transferFundsCalculateFee.js
Labels: :hourglass_flowing_sand:release-vNext-ITN1, bug

#1782 Add installation instructions (esp osx Catalina)
  README.md
Labels: :hourglass_flowing_sand:release-vNext-ITN1, docs
