Repository input-output-hk/daedalus, pull requests merged in 2019-09, with the labels that each got.

#1547 [DDW-836] Fix design implementation issues
  CHANGELOG.md
  source/renderer/app/components/loading/system-time-error/SystemTimeError.scss
  source/renderer/app/components/profile/data-layer-migration/DataLayerMigrationForm.scss
  source/renderer/app/components/staking/countdown/StakingCountdown.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsConfirmationDialog.scss
  source/renderer/app/components/staking/epochs/StakingEpochs.scss
  source/renderer/app/components/staking/info/StakingInfo.scss
  source/renderer/app/components/staking/rewards/StakingRewards.scss
  source/renderer/app/components/wallet/WalletCreateDialog.js
  source/renderer/app/components/wallet/WalletCreateDialog.scss
  source/renderer/app/components/wallet/WalletRestoreDialog.js
  source/renderer/app/components/wallet/WalletRestoreDialog.scss
  source/renderer/app/components/wallet/file-import/WalletFileImportDialog.scss
  source/renderer/app/components/wallet/receive/VirtualAddressesList.scss
  source/renderer/app/components/wallet/settings/ChangeSpendingPasswordDialog.js
  source/renderer/app/components/wallet/settings/ChangeSpendingPasswordDialog.scss
  source/renderer/app/components/wallet/transactions/Transaction.scss
  source/renderer/app/components/wallet/utxo/WalletUtxo.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/index.global.scss
  source/renderer/app/themes/utils/createShades.js
  source/renderer/app/themes/utils/createTheme.js
Labels: bug, release-vNext

#1554 [DDW-870]: Overlay screens displayed on default theme rather than current one for a second
  CHANGELOG.md
  source/renderer/app/App.js
  source/renderer/app/stores/NetworkStatusStore.js
Labels: bug, release-vNext

#1548 [DDW-860] Review and improvements of already implemented V2 API endpoints
  CHANGELOG.md
  source/renderer/app/api/addresses/requests/getAddresses.js
  source/renderer/app/api/addresses/types.js
  source/renderer/app/api/api.js
  source/renderer/app/api/transactions/types.js
  source/renderer/app/api/wallets/requests/createWallet.js
  source/renderer/app/api/wallets/requests/updateWallet.js
  source/renderer/app/api/wallets/types.js
  source/renderer/app/components/notifications/RestoreNotification.js
  source/renderer/app/components/wallet/settings/WalletSettings.js
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/components/wallet/transactions/Transaction.scss
  source/renderer/app/components/wallet/transactions/WalletTransactionsList.js
  source/renderer/app/containers/wallet/Wallet.js
  source/renderer/app/containers/wallet/WalletSendPage.js
  source/renderer/app/containers/wallet/WalletSettingsPage.js
  source/renderer/app/containers/wallet/WalletSummaryPage.js
  source/renderer/app/containers/wallet/WalletTransactionsPage.js
  source/renderer/app/domains/Wallet.js
  source/renderer/app/domains/WalletAddress.js
  source/renderer/app/domains/WalletTransaction.js
  source/renderer/app/i18n/global-messages.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/SidebarStore.js
  source/renderer/app/stores/TransactionsStore.js
  source/renderer/app/stores/WalletSettingsStore.js
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/Staking-DelegationCenter.stories.js
  storybook/stories/WalletScreens-Settings.stories.js
  storybook/stories/WalletScreens.stories.js
  storybook/stories/WalletTransactionsList.stories.js
  storybook/stories/support/StoryProvider.js
  storybook/stories/support/utils.js
Labels: V2-API, chore, release-vNext

#1550 [DDW-828] Remove dropdown arrow
  CHANGELOG.md
  source/renderer/app/components/profile/data-layer-migration/DataLayerMigrationForm.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.scss
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/overrides/OptionsOverrides.scss
  source/renderer/app/themes/overrides/SelectOverrides.scss
  source/renderer/app/themes/overrides/index.js
  source/renderer/app/themes/utils/createTheme.js
Labels: feature, release-vNext

#1564 V2 integration with latest develop
  CHANGELOG.md
  source/renderer/app/components/loading/system-time-error/SystemTimeError.scss
  source/renderer/app/components/profile/data-layer-migration/DataLayerMigrationForm.scss
  source/renderer/app/components/staking/countdown/StakingCountdown.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsConfirmationDialog.scss
  source/renderer/app/components/staking/epochs/StakingEpochs.scss
  source/renderer/app/components/staking/info/StakingInfo.scss
  source/renderer/app/components/staking/rewards/StakingRewards.scss
  source/renderer/app/components/wallet/WalletCreateDialog.js
  source/renderer/app/components/wallet/WalletCreateDialog.scss
  source/renderer/app/components/wallet/WalletRestoreDialog.js
  source/renderer/app/components/wallet/WalletRestoreDialog.scss
  source/renderer/app/components/wallet/file-import/WalletFileImportDialog.scss
  source/renderer/app/components/wallet/receive/VirtualAddressesList.scss
  source/renderer/app/components/wallet/settings/ChangeSpendingPasswordDialog.js
  source/renderer/app/components/wallet/settings/ChangeSpendingPasswordDialog.scss
  source/renderer/app/components/wallet/transactions/Transaction.scss
  source/renderer/app/components/wallet/utxo/WalletUtxo.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/index.global.scss
  source/renderer/app/themes/overrides/OptionsOverrides.scss
  source/renderer/app/themes/overrides/SelectOverrides.scss
  source/renderer/app/themes/overrides/index.js
  source/renderer/app/themes/utils/createShades.js
  source/renderer/app/themes/utils/createTheme.js
Labels: V2-API, chore, release-vNext

#1551 [DDW-861] V2 API error handlers
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/api/utils/request.js
  source/renderer/app/components/notifications/AutomaticUpdateNotification.scss
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/containers/wallet/Wallet.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
Labels: V2-API, chore, release-vNext

#1566 V2 integration with latest develop
  CHANGELOG.md
  features/send-money-to-receiver.feature
  features/tests/e2e/steps/select-language-steps.js
  features/tests/e2e/steps/settings-steps.js
  package.json
  source/renderer/app/components/wallet/WalletSendForm.js
  source/renderer/app/i18n/locales/defaultMessages.json
  yarn.lock
Labels: V2-API, chore, release-vNext

#1552 [DDW-871] Delete Wallet V2 API integration
  CHANGELOG.md
  source/renderer/app/api/wallets/requests/deleteWallet.js
Labels: V2-API, chore, release-vNext

#1558 [DDW-875] Update wallet passphrase V2 API integration
  CHANGELOG.md
  features/add-wallet-via-sidebar.feature
  features/import-wallet-via-sidebar.feature
  features/mnemonics-generation-and-validation.feature
  features/restore-wallet-via-sidebar.feature
  features/send-money-to-receiver.feature
  features/spending-password-validation.feature
  features/tests/e2e/helpers/wallets-helpers.js
  features/tests/e2e/steps/settings-steps.js
  features/tests/e2e/steps/wallets-steps.js
  features/wallet-address-generate.feature
  features/wallet-settings.feature
  source/renderer/app/api/api.js
  source/renderer/app/api/utils/request.js
  source/renderer/app/api/wallets/requests/changeSpendingPassword.js
  source/renderer/app/i18n/global-messages.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/utils/validations.js
Labels: V2-API, chore, release-vNext

#1559 [DDW-876] Get wallet UTXO statistics v2 api integration
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/api/wallets/requests/getWalletUtxos.js
  source/renderer/app/api/wallets/types.js
  source/renderer/app/containers/wallet/WalletUtxoPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  storybook/stories/WalletScreens-Utxo.stories.js
Labels: V2-API, chore, release-vNext

#1569 [DDW-900] News feed - feature specification
  CHANGELOG.md
  features/news-feed.feature
  package.json
Labels: release-0.15.0, specification

#1568 [DEVOPS] Only build mac installers with queue=daedalus agents
  .buildkite/pipeline.yml
  CHANGELOG.md
  installers/common/MacInstaller.hs
Labels: chore, release-0.15.0

#1567 [DDW-897] Rust node integration
  .gitignore
  CHANGELOG.md
  README.md
  default.nix
  installers/dhall/cluster.type
  installers/dhall/launcher.dhall
  installers/dhall/linux64.dhall
  installers/dhall/macos64.dhall
  installers/dhall/os.type
  installers/dhall/win64.dhall
  lib.nix
  package.json
  shell.nix
  source/common/ipc/api.js
  source/common/types/cardano-node.types.js
  source/main/cardano/CardanoNode.js
  source/main/cardano/CardanoWalletLauncher.js
  source/main/cardano/nodes/http-bridge.js
  source/main/cardano/nodes/index.js
  source/main/cardano/nodes/jormungandr.js
  source/main/cardano/setupCardanoNodeMode.js
  source/main/config.js
  source/main/ipc/cardano.ipc.js
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/ipc/cardano.ipc.js
  source/renderer/app/stores/NetworkStatusStore.js
  utils/jormungandr/testnet/genesis.yaml
  utils/v2-api-importer/faucet-txt.b64
  utils/v2-api-importer/index.js
  utils/v2-api-importer/mnemonics.txt
  yarn.lock
Labels: Infrastructure, V2-API, release-vNext

#1560 [DDW-879] Calculate transaction fee v2 api integration
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/api/transactions/requests/createTransaction.js
  source/renderer/app/api/transactions/requests/getTransactionFee.js
  source/renderer/app/api/transactions/types.js
  source/renderer/app/components/wallet/WalletSendForm.js
  source/renderer/app/containers/wallet/WalletSendPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/stores/TransactionsStore.js
  storybook/stories/WalletScreens.stories.js
Labels: V2-API, chore, release-vNext

#1573 [DDW-912] Bump Daedalus version
  CHANGELOG.md
  features/tests/e2e/documents/dummy-news.json
  package.json
Labels: chore, release-0.15.0
