Repository input-output-hk/daedalus, pull requests merged in 2019-03, with the labels that each got.

#1324 [DEVOPS-1238] Update the Windows signing certificate and secret
  appveyor.yml
Labels: bug, release-0.13.0

#1326 [DEVOPS-1237] Fix uninstaller unicode
  installers/common/WindowsInstaller.hs
Labels: bug, release-0.13.0

#1327 Merge release/0.13.0 into develop branch
  CHANGELOG.md
  appveyor.yml
  cardano-sl-src.json
  installers/common/WindowsInstaller.hs
  source/renderer/app/api/api.js
  source/renderer/app/api/nodes/types.js
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/config/timingConfig.js
  source/renderer/app/stores/NetworkStatusStore.js
Labels: chore, release-0.13.0

#1328 Revert "[DEVOPS-1238] update the windows signing certificate and secret"
  appveyor.yml
Labels: bug, release-0.13.0

#1331 [DDW-587] Improve support page text
  CHANGELOG.md
  source/renderer/app/api/transactions/errors.js
  source/renderer/app/components/settings/categories/SupportSettings.js
  source/renderer/app/containers/settings/categories/SupportSettingsPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
Labels: chore, release-0.13.0

#1332 [DDW-313] Cleanup IPC API
  CHANGELOG.md
  source/common/ipc-api.js
  source/common/ipc/api.js
  source/common/ipc/constants.js
  source/common/ipc/lib/IpcChannel.js
  source/common/types/ada-redemption.types.js
  source/common/types/bug-report-request.types.js
  source/main/cardano/CardanoNode.js
  source/main/cardano/setupCardanoNodeMode.js
  source/main/cardano/setupFrontendOnlyMode.js
  source/main/ipc/bugReportRequestChannel.js
  source/main/ipc/cardano.ipc.js
  source/main/ipc/compress-logs.js
  source/main/ipc/control-ui-parts.js
  source/main/ipc/download-logs.js
  source/main/ipc/generatePaperWalletChannel.js
  source/main/ipc/get-disk-space-status.js
  source/main/ipc/get-gpu-status.js
  source/main/ipc/get-logs.js
  source/main/ipc/getNumberOfEpochsConsolidated.ipc.js
  source/main/ipc/getSystemStartTime.ipc.js
  source/main/ipc/index.js
  source/main/ipc/lib/MainIpcChannel.js
  source/main/ipc/load-asset.js
  source/main/ipc/open-external-url.js
  source/main/ipc/parse-redemption-code-from-pdf.js
  source/main/ipc/parse-redemption-code.js
  source/main/ipc/rebuild-application-menu.js
  source/main/utils/buildAppMenus.js
  source/main/utils/getNumberOfEpochsConsolidated.js
  source/renderer/app/ipc/bugReportRequestChannel.js
  source/renderer/app/ipc/cardano.ipc.js
  source/renderer/app/ipc/control-ui-parts.js
  source/renderer/app/ipc/generatePaperWalletChannel.js
  source/renderer/app/ipc/get-gpu-status.ipc.js
  source/renderer/app/ipc/getDiskSpaceChannel.js
  source/renderer/app/ipc/getNumberOfEpochsConsolidatedChannel.js
  source/renderer/app/ipc/getSystemStartTime.ipc.js
  source/renderer/app/ipc/lib/RendererIpcChannel.js
  source/renderer/app/ipc/loadAsset.js
  source/renderer/app/ipc/logs.ipc.js
  source/renderer/app/ipc/open-external-url.js
  source/renderer/app/ipc/parse-redemption-code.js
  source/renderer/app/ipc/rebuild-application-menu.js
  source/renderer/app/ipc/reportRequestChannel.js
  source/renderer/app/stores/AdaRedemptionStore.js
  source/renderer/app/stores/AppStore.js
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/ProfileStore.js
  source/renderer/app/types/LogTypes.js
Labels: chore, release-0.14.0

#1316 [DDW-544] Fix 'Daedalus' state directory on 'Staging' and 'Testnet'
  CHANGELOG.md
  default.nix
  installers/common/WindowsInstaller.hs
  installers/dhall/win64.dhall
  scripts/build-installer-nix.sh
Labels: bug, release-0.14.0

#1338 [DDW-591] Removal of the REPORT_URL env variable
  CHANGELOG.md
  source/common/types/environment.types.js
  source/main/environment.js
  source/main/webpack.config.js
  source/renderer/webpack.config.js
Labels: bug, release-0.14.0

#1340 [DDW-592] Make sure wallets data is reloaded after Daedalus reconnects
  CHANGELOG.md
  source/renderer/app/containers/Root.js
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/WalletsStore.js
Labels: bug, release-0.13.0

#1343 Merge release/0.13.0 into develop branch
  CHANGELOG.md
  cardano-sl-src.json
  source/renderer/app/containers/Root.js
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/WalletsStore.js
Labels: chore, release-0.13.0

#1337 [DEVOPS] Be more verbose about which build artifact its fetching
  installers/common/AppVeyor.hs
Labels: chore, release-0.14.0

#1346 [RCD-56] Fix Windows unicode problem
  installers/dhall/win64.dhall
Labels: bug, release-0.13.0

#1344 [DDW-92] Improve error messages on connecting screen
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/api/nodes/errors.js
  source/renderer/app/components/loading/Loading.js
  source/renderer/app/containers/LoadingPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/NetworkStatusStore.js
Labels: WIP, feature, release-0.14.0

#1318 [DDW-458] Improve Acceptance Tests Coverage
  CHANGELOG.md
  features/block-consolidation-page.feature
  features/step_definitions/ada-redemption-steps.js
  features/step_definitions/block-consolidation-page-steps.js
  features/step_definitions/paper-wallets-certificate-steps.js
  features/step_definitions/sidebar-steps.js
  features/step_definitions/trouble-connecting-notification-steps.js
  features/step_definitions/trouble-syncing-notification-steps.js
  features/step_definitions/wallets-steps.js
  features/trouble-connecting-notification.feature
  features/trouble-syncing-notification.feature
  source/renderer/app/api/api.js
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/config/timingConfig.js
  source/renderer/app/i18n/locales/defaultMessages.json
Labels: chore, release-0.14.0

#1350 Merge master into develop branch
  installers/dhall/win64.dhall
Labels: chore, release-0.13.0

#1348 [DDW-588] Detect User Locale on Daedalus Start
  CHANGELOG.md
  default.nix
  source/common/ipc/api.js
  source/common/types/environment.types.js
  source/common/types/locales.types.js
  source/main/index.js
  source/main/ipc/detect-system-locale.js
  source/main/utils/detectSystemLocale.js
  source/main/utils/getLocale.js
  source/renderer/app/components/profile/language-selection/LanguageSelectionForm.js
  source/renderer/app/containers/profile/LanguageSelectionPage.js
  source/renderer/app/ipc/detect-system-locale.js
  source/renderer/app/stores/ProfileStore.js
  storybook/stories/LanguageSelectionForm.stories.js
Labels: feature, release-0.14.0

#1358 [DDW-607] Fix Daedalus log file rotation
  CHANGELOG.md
  source/main/config.js
  source/main/utils/setupLogging.js
Labels: bug, release-0.13.1

#1361 [DDW-606] Improve text on the Support screen
  CHANGELOG.md
  source/renderer/app/components/settings/categories/SupportSettings.js
  source/renderer/app/components/settings/categories/SupportSettings.scss
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
Labels: bug, release-0.13.1

#1359 Release/0.13.1
  CHANGELOG.md
  cardano-sl-src.json
  package.json
  source/main/config.js
  source/main/utils/setupLogging.js
  source/renderer/app/components/settings/categories/SupportSettings.js
  source/renderer/app/components/settings/categories/SupportSettings.scss
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
Labels: release-0.13.1

#1364 Merge master into develop branch
  CHANGELOG.md
  cardano-sl-src.json
  package.json
  source/main/config.js
  source/main/utils/setupLogging.js
  source/renderer/app/components/settings/categories/SupportSettings.js
  source/renderer/app/components/settings/categories/SupportSettings.scss
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
Labels: chore, release-0.13.1

#1367 [DDW-593] Refactor to mobx runInAction within async functions
  CHANGELOG.md
  source/renderer/app/components/wallet/paper-wallet-certificate/VerificationDialog.js
  source/renderer/app/stores/AdaRedemptionStore.js
  source/renderer/app/stores/AppStore.js
  source/renderer/app/stores/ProfileStore.js
  source/renderer/app/stores/WalletBackupStore.js
Labels: chore, release-0.14.0

#1341 [DDW-584] Implement "In progress" download logs notification
  CHANGELOG.md
  source/renderer/app/actions/profile-actions.js
  source/renderer/app/assets/images/success-small.inline.svg
  source/renderer/app/components/loading/Loading.js
  source/renderer/app/components/loading/Loading.scss
  source/renderer/app/components/notifications/GenericNotification.js
  source/renderer/app/components/notifications/GenericNotification.scss
  source/renderer/app/components/settings/categories/SupportSettings.js
  source/renderer/app/components/settings/categories/SupportSettings.scss
  source/renderer/app/components/widgets/NotificationMessage.js
  source/renderer/app/containers/LoadingPage.js
  source/renderer/app/containers/notifications/GenericNotificationContainer.js
  source/renderer/app/containers/settings/Settings.js
  source/renderer/app/containers/settings/categories/SupportSettingsPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/ProfileStore.js
Labels: feature, release-0.14.0

#1368 [DDW-594] Mention origin in IPC channel message types
  .flowconfig
  CHANGELOG.md
  source/common/ipc/api.js
  source/main/ipc/bugReportRequestChannel.js
  source/main/ipc/cardano.ipc.js
  source/main/ipc/compress-logs.js
  source/main/ipc/control-ui-parts.js
  source/main/ipc/detect-system-locale.js
  source/main/ipc/download-logs.js
  source/main/ipc/generatePaperWalletChannel.js
  source/main/ipc/get-gpu-status.js
  source/main/ipc/get-logs.js
  source/main/ipc/getNumberOfEpochsConsolidated.ipc.js
  source/main/ipc/getSystemStartTime.ipc.js
  source/main/ipc/open-external-url.js
  source/main/ipc/parse-redemption-code.js
  source/main/utils/getNumberOfEpochsConsolidated.js
  source/renderer/app/ipc/bugReportRequestChannel.js
  source/renderer/app/ipc/cardano.ipc.js
  source/renderer/app/ipc/control-ui-parts.js
  source/renderer/app/ipc/detect-system-locale.js
  source/renderer/app/ipc/generatePaperWalletChannel.js
  source/renderer/app/ipc/get-gpu-status.ipc.js
  source/renderer/app/ipc/getNumberOfEpochsConsolidatedChannel.js
  source/renderer/app/ipc/getSystemStartTime.ipc.js
  source/renderer/app/ipc/logs.ipc.js
  source/renderer/app/ipc/open-external-url.js
  source/renderer/app/ipc/parse-redemption-code.js
  source/renderer/app/ipc/rebuild-application-menu.js
  source/renderer/app/stores/NetworkStatusStore.js
Labels: chore, release-0.14.0

#1365 [DDW-460] Implement calculating state for the time difference icon
  CHANGELOG.md
  source/renderer/app/components/loading/Loading.js
  source/renderer/app/i18n/locales/ja-JP.json
Labels: feature, release-0.14.0
