Repository input-output-hk/daedalus, pull requests merged in 2019-01, with the labels that each got.

#1245 [DDW-538] Fix acceptance tests
  features/support/electron.js
  package.json
  scripts/package.js
  yarn.lock
Labels: chore, release-0.13.0

#1250 [DEVOPS-1200] Disable Appveyor checks for bors
  bors.toml
Labels: chore, release-0.13.0

#1251 [DDW-542] Fix ellipsis animation on Loading screen
  CHANGELOG.md
  source/renderer/app/themes/mixins/animations.scss
  source/renderer/app/themes/mixins/loading-spinner.scss
Labels: bug, release-0.13.0

#1252 [DEVOPS-1200] Disable Appveyor checks for bors - REVERT
  bors.toml
Labels: chore, release-0.13.0

#1246 [DDW-529] Blocks stalling logic improvement
  CHANGELOG.md
  package.json
  source/renderer/app/components/status/NetworkStatus.js
  source/renderer/app/containers/status/NetworkStatusPage.js
  source/renderer/app/stores/NetworkStatusStore.js
Labels: bug, release-0.12.1

#1254 Merge release/0.12.1 into develop branch
  CHANGELOG.md
  package.json
  source/renderer/app/components/status/NetworkStatus.js
  source/renderer/app/containers/status/NetworkStatusPage.js
  source/renderer/app/stores/NetworkStatusStore.js
Labels: chore, release-0.12.1

#1247 [DDW-541] Fix blank window rendering issue
  installers/nix/electron.nix
  installers/nix/linux.nix
  package.json
  source/renderer/app/api/utils/localStorage.js
  yarn.lock
Labels: bug, release-0.13.0

#1241 [DDW-535] Support frontend only mode
  CHANGELOG.md
  README.md
  default.nix
  installers/nix/linux.nix
  shell.nix
  source/common/types/cardano-node.types.js
  source/main/cardano/CardanoNode.js
  source/main/cardano/setup.js
  source/main/cardano/setupCardanoNodeMode.js
  source/main/cardano/setupFrontendOnlyMode.js
  source/main/config.js
  source/main/index.js
  source/renderer/app/api/accounts/requests/getAccounts.js
  source/renderer/app/api/addresses/requests/createAddress.js
  source/renderer/app/api/addresses/requests/getAddress.js
  source/renderer/app/api/common/types.js
  source/renderer/app/api/index.js
  source/renderer/app/api/nodes/requests/applyNodeUpdate.js
  source/renderer/app/api/nodes/requests/getNextNodeUpdate.js
  source/renderer/app/api/nodes/requests/getNodeInfo.js
  source/renderer/app/api/nodes/requests/postponeNodeUpdate.js
  source/renderer/app/api/transactions/requests/createTransaction.js
  source/renderer/app/api/transactions/requests/getTransactionFee.js
  source/renderer/app/api/transactions/requests/getTransactionHistory.js
  source/renderer/app/api/transactions/requests/redeemAda.js
  source/renderer/app/api/transactions/requests/redeemPaperVendedAda.js
  source/renderer/app/api/wallets/requests/changeSpendingPassword.js
  source/renderer/app/api/wallets/requests/createWallet.js
  source/renderer/app/api/wallets/requests/deleteWallet.js
  source/renderer/app/api/wallets/requests/exportWalletAsJSON.js
  source/renderer/app/api/wallets/requests/getWallets.js
  source/renderer/app/api/wallets/requests/importWalletAsJSON.js
  source/renderer/app/api/wallets/requests/importWalletAsKey.js
  source/renderer/app/api/wallets/requests/resetWalletState.js
  source/renderer/app/api/wallets/requests/restoreWallet.js
  source/renderer/app/api/wallets/requests/updateWallet.js
Labels: feature, release-0.13.0

#1256 [DEVOPS-1203] Update cardano-sl to latest release/2.0.1
  cardano-sl-src.json
Labels: release-0.12.1

#1260 [DDW-558] Fix handling of the 'frontendOnlyMode' variable
  CHANGELOG.md
  shell.nix
  source/main/cardano/setup.js
  source/main/config.js
Labels: bug, release-0.13.0

#1261 [DDW-562] Fix the transaction loading logic
  CHANGELOG.md
  source/renderer/app/api/api.js
Labels: bug, release-0.12.1

#1258 [DDW-514] Improve NTP check UX
  CHANGELOG.md
  source/renderer/app/components/status/NetworkStatus.js
  source/renderer/app/config/timingConfig.js
  source/renderer/app/stores/NetworkStatusStore.js
Labels: feature, release-0.13.0

#1266 [DDW-539] False 'Another Daedalus instance is already running' errors
  CHANGELOG.md
  default.nix
  fastlist.nix
  installers/common/WindowsInstaller.hs
  package.json
  source/main/cardano/CardanoNode.js
  source/main/config.js
  source/main/environment.js
  source/main/index.js
  source/main/utils/processes.js
  yarn.lock
Labels: bug, release-0.13.0

#1267 [DDW-563] Loading all transactions impacts performance
  CHANGELOG.md
  source/renderer/app/stores/TransactionsStore.js
Labels: bug, release-0.12.1

#1270 Merge release/0.12.1 into develop branch
  CHANGELOG.md
  source/renderer/app/stores/TransactionsStore.js
Labels: chore, release-0.12.1

#1271 Bump Cardano SL revision to the tip of release/2.0.1 branch
  cardano-sl-src.json
Labels: chore, release-0.12.1

#1272 Merge release/0.12.1 into develop branch
  cardano-sl-src.json
Labels: chore, release-0.12.1

#1273 [DEVOPS-1203] Bump cardano-sl to latest release/2.0.1
  cardano-sl-src.json
Labels: chore, release-0.12.1

#1274 [DEVOPS-1090] Bump cardano-sl to current develop
  cardano-sl-src.json
Labels: chore, release-0.13.0

#1228 [DDW-509] Show success message for saving logs
  CHANGELOG.md
  features/step_definitions/wallets-steps.js
  source/renderer/app/components/widgets/NotificationMessage.js
  source/renderer/app/components/widgets/NotificationMessage.scss
  source/renderer/app/config/timingConfig.js
  source/renderer/app/containers/LoadingPage.js
  source/renderer/app/containers/settings/categories/SupportSettingsPage.js
  source/renderer/app/containers/wallet/WalletReceivePage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/UiNotificationsStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
Labels: feature, release-0.13.0

#1277 [DDW-568] Fix broken Storybook
  storybook/stories/index.js
  storybook/stories/support/environment.js
Labels: chore, release-0.13.0

#1278 [DDW-546] Add more logging for API errors
  CHANGELOG.md
  source/renderer/app/api/api.js
Labels: chore, release-0.13.0

#1279 [DDW-566] Decouples LoadingPage and Initial Setup
  CHANGELOG.md
  source/renderer/app/components/loading/Loading.js
  source/renderer/app/containers/LoadingPage.js
  source/renderer/app/containers/Root.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/ProfileStore.js
Labels: bug, release-0.13.0

#1280 [DEVOPS-1219] cardano version bump for testnet config
  cardano-sl-src.json
Labels: chore, release-0.12.1

#1282 [DDW-407] Update the list of contributors on the "About" screen
  CHANGELOG.md
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: chore, release-0.13.0

#1253 Release/0.12.1
  CHANGELOG.md
  cardano-sl-src.json
  package.json
  source/renderer/app/api/api.js
  source/renderer/app/components/status/NetworkStatus.js
  source/renderer/app/containers/status/NetworkStatusPage.js
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/TransactionsStore.js
Labels: release-0.12.1

#1286 [DDW-482] Improve Network Status screen closing navigation
  CHANGELOG.md
  source/common/ipc/api.js
  source/main/menus/MenuActions.types.js
  source/main/menus/osx.js
  source/main/menus/win-linux.js
  source/main/utils/buildAppMenus.js
  source/renderer/app/App.js
  source/renderer/app/Routes.js
  source/renderer/app/actions/app-actions.js
  source/renderer/app/components/status/NetworkStatus.scss
  source/renderer/app/containers/Root.js
  source/renderer/app/containers/static/AboutDialog.js
  source/renderer/app/containers/status/NetworkStatusDialog.js
  source/renderer/app/containers/status/NetworkStatusDialog.scss
  source/renderer/app/routes-config.js
  source/renderer/app/stores/AppStore.js
Labels: chore, release-0.13.0

#1285 [DEVOPS-1208] installers: Get cross-compiled windows exes from Hydra
  cardano-sl-src.json
  installers/.gitignore
  installers/Spec.hs
  installers/common/AppVeyor.hs
  installers/daedalus-installer.cabal
  installers/shell.nix
Labels: chore, release-0.13.0

#1275 [DDW-557] Implement block-consolidation status screen
  CHANGELOG.md
  installers/dhall/win64.dhall
  source/common/ipc/api.js
  source/common/types/environment.types.js
  source/main/config.js
  source/main/environment.js
  source/main/index.js
  source/main/ipc/getNumberOfEpochsConsolidated.ipc.js
  source/main/ipc/getSystemStartTime.ipc.js
  source/main/menus/MenuActions.types.js
  source/main/menus/osx.js
  source/main/menus/win-linux.js
  source/main/utils/buildAppMenus.js
  source/main/utils/getNumberOfEpochsConsolidated.js
  source/renderer/app/Routes.js
  source/renderer/app/actions/app-actions.js
  source/renderer/app/actions/network-status-actions.js
  source/renderer/app/assets/images/back-arrow-thin-ic.inline.svg
  source/renderer/app/assets/images/block-consolidation/epochs.png
  source/renderer/app/components/layout/TopBar.js
  source/renderer/app/components/status/BlockConsolidationStatus.js
  source/renderer/app/components/status/BlockConsolidationStatus.scss
  source/renderer/app/config/epochsConfig.js
  source/renderer/app/config/timingConfig.js
  source/renderer/app/containers/Root.js
  source/renderer/app/containers/TopBarContainer.js
  source/renderer/app/containers/status/BlockConsolidationStatusPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/ipc/getNumberOfEpochsConsolidatedChannel.js
  source/renderer/app/ipc/getSystemStartTime.ipc.js
  source/renderer/app/routes-config.js
  source/renderer/app/stores/AppStore.js
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/utils/network.js
  storybook/stories/BlockConsolidationStatus.stories.js
  storybook/stories/index.js
Labels: feature, release-0.13.0

#1288 [DEVOPS-1219] Bump cardano-sl to latest release/2.0.1
  cardano-sl-src.json
Labels: bug, chore, release-0.12.1

#1289 [DDW-571] Several minor issues with text selection
  CHANGELOG.md
  source/main/preload.js
  source/renderer/app/components/layout/TopBar.scss
  source/renderer/app/components/profile/terms-of-use/TermsOfUseText.scss
  source/renderer/app/components/static/About.scss
  source/renderer/app/components/wallet/WalletReceive.scss
  source/renderer/app/components/wallet/WalletSendConfirmationDialog.scss
  source/renderer/app/components/wallet/paper-wallet-certificate/CompletionDialog.scss
  source/renderer/app/components/wallet/skins/AmountInputSkin.scss
  source/renderer/app/components/wallet/summary/WalletSummary.scss
  source/renderer/app/components/wallet/transactions/Transaction.scss
Labels: bug, release-0.13.0

#1291 Release/0.12.1 (Linux Testnet applicationVersion bump)
  cardano-sl-src.json
Labels: chore, release-0.12.1

#1290 Release/0.12.1 (Linux Testnet applicationVersion bump)
  cardano-sl-src.json
Labels: chore, release-0.12.1

#1294 [DDW-572] Fix broken Windows launcher config
  CHANGELOG.md
  installers/dhall/win64.dhall
Labels: bug, release-0.13.0

#1296 [DDW-570] Japanese text not being rendered on Linux
  CHANGELOG.md
  default.nix
  installers/nix/nix-installer.nix
  yarn2nix.nix
Labels: bug, release-0.13.0

#1292 [DDW-567] Log system specification info to a dedicated log file
  CHANGELOG.md
  source/main/config.js
  source/main/index.js
  source/main/utils/setupLogging.js
Labels: feature, release-0.13.0

#1297 [DDW-573] Update transactions API error handling
  CHANGELOG.md
  source/renderer/app/api/api.js
Labels: chore, release-0.13.0
