Repository input-output-hk/daedalus, pull requests merged in 2019-04, with the labels that each got.

#1372 [DDW-621] Fix the position in Japanese version of the Support page
  CHANGELOG.md
  source/renderer/app/i18n/locales/ja-JP.json
Labels: bug, release-0.14.0

#1374 Revert '[DEVOPS-1238] update the windows signing certificate and secret'
  appveyor.yml
Labels: bug, release-0.14.0

#1369 [DDW-608] Implement new About dialog design
  CHANGELOG.md
  source/renderer/app/components/static/About.js
  source/renderer/app/components/static/About.scss
  source/renderer/app/components/widgets/DialogCloseButton.js
  source/renderer/app/components/widgets/DialogCloseButton.scss
  source/renderer/app/containers/static/AboutDialog.js
  source/renderer/app/containers/static/AboutDialog.scss
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
Labels: chore, release-0.14.0, ui-update

#1373 [DDW-613] Settings screen shown during wallet-loading phase
  CHANGELOG.md
  source/renderer/app/Routes.js
  source/renderer/app/containers/Root.js
  source/renderer/app/stores/ProfileStore.js
Labels: bug, release-0.14.0

#1375 [DDW-628] Fix broken "Submit form on enter" feature
  CHANGELOG.md
  source/renderer/app/components/profile/terms-of-use/TermsOfUseForm.js
  source/renderer/app/components/wallet/WalletCreateDialog.js
  source/renderer/app/components/wallet/WalletRestoreDialog.js
  source/renderer/app/components/wallet/WalletSendConfirmationDialog.js
  source/renderer/app/components/wallet/WalletSendForm.js
  source/renderer/app/components/wallet/ada-redemption/AdaRedemptionForm.js
  source/renderer/app/components/wallet/paper-wallet-certificate/PrintDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/SecuringPasswordDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/VerificationDialog.js
  source/renderer/app/components/wallet/receive/WalletReceive.js
  source/renderer/app/components/wallet/settings/ChangeSpendingPasswordDialog.js
  source/renderer/app/components/wallet/settings/ExportWalletToFileDialog.js
Labels: bug, release-0.14.0

#1354 [DDW-590] Improve spending password validation
  .babelrc
  CHANGELOG.md
  nodemon.json
  package.json
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/components/wallet/settings/ChangeSpendingPasswordDialog.js
  source/renderer/app/config/timingConfig.js
  source/renderer/app/utils/validations.js
  source/tests/unit/spending-password-validation.feature
  source/tests/unit/steps/spending-password-validation-steps.js
  source/tests/unit/support/context.js
  source/tests/unit/support/parameter-types.js
Labels: bug, release-0.14.0

#1339 [DDW-589] Refactor consolidation status screen epoch calculation
  CHANGELOG.md
  features/block-consolidation-page.feature
  features/step_definitions/block-consolidation-page-steps.js
  source/common/ipc/api.js
  source/main/index.js
  source/main/ipc/getSystemStartTime.ipc.js
  source/main/preload.js
  source/renderer/app/actions/block-consolidation-actions.js
  source/renderer/app/actions/index.js
  source/renderer/app/actions/network-status-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/api/nodes/requests/getCurrentEpoch.js
  source/renderer/app/api/nodes/requests/getNodeInfo.js
  source/renderer/app/api/nodes/requests/getNodeSettings.js
  source/renderer/app/api/nodes/types.js
  source/renderer/app/api/utils/externalRequest.js
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/components/status/BlockConsolidationStatus.js
  source/renderer/app/components/status/BlockConsolidationStatus.scss
  source/renderer/app/config/timingConfig.js
  source/renderer/app/config/urlsConfig.js
  source/renderer/app/containers/status/BlockConsolidationStatusPage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/ipc/getSystemStartTime.ipc.js
  source/renderer/app/stores/BlockConsolidationStore.js
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/index.js
  source/renderer/app/utils/network.js
Labels: chore, release-0.14.0

#1376 [DDW-603] Updated PR template
  .github/pull_request_template.md
  CHANGELOG.md
Labels: chore, release-0.14.0

#1379 [DDW-614] Add unit tests for mnemonics
  CHANGELOG.md
  features/README.md
  features/mnemonics-generation-and-validation.feature
  features/tests/unit/steps/mnemonics-steps.js
  package.json
Labels: chore, release-0.14.0

#1377 [DDW-610] Implement new Block-consolidation status design
  CHANGELOG.md
  source/renderer/app/Routes.js
  source/renderer/app/assets/images/block-consolidation/epochs.png
  source/renderer/app/components/status/BlockConsolidationStatus.js
  source/renderer/app/components/status/BlockConsolidationStatus.scss
  source/renderer/app/containers/Root.js
  source/renderer/app/containers/status/BlockConsolidationStatusDialog.js
  source/renderer/app/containers/status/BlockConsolidationStatusDialog.scss
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/stores/AppStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/light-blue.js
  storybook/stories/BlockConsolidationStatus.stories.js
Labels: feature, release-0.14.0

#1381 [DDW-616] Save daedalus log as json file
  CHANGELOG.md
  source/main/index.js
  source/main/ipc/compress-logs.js
  source/main/utils/mainErrorHandler.js
  source/main/utils/safeExitWithCode.js
  source/renderer/app/stores/NetworkStatusStore.js
Labels: bug, release-0.14.0
