Repository input-output-hk/daedalus, pull requests merged in 2019-10, with the labels that each got.

#1575 [DDW-878] Create transaction v2 API integration
  CHANGELOG.md
  source/renderer/app/actions/wallets-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/api/transactions/requests/createTransaction.js
  source/renderer/app/api/transactions/requests/getTransactionFee.js
  source/renderer/app/api/transactions/types.js
  source/renderer/app/components/wallet/WalletSendConfirmationDialog.js
  source/renderer/app/components/wallet/WalletSendConfirmationDialog.scss
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/components/wallet/transactions/TransactionTypeIcon.js
  source/renderer/app/containers/wallet/dialogs/WalletSendConfirmationDialogContainer.js
  source/renderer/app/domains/WalletTransaction.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/TransactionsStore.js
  source/renderer/app/stores/WalletsStore.js
  storybook/stories/WalletScreens.stories.js
  storybook/stories/WalletTransactionsList.stories.js
  storybook/stories/support/utils.js
Labels: V2-API, chore, release-vNext

#1577 [DDW-877] Get Transactions v2 API integration
  CHANGELOG.md
  source/renderer/app/actions/addresses-actions.js
  source/renderer/app/actions/index.js
  source/renderer/app/api/addresses/requests/createAddress.js
  source/renderer/app/api/addresses/types.js
  source/renderer/app/api/api.js
  source/renderer/app/api/transactions/requests/getTransactionHistory.js
  source/renderer/app/api/transactions/types.js
  source/renderer/app/components/wallet/receive/WalletReceive.js
  source/renderer/app/components/wallet/receive/WalletReceive.scss
  source/renderer/app/containers/wallet/WalletReceivePage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/stores/AddressesStore.js
  source/renderer/app/stores/TransactionsStore.js
  source/renderer/app/stores/WalletsStore.js
Labels: V2-API, chore, release-vNext

#1578 [DDW-901] Fix yellow theme newsfeed sidebar message text color
  CHANGELOG.md
  source/renderer/app/themes/daedalus/yellow.js
Labels: bug, release-0.15.0

#1580 [DDW-911] Update newsfeed JSON and verification files hosting URLs
  CHANGELOG.md
  source/renderer/app/components/notifications/AutomaticUpdateNotification.js
  source/renderer/app/config/urlsConfig.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: chore, release-0.15.0

#1587 0.15.0 daedalus bridge override
  default.nix
  installers/cardano-configuration.yaml
Labels: chore, release-0.15.0

#1591 Merge release/0.15.0 into develop branch
  CHANGELOG.md
  default.nix
  features/tests/e2e/documents/paper_wallet_certificates/paper-wallet-certificate.pdf
  installers/cardano-configuration.yaml
  source/renderer/app/components/notifications/AutomaticUpdateNotification.js
  source/renderer/app/config/urlsConfig.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/themes/daedalus/yellow.js
Labels: chore, release-0.15.0

#1583 [DDW-952] Allow nix-free frontend only mode
  .flowconfig
  .gitignore
  CHANGELOG.md
  README.md
  package.json
  utils/js-launcher/README.md
  utils/js-launcher/index.js
  utils/js-launcher/launcher-config-base.yaml
  utils/js-launcher/lib/rimraf.js
  utils/js-launcher/lib/x509.js
  yarn.lock
Labels: V2-API, release-vNext

#1586 [DDW-904] Fix Flat button color
  CHANGELOG.md
  source/renderer/app/components/wallet/settings/WalletRecoveryPhrase.scss
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/mixins/buttons.scss
  source/renderer/app/themes/utils/createTheme.js
Labels: bug, release-vNext

#1592 [DDW-957] Remove automatic and manual update features
  CHANGELOG.md
  features/app-version-difference.feature
  features/node-update-exit.feature
  features/node-update-notification.feature
  features/tests/e2e/documents/paper_wallet_certificates/paper-wallet-certificate.pdf
  features/tests/e2e/steps/app-version-difference.js
  features/tests/e2e/steps/helper-steps.js
  features/tests/e2e/steps/node-update-notification-steps.js
  source/renderer/app/actions/index.js
  source/renderer/app/actions/node-update-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/api/nodes/requests/applyNodeUpdate.js
  source/renderer/app/api/nodes/requests/getLatestAppVersion.js
  source/renderer/app/api/nodes/requests/getNextNodeUpdate.js
  source/renderer/app/api/nodes/requests/postponeNodeUpdate.js
  source/renderer/app/api/nodes/types.js
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/api/utils/request.js
  source/renderer/app/components/layout/SidebarLayout.js
  source/renderer/app/components/loading/manual-update/ManualUpdate.js
  source/renderer/app/components/loading/manual-update/ManualUpdate.scss
  source/renderer/app/components/loading/syncing-connecting/SyncingConnecting.js
  source/renderer/app/components/notifications/NodeUpdateNotification.js
  source/renderer/app/components/notifications/NodeUpdateNotification.scss
  source/renderer/app/config/timingConfig.js
  source/renderer/app/config/urlsConfig.js
  source/renderer/app/containers/MainLayout.js
  source/renderer/app/containers/loading/LoadingPage.js
  source/renderer/app/containers/loading/ManualUpdatePage.js
  source/renderer/app/containers/loading/SyncingConnectingPage.js
  source/renderer/app/containers/notifications/NodeUpdatePage.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/NodeUpdateStore.js
  source/renderer/app/stores/index.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  source/renderer/app/utils/network.js
  storybook/stories/Loading-ManualUpdate.stories.js
  storybook/stories/Loading-SyncingConnecting.stories.js
  storybook/stories/Loading.stories.js
  storybook/stories/Widgets.stories.js
Labels: feature, release/0.14.AR

#1588 [DDW-957] Disable auto updates
  CHANGELOG.md
  installers/dhall/mainnet.dhall
  installers/dhall/staging.dhall
  installers/dhall/testnet.dhall
Labels: feature, release/0.14.AR

#1584 [DDW-883] Update cardano theme styles
  CHANGELOG.md
  source/renderer/app/components/news/IncidentOverlay.scss
  source/renderer/app/components/settings/categories/DisplaySettings.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsConfirmationDialog.scss
  source/renderer/app/components/wallet/transactions/Transaction.scss
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
Labels: bug, release-vNext

#1594 [DDW-967] Fix broken source maps
  CHANGELOG.md
  source/renderer/webpack.config.js
Labels: chore, release-vNext

#1597 [DDW-956] UI Label for 1.6.AR
  CHANGELOG.md
  source/renderer/app/assets/images/top-bar/sticker.svg
  source/renderer/app/components/widgets/NodeSyncStatusIcon.js
  source/renderer/app/components/widgets/NodeSyncStatusIcon.scss
  source/renderer/app/components/widgets/WalletTestEnvironmentLabel.js
  source/renderer/app/components/widgets/WalletTestEnvironmentLabel.scss
  source/renderer/app/containers/TopBarContainer.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/AdaRedemptionStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
Labels: chore, release/0.14.AR

#1598 [DDW-955] Full Screen Explanation for 0.14.AR Version of Daedalus
  CHANGELOG.md
  source/renderer/app/App.js
  source/renderer/app/components/wallet/ada-redemption/AdaRedemptionUpgradeOverlay.js
  source/renderer/app/components/wallet/ada-redemption/AdaRedemptionUpgradeOverlay.scss
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/ProfileStore.js
Labels: feature, release/0.14.AR

#1601 [DEVOPS] Enable signing of macOS builds
  installers/common/Config.hs
  installers/common/MacInstaller.hs
  installers/common/Types.hs
  installers/common/Util.hs
  installers/daedalus-installer.cabal
  installers/load-certificate.hs
  scripts/build-installer-unix.sh
Labels: Infrastructure, release-0.15.0

#1602 [DEVOPS] Enable signing of macOS builds
  installers/common/Config.hs
  installers/common/MacInstaller.hs
  installers/common/Types.hs
  installers/common/Util.hs
  installers/daedalus-installer.cabal
  installers/load-certificate.hs
  scripts/build-installer-unix.sh
Labels: Infrastructure, release/0.14.AR

#1603 Merge release/0.15.0 into develop branch
  installers/common/Config.hs
  installers/common/MacInstaller.hs
  installers/common/Types.hs
  installers/common/Util.hs
  installers/daedalus-installer.cabal
  installers/load-certificate.hs
  scripts/build-installer-unix.sh
Labels: chore, release-0.15.0

#1579 [DDW-931] Import wallet with funds for E2E tests purposes
  CHANGELOG.md
  features/add-wallet-via-sidebar.feature
  features/app-version-difference.feature
  features/block-consolidation-page.feature
  features/delete-wallet-via-settings.feature
  features/import-wallet-via-sidebar.feature
  features/local-time-difference.feature
  features/navigate-general-settings-menu.feature
  features/navigate-sidebar-categories.feature
  features/newsfeed.feature
  features/node-update-exit.feature
  features/paper-wallets-certificate.feature
  features/quit-app.feature
  features/receive-money.feature
  features/restore-wallet-via-sidebar.feature
  features/send-money-to-receiver.feature
  features/tests/e2e/documents/default-wallet.json
  features/tests/e2e/documents/default-wallet.key
  features/tests/e2e/documents/default-wallet.key.lock
  features/tests/e2e/helpers/wallets-helpers.js
  features/tests/e2e/steps/receive-steps.js
  features/tests/e2e/steps/transactions-steps.js
  features/tests/e2e/steps/wallets-steps.js
  features/tests/e2e/steps/wallets-utxos-steps.js
  features/toggle-sidebar-submenus.feature
  features/transactions-display.feature
  features/trouble-connecting-notification.feature
  features/trouble-syncing-notification.feature
  features/wallet-address-generate.feature
  features/wallet-settings-recovery-phrase-verification.feature
  features/wallet-settings.feature
  features/wallet-utxos.feature
  source/renderer/app/api/api.js
  source/renderer/app/api/transactions/errors.js
  source/renderer/app/components/wallet/WalletSendForm.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
Labels: V2-API, chore, release-vNext

#1599 Bump cardano wallet version
  lib.nix
  source/main/cardano/CardanoNode.js
  source/main/cardano/nodes/jormungandr.js
  utils/jormungandr/testnet/genesis.yaml
Labels: V2-API, chore

#1608 [DEVOPS] Staging applicationVersion bump -> 27
  installers/cardano-configuration.yaml
Labels: chore, release-0.15.0

#1595 [DDW-33] Reduce layout re-renderings
  CHANGELOG.md
  package.json
  source/renderer/app/containers/wallet/Wallet.js
  source/renderer/app/containers/wallet/WalletSummaryPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/stores/SidebarStore.js
  source/renderer/app/stores/WalletsStore.js
  yarn.lock
Labels: bug, release-vNext

#1604 [DDW-978] Handle transaction "pending since" timestamp
  CHANGELOG.md
  features/tests/e2e/steps/transactions-steps.js
  features/transactions-display.feature
  source/renderer/app/api/api.js
  source/renderer/app/api/transactions/types.js
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/components/wallet/transactions/Transaction.scss
  source/renderer/app/components/wallet/transactions/TransactionTypeIcon.js
  source/renderer/app/components/wallet/transactions/TransactionTypeIcon.scss
  source/renderer/app/domains/WalletTransaction.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/WalletTransactionsList.stories.js
Labels: feature, release-vNext

#1607 [DDW-981] Speedup storybook builds in development
  CHANGELOG.md
  storybook/webpack.config.js
Labels: chore, release-vNext

#1609 [DDW-968] Introduce address validator
  CHANGELOG.md
  features/send-money-to-receiver.feature
  package.json
  source/renderer/app/api/api.js
  source/renderer/app/components/wallet/WalletSendForm.js
  source/renderer/app/stores/WalletsStore.js
  yarn.lock
Labels: V2-API, chore, release-vNext

#1610 [DDW-965] Remove Block Consolidation status dialog
  CHANGELOG.md
  features/block-consolidation-page.feature
  features/tests/e2e/steps/block-consolidation-page-steps.js
  source/common/ipc/api.js
  source/common/ipc/constants.js
  source/main/index.js
  source/main/ipc/getNumberOfEpochsConsolidated.ipc.js
  source/main/locales/en-US.json
  source/main/locales/ja-JP.json
  source/main/menus/MenuActions.types.js
  source/main/menus/osx.js
  source/main/menus/win-linux.js
  source/main/utils/buildAppMenus.js
  source/main/utils/getNumberOfEpochsConsolidated.js
  source/renderer/app/App.js
  source/renderer/app/actions/app-actions.js
  source/renderer/app/actions/block-consolidation-actions.js
  source/renderer/app/actions/index.js
  source/renderer/app/api/api.js
  source/renderer/app/api/nodes/requests/getCurrentEpoch.js
  source/renderer/app/api/nodes/requests/getNodeSettings.js
  source/renderer/app/api/nodes/types.js
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/assets/images/block-consolidation/epochs.inline.svg
  source/renderer/app/assets/images/block-consolidation/epochs.png
  source/renderer/app/components/status/BlockConsolidationStatus.js
  source/renderer/app/components/status/BlockConsolidationStatus.scss
  source/renderer/app/config/timingConfig.js
  source/renderer/app/containers/status/BlockConsolidationStatusDialog.js
  source/renderer/app/containers/status/BlockConsolidationStatusDialog.scss
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/ipc/getNumberOfEpochsConsolidatedChannel.js
  source/renderer/app/stores/AppStore.js
  source/renderer/app/stores/BlockConsolidationStore.js
  source/renderer/app/stores/index.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  source/renderer/app/types/applicationDialogTypes.js
  storybook/stories/BlockConsolidationStatus.stories.js
  storybook/stories/index.js
Labels: V2-API, chore, release-vNext

#1614 [DDW-899] Remove accounts
  CHANGELOG.md
  features/tests/e2e/steps/transactions-steps.js
  features/tests/e2e/steps/wallets-steps.js
  source/renderer/app/api/accounts/errors.js
  source/renderer/app/api/accounts/requests/getAccounts.js
  source/renderer/app/api/accounts/types.js
  source/renderer/app/api/addresses/types.js
  source/renderer/app/api/api.js
  source/renderer/app/stores/AddressesStore.js
  source/renderer/app/stores/WalletsStore.js
Labels: V2-API, chore, release-vNext

#1615 [DDW 953] Jormungandr Testnet Support
  README.md
  lib.nix
  package.json
  source/main/cardano/CardanoWalletLauncher.js
  source/main/cardano/nodes/jormungandr.js
  utils/jormungandr/selfnode/genesis.yaml
Labels: V2-API, release-vNext

#1612 [DDW-922] Change the "Delete Wallet" Button Layout
  CHANGELOG.md
  source/renderer/app/actions/wallet-settings-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/api/wallets/requests/exportWalletAsJSON.js
  source/renderer/app/api/wallets/types.js
  source/renderer/app/components/wallet/settings/DeleteWalletButton.js
  source/renderer/app/components/wallet/settings/DeleteWalletButton.scss
  source/renderer/app/components/wallet/settings/ExportWalletToFileDialog.js
  source/renderer/app/components/wallet/settings/ExportWalletToFileDialog.scss
  source/renderer/app/components/wallet/settings/WalletSettings.js
  source/renderer/app/components/wallet/settings/WalletSettings.scss
  source/renderer/app/containers/wallet/WalletSettingsPage.js
  source/renderer/app/containers/wallet/dialogs/settings/ExportWalletToFileDialogContainer.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/WalletSettingsStore.js
  storybook/stories/wallets/actions/Export.stories.js
  storybook/stories/wallets/actions/index.js
  storybook/stories/wallets/settings/WalletSettingsScreen.stories.js
  storybook/stories/wallets/utils/defaultWalletProps.js
Labels: chore, release-vNext

#1616 Jormungandr version bump
  lib.nix
  source/main/cardano/nodes/jormungandr.js
Labels: V2-API, chore, release-vNext

#1619 [DDW-1016] Fix E2E broken 'Delete Wallet' test
  CHANGELOG.md
  tests/nodes/e2e/steps/helpers.js
  tests/wallets/e2e/steps/wallets.js
Labels: bug, release-vNext

#1623 [DDW-1022] Fix missing Japanese translation for recovery phrase verification
  CHANGELOG.md
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseStep3Dialog.js
Labels: bug, release-0.15.0

#1624 Merge release/0.15.0 into develop branch
  CHANGELOG.md
  installers/cardano-configuration.yaml
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseStep3Dialog.js
Labels: chore, release-0.15.0

#1627 [DEVOPS] Bump Daedalus application versions (staging -> 28, testnet -> 5)
  installers/cardano-configuration.yaml
Labels: chore, release-0.15.0

#1625 [DDW-1003]: Decentralization countdown, info, and staking epochs screens removal
  CHANGELOG.md
  source/renderer/app/actions/network-status-actions.js
  source/renderer/app/actions/staking-actions.js
  source/renderer/app/components/staking/layouts/StakingWithNavigation.js
  source/renderer/app/components/staking/navigation/StakingNavigation.js
  source/renderer/app/containers/staking/Staking.js
  source/renderer/app/containers/staking/StakingCountdownPage.js
  source/renderer/app/containers/staking/StakingEpochsPage.js
  source/renderer/app/containers/staking/StakingInfoPage.js
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/SidebarStore.js
  source/renderer/app/stores/StakingStore.js
  storybook/stories/Staking.stories.js
Labels: V2-API, chore, release-vNext

#1618 [DDW-968] Introduce address validator
  CHANGELOG.md
  source/renderer/app/stores/WalletsStore.js
Labels: V2-API, chore, release-vNext

#1617 [DDW-907] Add internal link support in newsfeed items
  .prettierignore
  CHANGELOG.md
  package.json
  source/renderer/app/actions/app-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/components/news/AlertsOverlay.js
  source/renderer/app/components/news/IncidentOverlay.js
  source/renderer/app/components/news/NewsFeed.js
  source/renderer/app/components/news/NewsItem.js
  source/renderer/app/config/newsfeed-files/news.dummy.json
  source/renderer/app/config/newsfeed-files/newsfeed_development.json
  source/renderer/app/config/newsfeed-files/newsfeed_mainnet.json
  source/renderer/app/config/newsfeed-files/newsfeed_staging.json
  source/renderer/app/config/newsfeed-files/newsfeed_testnet.json
  source/renderer/app/containers/news/NewsFeedContainer.js
  source/renderer/app/containers/news/NewsOverlayContainer.js
  source/renderer/app/stores/AppStore.js
  source/renderer/app/stores/NewsFeedStore.js
  storybook/stories/news/AlertsOverlay.stories.js
  storybook/stories/news/IncidentOverlay.stories.js
  storybook/stories/news/NewsFeed.stories.js
  tests/news/README.md
  utils/create-news-verification-hashes/index.js
Labels: feature, release-vNext
