Repository input-output-hk/daedalus, pull requests merged in 2020-03, with the labels that each got.

#1866 [DDW-850] Update Flow and EsLint dependencies
  .eslintrc
  CHANGELOG.md
  flow/declarations/EnumMap.js
  package.json
  source/common/types/bug-report-request.types.js
  source/common/types/cardano-node.types.js
  source/main/cardano/CardanoWalletLauncher.js
  source/renderer/app/ThemeManager.js
  source/renderer/app/WindowSizeManager.js
  source/renderer/app/api/common/types.js
  source/renderer/app/api/utils/requestV0.js
  source/renderer/app/components/wallet/settings/ExportWalletToFileDialog.js
  source/renderer/app/components/widgets/RadioSet.js
  source/renderer/app/components/widgets/forms/TinyButton.js
  source/renderer/app/components/widgets/forms/TinyCheckbox.js
  source/renderer/app/components/widgets/forms/TinyDatePicker.js
  source/renderer/app/components/widgets/forms/TinyInput.js
  source/renderer/app/components/widgets/forms/TinySelect.js
  source/renderer/app/components/widgets/forms/WalletsDropdown.js
  source/renderer/app/config/walletRestoreConfig.js
  source/renderer/app/containers/notifications/NotificationsContainer.js
  source/renderer/app/domains/WalletTransaction.js
  source/renderer/app/stores/NetworkStatusStore.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext-ITN0, chore, dependencies

#1870 [DDW-1218] Update cardano-wallet revision
  CHANGELOG.md
  default.nix
  installers/common/MacInstaller.hs
  installers/common/Types.hs
  installers/common/WindowsInstaller.hs
  nix/jormungandr-bridge.nix
  nix/launcher-config.nix
  nix/sources.json
  scripts/build-installer-unix.sh
  source/main/cardano/CardanoNode.js
  source/main/cardano/CardanoWalletLauncher.js
  source/main/cardano/nodes/index.js
  source/main/cardano/setupCardanoNodeMode.js
  source/main/config.js
  source/renderer/app/api/api.js
  source/renderer/app/api/staking/requests/getDelegationFee.js
  source/renderer/app/api/staking/requests/quitStakePool.js
  source/renderer/app/api/staking/types.js
  source/renderer/app/api/transactions/requests/getTransactionFee.js
  source/renderer/app/api/wallets/requests/restoreByronWallet.js
  source/renderer/app/stores/StakingStore.js
  utils/jormungandr/selfnode/config.yaml
  utils/jormungandr/selfnode/secret.yaml
  utils/v2-api-importer/legacy.js
Labels: :hourglass_flowing_sand:release-vNext-ITN1, chore

#1875 [DDW-1221] Bump Daedalus version to 2.3.0-ITN1
  CHANGELOG.md
  package.json
Labels: :hourglass_flowing_sand:release-vNext-ITN1, chore

#1868 [DDW-1152] Implement acceptance tests for custom number, date and time formats
  CHANGELOG.md
  tests/common/e2e/steps/helpers.js
  tests/delegation/e2e/steps/delegation-pending.js
  tests/settings/e2e/features/custom-formats.feature
  tests/settings/e2e/steps/custom-formats.js
  tests/settings/e2e/steps/helpers.js
  tests/transactions/e2e/steps/transactions.js
  tests/wallets/e2e/steps/transfer-funds-wizard.js
Labels: :hourglass_flowing_sand:release-vNext-ITN1, chore

#1872 [DDW-1220] Re-enable theme selection
  CHANGELOG.md
  source/renderer/app/components/settings/categories/DisplaySettings.scss
  source/renderer/app/components/settings/menu/SettingsMenu.js
  source/renderer/app/containers/settings/Settings.js
  source/renderer/app/stores/ProfileStore.js
  storybook/stories/settings/utils/SettingsWrapper.js
Labels: :hourglass_flowing_sand:release-vNext-ITN0, chore

#1873 [DDW-856] Update storybook dependencies
  CHANGELOG.md
  package.json
  source/renderer/app/stores/WalletsStore.js
  storybook/stories/_support/StoryLayout.js
  storybook/stories/wallets/transferFunds/TransferFunds.stories.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext-ITN1, chore, dependencies

#1877 [DDW-844] Update small 3rd party dependencies
  CHANGELOG.md
  package.json
  source/main/cardano/CardanoNode.js
  source/main/ipc/get-logs.js
  source/renderer/app/components/loading/syncing-connecting/logo-animation-data.json
  source/renderer/app/components/staking/epochs/StakingEpochsCurrentEpochData.js
  source/renderer/app/components/staking/epochs/StakingEpochsPreviousEpochData.js
  source/renderer/app/components/wallet/transactions/render-strategies/VirtualTransactionList.js
  source/renderer/app/components/wallet/wallet-restore/WalletTypeDialog.js
  source/renderer/app/stores/ProfileStore.js
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/stores/index.js
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/settings/general/General.stories.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext-ITN1, chore, dependencies

#1871 [DDW-769] Remove locale-specific rules from the CSS files
  CHANGELOG.md
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/components/status/DaedalusDiagnostics.scss
  source/renderer/app/components/wallet/wallet-restore/WalletTypeDialog.js
  source/renderer/app/containers/status/DaedalusDiagnosticsDialog.js
  source/renderer/app/stores/WalletsStore.js
  storybook/stories/nodes/status/Diagnostics.stories.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext-ITN1, bug

#1885 [DDW-1202] Daedalus wallet restoration spinner improvement
  CHANGELOG.md
  source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.scss
  source/renderer/app/components/widgets/LoadingSpinner.scss
Labels: :hourglass_flowing_sand:release-vNext-ITN1, bug

#1883 [DDW-854] Update node and yarn
  package.json
  shell.nix
  yarn.lock
  yarn2nix.nix
Labels: :hourglass_flowing_sand:release-vNext-ITN1, chore, dependencies

#1888 [DDW-1230] Bump cardano wallet revision
  CHANGELOG.md
  nix/sources.json
Labels: :hourglass_flowing_sand:release-vNext-ITN1, chore

#1890 Release/2.3.1 itn1 codesign
  CHANGELOG.md
  installers/DarwinLauncher.hs
  installers/common/Config.hs
  installers/common/MacInstaller.hs
  installers/daedalus-installer.cabal
  installers/daedalus-installer.nix
  nix/launcher-config.nix
  scripts/build-installer-unix.sh
  shell.nix
Labels: :hourglass_flowing_sand:release-vNext-ITN1, bug

#1891 [DDW-1232] Fix stake pool rank color within the stake pool tooltip
  CHANGELOG.md
  source/renderer/app/components/staking/stake-pools/StakePoolThumbnail.js
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.js
Labels: bug, release-2.3.1-ITN1

#1889 [DEVOPS] Begin adding the haskell bridge
  default.nix
  nix/cardano-bridge.nix
  nix/launcher-config.nix
  nix/sources.json
  package.json
  release.nix
  scripts/build-cross-windows.sh
  scripts/build-installer-nix.sh
  scripts/build-installer-unix.sh
  shell.nix
Labels: infrastructure

#1882 [DDW-855] Update React-Polymorph dependency
  CHANGELOG.md
  package.json
  source/renderer/app/components/navigation/NavDropdown.js
  source/renderer/app/components/navigation/NavDropdown.scss
  source/renderer/app/components/staking/epochs/StakingEpochs.js
  source/renderer/app/components/wallet/WalletRestoreDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/VerificationDialog.js
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseStep2Dialog.js
  source/renderer/app/components/wallet/wallet-restore/MnemonicsDialog.js
  source/renderer/app/components/widgets/forms/ProfileSettingsForm.js
  source/renderer/app/components/widgets/forms/TinySelect.js
  source/renderer/app/components/widgets/forms/WalletsDropdown.js
  source/renderer/app/themes/daedalus.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext-ITN1, chore, dependencies

#1893 Merge release/2.3.1-ITN1 into v2-integration
  CHANGELOG.md
  installers/DarwinLauncher.hs
  installers/common/Config.hs
  installers/common/MacInstaller.hs
  installers/daedalus-installer.cabal
  installers/daedalus-installer.nix
  nix/launcher-config.nix
  nix/sources.json
  package.json
  scripts/build-installer-unix.sh
  shell.nix
  source/renderer/app/components/staking/stake-pools/StakePoolThumbnail.js
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.js
Labels: chore, release-2.3.1-ITN1

#1874 [DDW-1213] Optimize E2E tests
  .gitignore
  CHANGELOG.md
  package.json
  source/renderer/app/api/api.js
  source/renderer/app/api/utils/patchAdaApi.js
  tests-report/.gitkeep
  tests/.gitignore
  tests/addresses/e2e/steps/addresses.js
  tests/common/e2e/steps/config.js
  tests/common/e2e/steps/helpers.js
  tests/delegation/e2e/features/delegation.feature
  tests/delegation/e2e/steps/delegation-pending.js
  tests/delegation/e2e/steps/delegation.js
  tests/delegation/e2e/steps/helpers.js
  tests/delegation/e2e/steps/stake-pools.js
  tests/navigation/e2e/steps/helpers.js
  tests/nodes/e2e/steps/about-dialog.js
  tests/paper-wallets/e2e/steps/paper-wallets-certificate.js
  tests/reporter.js
  tests/screenshots/nodes/e2e/features/wallet-settings-recovery-phrase-verification-2019-10-02T183344.0435Z.png
  tests/screenshots/paper-wallets/e2e/features/paper-wallets-certificate-2019-10-02T183449.0434Z.png
  tests/settings/e2e/features/custom-formats.feature
  tests/settings/e2e/features/wallet-settings.feature
  tests/settings/e2e/steps/settings.js
  tests/setup-e2e.js
  tests/transactions/e2e/steps/transactions.js
  tests/wallets/e2e/features/balance-wallets-notification.feature
  tests/wallets/e2e/features/transfer-funds-wizard.feature
  tests/wallets/e2e/steps/balance-wallets-notification.js
  tests/wallets/e2e/steps/create-wallet.js
  tests/wallets/e2e/steps/delete-wallet.js
  tests/wallets/e2e/steps/helpers.js
  tests/wallets/e2e/steps/import-wallet.js
  tests/wallets/e2e/steps/transfer-funds-wizard.js
  tests/wallets/e2e/steps/wallets-limit.js
  tests/wallets/e2e/steps/wallets-ordering.js
  tests/wallets/e2e/steps/wallets.js
  utils/v2-api-importer/legacy.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext-ITN1, chore

#1886 [DDW-24] Install cardano-launcher, refactor Daedalus to implement the library
  .flowconfig
  CHANGELOG.md
  default.nix
  nix/cardano-bridge.nix
  nix/launcher-config.nix
  nix/sources.json
  package.json
  release.nix
  scripts/build-cross-windows.sh
  scripts/build-installer-nix.sh
  scripts/build-installer-unix.sh
  shell.nix
  source/main/cardano/CardanoNode.js
  source/main/cardano/CardanoWalletLauncher.js
  source/main/cardano/config.js
  source/main/cardano/setupCardanoNodeMode.js
  source/main/config.js
  source/main/index.js
  source/renderer/app/api/api.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext-ITN1, feature

#1894 [DDW-27] Update installers to bundle the new services as determined by the cardano-wallet dependency
  CHANGELOG.md
  default.nix
  installer-clusters.cfg
  installers/Installer.hs
  installers/common/Config.hs
  installers/common/MacInstaller.hs
  installers/common/Types.hs
  installers/common/Util.hs
  installers/common/WindowsInstaller.hs
  nix/cardano-bridge.nix
  nix/launcher-config.nix
  nix/sources.json
  release.nix
  scripts/build-cross-windows.sh
  scripts/build-installer-nix.sh
  scripts/build-installer-unix.sh
Labels: :hourglass_flowing_sand:release-vNext, feature

#1900 [DDW-65] Inject start-time into genesis file for selfnode cluster
  nix/launcher-config.nix
  source/main/cardano/CardanoNode.js
  source/main/cardano/CardanoWalletLauncher.js
  source/main/cardano/utils.js
  source/main/utils/mainErrorHandler.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#1904 Extra bins launcher config
  nix/launcher-config.nix
  source/renderer/app/api/api.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#1901 [DDW-64] Handle non-responding wallets
  CHANGELOG.md
  nix/sources.json
  source/renderer/app/api/api.js
  source/renderer/app/api/wallets/types.js
  source/renderer/app/assets/images/not-responding.inline.svg
  source/renderer/app/components/sidebar/wallets/SidebarWalletMenuItem.js
  source/renderer/app/components/sidebar/wallets/SidebarWalletMenuItem.scss
  source/renderer/app/components/sidebar/wallets/SidebarWalletsMenu.js
  source/renderer/app/components/wallet/layouts/WalletWithNavigation.js
  source/renderer/app/components/wallet/not-responding/NotResponding.js
  source/renderer/app/components/wallet/not-responding/NotResponding.scss
  source/renderer/app/containers/wallet/Wallet.js
  source/renderer/app/domains/Wallet.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/SidebarStore.js
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  source/renderer/app/types/sidebarTypes.js
  storybook/stories/_support/StoryLayout.js
  storybook/stories/_support/StoryProvider.js
  storybook/stories/navigation/Sidebar.stories.js
  storybook/stories/navigation/SidebarWalletsMenu.stories.js
  storybook/stories/wallets/_utils/WalletsWrapper.js
  tests/wallets/e2e/features/wallet-not-responding.feature
  tests/wallets/e2e/steps/helpers.js
  tests/wallets/e2e/steps/wallet-not-responding.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#1906 [DDW-60] Refactor launcher config
  default.nix
  installers/common/MacInstaller.hs
  installers/common/WindowsInstaller.hs
  nix/launcher-config.nix
  scripts/build-installer-unix.sh
  shell.nix
Labels: :hourglass_flowing_sand:release-vNext, chore

#1907 [DDW-42] Update UI copy
  CHANGELOG.md
  source/renderer/app/components/wallet/WalletAdd.js
  source/renderer/app/components/wallet/WalletCreateDialog.js
  source/renderer/app/components/wallet/backup-recovery/WalletBackupPrivacyWarningDialog.js
  source/renderer/app/components/wallet/backup-recovery/WalletRecoveryPhraseDisplayDialog.js
  source/renderer/app/components/wallet/backup-recovery/WalletRecoveryPhraseEntryDialog.js
  source/renderer/app/components/wallet/backup-recovery/WalletRecoveryPhraseEntryDialog.scss
  source/renderer/app/components/wallet/wallet-restore/SuccessDialog.js
  source/renderer/app/components/wallet/wallet-restore/WalletTypeDialog.js
  source/renderer/app/containers/wallet/dialogs/WalletBackupDialogContainer.js
  source/renderer/app/i18n/global-messages.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: :hourglass_flowing_sand:release-vNext, chore

#1905 [DDW-60] V2 -> V3 wallet migration
  nix/launcher-config.nix
  nix/sources.json
  source/common/ipc/api.js
  source/common/types/logging.types.js
  source/main/cardano/CardanoNode.js
  source/main/cardano/config.js
  source/main/cardano/setup.js
  source/main/cardano/setupCardanoNodeMode.js
  source/main/cardano/setupFrontendOnlyMode.js
  source/main/config.js
  source/main/index.js
  source/main/ipc/cardano.ipc.js
  source/main/ipc/generateWalletMigrationReportChannel.js
  source/main/utils/setupLogging.js
  source/renderer/app/actions/wallets-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/api/utils/localStorage.js
  source/renderer/app/api/wallets/requests/restoreExportedByronWallet.js
  source/renderer/app/api/wallets/types.js
  source/renderer/app/ipc/cardano.ipc.js
  source/renderer/app/ipc/generateWalletMigrationReportChannel.js
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/WalletMigrationStore.js
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/stores/index.js
  source/renderer/app/types/walletExportTypes.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#1908 [DDW-75] Implement flight candidates changes
  CHANGELOG.md
  source/renderer/app/components/wallet/WalletSendConfirmationDialog.js
  source/renderer/app/components/wallet/WalletSendConfirmationDialog.scss
  source/renderer/app/containers/wallet/dialogs/WalletSendConfirmationDialogContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: :hourglass_flowing_sand:release-vNext, feature

#1911 [DDW-49] Enable wallet name editing in "Wallet settings"
  CHANGELOG.md
  source/renderer/app/api/api.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#1913 [DDW-51] Enable Wallet UTxO distribution for Byron wallets
  CHANGELOG.md
  source/renderer/app/api/api.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#1914 [DDW-71] Implement new theme - Flight Candidate
  CHANGELOG.md
  gulpfile.js
  source/renderer/app/assets/images/themes/flight-candidate.png
  source/renderer/app/components/settings/categories/DisplaySettings.js
  source/renderer/app/components/settings/menu/SettingsMenu.js
  source/renderer/app/containers/settings/Settings.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/ProfileStore.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/index.js
  source/renderer/app/themes/index.js
  source/renderer/app/themes/types.js
  source/renderer/app/themes/utils/constants.js
  storybook/stories/_support/config.js
  storybook/stories/settings/utils/SettingsWrapper.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#1915 [DDW-80] Integrate network parameters api endpoint
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/api/network/requests/getNetworkParameters.js
  source/renderer/app/api/network/types.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#1917 [DDW-39] Flight release information window
  CHANGELOG.md
  source/main/preload.js
  source/renderer/app/components/splash/Network.js
  source/renderer/app/components/splash/SplashNetworkFlight.js
  source/renderer/app/components/splash/SplashNetworkITN.js
  source/renderer/app/components/widgets/splash/Splash.js
  source/renderer/app/components/widgets/splash/Splash.scss
  source/renderer/app/containers/Root.js
  source/renderer/app/containers/splash/NetworkPage.js
  source/renderer/app/containers/splash/SplashNetworkPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/themes/daedalus/flight-candidate.js
  storybook/stories/nodes/splash/Splash.stories.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#1918 [DDW-81] Integrate network clock api endpoint
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/api/network/requests/getNetworkClock.js
  source/renderer/app/api/network/types.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#1919 [DEVOPS] Update cardano-sl for latest export-wallets
  nix/sources.json
Labels: :hourglass_flowing_sand:release-vNext, chore

#1921 Fix migration issues
  nix/launcher-config.nix
Labels: :hourglass_flowing_sand:release-vNext, bug

#1916 [DDW-1222] Fix theming issues
  CHANGELOG.md
  source/renderer/app/components/news/AlertsOverlay.scss
  source/renderer/app/components/news/IncidentOverlay.scss
  source/renderer/app/components/news/NewsFeed.scss
  source/renderer/app/components/profile/terms-of-use/TermsOfUseText.scss
  source/renderer/app/components/sidebar/SidebarCategoryNetworkInfo.scss
  source/renderer/app/components/splash/Network.scss
  source/renderer/app/components/splash/SplashNetworkITN.js
  source/renderer/app/components/staking/delegation-center/WalletRow.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.js
  source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.scss
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsSearch.scss
  source/renderer/app/components/wallet/receive/VirtualAddressesList.scss
  source/renderer/app/components/wallet/settings/ResyncWalletButton.scss
  source/renderer/app/components/wallet/skins/AmountInputSkin.scss
  source/renderer/app/components/wallet/transactions/FilterButton.scss
  source/renderer/app/components/wallet/transactions/FilterDialog.js
  source/renderer/app/components/wallet/transactions/FilterDialog.scss
  source/renderer/app/components/widgets/forms/InlineEditingInput.scss
  source/renderer/app/components/widgets/forms/TinySwitch.scss
  source/renderer/app/components/widgets/splash/Splash.js
  source/renderer/app/components/widgets/splash/Splash.scss
  source/renderer/app/containers/notifications/NotificationsContainer.js
  source/renderer/app/containers/splash/SplashNetworkPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/ProfileStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/nodes/splash/Splash.stories.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#1922 [DDW-60] Handle wallet migration errors
  CHANGELOG.md
  source/main/cardano/setup.js
  source/main/cardano/utils.js
  source/main/index.js
  source/main/locales/en-US.json
  source/main/locales/ja-JP.json
  source/renderer/app/components/staking/stake-pools/StakePoolsSearch.scss
  source/renderer/app/components/widgets/splash/Splash.scss
  source/renderer/app/themes/daedalus/dark-blue.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#1926 [DDW-91] Reduce connection timeout limit for Byron Reboot builds
  CHANGELOG.md
  source/renderer/app/config/timingConfig.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#1927 [DDW-89] Adds Daedalus Flight newsfeed
  CHANGELOG.md
  source/renderer/app/api/news/requests/getNews.js
  source/renderer/app/api/news/requests/getNewsHash.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#1928 [DDW-83] Update about screen
  CHANGELOG.md
  source/common/types/environment.types.js
  source/main/config.js
  source/main/environment.js
  source/main/preload.js
  source/main/windows/main.js
  source/renderer/app/components/static/About.js
  source/renderer/app/containers/static/AboutDialog.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/WalletsStore.js
  storybook/stories/nodes/_utils/props.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#1930 [DDW-84] Update copy of "Automatic wallet migration" warning dialog
  CHANGELOG.md
  source/main/locales/en-US.json
  source/main/locales/ja-JP.json
Labels: :hourglass_flowing_sand:release-vNext, chore

#1920 [DDW-82] Implement TLS support
  README.md
  installer-clusters.cfg
  nix/launcher-config.nix
  nix/sources.json
  package.json
  source/main/cardano/CardanoNode.js
  source/main/cardano/CardanoWalletLauncher.js
  source/renderer/app/api/api.js
  source/renderer/app/api/utils/request.js
  tls/ca.crt
  tls/client/ca.crt
  tls/client/client.crt
  tls/client/client.key
  tls/client/client.pem
  tls/server.crt
  tls/server.key
  tls/server/ca.crt
  tls/server/server.crt
  tls/server/server.key
  tls/server/server.pem
  utils/api-importer/byron-wallet-importer.js
  utils/api-importer/itn-byron-wallet-importer.js
  utils/api-importer/itn-shelley-wallet-importer.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext, feature

#1933 [DEVOPS] Fix Linux mainnet_flight name
  default.nix
  installers/common/Types.hs
Labels: :hourglass_flowing_sand:release-vNext, bug

#1937 [DEVOPS] Add useLocalNode flag for development testing
  default.nix
  shell.nix
Labels: :hourglass_flowing_sand:release-vNext, chore

#1931 [DDW-95] Disable 'Recovery phrase verification' feature
  CHANGELOG.md
  source/renderer/app/components/wallet/settings/WalletSettings.js
  source/renderer/app/containers/wallet/WalletSettingsPage.js
Labels: :hourglass_flowing_sand:release-vNext, DO NOT MERGE, feature

#1935 [DDW-84] Handle migration of passwordless wallets
  CHANGELOG.md
  nix/sources.json
  source/main/cardano/CardanoWalletLauncher.js
  source/main/environment.js
  source/renderer/app/api/api.js
  source/renderer/app/components/wallet/settings/ChangeSpendingPasswordDialog.js
  source/renderer/app/components/widgets/Dialog.js
  source/renderer/app/containers/wallet/Wallet.js
  source/renderer/app/containers/wallet/WalletSummaryPage.js
  source/renderer/app/containers/wallet/dialogs/settings/ChangeSpendingPasswordDialogContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/AddressesStore.js
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  storybook/stories/wallets/_utils/defaultWalletProps.js
  storybook/stories/wallets/settings/WalletSettingsScreen.stories.js
  utils/api-importer/byron-wallet-importer.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#1925 [DDW-57] Implement NTP checks
  CHANGELOG.md
  README.md
  nix/sources.json
  source/renderer/app/api/api.js
  source/renderer/app/api/network/types.js
  source/renderer/app/components/loading/syncing-connecting/StatusIcons.js
  source/renderer/app/components/loading/syncing-connecting/SyncingConnecting.js
  source/renderer/app/components/loading/system-time-error/SystemTimeError.js
  source/renderer/app/components/loading/system-time-error/SystemTimeError.scss
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/components/wallet/backup-recovery/WalletBackupPrivacyWarningDialog.js
  source/renderer/app/config/timingConfig.js
  source/renderer/app/containers/loading/LoadingPage.js
  source/renderer/app/containers/loading/SyncingConnectingPage.js
  source/renderer/app/containers/loading/SystemTimeErrorPage.js
  source/renderer/app/containers/status/DaedalusDiagnosticsDialog.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/utils/humanizeDurationByLocale.js
  storybook/stories/nodes/status/Diagnostics.stories.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#1934 [DDW-68] New terms of service
  CHANGELOG.md
  source/renderer/app/i18n/locales/terms-of-use/en-US.md
  source/renderer/app/i18n/locales/terms-of-use/itn-rewards-v1/en-US.md
  source/renderer/app/i18n/locales/terms-of-use/itn-rewards-v1/ja-JP.md
  source/renderer/app/i18n/locales/terms-of-use/ja-JP.md
  source/renderer/app/i18n/locales/terms-of-use/mainnet/en-US.md
  source/renderer/app/i18n/locales/terms-of-use/mainnet/ja-JP.md
  source/renderer/app/i18n/locales/terms-of-use/other/en-US.md
  source/renderer/app/i18n/locales/terms-of-use/other/ja-JP.md
  source/renderer/app/stores/ProfileStore.js
  storybook/stories/settings/general/General.stories.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#1936 [DDW-97] Disabled wallet migration
  CHANGELOG.md
  source/renderer/app/stores/NetworkStatusStore.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#1938 [DEVOPS] cardano-wallet: bump node and client libs to 1.9.3
  nix/launcher-config.nix
  nix/sources.json
Labels: :hourglass_flowing_sand:release-vNext, chore
