Repository input-output-hk/daedalus, pull requests merged in 2020-11, with the labels that each got.

#2227 [DDW-432] Stake pool ranking logic update
  CHANGELOG.md
  source/renderer/app/components/staking/stake-pools/StakePoolsTable.js
  source/renderer/app/components/staking/stake-pools/StakePoolsTable.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsTableBody.js
  source/renderer/app/components/staking/widgets/ThumbPoolContent.js
  source/renderer/app/components/staking/widgets/ThumbPoolContent.scss
  source/renderer/app/components/staking/widgets/ThumbSelectedPool.js
  source/renderer/app/components/staking/widgets/TooltipPool.js
  source/renderer/app/components/staking/widgets/TooltipPool.scss
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: :hourglass_flowing_sand:release-vNext, feature

#2232 [DDW-424] Fix prettier/flow linting issue
  .eslintrc
  storybook/stories/wallets/transactions/Utxo.stories.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2231 [DDW-436] Fix leftovers not being displayed correctly
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/components/wallet/transfer-funds/TransferFundsStep2Dialog.js
  storybook/stories/wallets/legacyWallets/TransferFunds.stories.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2233 Merge release/2.4.1-FC1 into develop
  CHANGELOG.md
  package.json
Labels: :airplane: release-2.4.1-FC1, chore

#2234 Merge release/2.4.1 into develop
  CHANGELOG.md
  package.json
Labels: chore, release-2.4.1

#2236 Merge release/2.4.1-FC1 and release/2.4.1 into master
  .eslintrc
  CHANGELOG.md
  nix/sources.json
  package.json
  source/common/types/cardano-node.types.js
  source/renderer/app/api/api.js
  source/renderer/app/components/appUpdate/AppUpdateOverlay.js
  source/renderer/app/components/loading/syncing-connecting/StatusIcons-tooltip.scss
  source/renderer/app/components/loading/syncing-connecting/StatusIcons.js
  source/renderer/app/components/loading/syncing-connecting/StatusIcons.scss
  source/renderer/app/components/news/NewsFeed.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsRanking.js
  source/renderer/app/components/staking/stake-pools/StakePoolsTable.js
  source/renderer/app/components/staking/stake-pools/StakePoolsTable.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsTableBody.js
  source/renderer/app/components/staking/widgets/ThumbPoolContent.js
  source/renderer/app/components/staking/widgets/ThumbPoolContent.scss
  source/renderer/app/components/staking/widgets/ThumbSelectedPool.js
  source/renderer/app/components/staking/widgets/TooltipPool.js
  source/renderer/app/components/staking/widgets/TooltipPool.scss
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseVerificationWidget.js
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseVerificationWidget.scss
  source/renderer/app/components/wallet/transfer-funds/TransferFundsStep2Dialog.js
  source/renderer/app/components/widgets/Slider.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/themes/daedalus.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/shelley-testnet.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/overrides/PopOverOverrides.scss
  source/renderer/app/themes/overrides/index.js
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/wallets/legacyWallets/TransferFunds.stories.js
  storybook/stories/wallets/transactions/Utxo.stories.js
  yarn.lock
Labels: :airplane: release-2.4.1-FC1, release-2.4.1

#2237 [DDW-433]: Hide hardware wallet restoration support
  CHANGELOG.md
  source/renderer/app/config/walletRestoreConfig.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2196 [DDW-369] Implement copy CSS variables
  CHANGELOG.md
  package.json
  source/renderer/app/themes/README.md
  source/renderer/app/themes/utils/copyTheme.js
  source/renderer/app/themes/utils/writeThemeUpdate.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext, feature

#2207 [DDW-385] Filter and export transactions to a CSV file
  CHANGELOG.md
  source/common/ipc/api.js
  source/common/types/csv-request.types.js
  source/common/types/rewards-csv-request.types.js
  source/main/ipc/generateCsvChannel.js
  source/main/ipc/index.js
  source/renderer/app/actions/staking-actions.js
  source/renderer/app/actions/transactions-actions.js
  source/renderer/app/actions/wallets-actions.js
  source/renderer/app/assets/images/download-icon.inline.svg
  source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.js
  source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.scss
  source/renderer/app/components/wallet/layouts/WalletWithNavigation.js
  source/renderer/app/components/wallet/layouts/WalletWithNavigation.scss
  source/renderer/app/components/wallet/summary/WalletSummary.scss
  source/renderer/app/components/wallet/transactions/FilterButton.js
  source/renderer/app/components/wallet/transactions/FilterButton.scss
  source/renderer/app/components/wallet/transactions/FilterDialog.js
  source/renderer/app/components/wallet/transactions/WalletTransactions.js
  source/renderer/app/components/wallet/transactions/WalletTransactions.scss
  source/renderer/app/components/wallet/transactions/WalletTransactionsHeader.js
  source/renderer/app/components/wallet/transactions/WalletTransactionsHeader.scss
  source/renderer/app/components/wallet/transactions/WalletTransactionsList.js
  source/renderer/app/components/wallet/transactions/WalletTransactionsList.scss
  source/renderer/app/components/wallet/transactions/render-strategies/SimpleTransactionList.js
  source/renderer/app/components/wallet/transactions/render-strategies/VirtualTransactionList.js
  source/renderer/app/components/widgets/forms/TinyButton.js
  source/renderer/app/containers/notifications/NotificationsContainer.js
  source/renderer/app/containers/staking/StakingRewardsPage.js
  source/renderer/app/containers/wallet/WalletTransactionsPage.js
  source/renderer/app/containers/wallet/dialogs/FilterDialogContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/ipc/generateCsvChannel.js
  source/renderer/app/ipc/generateRewardsCsvChannel.js
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/stores/TransactionsStore.js
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/shelley-testnet.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  source/renderer/app/types/notificationTypes.js
  source/renderer/app/utils/csvGenerator.js
  source/renderer/app/utils/rewardsCsvGenerator.js
  source/renderer/app/utils/transactionsCsvGenerator.js
  storybook/stories/wallets/_utils/WalletsTransactionsWrapper.js
  storybook/stories/wallets/transactions/TransactionsList.stories.js
  storybook/stories/wallets/transactions/TransactionsListWithFilter.stories.js
  storybook/stories/wallets/transactions/WalletTransactions.stories.js
  tests/delegation/e2e/steps/rewards.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2241 [DDW-192] Improve form fields feedback UX
  CHANGELOG.md
  package.json
  source/renderer/app/App.js
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseVerificationWidget.js
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseVerificationWidget.scss
  source/renderer/app/components/wallet/wallet-restore/ConfigurationDialog.js
  source/renderer/app/components/widgets/DialogFullSizeOverride.scss
  source/renderer/app/i18n/locales/ja-JP.json
  storybook/stories/_support/StoryDecorator.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext, feature

#2246 [DDW-483] Bumps cardano-wallet version
  CHANGELOG.md
  README.md
  installers/common/Config.hs
  installers/common/MacInstaller.hs
  installers/common/Types.hs
  installers/common/Util.hs
  installers/common/WindowsInstaller.hs
  nix/jormungandr-bridge.nix
  nix/sources.json
  source/main/cardano/CardanoWalletLauncher.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2245 [DDW-391] Receive screen with address sharing functionality
  CHANGELOG.md
  package.json
  source/common/ipc/api.js
  source/common/types/save-qrCode.types.js
  source/common/utils/files.js
  source/main/ipc/generateAddressPDFChannel.js
  source/main/ipc/index.js
  source/main/ipc/saveQRCodeImageChannel.js
  source/renderer/app/actions/wallets-actions.js
  source/renderer/app/components/wallet/receive/AddressActions.js
  source/renderer/app/components/wallet/receive/AddressActions.scss
  source/renderer/app/components/wallet/receive/AddressSequential.js
  source/renderer/app/components/wallet/receive/AddressSequential.scss
  source/renderer/app/components/wallet/receive/WalletReceiveDialog.js
  source/renderer/app/components/wallet/receive/WalletReceiveDialog.scss
  source/renderer/app/components/wallet/receive/WalletReceiveRandom.js
  source/renderer/app/components/wallet/receive/WalletReceiveSequential.js
  source/renderer/app/containers/notifications/NotificationsContainer.js
  source/renderer/app/containers/wallet/WalletReceivePage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/ipc/saveQRCodeImageChannel.js
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/types/notificationTypes.js
  storybook/stories/wallets/receive/WalletReceive.stories.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext, feature

#2242 [DDW-431] Newsfeed shadow
  CHANGELOG.md
  source/renderer/app/components/news/NewsFeed.js
  source/renderer/app/components/news/NewsFeed.scss
  source/renderer/app/components/news/NewsItem.js
  source/renderer/app/components/news/NewsItem.scss
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/shelley-testnet.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2243 [DDW-430] Smart tooltips
  CHANGELOG.md
  package.json
  source/renderer/app/components/staking/delegation-center/WalletRow.js
  source/renderer/app/components/staking/delegation-center/WalletRow.scss
  source/renderer/app/components/staking/delegation-center/WalletRowTooltip.scss
  source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.js
  source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnetTooltip.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsRanking.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsSearch.js
  source/renderer/app/components/staking/stake-pools/StakePoolsSearch.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsTable.js
  source/renderer/app/components/staking/stake-pools/StakePoolsTable.scss
  source/renderer/app/components/staking/widgets/ThumbPool.js
  source/renderer/app/components/staking/widgets/TooltipPool-copyId-tooltip.scss
  source/renderer/app/components/staking/widgets/TooltipPool-experimental-tooltip.scss
  source/renderer/app/components/staking/widgets/TooltipPool.js
  source/renderer/app/components/staking/widgets/TooltipPool.scss
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/components/status/DaedalusDiagnostics.scss
  source/renderer/app/components/wallet/WalletCreateDialog.js
  source/renderer/app/components/wallet/WalletCreateDialog.scss
  source/renderer/app/components/wallet/WalletRestoreDialog.js
  source/renderer/app/components/wallet/WalletRestoreDialog.scss
  source/renderer/app/components/wallet/settings/ChangeSpendingPasswordDialog.js
  source/renderer/app/components/wallet/settings/ChangeSpendingPasswordDialog.scss
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseVerificationWidget.js
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseVerificationWidget.scss
  source/renderer/app/components/wallet/transfer-funds/TransferFundsStep2Dialog.scss
  source/renderer/app/components/wallet/wallet-import/WalletSelectImportDialog.js
  source/renderer/app/components/wallet/wallet-import/WalletSelectImportDialog.scss
  source/renderer/app/components/wallet/wallet-restore/ConfigurationDialog.js
  source/renderer/app/components/wallet/wallet-restore/ConfigurationDialog.scss
  source/renderer/app/components/widgets/forms/FormFieldSkinTooltip-tooltip.scss
  source/renderer/app/components/widgets/forms/FormFieldSkinTooltip.js
  source/renderer/app/components/widgets/forms/FormFieldSkinTooltip.scss
  source/renderer/app/components/widgets/forms/InlineEditingDropdown-tooltip.scss
  source/renderer/app/components/widgets/forms/InlineEditingDropdown.js
  source/renderer/app/components/widgets/forms/InlineEditingDropdown.scss
  source/renderer/app/config/stakingStakePools.dummy.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/themes/overrides/TooltipOverrides.scss
  source/renderer/app/themes/overrides/index.js
  storybook/stories/wallets/addWallet/Restore.stories.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext, chore

#2249 [DDW-426] Wrong transaction height when filtering
  CHANGELOG.md
  source/renderer/app/components/wallet/transactions/render-strategies/VirtualTransactionList.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2253 Merge release/2.5.0 into develop
  CHANGELOG.md
  package.json
Labels: chore, release-2.5.0

#2251 [DDW-455] Fix X Button Overlap in Stake Pools Search
  CHANGELOG.md
  source/renderer/app/components/staking/stake-pools/StakePoolsSearch.scss
Labels: :hourglass_flowing_sand:release-vNext, bug
