Repository input-output-hk/daedalus, pull requests merged in 2020-10, with the labels that each got.

#2192 Merge release/2.3.0-FC1 into develop
  CHANGELOG.md
  installer-clusters.cfg
  nix/sources.json
  package.json
  source/renderer/app/components/appUpdate/AppUpdateOverlay.js
  source/renderer/app/components/staking/widgets/ThumbSelectedPool.scss
  source/renderer/app/config/stakingConfig.js
Labels: :airplane: release-2.3.0-FC1, chore

#2194 Merge release/2.3.0-FC2 into develop
  CHANGELOG.md
  package.json
Labels: :airplane: release-2.3.0-FC2, chore

#2195 [DDW-405] Wait Daedalus to quit before launching app update
  CHANGELOG.md
  source/main/ipc/manageAppUpdateChannel.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2197 Merge release/2.3.0 into develop
  CHANGELOG.md
  package.json
Labels: chore, release-2.3.0

#2178 [DDW-337] Handle wallet migration leftovers
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/api/wallets/requests/transferFundsCalculateFee.js
  source/renderer/app/api/wallets/types.js
  source/renderer/app/components/wallet/transfer-funds/TransferFundsStep1Dialog.scss
  source/renderer/app/components/wallet/transfer-funds/TransferFundsStep2Dialog.js
  source/renderer/app/components/wallet/transfer-funds/TransferFundsStep2Dialog.scss
  source/renderer/app/containers/wallet/dialogs/transfer-funds/TransferFundsStep2Container.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/shelley-testnet.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/wallets/legacyWallets/TransferFunds.stories.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2198 [DDW-408] Fix cardanoexplorer.com domain to explorer.cardano.org
  CHANGELOG.md
  source/renderer/app/config/urlsConfig.js
  tests/paper-wallets/e2e/steps/paper-wallets-certificate.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2190 [DDW-354]: Dependency update
  .babelrc
  CHANGELOG.md
  package.json
  source/common/config/crypto/decrypt.js
  source/renderer/app/api/api.js
  source/renderer/app/components/wallet/transfer-funds/TransferFundsStep2Dialog.js
  source/renderer/app/containers/wallet/dialogs/transfer-funds/TransferFundsStep2Container.js
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/utils/crypto.js
  storybook/stories/wallets/paperWallets/PaperWallets.stories.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext, feature

#2200 Enable Saturation Indicator
  CHANGELOG.md
  README.md
  nix/sources.json
  source/main/environment.js
  source/renderer/app/components/staking/widgets/ThumbSelectedPool.scss
  source/renderer/app/config/stakingConfig.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2203 [DDW-402]: Fix stake pool tooltip height changing issue when hovering id
  CHANGELOG.md
  source/renderer/app/components/staking/widgets/TooltipPool.js
  source/renderer/app/components/staking/widgets/TooltipPool.scss
  source/renderer/app/themes/daedalus/shelley-testnet.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2191 [DDW-373] Syncing animation on wallet dropdown option not showing during redemption process
  CHANGELOG.md
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.scss
  source/renderer/app/components/staking/redeem-itn-rewards/NoWalletsDialog.scss
  source/renderer/app/components/staking/redeem-itn-rewards/Step1ConfigurationDialog.js
  source/renderer/app/components/staking/redeem-itn-rewards/Step1ConfigurationDialog.scss
  source/renderer/app/components/staking/redeem-itn-rewards/Step3FailureDialog.scss
  source/renderer/app/components/widgets/DialogFullSizeOverride.scss
  source/renderer/app/components/widgets/forms/WalletsDropdown.js
  source/renderer/app/components/widgets/forms/WalletsDropdownOption.js
  source/renderer/app/components/widgets/forms/WalletsDropdownOption.scss
  source/renderer/app/containers/staking/dialogs/redeem-itn-rewards/Step1ConfigurationContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: :hourglass_flowing_sand:release-vNext, chore

#2211 [DDW-421] Stake pool details explanation tooltips
  CHANGELOG.md
  source/renderer/app/components/appUpdate/AppUpdateOverlay.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.scss
  source/renderer/app/components/staking/redeem-itn-rewards/Step1ConfigurationDialog.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsRanking.js
  source/renderer/app/components/staking/widgets/ThumbPoolContent.scss
  source/renderer/app/components/staking/widgets/TooltipPool.js
  source/renderer/app/components/staking/widgets/TooltipPool.scss
  source/renderer/app/components/widgets/DialogFullSizeOverride.scss
  source/renderer/app/components/widgets/forms/WalletsDropdownOption.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: :hourglass_flowing_sand:release-vNext, feature

#2186 [DDW-16] Table view for stake pools
  CHANGELOG.md
  source/renderer/app/assets/images/grid-ic.inline.svg
  source/renderer/app/assets/images/list-ic.inline.svg
  source/renderer/app/components/staking/countdown/StakingCountdown.scss
  source/renderer/app/components/staking/delegation-center/DelegationCenterBody.scss
  source/renderer/app/components/staking/delegation-center/DelegationCenterHeader.scss
  source/renderer/app/components/staking/epochs/StakingEpochs.scss
  source/renderer/app/components/staking/info/StakingInfo.scss
  source/renderer/app/components/staking/layouts/StakingWithNavigation.scss
  source/renderer/app/components/staking/rewards/StakingRewards.scss
  source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.scss
  source/renderer/app/components/staking/stake-pools/StakePools.js
  source/renderer/app/components/staking/stake-pools/StakePools.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsRanking.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsSearch.js
  source/renderer/app/components/staking/stake-pools/StakePoolsSearch.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsTable.js
  source/renderer/app/components/staking/stake-pools/StakePoolsTable.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsTableBody.js
  source/renderer/app/components/staking/stake-pools/StakePoolsTableHeader.js
  source/renderer/app/components/staking/widgets/ThumbPool.js
  source/renderer/app/components/staking/widgets/ThumbPoolContent.js
  source/renderer/app/components/staking/widgets/TooltipPool.js
  source/renderer/app/components/staking/widgets/TooltipPool.scss
  source/renderer/app/components/widgets/BackToTopButton.js
  source/renderer/app/components/widgets/BackToTopButton.scss
  source/renderer/app/config/stakingConfig.js
  source/renderer/app/containers/staking/StakePoolsListPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/utils/domManipulation.js
  source/renderer/app/utils/formatters.js
  storybook/stories/staking/StakePoolsTable.stories.js
  storybook/stories/staking/Staking.stories.js
  storybook/stories/wallets/transactions/Utxo.stories.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2212 [DDW-420] Remove broken feature requests link
  CHANGELOG.md
  source/main/menus/osx.js
  source/main/menus/win-linux.js
  storybook/stories/wallets/transactions/Utxo.stories.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2214 [DDW-422]: Add tooltips to stake pools table view headers
  CHANGELOG.md
  source/renderer/app/components/staking/stake-pools/StakePoolsTable.js
  source/renderer/app/components/staking/stake-pools/StakePoolsTable.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsTableHeader.js
  source/renderer/app/components/staking/widgets/TooltipPool.scss
  source/renderer/app/components/widgets/BackToTopButton.js
  source/renderer/app/components/widgets/BackToTopButton.scss
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: :hourglass_flowing_sand:release-vNext, feature

#2213 [DDW-423] Respect number format on staking screens
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/components/staking/stake-pools/StakePoolsRanking.js
  source/renderer/app/components/staking/stake-pools/StakePoolsTable.js
  source/renderer/app/components/staking/stake-pools/StakePoolsTableBody.js
  source/renderer/app/components/staking/widgets/TooltipPool.js
  source/renderer/app/components/staking/widgets/TooltipPool.scss
  source/renderer/app/components/widgets/Slider.js
  source/renderer/app/domains/StakePool.js
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/utils/formatters.js
  storybook/stories/_support/StoryLayout.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2215 Fix "Stake pools" screen UI/UX issues
  CHANGELOG.md
  source/renderer/app/components/staking/stake-pools/StakePools.js
  source/renderer/app/components/staking/stake-pools/StakePools.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsList.js
  source/renderer/app/components/staking/stake-pools/StakePoolsRanking.js
  source/renderer/app/components/staking/stake-pools/StakePoolsSearch.js
  source/renderer/app/components/staking/stake-pools/StakePoolsSearch.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsTable.js
  source/renderer/app/components/staking/stake-pools/StakePoolsTable.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsTableBody.js
  source/renderer/app/components/staking/widgets/TooltipPool.js
  source/renderer/app/components/staking/widgets/TooltipPool.scss
  source/renderer/app/components/widgets/BackToTopButton.js
  source/renderer/app/components/widgets/BackToTopButton.scss
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/shelley-testnet.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/utils/formatters.js
  storybook/stories/staking/StakePoolsTable.stories.js
Labels: bug, release-2.4.0

#2217 Merge release/2.4.0 into develop
  CHANGELOG.md
  package.json
  source/main/menus/osx.js
  source/main/menus/win-linux.js
  source/renderer/app/api/api.js
  source/renderer/app/components/staking/stake-pools/StakePools.js
  source/renderer/app/components/staking/stake-pools/StakePools.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsList.js
  source/renderer/app/components/staking/stake-pools/StakePoolsRanking.js
  source/renderer/app/components/staking/stake-pools/StakePoolsSearch.js
  source/renderer/app/components/staking/stake-pools/StakePoolsSearch.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsTable.js
  source/renderer/app/components/staking/stake-pools/StakePoolsTable.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsTableBody.js
  source/renderer/app/components/staking/stake-pools/StakePoolsTableHeader.js
  source/renderer/app/components/staking/widgets/ThumbSelectedPool.js
  source/renderer/app/components/staking/widgets/ThumbSelectedPool.scss
  source/renderer/app/components/staking/widgets/TooltipPool.js
  source/renderer/app/components/staking/widgets/TooltipPool.scss
  source/renderer/app/components/widgets/BackToTopButton.js
  source/renderer/app/components/widgets/BackToTopButton.scss
  source/renderer/app/components/widgets/Slider.js
  source/renderer/app/domains/StakePool.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/shelley-testnet.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/utils/formatters.js
  storybook/stories/_support/StoryLayout.js
  storybook/stories/staking/StakePoolsTable.stories.js
  storybook/stories/wallets/transactions/Utxo.stories.js
Labels: chore, release-2.4.0

#2210 [DDW-291] Smart Tooltip MVP integration
  CHANGELOG.md
  package.json
  source/renderer/app/components/loading/syncing-connecting/StatusIcons-tooltip.scss
  source/renderer/app/components/loading/syncing-connecting/StatusIcons.js
  source/renderer/app/components/loading/syncing-connecting/StatusIcons.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsRanking.js
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseVerificationWidget.js
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseVerificationWidget.scss
  source/renderer/app/components/widgets/Slider.js
  source/renderer/app/themes/daedalus.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/shelley-testnet.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/overrides/PopOverOverrides.scss
  source/renderer/app/themes/overrides/index.js
  source/renderer/app/themes/utils/createTheme.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext, chore

#2219 [DDW-429] Fix missing space in error message
  CHANGELOG.md
  source/renderer/app/components/appUpdate/AppUpdateOverlay.js
  source/renderer/app/i18n/locales/defaultMessages.json
Labels: :hourglass_flowing_sand:release-vNext, bug

#2216 [DDW-418] Align vertically the newsfeed empty message
  CHANGELOG.md
  source/renderer/app/components/news/NewsFeed.scss
Labels: :hourglass_flowing_sand:release-vNext, bug

#2218 [DDW-376] Fix address validation on the Shelley QA and Staging networks
  CHANGELOG.md
  nix/sources.json
  source/common/types/cardano-node.types.js
  source/renderer/app/components/news/NewsFeed.scss
Labels: :hourglass_flowing_sand:release-vNext, bug

#2223 [DDW-291] Fix PopOver Themes
  CHANGELOG.md
  package.json
  source/renderer/app/components/loading/syncing-connecting/StatusIcons.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/shelley-testnet.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext, bug
