Repository input-output-hk/daedalus, pull requests merged in 2020-02, with the labels that each got.

#1838 Merge release/2.1.0-ITN1 into v2-integration
  CHANGELOG.md
  nix/sources.json
Labels: :hourglass_flowing_sand:release-vNext-ITN1, chore

#1831 [DDW-1187] - Download logs link underline color fix
  CHANGELOG.md
  source/renderer/app/components/loading/syncing-connecting/ReportIssue.scss
Labels: :hourglass_flowing_sand:release-vNext-ITN1, bug

#1835 [DDW-1075] Upgrade cucumber & setup new rerun feature
  CHANGELOG.md
  package.json
  tests/.gitignore
  tests/README.md
  tests/transactions/unit/steps/utxos-chart.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext-ITN1, chore

#1833 [DDW-1185] - Low disk space alert message not displayed for ITN
  CHANGELOG.md
  source/renderer/app/components/loading/no-disk-space-error/NoDiskSpaceError.scss
  source/renderer/app/components/loading/system-time-error/SystemTimeError.scss
  source/renderer/app/containers/loading/LoadingPage.js
Labels: :hourglass_flowing_sand:release-vNext-ITN1, bug

#1840 [DDW-1166] Delete unused locales and translation files
  CHANGELOG.md
  source/renderer/app/components/staking/epochs/helpers.js
  source/renderer/app/config/profileConfig.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/whitelist_de-DE.json
  source/renderer/app/i18n/locales/whitelist_hr-HR.json
  source/renderer/app/i18n/locales/whitelist_ko-KR.json
  source/renderer/app/i18n/locales/whitelist_zh-CN.json
  source/renderer/app/i18n/locales/zh-CN.json
  translations/translation-runner.js
Labels: :hourglass_flowing_sand:release-vNext-ITN1, chore

#1832 [DDW-1186] Stake pool descriptions is not fully shown if it is long enough
  CHANGELOG.md
  source/main/config.js
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.js
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.scss
  source/renderer/app/i18n/locales/defaultMessages.json
  storybook/stories/_support/config.js
Labels: :hourglass_flowing_sand:release-vNext-ITN1, bug

#1841 [DDW-1195] Stake pool tooltip update
  CHANGELOG.md
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: :hourglass_flowing_sand:release-vNext, feature

#1843 [DDW-1196] Improve PR review checklist
  .github/pull_request_template.md
  CHANGELOG.md
Labels: :hourglass_flowing_sand:release-vNext-ITN1, chore

#1845 [DDW-1197] Implement experimental data UI
  CHANGELOG.md
  source/renderer/app/assets/images/experiment-icon.inline.svg
  source/renderer/app/assets/images/experiment-icon.svg
  source/renderer/app/assets/images/testnet-bulb.inline.svg
  source/renderer/app/components/notifications/ExperimentalDataOverlay.js
  source/renderer/app/components/notifications/ExperimentalDataOverlay.scss
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip-experimental-tooltip.scss
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.js
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.scss
  source/renderer/app/containers/staking/Staking.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/staking/Staking.stories.js
  tests/stake-pools/e2e/features/stake-pools.feature
  tests/stake-pools/e2e/steps/stake-pools.js
Labels: :hourglass_flowing_sand:release-vNext-ITN1, feature

#1847 [DDW-1200] Handle delegation during wallet restoration
  CHANGELOG.md
  source/renderer/app/components/staking/delegation-center/WalletRow.js
  source/renderer/app/components/staking/delegation-center/WalletRow.scss
  source/renderer/app/components/staking/delegation-center/WalletRowTooltip.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.js
  source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.js
  source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.scss
  source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnetTooltip.scss
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/StakingStore.js
Labels: :hourglass_flowing_sand:release-vNext-ITN1, feature

#1850 [DDW-1204] Experimental data UI copy update
  CHANGELOG.md
  source/renderer/app/components/notifications/ExperimentalDataOverlay.js
  source/renderer/app/components/notifications/ExperimentalDataOverlay.scss
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: :hourglass_flowing_sand:release-vNext-ITN1, chore

#1855 Merge release/2.1.0-ITN1 into v2-integration
  CHANGELOG.md
  default.nix
  nix/sources.json
  source/renderer/app/api/api.js
  source/renderer/app/api/wallets/types.js
  source/renderer/app/assets/images/sand-clock.inline.svg
  source/renderer/app/components/staking/delegation-center/DelegationCenterBody.js
  source/renderer/app/components/staking/delegation-center/UndelegateConfirmationDialog.js
  source/renderer/app/components/staking/delegation-center/WalletRow.js
  source/renderer/app/components/staking/delegation-center/WalletRow.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.js
  source/renderer/app/components/staking/stake-pools/StakePoolThumbnail.scss
  source/renderer/app/components/widgets/forms/WalletsDropdown.js
  source/renderer/app/containers/staking/dialogs/UndelegateDialogContainer.js
  source/renderer/app/domains/Wallet.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: :hourglass_flowing_sand:release-vNext-ITN1, chore

#1815 [DDW-926] Transaction filtering
  CHANGELOG.md
  package.json
  source/renderer/app/actions/transactions-actions.js
  source/renderer/app/assets/images/filter-dis-ic.inline.svg
  source/renderer/app/components/wallet/transactions/FilterButton.js
  source/renderer/app/components/wallet/transactions/FilterButton.scss
  source/renderer/app/components/wallet/transactions/FilterDialog.js
  source/renderer/app/components/wallet/transactions/FilterDialog.scss
  source/renderer/app/components/wallet/transactions/FilterResultInfo.js
  source/renderer/app/components/wallet/transactions/FilterResultInfo.scss
  source/renderer/app/components/wallet/transactions/WalletNoTransactions.js
  source/renderer/app/components/wallet/transactions/WalletTransactionsList.js
  source/renderer/app/components/wallet/transactions/render-strategies/SimpleTransactionList.js
  source/renderer/app/components/wallet/transactions/render-strategies/VirtualTransactionList.js
  source/renderer/app/components/wallet/transactions/render-strategies/VirtualTransactionList.scss
  source/renderer/app/components/widgets/forms/TinyButton.js
  source/renderer/app/components/widgets/forms/TinyButton.scss
  source/renderer/app/components/widgets/forms/TinyCheckbox.js
  source/renderer/app/components/widgets/forms/TinyCheckbox.scss
  source/renderer/app/components/widgets/forms/TinyDatePicker.js
  source/renderer/app/components/widgets/forms/TinyDatePicker.scss
  source/renderer/app/components/widgets/forms/TinyInput.js
  source/renderer/app/components/widgets/forms/TinyInput.scss
  source/renderer/app/components/widgets/forms/TinySelect.js
  source/renderer/app/components/widgets/forms/TinySelect.scss
  source/renderer/app/containers/wallet/WalletTransactionsPage.js
  source/renderer/app/containers/wallet/dialogs/FilterDialogContainer.js
  source/renderer/app/i18n/global-messages.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/index.js
  source/renderer/app/stores/TransactionsStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/index.global.scss
  source/renderer/app/themes/utils/createTheme.js
  source/renderer/app/types/injectedPropsType.js
  source/renderer/app/utils/transaction.js
  source/renderer/webpack.config.js
  storybook/stories/wallets/transactions/TransactionsListWithFilter.stories.js
  storybook/stories/wallets/transactions/WalletTransactions.stories.js
  storybook/webpack.config.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext-ITN1, feature

#1814 [DDW-1148] Implement acceptance tests for wallet delegation
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/components/staking/delegation-center/DelegationCenter.js
  source/renderer/app/containers/staking/DelegationCenterPage.js
  source/renderer/app/containers/staking/StakePoolsListPage.js
  storybook/stories/staking/DelegationCenter.stories.js
  tests/decentralization/e2e/steps/delegation.js
  tests/decentralization/e2e/steps/helpers.js
  tests/news/e2e/steps/newsfeed-steps.js
  tests/wallets/e2e/features/wallet-delegation.feature
  tests/wallets/e2e/steps/helpers.js
  tests/wallets/e2e/steps/wallets.js
  utils/v2-api-importer/legacy.js
Labels: :hourglass_flowing_sand:release-vNext-ITN1, feature

#1856 [DDW-1206] Fix pending delegation preferences handling
  CHANGELOG.md
  nix/sources.json
  source/renderer/app/api/api.js
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/api/wallets/types.js
  source/renderer/app/components/staking/delegation-center/DelegationCenterBody.js
  source/renderer/app/components/staking/delegation-center/WalletRow.js
  source/renderer/app/components/staking/delegation-center/WalletRow.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.js
  source/renderer/app/components/wallet/transactions/FilterDialog.scss
  source/renderer/app/components/widgets/forms/WalletsDropdown.js
  source/renderer/app/domains/Wallet.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/index.global.scss
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/staking/DelegationCenter.stories.js
  tests/decentralization/e2e/steps/helpers.js
  tests/delegation/e2e/features/delegation-pending.feature
  tests/delegation/e2e/features/delegation.feature
  tests/delegation/e2e/features/stake-pools.feature
  tests/delegation/e2e/steps/delegation-pending.js
  tests/delegation/e2e/steps/delegation.js
  tests/delegation/e2e/steps/helpers.js
  tests/delegation/e2e/steps/stake-pools.js
  tests/stake-pools/e2e/steps/helpers.js
  tests/wallets/e2e/features/restore-wallet/restore-daedalus-wallet.feature
Labels: bug, release-2.2.0-ITN1

#1857 [DEVOPS] Add block 0
  CHANGELOG.md
  default.nix
  installers/common/MacInstaller.hs
  installers/common/Types.hs
  installers/common/WindowsInstaller.hs
  installers/nix/linux.nix
  nix/launcher-config.nix
  nix/sources.json
  scripts/build-installer-unix.sh
  source/main/cardano/CardanoNode.js
  source/main/cardano/CardanoWalletLauncher.js
  source/main/cardano/setupCardanoNodeMode.js
  source/main/config.js
Labels: feature, release-2.2.0-ITN1

#1859 Merge release/2.2.0-ITN1 into v2-integration
  CHANGELOG.md
  nix/sources.json
  package.json
  source/renderer/app/api/api.js
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/api/wallets/types.js
  source/renderer/app/components/staking/delegation-center/DelegationCenterBody.js
  source/renderer/app/components/staking/delegation-center/WalletRow.js
  source/renderer/app/components/staking/delegation-center/WalletRow.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.js
  source/renderer/app/components/wallet/transactions/FilterDialog.scss
  source/renderer/app/components/widgets/forms/WalletsDropdown.js
  source/renderer/app/domains/Wallet.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/index.global.scss
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/staking/DelegationCenter.stories.js
  tests/decentralization/e2e/steps/helpers.js
  tests/delegation/e2e/features/delegation-pending.feature
  tests/delegation/e2e/features/delegation.feature
  tests/delegation/e2e/features/stake-pools.feature
  tests/delegation/e2e/steps/delegation-pending.js
  tests/delegation/e2e/steps/delegation.js
  tests/delegation/e2e/steps/helpers.js
  tests/delegation/e2e/steps/stake-pools.js
  tests/stake-pools/e2e/steps/helpers.js
  tests/wallets/e2e/features/restore-wallet/restore-daedalus-wallet.feature
Labels: chore, release-2.2.0-ITN1

#1849 [DDW-1163] Write unit tests for scrambling and unscrambling mnemonics
  CHANGELOG.md
  source/renderer/app/utils/crypto.js
  tests/wallets/unit/features/scrambling-and-unscrambling-mnemonics.feature
  tests/wallets/unit/steps/mnemonics.js
Labels: :hourglass_flowing_sand:release-vNext-ITN1, chore

#1862 [DDW-1210] Error is shown trying to delegate to the same wallet
  CHANGELOG.md
  default.nix
  nix/jormungandr-bridge.nix
  nix/sources.json
Labels: bug, chore, release-2.2.0-ITN1

#1863 [DDW-1175] Storybook - Decentralization Countdown
  CHANGELOG.md
  storybook/stories/staking/DelegationCenter.stories.js
  storybook/stories/staking/Staking.stories.js
Labels: :hourglass_flowing_sand:release-vNext-ITN1, bug

#1869 Merge release/2.2.0-ITN1 into v2-integration
  CHANGELOG.md
  default.nix
  nix/jormungandr-bridge.nix
  nix/sources.json
Labels: :hourglass_flowing_sand:release-vNext-ITN1, chore

#1861 [DDW-1151] Implement acceptance tests for "Rewards" screen
  CHANGELOG.md
  source/renderer/app/actions/staking-actions.js
  source/renderer/app/api/staking/types.js
  source/renderer/app/containers/staking/StakingRewardsPage.js
  source/renderer/app/stores/StakingStore.js
  tests/delegation/e2e/documents/.gitkeep
  tests/delegation/e2e/features/rewards.feature
  tests/delegation/e2e/steps/rewards.js
  tests/delegation/e2e/steps/stake-pools.js
  tests/setup-e2e.js
Labels: :hourglass_flowing_sand:release-vNext-ITN1, chore

#1864 [DDW-849] Update stylelint and stylelint-order dependencies
  CHANGELOG.md
  package.json
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext-ITN1, chore, dependencies

#1865 [DDW-851] Update Husky dependency
  CHANGELOG.md
  package.json
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext-ITN1, chore, dependencies

#1867 [DDW-857]: Update test environment dependencies
  CHANGELOG.md
  package.json
  tests/delegation/e2e/steps/rewards.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext-ITN1, chore, dependencies
