Repository input-output-hk/daedalus, pull requests merged in 2020-05, with the labels that each got.

#1978 [DDW-152] Cover all Api error messages with automated tests
  CHANGELOG.md
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/containers/wallet/dialogs/settings/DeleteWalletDialogContainer.js
  source/renderer/app/stores/WalletSettingsStore.js
  source/renderer/app/stores/WalletsStore.js
  tests/addresses/e2e/features/receive-money.feature
  tests/addresses/e2e/steps/addresses.js
  tests/common/e2e/steps/helpers.js
  tests/delegation/e2e/features/delegation.feature
  tests/delegation/e2e/steps/delegation-pending.js
  tests/delegation/e2e/steps/delegation.js
  tests/delegation/e2e/steps/helpers.js
  tests/delegation/e2e/steps/rewards.js
  tests/delegation/e2e/steps/stake-pools.js
  tests/navigation/e2e/steps/helpers.js
  tests/news/e2e/features/newsfeed.feature
  tests/news/e2e/steps/newsfeed-steps.js
  tests/nodes/e2e/features/local-time-difference.feature
  tests/nodes/e2e/features/trouble-connecting-notification.feature
  tests/nodes/e2e/features/trouble-syncing-notification.feature
  tests/nodes/e2e/features/wallet-settings-recovery-phrase-verification.feature
  tests/nodes/e2e/steps/app-version-difference.js
  tests/nodes/e2e/steps/daedalus-process.js
  tests/nodes/e2e/steps/helpers.js
  tests/nodes/e2e/steps/local-time-difference.js
  tests/nodes/e2e/steps/node-update-notification.js
  tests/nodes/e2e/steps/trouble-connecting-notification.js
  tests/nodes/e2e/steps/trouble-syncing-notification.js
  tests/nodes/e2e/steps/wallet-recovery-phrase-verification-steps.js
  tests/reporter.js
  tests/settings/e2e/features/wallet-settings.feature
  tests/settings/e2e/steps/custom-formats.js
  tests/settings/e2e/steps/helpers.js
  tests/settings/e2e/steps/settings.js
  tests/setup-e2e.js
  tests/transactions/e2e/features/send-money-to-receiver.feature
  tests/transactions/e2e/steps/transactions.js
  tests/wallets/e2e/features/restore-wallet/restore-daedalus-wallet.feature
  tests/wallets/e2e/features/restore-wallet/restore-yoroi-wallet.feature
  tests/wallets/e2e/features/transfer-funds-wizard.feature
  tests/wallets/e2e/steps/helpers.js
  tests/wallets/e2e/steps/import-wallet.js
  tests/wallets/e2e/steps/restore-wallet.js
  tests/wallets/e2e/steps/transfer-funds-wizard.js
  tests/wallets/e2e/steps/wallet-not-responding.js
  tests/wallets/e2e/steps/wallets-limit.js
  tests/wallets/e2e/steps/wallets.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2006 [DDW-170] Bump Daedalus version
  CHANGELOG.md
  package.json
Labels: :hourglass_flowing_sand:release-vNext, chore

#2009 [DDW-194] Fix system locale detection
  CHANGELOG.md
  source/common/ipc/api.js
  source/common/types/locales.types.js
  source/main/index.js
  source/main/ipc/detect-system-locale.js
  source/main/ipc/getSystemLocaleChannel.js
  source/main/utils/detectSystemLocale.js
  source/renderer/app/ipc/detect-system-locale.js
  source/renderer/app/ipc/getSystemLocaleChannel.js
  source/renderer/app/stores/ProfileStore.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#1998 [DDW-173] - Button should be disabled when there is nothing to submit
  CHANGELOG.md
  source/renderer/app/components/wallet/WalletCreateDialog.js
  source/renderer/app/components/wallet/receive/WalletReceiveRandom.js
  source/renderer/app/components/wallet/settings/ChangeSpendingPasswordDialog.js
  source/renderer/app/components/wallet/wallet-restore/ConfigurationDialog.js
  source/renderer/app/components/wallet/wallet-restore/MnemonicsDialog.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2010 [DDW-173] Fix failing tests
  CHANGELOG.md
  tests/settings/e2e/features/wallet-settings.feature
  tests/settings/e2e/steps/settings.js
  tests/wallets/e2e/steps/create-wallet.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2011 [DDW-154] Implement automated tests for wallet migration and import features
  CHANGELOG.md
  source/renderer/app/components/wallet/wallet-import/WalletSelectImportDialog.js
  source/renderer/app/stores/WalletMigrationStore.js
  tests/nodes/e2e/steps/daedalus-process.js
  tests/wallets/e2e/documents/import-files/Secrets-1.0/.DS_Store
  tests/wallets/e2e/documents/import-files/Secrets-1.0/secret.key
  tests/wallets/e2e/documents/import-files/Secrets-1.0/wrong-secret.key
  tests/wallets/e2e/documents/import-files/Wallet-1.0-acid/-acid/checkpoints-0000000000.log
  tests/wallets/e2e/documents/import-files/Wallet-1.0-acid/-acid/checkpoints-0000000001.log
  tests/wallets/e2e/documents/import-files/Wallet-1.0-acid/-acid/checkpoints.version
  tests/wallets/e2e/documents/import-files/Wallet-1.0-acid/-acid/events-0000000000.log
  tests/wallets/e2e/documents/import-files/Wallet-1.0-acid/-acid/events.version
  tests/wallets/e2e/documents/import-files/Wallet-1.0-acid/-acid/open.lock
  tests/wallets/e2e/documents/import-files/Wallet-1.0-acid/-sqlite.sqlite3
  tests/wallets/e2e/documents/import-files/Wallet-1.0-acid/.DS_Store
  tests/wallets/e2e/documents/import-files/Wallet-1.0-acid/Archive/archive_2020-04-23T17_59_40.tar.gz
  tests/wallets/e2e/documents/import-files/Wallet-1.0-acid/Archive/archive_2020-04-24T13_22_09.tar.gz
  tests/wallets/e2e/documents/import-files/Wallet-1.0-acid/Archive/checkpoints-0000000173.log
  tests/wallets/e2e/documents/import-files/Wallet-1.0-acid/Archive/events-0000418460.log
  tests/wallets/e2e/documents/import-files/Wallet-1.0-acid/checkpoints-0000000174.log
  tests/wallets/e2e/documents/import-files/Wallet-1.0-acid/checkpoints-0000000175.log
  tests/wallets/e2e/documents/import-files/Wallet-1.0-acid/checkpoints.version
  tests/wallets/e2e/documents/import-files/Wallet-1.0-acid/events-0000419306.log
  tests/wallets/e2e/documents/import-files/Wallet-1.0-acid/events.version
  tests/wallets/e2e/documents/import-files/Wallet-1.0-acid/open.lock
  tests/wallets/e2e/features/import-and-migrate-wallets.feature
  tests/wallets/e2e/features/import-wallet.feature
  tests/wallets/e2e/steps/import-and-migrate-wallets.js
  tests/wallets/e2e/steps/import-wallet.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2012 [DDW-166] Prevent importing more than maximum number of wallets
  CHANGELOG.md
  source/renderer/app/components/wallet/wallet-import/WalletSelectImportDialog.js
  source/renderer/app/components/wallet/wallet-import/WalletSelectImportDialog.scss
  source/renderer/app/containers/wallet/dialogs/WalletImportDialogContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  storybook/stories/wallets/import/WalletImportFile.stories.js
  tests/wallets/e2e/features/import-and-migrate-wallets.feature
  tests/wallets/e2e/steps/import-and-migrate-wallets.js
  tests/wallets/e2e/steps/wallets-limit.js
  tests/wallets/e2e/steps/wallets.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2015 [DDW-192] Bump Daedalus version
  CHANGELOG.md
  package.json
Labels: :hourglass_flowing_sand:release-vNext, chore

#2008 Enable the Recovery Phrase Verification feature on ITN
  CHANGELOG.md
  source/main/locales/ja-JP.json
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.js
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseVerificationWidget.js
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseVerificationWidget.scss
  source/renderer/app/components/wallet/settings/WalletSettings.js
  source/renderer/app/containers/wallet/WalletSettingsPage.js
  source/renderer/app/containers/wallet/dialogs/WalletImportDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/settings/WalletRecoveryPhraseContainer.js
  source/renderer/app/domains/Wallet.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/utils/numbers.js
  source/renderer/app/utils/rangeMap.js
  storybook/stories/wallets/_utils/defaultWalletProps.js
  storybook/stories/wallets/settings/WalletRecoveryPhraseVerification.stories.js
  storybook/stories/wallets/settings/WalletSettingsScreen.stories.js
  tests/nodes/e2e/features/wallet-settings-recovery-phrase-verification.feature
  tests/wallets/e2e/features/recovery-phrase-verification.feature
  tests/wallets/e2e/steps/helpers.js
  tests/wallets/e2e/steps/recovery-phrase-verification-steps.js
  tests/wallets/e2e/steps/wallets.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2003 [DDW-167] Consolidate Japanese translations
  CHANGELOG.md
  source/main/locales/en-US.json
  source/main/locales/ja-JP.json
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/i18n/locales/babeledit-project.babel
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: :hourglass_flowing_sand:release-vNext, chore

#2017 Merge release/1.1.0 into develop
  CHANGELOG.md
  package.json
Labels: chore, release-1.1.0

#2018 Bumps Daedalus version to 1.2.0-FC1
  CHANGELOG.md
  package.json
Labels: :airplane: release-1.2.0-FC1, chore

#2014 [DDW-174] Improve wallet import dialogs
  CHANGELOG.md
  source/renderer/app/actions/wallet-migration-actions.js
  source/renderer/app/components/wallet/WalletAdd.js
  source/renderer/app/components/wallet/wallet-import/WalletImportFileDialog.js
  source/renderer/app/components/wallet/wallet-import/WalletImportFileDialog.scss
  source/renderer/app/components/wallet/wallet-import/WalletSelectImportDialog.js
  source/renderer/app/components/wallet/wallet-import/WalletSelectImportDialog.scss
  source/renderer/app/components/widgets/Dialog.js
  source/renderer/app/components/widgets/DialogOverride.scss
  source/renderer/app/components/widgets/forms/InlineEditingSmallInput.js
  source/renderer/app/config/walletRestoreConfig.js
  source/renderer/app/containers/wallet/WalletAddPage.js
  source/renderer/app/containers/wallet/dialogs/WalletFileImportDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/WalletImportDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/wallet-import/WalletFileImportStepContainer.js
  source/renderer/app/containers/wallet/dialogs/wallet-import/WalletSelectImportStepContainer.js
  source/renderer/app/stores/WalletMigrationStore.js
  source/renderer/app/types/walletRestoreTypes.js
  storybook/stories/wallets/addWallet/Add.stories.js
  storybook/stories/wallets/import/WalletImportFile.stories.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2016 [DDW-131] Connecting a hardware wallet
  CHANGELOG.md
  source/renderer/app/Routes.js
  source/renderer/app/actions/sidebar-actions.js
  source/renderer/app/assets/images/hardware-wallet/check.inline.svg
  source/renderer/app/assets/images/hardware-wallet/close-cross-red.inline.svg
  source/renderer/app/assets/images/hardware-wallet/disconnected.inline.svg
  source/renderer/app/assets/images/hardware-wallet/export.inline.svg
  source/renderer/app/assets/images/hardware-wallet/ledger-bold-ic.inline.svg
  source/renderer/app/assets/images/hardware-wallet/ledger-cropped.inline.svg
  source/renderer/app/assets/images/hardware-wallet/ledger-x-cropped-outlines.inline.svg
  source/renderer/app/assets/images/hardware-wallet/trezor-ledger.inline.svg
  source/renderer/app/assets/images/sidebar/hardware-wallet-ic.inline.svg
  source/renderer/app/components/hardware-wallet/layouts/HardwareWalletWithNavigation.js
  source/renderer/app/components/hardware-wallet/layouts/HardwareWalletWithNavigation.scss
  source/renderer/app/components/hardware-wallet/navigation/HardwareWalletNavigation.js
  source/renderer/app/components/hardware-wallet/settings/ConnectHardwareWallet.js
  source/renderer/app/components/hardware-wallet/settings/ConnectHardwareWallet.scss
  source/renderer/app/components/sidebar/Sidebar.js
  source/renderer/app/components/sidebar/SidebarCategory.scss
  source/renderer/app/components/sidebar/wallets/SidebarWalletMenuItem.js
  source/renderer/app/components/sidebar/wallets/SidebarWalletMenuItem.scss
  source/renderer/app/components/sidebar/wallets/SidebarWalletsMenu.js
  source/renderer/app/components/wallet/wallet-import/WalletSelectImportDialog.js
  source/renderer/app/config/sidebarConfig.js
  source/renderer/app/containers/MainLayout.js
  source/renderer/app/containers/Root.js
  source/renderer/app/containers/hardware-wallet/HardwareWallet.js
  source/renderer/app/domains/Wallet.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/routes-config.js
  source/renderer/app/stores/SidebarStore.js
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  source/renderer/app/types/sidebarTypes.js
  storybook/stories/_support/StoryLayout.js
  storybook/stories/navigation/Sidebar.stories.js
  storybook/stories/wallets/_utils/HardwareWalletWithNavigationLayout.js
  storybook/stories/wallets/_utils/HardwareWalletsWrapper.js
  storybook/stories/wallets/hardwareWallets/HardwareWallets.stories.js
  storybook/stories/wallets/index.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2021 [DDW-247] Update transaction fee estimation Api endpoint implementation
  CHANGELOG.md
  nix/sources.json
  source/renderer/app/api/api.js
  source/renderer/app/api/transactions/types.js
  source/renderer/app/components/sidebar/Sidebar.js
  source/renderer/app/config/sidebarConfig.js
  source/renderer/app/containers/MainLayout.js
  source/renderer/app/stores/SidebarStore.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2022 [DDW-247] Update transaction fee estimation Api endpoint implementation
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/api/staking/requests/getDelegationFee.js
  source/renderer/app/api/staking/types.js
  source/renderer/app/components/sidebar/Sidebar.js
  source/renderer/app/routes-config.js
Labels: :hourglass_flowing_sand:release-vNext, chore
