Repository input-output-hk/daedalus, pull requests merged in 2020-08, with the labels that each got.

#2125 [DDW-333] Fix text copy on the "Delegation center" screen
  CHANGELOG.md
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: :hourglass_flowing_sand:release-vNext, bug

#2124 [DDW-322] Fix Daedalus logo animation
  CHANGELOG.md
  source/renderer/app/components/loading/syncing-connecting/LogosDisplay.scss
  source/renderer/app/components/widgets/splash/Splash.scss
Labels: :hourglass_flowing_sand:release-vNext, bug

#2126 [DDW-336] Disabled wallet creation before the Shelley HF
  CHANGELOG.md
  source/renderer/app/components/wallet/WalletAdd.js
  source/renderer/app/containers/wallet/WalletAddPage.js
  storybook/stories/wallets/addWallet/Add.stories.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2119 [DDW-331] Update API request breaking changes
  CHANGELOG.md
  nix/sources.json
  source/renderer/app/api/transactions/requests/createTransaction.js
  source/renderer/app/api/transactions/requests/getTransactionFee.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2111 [DDW-330] Fix wallet delegation minimum Balance logic
  CHANGELOG.md
  installer-clusters.cfg
  package.json
  source/renderer/app/api/api.js
  source/renderer/app/api/transactions/requests/createTransaction.js
  source/renderer/app/api/transactions/requests/getTransactionFee.js
  source/renderer/app/api/transactions/types.js
  source/renderer/app/components/loading/syncing-connecting/SyncingConnecting.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.js
  source/renderer/app/components/wallet/wallet-restore/WalletTypeDialog.js
  source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
  source/renderer/app/domains/WalletTransaction.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: :hourglass_flowing_sand:release-vNext, bug

#2133 [DDW-344] Integrate Rewards redemption API endpoint
  CHANGELOG.md
  nix/sources.json
  source/renderer/app/api/api.js
  source/renderer/app/api/staking/requests/submitRedeemItnRewards.js
  source/renderer/app/api/staking/types.js
  source/renderer/app/api/transactions/types.js
  source/renderer/app/components/staking/redeem-itn-rewards/LoadingOverlay.js
  source/renderer/app/components/staking/redeem-itn-rewards/LoadingOverlay.scss
  source/renderer/app/components/staking/redeem-itn-rewards/NoWalletsDialog.js
  source/renderer/app/components/staking/redeem-itn-rewards/RedeemDialogOverride.scss
  source/renderer/app/components/staking/redeem-itn-rewards/Step1ConfigurationDialog.js
  source/renderer/app/components/staking/redeem-itn-rewards/Step1ConfigurationDialog.scss
  source/renderer/app/components/staking/redeem-itn-rewards/Step2ConfirmationDialog.js
  source/renderer/app/components/staking/redeem-itn-rewards/Step2ConfirmationDialog.scss
  source/renderer/app/components/staking/redeem-itn-rewards/Step3FailureDialog.js
  source/renderer/app/components/staking/redeem-itn-rewards/Step3FailureDialog.scss
  source/renderer/app/components/staking/redeem-itn-rewards/Step3SuccessDialog.js
  source/renderer/app/components/staking/redeem-itn-rewards/Step3SuccessDialog.scss
  source/renderer/app/components/widgets/Dialog.js
  source/renderer/app/components/widgets/DialogFullSizeOverride.scss
  source/renderer/app/config/stakingConfig.js
  source/renderer/app/containers/staking/RedeemItnRewardsContainer.js
  source/renderer/app/containers/staking/dialogs/redeem-itn-rewards/Step1ConfigurationContainer.js
  source/renderer/app/containers/staking/dialogs/redeem-itn-rewards/Step2ConfirmationContainer.js
  source/renderer/app/containers/staking/dialogs/redeem-itn-rewards/Step3ResultContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/SidebarStore.js
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/shelley-testnet.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  source/renderer/app/utils/formatters.js
  storybook/stories/staking/RedeemItnWallets.stories.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2131 [DDW-343] Stake pool search performance fix
  package.json
  release-build.nix
  source/common/utils/logging.js
  source/main/utils/setupLogging.js
  source/renderer/app/api/transactions/types.js
  source/renderer/app/components/staking/stake-pools/StakePoolsList.js
  source/renderer/app/components/staking/stake-pools/StakePoolsList.scss
  yarn.lock
Labels: WIP, bug

#2138 [DDW-345] Fix ada redemption styling issues
  CHANGELOG.md
  nix/sources.json
  package.json
  source/renderer/app/components/wallet/wallet-restore/WalletTypeDialog.js
  source/renderer/app/components/widgets/DialogFullSizeOverride.scss
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/themes/daedalus/dark-cardano.js
  yarn.lock
Labels: WIP, bug

#2136 fix yarn.lock
  yarn.lock
Labels: DO NOT MERGE

#2140 [DDW-346] Fix Ada Redemption styling issues - Part 2
  source/renderer/app/components/staking/redeem-itn-rewards/NoWalletsDialog.scss
  source/renderer/app/components/staking/redeem-itn-rewards/Step2ConfirmationDialog.scss
  source/renderer/app/components/staking/redeem-itn-rewards/Step3FailureDialog.scss
  source/renderer/app/components/staking/redeem-itn-rewards/Step3SuccessDialog.scss
  source/renderer/app/components/widgets/DialogFullSizeOverride.scss
Labels: WIP, bug, release-2.1.0

#2141 [DDW-347] Fix Rewards Redemption API response handling
  source/renderer/app/api/api.js
Labels: WIP, bug, release-2.1.0

#2142 Merge release/2.1.0 into develop
  CHANGELOG.md
  nix/sources.json
  source/renderer/app/api/api.js
  source/renderer/app/components/staking/redeem-itn-rewards/NoWalletsDialog.scss
  source/renderer/app/components/staking/redeem-itn-rewards/Step2ConfirmationDialog.scss
  source/renderer/app/components/staking/redeem-itn-rewards/Step3FailureDialog.scss
  source/renderer/app/components/staking/redeem-itn-rewards/Step3SuccessDialog.scss
  source/renderer/app/components/widgets/DialogFullSizeOverride.scss
Labels: chore, release-2.1.0

#2143 [DDW-338] Update cardano-launcher and set up SMASH
  CHANGELOG.md
  nix/launcher-config.nix
  nix/sources.json
  package.json
  source/main/config.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext, chore

#2146 [DDW-349] Disabled ITN redemption before being synced
  CHANGELOG.md
  source/renderer/app/components/staking/redeem-itn-rewards/RedemptionUnavailableDialog.js
  source/renderer/app/components/staking/redeem-itn-rewards/RedemptionUnavailableDialog.scss
  source/renderer/app/components/staking/redeem-itn-rewards/Step1ConfigurationDialog.scss
  source/renderer/app/containers/staking/RedeemItnRewardsContainer.js
  source/renderer/app/containers/staking/dialogs/redeem-itn-rewards/RedemptionUnavailableContainer.js
  source/renderer/app/containers/wallet/dialogs/WalletTransferFundsContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  storybook/stories/staking/RedeemItnWallets.stories.js
  storybook/stories/staking/Staking.stories.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2147 [DDW-350] Fix Japanese translation for Byron wallets
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/components/notifications/LegacyNotification.js
  source/renderer/app/config/walletNavigationConfig.js
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/utils/validations.js
Labels: :hourglass_flowing_sand:release-vNext, bug, feature

#2144 [DDW-335]: Fix double loading spinner on stake pools list page
  CHANGELOG.md
  source/renderer/app/components/wallet/wallet-restore/WalletTypeDialog.js
  source/renderer/app/containers/staking/StakePoolsListPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: :hourglass_flowing_sand:release-vNext, bug

#2150 [DDW-341] Fix display priority of shutdown sequence status messages
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/components/loading/syncing-connecting/SyncingConnectingStatus.js
  source/renderer/app/components/wallet/WalletAdd.js
  source/renderer/app/components/wallet/WalletBackupDialog.js
  source/renderer/app/components/wallet/WalletCreateDialog.js
  source/renderer/app/components/wallet/backup-recovery/WalletBackupPrivacyWarningDialog.js
  source/renderer/app/components/wallet/backup-recovery/WalletRecoveryPhraseDisplayDialog.js
  source/renderer/app/components/wallet/backup-recovery/WalletRecoveryPhraseEntryDialog.js
  source/renderer/app/components/wallet/wallet-restore/WalletTypeDialog.js
  source/renderer/app/containers/wallet/WalletAddPage.js
  source/renderer/app/containers/wallet/dialogs/WalletBackupDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/wallet-restore/StepWalletTypeContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/WalletsStore.js
  storybook/stories/wallets/addWallet/Add.stories.js
  storybook/stories/wallets/addWallet/Restore.stories.js
  tests/wallets/e2e/steps/helpers.js
Labels: :hourglass_flowing_sand:release-vNext, bug, feature

#2153 [DDW-320] Text copy fixes
  CHANGELOG.md
  source/renderer/app/components/staking/delegation-center/DelegationCenterNoWallets.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsNotAvailableDialog.js
  source/renderer/app/components/wallet/transfer-funds/TransferFundsStep1Dialog.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: :hourglass_flowing_sand:release-vNext, bug

#2151 [DDW-317] Handle random stake pool data during the first shelley epochs
  CHANGELOG.md
  source/renderer/app/assets/images/no-data-dash-big.inline.svg
  source/renderer/app/assets/images/no-data-dash-small.inline.svg
  source/renderer/app/assets/images/sand-clock-big.inline.svg
  source/renderer/app/assets/images/sand-clock-small.inline.svg
  source/renderer/app/components/staking/stake-pools/StakePools.js
  source/renderer/app/components/staking/stake-pools/StakePoolsRanking.js
  source/renderer/app/components/staking/widgets/ThumbPool.scss
  source/renderer/app/components/staking/widgets/ThumbPoolContent.js
  source/renderer/app/components/staking/widgets/ThumbPoolContent.scss
  source/renderer/app/components/staking/widgets/ThumbSelectedPool.js
  source/renderer/app/components/staking/widgets/ThumbSelectedPool.scss
  source/renderer/app/components/staking/widgets/TooltipPool.js
  source/renderer/app/components/staking/widgets/TooltipPool.scss
  source/renderer/app/config/stakingConfig.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/shelley-testnet.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2155 [DDW-356] Bump Daedalus version and cardano-wallet revision
  CHANGELOG.md
  default.nix
  installers/Installer.hs
  installers/README.md
  installers/Spec.hs
  installers/common/AppVeyor.hs
  installers/common/Config.hs
  installers/common/MacInstaller.hs
  installers/common/Types.hs
  installers/common/Util.hs
  installers/common/WindowsInstaller.hs
  installers/daedalus-installer.cabal
  nix/launcher-config.nix
  nix/sources.json
  package.json
  scripts/build-installer-unix.sh
  scripts/build-installer-win64.bat
  shell.nix
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext, chore

#2157 Cardano-wallet bump
  CHANGELOG.md
  nix/sources.json
  source/renderer/app/config/stakingConfig.js
  source/renderer/app/containers/staking/StakePoolsListPage.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2128 [DDW-262] Tooltip promoting password managers
  source/renderer/app/components/staking/stake-pools/StakePoolsRanking.scss
  source/renderer/app/components/staking/widgets/ThumbSelectedPool.scss
  source/renderer/app/components/staking/widgets/TooltipPool.scss
  source/renderer/app/components/wallet/WalletCreateDialog.js
  source/renderer/app/components/wallet/WalletCreateDialog.scss
  source/renderer/app/components/wallet/WalletRestoreDialog.js
  source/renderer/app/components/wallet/WalletRestoreDialog.scss
  source/renderer/app/components/wallet/settings/ChangeSpendingPasswordDialog.js
  source/renderer/app/components/wallet/settings/ChangeSpendingPasswordDialog.scss
  source/renderer/app/components/wallet/wallet-restore/ConfigurationDialog.js
  source/renderer/app/components/wallet/wallet-restore/ConfigurationDialog.scss
  source/renderer/app/containers/wallet/dialogs/WalletCreateDialogContainerOld.js
  source/renderer/app/containers/wallet/dialogs/settings/ChangeSpendingPasswordDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/wallet-restore/StepConfigurationContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  storybook/stories/wallets/_utils/defaultWalletProps.js
  storybook/stories/wallets/addWallet/Restore.stories.js
  storybook/stories/wallets/setPassword/SetWalletPassword.stories.js
  storybook/stories/wallets/settings/WalletSettingsScreen.stories.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2167 [DDW-371] Update team on about screen
  CHANGELOG.md
  source/renderer/app/components/static/About.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: :hourglass_flowing_sand:release-vNext, chore

#2173 Merge release/2.2.0 into develop
  nix/sources.json
  source/main/environment.js
  source/renderer/app/components/wallet/WalletCreateDialog.js
  source/renderer/app/components/wallet/WalletCreateDialog.scss
  source/renderer/app/components/wallet/WalletRestoreDialog.js
  source/renderer/app/components/wallet/WalletRestoreDialog.scss
  source/renderer/app/components/wallet/settings/ChangeSpendingPasswordDialog.js
  source/renderer/app/components/wallet/settings/ChangeSpendingPasswordDialog.scss
  source/renderer/app/components/wallet/wallet-restore/ConfigurationDialog.js
  source/renderer/app/components/wallet/wallet-restore/ConfigurationDialog.scss
Labels: chore, release-2.2.0
