Repository input-output-hk/daedalus, pull requests merged in 2020-09, with the labels that each got.

#2168 [DDW-370] Remove wallet balance while syncing
  source/renderer/app/components/layout/TopBar.js
  source/renderer/app/components/sidebar/wallets/SidebarWalletMenuItem.js
  source/renderer/app/components/staking/delegation-center/WalletRow.js
  source/renderer/app/components/staking/rewards/StakingRewards.js
  source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.js
  source/renderer/app/components/wallet/summary/WalletSummary.js
  source/renderer/app/components/widgets/forms/WalletsDropdown.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2176 [DDW-339] Correct order of receiving addresses
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/components/wallet/backup-recovery/WalletRecoveryPhraseEntryDialog.scss
Labels: :hourglass_flowing_sand:release-vNext, chore

#2177 [DDW-355] Improve stake pools rendering performance
  CHANGELOG.md
  source/renderer/app/components/staking/stake-pools/StakePools.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsList.js
  source/renderer/app/components/staking/stake-pools/StakePoolsList.scss
Labels: :hourglass_flowing_sand:release-vNext, bug

#2165 [DDW-368]: Fetch slot and epoch info from the API
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/api/network/types.js
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/components/staking/delegation-center/DelegationCenter.js
  source/renderer/app/components/staking/delegation-center/DelegationCenterHeader.js
  source/renderer/app/components/staking/delegation-center/UndelegateConfirmationResultDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsSuccessDialog.js
  source/renderer/app/config/epochsConfig.js
  source/renderer/app/config/stakingConfig.js
  source/renderer/app/containers/staking/DelegationCenterPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/stores/NetworkStatusStore.js
  storybook/stories/staking/DelegationCenter.stories.js
  storybook/stories/staking/DelegationSteps.stories.js
  storybook/stories/staking/Undelegate.stories.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2162 [DDW-304]: Implement logarithmic stake slider
  CHANGELOG.md
  source/renderer/app/components/staking/stake-pools/StakePoolsRanking.js
  source/renderer/app/components/widgets/Slider.js
  source/renderer/app/config/stakingConfig.js
  source/renderer/app/containers/staking/StakePoolsListPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/utils/formatters.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2180 [DDW-379] Remove one second delay on ranking stake pools
  CHANGELOG.md
  source/renderer/app/actions/staking-actions.js
  source/renderer/app/components/staking/stake-pools/StakePools.js
  source/renderer/app/components/staking/stake-pools/StakePoolsRanking.js
  source/renderer/app/containers/staking/StakePoolsListPage.js
  source/renderer/app/stores/StakingStore.js
  storybook/stories/staking/StakePools.stories.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2181 [DDW-378] "Delegate to this pool" button styles
  CHANGELOG.md
  source/renderer/app/components/staking/widgets/ThumbPool.js
  source/renderer/app/components/staking/widgets/ThumbPool.scss
  source/renderer/app/components/staking/widgets/ThumbPoolContent.scss
  source/renderer/app/components/staking/widgets/ThumbSelectedPool.js
  source/renderer/app/components/staking/widgets/ThumbSelectedPool.scss
  source/renderer/app/components/staking/widgets/TooltipPool.scss
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/shelley-testnet.js
  source/renderer/app/themes/daedalus/yellow.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2185 [DDW-394] Open ‘Delegation center’ as default staking screen
  CHANGELOG.md
  source/renderer/app/Routes.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2187 [DDW-395] Update WBE and Node dependencies
  CHANGELOG.md
  README.md
  default.nix
  nix/sources.json
  source/main/environment.js
  source/renderer/app/components/staking/widgets/ThumbPoolContent.js
  source/renderer/app/components/staking/widgets/ThumbSelectedPool.scss
  source/renderer/app/components/staking/widgets/TooltipPool.js
  source/renderer/app/config/stakingConfig.js
  source/renderer/app/utils/colors.js
Labels: :hourglass_flowing_sand:release-vNext, bug, chore

#2188 [DDW-395] Update WBE
  CHANGELOG.md
  nix/sources.json
  source/common/config/appUpdateConfig.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2189 [DDW-396] The retirement label is too light on yellow theme
  CHANGELOG.md
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2154 Add smashUrl for mainnet
  CHANGELOG.md
  nix/launcher-config.nix
  nix/sources.json
  source/main/cardano/CardanoNode.js
  source/main/cardano/CardanoWalletLauncher.js
  source/main/cardano/setup.js
  source/renderer/app/themes/daedalus/yellow.js
Labels: :hourglass_flowing_sand:release-vNext, chore, feature
