Repository input-output-hk/daedalus, pull requests merged in 2020-07, with the labels that each got.

#2053 Daedalus 1.1.0-STN1 release with delegation features
  CHANGELOG.md
  installer-clusters.cfg
  nix/launcher-config.nix
  nix/sources.json
  release-build.nix
  source/main/environment.js
  source/renderer/app/components/layout/TopBar.js
  source/renderer/app/components/wallet/WalletSendForm.js
  source/renderer/app/components/wallet/skins/AmountInputSkin.js
  source/renderer/app/components/wallet/skins/AmountInputSkin.scss
  source/renderer/app/components/wallet/summary/WalletSummary.js
  source/renderer/app/components/wallet/summary/WalletSummary.scss
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/SidebarStore.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2049 [DDW-290] UI fixes for delegation screens
  CHANGELOG.md
  package.json
  source/renderer/app/api/api.js
  source/renderer/app/components/notifications/LegacyNotification.js
  source/renderer/app/components/sidebar/wallets/SidebarWalletMenuItem.scss
  source/renderer/app/components/staking/delegation-center/WalletRow.scss
  source/renderer/app/components/staking/layouts/StakingWithNavigation.js
  source/renderer/app/components/staking/navigation/StakingNavigation.js
  source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnetTooltip.scss
  source/renderer/app/components/wallet/summary/WalletSummary.js
  source/renderer/app/containers/staking/Staking.js
  source/renderer/app/containers/staking/StakingEpochsPage.js
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/themes/daedalus/shelley-testnet.js
  storybook/stories/_support/StoryProvider.js
  storybook/stories/staking/DelegationCenter.stories.js
  storybook/stories/staking/Staking.stories.js
Labels: bug, release-1.2.0-STN1

#2058 Merge 1.2.0-STN1 release into develop
  nix/sources.json
  source/main/environment.js
  source/renderer/app/api/api.js
  source/renderer/app/components/layout/TopBar.js
  source/renderer/app/components/staking/delegation-center/WalletRow.js
  source/renderer/app/components/staking/delegation-center/WalletRow.scss
  source/renderer/app/components/wallet/summary/WalletSummary.js
  source/renderer/app/components/wallet/summary/WalletSummary.scss
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/SidebarStore.js
Labels: chore, release-1.2.0-STN1

#2051 [DDW-283]: Stake pools ranking based on delegated amount
  CHANGELOG.md
  nix/sources.json
  package.json
  source/renderer/app/actions/staking-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/api/staking/requests/getStakePools.js
  source/renderer/app/components/staking/stake-pools/StakePools.js
  source/renderer/app/components/staking/stake-pools/StakePoolsList.js
  source/renderer/app/components/staking/stake-pools/StakePoolsList.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsRanking.js
  source/renderer/app/components/staking/stake-pools/StakePoolsRanking.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsRankingLoader.js
  source/renderer/app/components/staking/stake-pools/StakePoolsRankingLoader.scss
  source/renderer/app/components/widgets/Slider.js
  source/renderer/app/components/widgets/Slider.scss
  source/renderer/app/components/widgets/forms/WalletsDropdown.js
  source/renderer/app/components/widgets/forms/WalletsDropdownOption.scss
  source/renderer/app/containers/staking/StakePoolsListPage.js
  source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/shelley-testnet.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/index.global.scss
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/staking/StakePools.stories.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext, feature

#2063 [DDW-283]: Quick fix on stake pools ranking panel
  source/renderer/app/components/staking/stake-pools/StakePoolsRanking.js
Labels: bug

#2042 [DDW-178] Redeem Incentivized testnet rewards
  CHANGELOG.md
  source/renderer/app/Routes.js
  source/renderer/app/actions/staking-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/api/staking/requests/submitRedeemItnRewards.js
  source/renderer/app/api/staking/types.js
  source/renderer/app/assets/images/sad-wallet.inline.svg
  source/renderer/app/assets/images/sidebar/redeem-itn-rewards-ic.inline.svg
  source/renderer/app/components/sidebar/Sidebar.js
  source/renderer/app/components/sidebar/SidebarCategory.scss
  source/renderer/app/components/staking/redeem-itn-rewards/NoWalletsDialog.js
  source/renderer/app/components/staking/redeem-itn-rewards/NoWalletsDialog.scss
  source/renderer/app/components/staking/redeem-itn-rewards/RedeemDialogOverride.scss
  source/renderer/app/components/staking/redeem-itn-rewards/Step1ConfigurationDialog.js
  source/renderer/app/components/staking/redeem-itn-rewards/Step1ConfigurationDialog.scss
  source/renderer/app/components/staking/redeem-itn-rewards/Step2ConfirmationDialog.js
  source/renderer/app/components/staking/redeem-itn-rewards/Step2ConfirmationDialog.scss
  source/renderer/app/components/staking/redeem-itn-rewards/Step3FailureDialog.js
  source/renderer/app/components/staking/redeem-itn-rewards/Step3FailureDialog.scss
  source/renderer/app/components/staking/redeem-itn-rewards/Step3SuccessDialog.js
  source/renderer/app/components/staking/redeem-itn-rewards/Step3SuccessDialog.scss
  source/renderer/app/components/wallet/wallet-create/WalletCreateDialog.js
  source/renderer/app/components/wallet/wallet-import/WalletImportFileDialog.js
  source/renderer/app/components/wallet/wallet-import/WalletSelectImportDialog.js
  source/renderer/app/components/wallet/wallet-restore/widgets/WalletRestoreDialog.js
  source/renderer/app/components/widgets/Dialog.js
  source/renderer/app/components/widgets/Dialog.scss
  source/renderer/app/components/widgets/forms/WalletsDropdown.js
  source/renderer/app/components/widgets/forms/WalletsDropdown.scss
  source/renderer/app/config/sidebarConfig.js
  source/renderer/app/config/stakingConfig.js
  source/renderer/app/containers/MainLayout.js
  source/renderer/app/containers/Root.js
  source/renderer/app/containers/staking/RedeemItnRewardsContainer.js
  source/renderer/app/containers/staking/dialogs/redeem-itn-rewards/NoWalletsContainer.js
  source/renderer/app/containers/staking/dialogs/redeem-itn-rewards/Step1ConfigurationContainer.js
  source/renderer/app/containers/staking/dialogs/redeem-itn-rewards/Step2ConfirmationContainer.js
  source/renderer/app/containers/staking/dialogs/redeem-itn-rewards/Step3ResultContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/routes-config.js
  source/renderer/app/stores/SidebarStore.js
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/shelley-testnet.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  source/renderer/app/types/injectedPropsType.js
  source/renderer/app/types/stakingTypes.js
  storybook/stories/staking/RedeemItnWallets.stories.js
  storybook/stories/staking/Staking.stories.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2064 [DDW-299] Bump dependencies and enable Byron wallets
  CHANGELOG.md
  nix/sources.json
  source/main/environment.js
  source/renderer/app/api/api.js
  source/renderer/app/components/wallet/wallet-restore/WalletTypeDialog.js
  source/renderer/app/i18n/locales/en-US.json
Labels: :hourglass_flowing_sand:release-vNext, chore

#2065 [DDW-298] Display withdrawals in transaction details
  .flowconfig
  CHANGELOG.md
  nix/sources.json
  source/renderer/app/api/api.js
  source/renderer/app/api/transactions/requests/createTransaction.js
  source/renderer/app/api/transactions/requests/getTransactionFee.js
  source/renderer/app/api/transactions/types.js
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/domains/WalletTransaction.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  storybook/stories/_support/utils.js
  storybook/stories/wallets/transactions/TransactionsList.stories.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2066 [DDW-297] Calculate and display total wallet rewards
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/api/transactions/requests/getWithdrawalHistory.js
  source/renderer/app/api/transactions/types.js
  source/renderer/app/containers/staking/DelegationCenterPage.js
  source/renderer/app/containers/staking/StakePoolsListPage.js
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/stores/TransactionsStore.js
  source/renderer/app/stores/WalletsStore.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2070 Remove ITN rewards icon from production builds
  CHANGELOG.md
  source/renderer/app/stores/SidebarStore.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2067 Hide stake pool saturation info
  CHANGELOG.md
  source/renderer/app/components/staking/stake-pools/StakePoolThumbnail.js
  source/renderer/app/components/staking/stake-pools/StakePoolThumbnail.scss
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2072 [DDW-283]: Stake pool ranking based on delegated amount
  CHANGELOG.md
  source/renderer/app/components/staking/stake-pools/StakePools.js
  source/renderer/app/components/staking/stake-pools/StakePoolsRanking.js
  source/renderer/app/config/stakingConfig.js
  source/renderer/app/containers/staking/StakePoolsListPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/utils/walletsForStakePoolsRanking.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2068 [DDW-295] Show stake pool retirement info
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/api/staking/types.js
  source/renderer/app/assets/images/clock-corner.inline.svg
  source/renderer/app/assets/images/clock.inline.svg
  source/renderer/app/components/staking/delegation-center/WalletRow.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsList.js
  source/renderer/app/components/staking/widgets/ThumbPool.js
  source/renderer/app/components/staking/widgets/ThumbPool.scss
  source/renderer/app/components/staking/widgets/ThumbPoolContent.js
  source/renderer/app/components/staking/widgets/ThumbPoolContent.scss
  source/renderer/app/components/staking/widgets/ThumbSelectedPool.js
  source/renderer/app/components/staking/widgets/ThumbSelectedPool.scss
  source/renderer/app/components/staking/widgets/TooltipPool-experimental-tooltip.scss
  source/renderer/app/components/staking/widgets/TooltipPool.js
  source/renderer/app/components/staking/widgets/TooltipPool.scss
  source/renderer/app/components/widgets/Dialog.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  tests/delegation/e2e/steps/delegation.js
  tests/delegation/e2e/steps/stake-pools.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2071 [DDW-300] Adds stake pool id to the stake pool tooltip
  CHANGELOG.md
  source/renderer/app/components/staking/delegation-center/WalletRow.js
  source/renderer/app/components/staking/widgets/ThumbPool.js
  source/renderer/app/components/staking/widgets/ThumbPoolContent.js
  source/renderer/app/components/staking/widgets/ThumbPoolContent.scss
  source/renderer/app/components/staking/widgets/TooltipPool.js
  source/renderer/app/components/staking/widgets/TooltipPool.scss
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/shelley-testnet.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2074 [DDW-301] Implement stake pool ID hover and copy
  CHANGELOG.md
  source/renderer/app/assets/images/clipboard-small-ic.inline.svg
  source/renderer/app/components/staking/widgets/TooltipPool-copyId-tooltip.scss
  source/renderer/app/components/staking/widgets/TooltipPool.js
  source/renderer/app/components/staking/widgets/TooltipPool.scss
  source/renderer/app/config/timingConfig.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: :hourglass_flowing_sand:release-vNext, feature

#2077 [DDW-302] Double punctuation on delegation dialog
  CHANGELOG.md
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsSuccessDialog.js
  source/renderer/app/i18n/locales/en-US.json
Labels: :hourglass_flowing_sand:release-vNext, bug

#2079 [DDW-294] Byron to Shelley transition
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/api/network/requests/getNetworkParameters.js
  source/renderer/app/api/network/types.js
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/components/layout/TopBar.js
  source/renderer/app/components/sidebar/Sidebar.js
  source/renderer/app/components/sidebar/wallets/SidebarWalletMenuItem.js
  source/renderer/app/components/sidebar/wallets/SidebarWalletsMenu.js
  source/renderer/app/components/splash/SplashNetworkSTN.js
  source/renderer/app/components/staking/countdown/StakingCountdown.js
  source/renderer/app/components/staking/info/StakingInfo.js
  source/renderer/app/components/staking/navigation/StakingNavigation.js
  source/renderer/app/components/wallet/WalletBackupDialog.js
  source/renderer/app/components/wallet/WalletCreateDialog.js
  source/renderer/app/components/wallet/backup-recovery/WalletBackupPrivacyWarningDialog.js
  source/renderer/app/components/wallet/backup-recovery/WalletRecoveryPhraseDisplayDialog.js
  source/renderer/app/components/wallet/navigation/WalletNavigation.js
  source/renderer/app/components/wallet/wallet-restore/WalletTypeDialog.js
  source/renderer/app/config/stakingConfig.js
  source/renderer/app/config/timingConfig.js
  source/renderer/app/containers/MainLayout.js
  source/renderer/app/containers/staking/Staking.js
  source/renderer/app/containers/staking/StakingInfoPage.js
  source/renderer/app/containers/wallet/dialogs/WalletBackupDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/WalletCreateDialogContainerOld.js
  source/renderer/app/containers/wallet/dialogs/wallet-restore/StepWalletTypeContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/SidebarStore.js
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/stores/WalletsStore.js
  storybook/stories/_support/StoryLayout.js
  storybook/stories/_support/utils.js
  storybook/stories/navigation/Sidebar.stories.js
  storybook/stories/navigation/SidebarWalletsMenu.stories.js
  storybook/stories/nodes/syncing/SyncingConnecting.stories.js
  storybook/stories/staking/Staking.stories.js
  storybook/stories/wallets/addWallet/Restore.stories.js
  tests/wallets/e2e/steps/helpers.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2080 Merge release/1.4.1-STN3 into develop
  CHANGELOG.md
  installers/common/MacInstaller.hs
  installers/common/WindowsInstaller.hs
  nix/launcher-config.nix
  nix/sources.json
  package.json
  source/main/cardano/CardanoNode.js
  source/main/cardano/CardanoWalletLauncher.js
  source/main/cardano/setup.js
  source/main/config.js
  source/renderer/app/components/layout/TopBar.js
  source/renderer/app/components/wallet/navigation/WalletNavigation.js
  source/renderer/app/components/wallet/wallet-restore/SuccessDialog.js
  source/renderer/app/containers/TopBarContainer.js
  source/renderer/app/containers/profile/InitialSettingsPage.js
  source/renderer/app/containers/profile/TermsOfUsePage.js
  source/renderer/app/containers/wallet/TransferFundsPage.js
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/StakingStore.js
  storybook/stories/_support/StoryLayout.js
  storybook/stories/nodes/environment/TopBarEnvironment.stories.js
  yarn.lock
Labels: chore, release-1.4.1-STN3

#2082 [DDW-308] Restoration of legacy Byron hardware wallets
  CHANGELOG.md
  source/renderer/app/components/staking/stake-pools/StakePoolsRanking.scss
  source/renderer/app/components/wallet/wallet-restore/WalletTypeDialog.js
  source/renderer/app/config/walletRestoreConfig.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/types/walletRestoreTypes.js
Labels: chore, release-1.5.1-STN4

#2083 [DDW-306] 24-word wallet recovery phrase for Shelley wallets
  CHANGELOG.md
  source/renderer/app/actions/wallet-backup-actions.js
  source/renderer/app/components/wallet/WalletBackupDialog.js
  source/renderer/app/components/wallet/backup-recovery/MnemonicWord.js
  source/renderer/app/components/wallet/backup-recovery/MnemonicWord.scss
  source/renderer/app/components/wallet/backup-recovery/WalletRecoveryPhraseEntryDialog.js
  source/renderer/app/components/wallet/wallet-restore/WalletTypeDialog.js
  source/renderer/app/config/cryptoConfig.js
  source/renderer/app/config/walletRestoreConfig.js
  source/renderer/app/containers/wallet/dialogs/WalletBackupDialogContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/WalletBackupStore.js
  source/renderer/app/types/walletBackupTypes.js
  source/renderer/app/types/walletRestoreTypes.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2090 Handle new error message codes
  CHANGELOG.md
  source/renderer/app/api/errors.js
  source/renderer/app/components/wallet/transfer-funds/TransferFundsStep1Dialog.js
  source/renderer/app/components/wallet/transfer-funds/TransferFundsStep1Dialog.scss
  source/renderer/app/containers/wallet/dialogs/transfer-funds/TransferFundsStep1Container.js
  source/renderer/app/domains/ApiError.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/WalletsStore.js
  storybook/stories/wallets/legacyWallets/TransferFunds.stories.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2095 [DDW-310] Update ITN rewards redemption to ask for 15-word recovery phrase
  CHANGELOG.md
  source/renderer/app/components/staking/redeem-itn-rewards/Step1ConfigurationDialog.js
  source/renderer/app/components/widgets/Dialog.js
  source/renderer/app/config/cryptoConfig.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2096 [DDW-318] Revert "Blocks (current epoch)" into "Blocks produced"
  CHANGELOG.md
  source/renderer/app/components/staking/widgets/TooltipPool.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: :hourglass_flowing_sand:release-vNext, bug

#2097 [DDW-313] Update cardano-wallet info shown on the "About" screen
  CHANGELOG.md
  source/renderer/app/components/static/About.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2098 [DDW-309] Enable Cardano Explorer links for STN network
  CHANGELOG.md
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/config/urlsConfig.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/utils/network.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2099 [DDW-316] Extend incident and alert newsfeed type
  CHANGELOG.md
  source/renderer/app/api/utils/localStorage.js
  source/renderer/app/components/news/IncidentOverlay.js
  source/renderer/app/components/news/IncidentOverlay.scss
  source/renderer/app/domains/News.js
  source/renderer/app/stores/NewsFeedStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/shelley-testnet.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/news/IncidentOverlay.stories.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2103 [DDW-319] Update network-info Api endpoint integration
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/api/network/types.js
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/api/wallets/types.js
  source/renderer/app/assets/images/sand-clock-xs.inline.svg
  source/renderer/app/components/staking/delegation-center/DelegationCenter.js
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/components/status/DaedalusDiagnostics.scss
  source/renderer/app/containers/staking/DelegationCenterPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/stores/NetworkStatusStore.js
  storybook/stories/nodes/status/Diagnostics.stories.js
  storybook/stories/staking/DelegationCenter.stories.js
  storybook/stories/staking/Staking.stories.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2104 [DDW-312] Update mainnet HF timestamp
  CHANGELOG.md
  source/main/menus/osx.js
  source/main/menus/win-linux.js
  source/main/preload.js
  source/renderer/app/api/api.js
  source/renderer/app/components/hardware-wallet/navigation/HardwareWalletNavigation.js
  source/renderer/app/components/layout/TopBar.js
  source/renderer/app/components/loading/syncing-connecting/SyncingConnecting.js
  source/renderer/app/components/loading/syncing-connecting/SyncingConnectingBackground.js
  source/renderer/app/components/settings/categories/DisplaySettings.js
  source/renderer/app/components/settings/menu/SettingsMenu.js
  source/renderer/app/components/sidebar/Sidebar.js
  source/renderer/app/components/sidebar/wallets/SidebarWalletMenuItem.js
  source/renderer/app/components/sidebar/wallets/SidebarWalletsMenu.js
  source/renderer/app/components/staking/layouts/StakingWithNavigation.js
  source/renderer/app/components/staking/navigation/StakingNavigation.js
  source/renderer/app/components/staking/redeem-itn-rewards/Step1ConfigurationDialog.scss
  source/renderer/app/components/staking/widgets/TooltipPool.js
  source/renderer/app/components/static/About.js
  source/renderer/app/components/wallet/WalletCreateDialog.js
  source/renderer/app/components/wallet/backup-recovery/WalletBackupPrivacyWarningDialog.js
  source/renderer/app/components/wallet/backup-recovery/WalletRecoveryPhraseDisplayDialog.js
  source/renderer/app/components/wallet/backup-recovery/WalletRecoveryPhraseEntryDialog.js
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseVerificationWidget.js
  source/renderer/app/components/wallet/wallet-restore/SuccessDialog.js
  source/renderer/app/components/wallet/wallet-restore/WalletTypeDialog.js
  source/renderer/app/config/walletRestoreConfig.js
  source/renderer/app/containers/MainLayout.js
  source/renderer/app/containers/loading/SyncingConnectingPage.js
  source/renderer/app/containers/settings/Settings.js
  source/renderer/app/containers/splash/SplashNetworkPage.js
  source/renderer/app/containers/staking/Staking.js
  source/renderer/app/containers/staking/StakingEpochsPage.js
  source/renderer/app/containers/staking/StakingInfoPage.js
  source/renderer/app/containers/staking/StakingRewardsPage.js
  source/renderer/app/containers/wallet/WalletReceivePage.js
  source/renderer/app/containers/wallet/WalletSettingsPage.js
  source/renderer/app/containers/wallet/dialogs/WalletBackupDialogContainer.js
  source/renderer/app/stores/AppUpdateStore.js
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/ProfileStore.js
  source/renderer/app/stores/SidebarStore.js
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/stores/WalletSettingsStore.js
  source/renderer/app/stores/WalletsStore.js
  storybook/stories/_support/StoryLayout.js
  storybook/stories/navigation/Sidebar.stories.js
  storybook/stories/navigation/SidebarWalletsMenu.stories.js
  storybook/stories/nodes/syncing/SyncingConnecting.stories.js
  storybook/stories/settings/utils/SettingsWrapper.js
  storybook/stories/staking/Staking.stories.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2100 [DDW-311] Handle "inputs_depleted" error code
  CHANGELOG.md
  source/renderer/app/api/errors.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsNotAvailableDialog.js
  source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  storybook/stories/_support/utils.js
  storybook/stories/staking/DelegationSteps.stories.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2105 [DDW-325] Extend network-parameters Api endpoint integration with hardfork info
  CHANGELOG.md
  README.md
  nix/sources.json
  source/renderer/app/api/api.js
  source/renderer/app/api/network/types.js
  source/renderer/app/api/utils/mnemonics.js
  source/renderer/app/components/hardware-wallet/navigation/HardwareWalletNavigation.js
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/components/status/DaedalusDiagnostics.scss
  source/renderer/app/components/wallet/WalletAdd.js
  source/renderer/app/components/wallet/WalletBackupDialog.js
  source/renderer/app/components/wallet/backup-recovery/WalletRecoveryPhraseEntryDialog.js
  source/renderer/app/components/wallet/layouts/WalletWithNavigation.scss
  source/renderer/app/components/wallet/navigation/WalletNavigation.js
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseVerificationWidget.js
  source/renderer/app/components/wallet/settings/WalletSettings.js
  source/renderer/app/config/stakingConfig.js
  source/renderer/app/config/walletNavigationConfig.js
  source/renderer/app/containers/MainLayout.js
  source/renderer/app/containers/TopBarContainer.js
  source/renderer/app/containers/profile/InitialSettingsPage.js
  source/renderer/app/containers/profile/TermsOfUsePage.js
  source/renderer/app/containers/staking/StakingCountdownPage.js
  source/renderer/app/containers/wallet/dialogs/WalletBackupDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/WalletCreateDialogContainerOld.js
  source/renderer/app/containers/wallet/dialogs/wallet-restore/StepWalletTypeContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/SidebarStore.js
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/stores/WalletMigrationStore.js
  source/renderer/app/stores/WalletsStore.js
  storybook/stories/wallets/settings/WalletRecoveryPhraseVerification.stories.js
  tests/wallets/e2e/features/import-and-migrate-wallets.feature
Labels: :hourglass_flowing_sand:release-vNext, chore

#2107 [DDW-327] Fix epoch duration copy
  CHANGELOG.md
  package.json
  source/renderer/app/components/staking/countdown/StakingCountdown.js
  source/renderer/app/containers/staking/StakingRewardsPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: :hourglass_flowing_sand:release-vNext, bug

#2108 [DDW-327] Fix epoch length and slot count info
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/components/staking/delegation-center/DelegationCenterHeader.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsSuccessDialog.js
  source/renderer/app/config/epochsConfig.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2109 [DDW-326] Extend the recovery phrase verification to all possible phrase lengths
  CHANGELOG.md
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseStep1Dialog.js
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseStep2Dialog.js
  source/renderer/app/config/cryptoConfig.js
  source/renderer/app/containers/wallet/dialogs/settings/WalletRecoveryPhraseContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: :hourglass_flowing_sand:release-vNext, bug

#2110 [DDW-329] Show block replay progress
  CHANGELOG.md
  source/common/ipc/api.js
  source/main/config.js
  source/main/index.js
  source/main/ipc/get-block-replay-progress.js
  source/main/utils/handleCheckBlockReplayProgress.js
  source/renderer/app/components/loading/syncing-connecting/SyncingConnecting.js
  source/renderer/app/components/loading/syncing-connecting/SyncingConnectingStatus.js
  source/renderer/app/containers/loading/SyncingConnectingPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/ipc/getBlockReplayChannel.js
  source/renderer/app/stores/NetworkStatusStore.js
  storybook/stories/nodes/syncing/SyncingConnecting.stories.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2041 [DDW-254] Address validation upgrade to use cardano-addresses CLI via IPC
  CHANGELOG.md
  nix/jormungandr-bridge.nix
  nix/sources.json
  package.json
  source/common/ipc/api.js
  source/common/types/address-introspection.types.js
  source/common/types/cardano-node.types.js
  source/main/cardano/utils.js
  source/main/config.js
  source/main/ipc/index.js
  source/main/ipc/introspect-address.js
  source/renderer/app/components/loading/syncing-connecting/SyncingConnecting.js
  source/renderer/app/components/wallet/WalletSendForm.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/ipc/introspect-address.js
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/utils/network.js
  storybook/stories/wallets/_utils/defaultWalletProps.js
Labels: :hourglass_flowing_sand:release-vNext, chore
