Repository input-output-hk/daedalus, pull requests merged in 2020-01, with the labels that each got.

#1810 [DDW-1168] Fix ITN Terms of Service typo
  CHANGELOG.md
  source/renderer/app/i18n/locales/terms-of-use/itn-rewards-v1/en-US.md
Labels: :hourglass_flowing_sand:release-vNext-ITN1, bug

#1785 [DDW-1176] Fix typo in the Staking Pools section
  CHANGELOG.md
  source/renderer/app/components/staking/stake-pools/StakePools.js
  source/renderer/app/components/staking/stake-pools/StakePoolsSearch.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
Labels: :hourglass_flowing_sand:release-vNext-ITN1, bug, contribution

#1799 [DDW-924] Create link component
  .eslintrc
  CHANGELOG.md
  package.json
  source/renderer/app/components/loading/manual-update/ManualUpdate.js
  source/renderer/app/components/loading/manual-update/ManualUpdate.scss
  source/renderer/app/components/loading/syncing-connecting/ReportIssue.js
  source/renderer/app/components/loading/syncing-connecting/ReportIssue.scss
  source/renderer/app/components/loading/system-time-error/SystemTimeError.js
  source/renderer/app/components/loading/system-time-error/SystemTimeError.scss
  source/renderer/app/components/news/AlertsOverlay.js
  source/renderer/app/components/news/AlertsOverlay.scss
  source/renderer/app/components/news/IncidentOverlay.js
  source/renderer/app/components/news/IncidentOverlay.scss
  source/renderer/app/components/news/NewsItem.js
  source/renderer/app/components/news/NewsItem.scss
  source/renderer/app/components/notifications/LegacyNotification.js
  source/renderer/app/components/notifications/LegacyNotification.scss
  source/renderer/app/components/settings/categories/SupportSettings.js
  source/renderer/app/components/settings/categories/SupportSettings.scss
  source/renderer/app/components/splash/Network.js
  source/renderer/app/components/splash/Network.scss
  source/renderer/app/components/staking/countdown/StakingCountdown.js
  source/renderer/app/components/staking/countdown/StakingCountdown.scss
  source/renderer/app/components/staking/delegation-center/DelegationCenterNoWallets.js
  source/renderer/app/components/staking/info/StakingInfo.js
  source/renderer/app/components/staking/info/StakingInfo.scss
  source/renderer/app/components/staking/rewards/StakingRewards.js
  source/renderer/app/components/staking/rewards/StakingRewards.scss
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.js
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.scss
  source/renderer/app/components/static/About.js
  source/renderer/app/components/static/About.scss
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/components/status/DaedalusDiagnostics.scss
  source/renderer/app/components/wallet/paper-wallet-certificate/CompletionDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/CompletionDialog.scss
  source/renderer/app/components/wallet/paper-wallet-certificate/InstructionsDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/InstructionsDialog.scss
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseStep4Dialog.js
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseStepDialogs.scss
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/components/wallet/transactions/Transaction.scss
  source/renderer/app/components/wallet/utxo/WalletUtxo.js
  source/renderer/app/components/wallet/utxo/WalletUtxo.scss
  source/renderer/app/components/widgets/ButtonLink.js
  source/renderer/app/components/widgets/ButtonLink.scss
  source/renderer/app/containers/wallet/dialogs/paper-wallet-certificate/InstructionsDialogContainer.js
  source/renderer/app/themes/daedalus.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/overrides/LinkOverrides.scss
  source/renderer/app/themes/overrides/index.js
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/common/Widgets.stories.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext-ITN1, feature

#1788 [DDW-1105] Introduce newsfeed update
  CHANGELOG.md
  source/renderer/app/api/wallets/requests/restoreLegacyWallet.js
  source/renderer/app/components/news/AlertsOverlay.js
  source/renderer/app/components/news/NewsFeed.js
  source/renderer/app/components/news/NewsItem.js
  source/renderer/app/components/news/NewsItem.scss
  source/renderer/app/components/widgets/ButtonLink.scss
  source/renderer/app/config/news.dummy.json
  source/renderer/app/containers/news/NewsFeedContainer.js
  source/renderer/app/domains/News.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/stores/NewsFeedStore.js
  storybook/stories/news/NewsFeed.stories.js
  tests/news/e2e/documents/dummy-news.json
  tests/news/e2e/steps/newsfeed-steps.js
  utils/v2-api-importer/legacy.js
Labels: :hourglass_flowing_sand:release-vNext-ITN1, chore

#1819 [DDW-1179]: Improve delete wallet text copy
  CHANGELOG.md
  source/renderer/app/components/wallet/settings/WalletSettings.js
  source/renderer/app/components/wallet/settings/WalletSettings.scss
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
Labels: :hourglass_flowing_sand:release-vNext-ITN1, chore

#1821 [DDW-1181] Bump cardano-wallet revision
  CHANGELOG.md
  nix/sources.json
  utils/jormungandr/selfnode/genesis.yaml
Labels: :hourglass_flowing_sand:release-vNext-ITN1, chore

#1818 [DDW-1178] Improve paper wallet recovery phrase validation
  CHANGELOG.md
  source/renderer/app/components/wallet/wallet-restore/MnemonicsDialog.js
  source/renderer/app/containers/wallet/dialogs/wallet-restore/StepMnemonicsContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/utils/crypto.js
  storybook/stories/wallets/addWallet/Restore.stories.js
  tests/wallets/e2e/features/restore-wallet-via-sidebar.feature
Labels: :hourglass_flowing_sand:release-vNext-ITN1, feature

#1822 [DDW-1180] Resync wallet
  CHANGELOG.md
  source/renderer/app/actions/wallet-settings-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/api/utils/apiHelpers.js
  source/renderer/app/api/wallets/requests/forceLegacyWalletResync.js
  source/renderer/app/api/wallets/requests/forceWalletResync.js
  source/renderer/app/api/wallets/requests/getLegacyWallet.js
  source/renderer/app/api/wallets/types.js
  source/renderer/app/components/layout/TopBar.js
  source/renderer/app/components/wallet/settings/ResyncWallet.js
  source/renderer/app/components/wallet/settings/ResyncWallet.scss
  source/renderer/app/components/wallet/settings/ResyncWalletButton.js
  source/renderer/app/components/wallet/settings/ResyncWalletButton.scss
  source/renderer/app/components/wallet/settings/WalletRecoveryPhrase.scss
  source/renderer/app/components/wallet/settings/WalletSettings.js
  source/renderer/app/components/wallet/settings/WalletSettings.scss
  source/renderer/app/components/widgets/forms/ReadOnlyInput.scss
  source/renderer/app/config/timingConfig.js
  source/renderer/app/containers/wallet/Wallet.js
  source/renderer/app/containers/wallet/WalletSendPage.js
  source/renderer/app/containers/wallet/WalletSettingsPage.js
  source/renderer/app/containers/wallet/WalletSummaryPage.js
  source/renderer/app/containers/wallet/WalletTransactionsPage.js
  source/renderer/app/containers/wallet/WalletUtxoPage.js
  source/renderer/app/domains/Wallet.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/stores/SidebarStore.js
  source/renderer/app/stores/TransactionsStore.js
  source/renderer/app/stores/WalletSettingsStore.js
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/wallets/settings/WalletSettingsScreen.stories.js
  tests/settings/e2e/features/wallet-settings.feature
  tests/settings/e2e/steps/settings.js
  tests/wallets/e2e/steps/helpers.js
  tests/wallets/e2e/steps/wallets.js
Labels: :hourglass_flowing_sand:release-vNext-ITN1, feature

#1823 [DDW-1182] Fix routing issues when deleting wallets
  CHANGELOG.md
  source/renderer/app/stores/WalletsStore.js
Labels: :hourglass_flowing_sand:release-vNext-ITN1, bug

#1826 [DDW-1184] Implement stake pool saturation and desirability attributes
  CHANGELOG.md
  nix/sources.json
  source/renderer/app/api/api.js
  source/renderer/app/api/staking/types.js
  source/renderer/app/components/staking/stake-pools/StakePoolThumbnail.js
  source/renderer/app/components/staking/stake-pools/StakePoolThumbnail.scss
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.js
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.scss
  source/renderer/app/config/generateStakePoolFakeData.js
  source/renderer/app/config/stakingStakePools.dummy.json
  source/renderer/app/domains/StakePool.js
  source/renderer/app/i18n/locales/de-DE.json
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/hr-HR.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/i18n/locales/ko-KR.json
  source/renderer/app/i18n/locales/zh-CN.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  source/renderer/app/utils/colors.js
Labels: :hourglass_flowing_sand:release-vNext-ITN1, feature

#1825 [DDW-1159] Prepare 2.1.0-ITN1 release
  CHANGELOG.md
  nix/sources.json
  package.json
Labels: :hourglass_flowing_sand:release-vNext-ITN1, chore

#1828 [DDW-1190] Bump cardano-wallet revision
  CHANGELOG.md
  nix/sources.json
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/domains/News.js
  utils/jormungandr/selfnode/genesis.yaml
Labels: chore, release-2.1.0-ITN1

#1829 Merge release/2.1.0-ITN1 into v2-integration
  CHANGELOG.md
  nix/sources.json
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/domains/News.js
  utils/jormungandr/selfnode/genesis.yaml
Labels: :hourglass_flowing_sand:release-vNext-ITN1, chore

#1820 [DDW-1149] Implement acceptance tests for stake pools loading
  CHANGELOG.md
  source/renderer/app/actions/staking-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.js
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.scss
  source/renderer/app/components/staking/stake-pools/StakePools.js
  source/renderer/app/components/staking/stake-pools/StakePools.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsList.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/stores/StakingStore.js
  tests/common/e2e/steps/helpers.js
  tests/stake-pools/e2e/features/stake-pools.feature
  tests/stake-pools/e2e/steps/helpers.js
  tests/stake-pools/e2e/steps/stake-pools.js
Labels: :hourglass_flowing_sand:release-vNext-ITN1, chore

#1816 [DDW-1147] Implement acceptance tests for Daedalus Balance wallets
  CHANGELOG.md
  source/renderer/app/components/wallet/wallet-restore/WalletTypeDialog.js
  tests/addresses/e2e/features/receive-money.feature
  tests/navigation/e2e/features/navigate-general-settings-menu.feature
  tests/navigation/e2e/features/navigate-sidebar-categories.feature
  tests/navigation/e2e/features/navigate-wallet-tabs.feature
  tests/navigation/e2e/features/switching-between-wallets.feature
  tests/navigation/e2e/features/toggle-sidebar-submenus.feature
  tests/nodes/e2e/features/data-layer-migration.feature
  tests/nodes/e2e/features/wallet-settings-recovery-phrase-verification.feature
  tests/paper-wallets/e2e/features/paper-wallets-certificate.feature
  tests/settings/e2e/features/wallet-settings.feature
  tests/transactions/e2e/features/send-money-to-receiver.feature
  tests/transactions/e2e/features/transactions-display.feature
  tests/transactions/e2e/features/wallet-utxos.feature
  tests/transactions/e2e/steps/transactions.js
  tests/wallets/e2e/features/balance-wallets-notification.feature
  tests/wallets/e2e/features/create-wallet.feature
  tests/wallets/e2e/features/delete-wallet-via-settings.feature
  tests/wallets/e2e/features/delete-wallet.feature
  tests/wallets/e2e/features/import-wallet.feature
  tests/wallets/e2e/features/restore-wallet/restore-daedalus-wallet.feature
  tests/wallets/e2e/features/restore-wallet/restore-hardware-wallet.feature
  tests/wallets/e2e/features/restore-wallet/restore-yoroi-wallet.feature
  tests/wallets/e2e/features/transfer-funds-wizard.feature
  tests/wallets/e2e/features/wallets-ordering.feature
  tests/wallets/e2e/steps/balance-wallets-notification.js
  tests/wallets/e2e/steps/create-wallet.js
  tests/wallets/e2e/steps/delete-wallet.js
  tests/wallets/e2e/steps/helpers.js
  tests/wallets/e2e/steps/import-wallet.js
  tests/wallets/e2e/steps/restore-wallet.js
  tests/wallets/e2e/steps/transfer-funds-wizard.js
  tests/wallets/e2e/steps/wallets-ordering.js
  tests/wallets/e2e/steps/wallets.js
Labels: :hourglass_flowing_sand:release-vNext-ITN1, chore

#1830 [DDW-1191] Fix broken acceptance tests
  CHANGELOG.md
  tests/stake-pools/e2e/features/stake-pools.feature
Labels: :hourglass_flowing_sand:release-vNext-ITN1, bug

#1834 [DDW-1192] Bump cardano-wallet revision
  CHANGELOG.md
  nix/sources.json
Labels: chore, release-2.1.0-ITN1
