Repository input-output-hk/daedalus, pull requests merged in 2020-06, with the labels that each got.

#2023 [DDW-250] - Improve hardware wallets theming
  CHANGELOG.md
  source/renderer/app/components/hardware-wallet/settings/ConnectHardwareWallet.scss
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2024 [DDW-251] Remove resync wallet feature
  CHANGELOG.md
  source/renderer/app/actions/wallet-settings-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/api/wallets/requests/forceLegacyWalletResync.js
  source/renderer/app/api/wallets/requests/forceWalletResync.js
  source/renderer/app/api/wallets/types.js
  source/renderer/app/components/hardware-wallet/settings/ConnectHardwareWallet.scss
  source/renderer/app/components/wallet/settings/ResyncWallet.js
  source/renderer/app/components/wallet/settings/ResyncWallet.scss
  source/renderer/app/components/wallet/settings/ResyncWalletButton.js
  source/renderer/app/components/wallet/settings/ResyncWalletButton.scss
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseVerificationWidget.js
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseVerificationWidget.scss
  source/renderer/app/components/wallet/settings/WalletSettings.js
  source/renderer/app/components/wallet/settings/WalletSettings.scss
  source/renderer/app/config/timingConfig.js
  source/renderer/app/containers/wallet/WalletSettingsPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/WalletSettingsStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/wallets/settings/WalletSettingsScreen.stories.js
  tests/settings/e2e/features/wallet-settings.feature
  tests/settings/e2e/steps/settings.js
  tests/wallets/e2e/steps/wallets-limit.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2026 Merge release/2.4.0-ITN1 into develop
  source/renderer/app/config/timingConfig.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2027 Bump cardano-wallet revision
  CHANGELOG.md
  nix/sources.json
Labels: :hourglass_flowing_sand:release-vNext, chore

#2032 [DDW-276]: Fix wallets root redirection route config
  CHANGELOG.md
  source/renderer/app/Routes.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2028 [DDW-256] Eliminate usage of UNSAFE_XXX legacy lifecycle methods
  CHANGELOG.md
  source/renderer/app/App.js
  source/renderer/app/components/loading/syncing-connecting/SyncingConnecting.js
  source/renderer/app/components/news/AlertsOverlay.js
  source/renderer/app/components/news/IncidentOverlay.js
  source/renderer/app/components/news/NewsItem.js
  source/renderer/app/components/sidebar/Sidebar.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationSetupWizardDialog.js
  source/renderer/app/components/staking/stake-pools/StakePoolTooltip.js
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/components/wallet/WalletRestoreDialog.js
  source/renderer/app/components/wallet/paper-wallet-certificate/InstructionsDialog.js
  source/renderer/app/components/wallet/transactions/render-strategies/VirtualTransactionList.js
  source/renderer/app/components/wallet/transfer-funds/TransferFundsStep2Dialog.js
  source/renderer/app/components/wallet/wallet-import/WalletImportFileDialog.js
  source/renderer/app/components/wallet/wallet-restore/ConfigurationDialog.js
  source/renderer/app/components/widgets/forms/MnemonicInputWidget.js
  source/renderer/app/containers/wallet/PaperWalletCreateCertificatePage.js
  source/renderer/app/containers/wallet/WalletUtxoPage.js
  source/renderer/app/i18n/global-messages.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/themes/mixins/forms.scss
  storybook/stories/common/Widgets.stories.js
  storybook/stories/news/AlertsOverlay.stories.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2030 [DDW-200] Update copy to cover additional screens
  CHANGELOG.md
  source/main/preload.js
  source/renderer/app/components/notifications/LegacyBadge.js
  source/renderer/app/components/notifications/LegacyNotification.js
  source/renderer/app/components/wallet/transfer-funds/TransferFundsStep1Dialog.js
  source/renderer/app/components/wallet/transfer-funds/TransferFundsStep2Dialog.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/WalletsStore.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2035 [DDW-277] Fix Download Manager directory creation error
  source/main/utils/downloadManager.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2040 [DDW-281] ITN message shown during creation of the wallet
  CHANGELOG.md
  source/renderer/app/components/wallet/backup-recovery/WalletBackupPrivacyWarningDialog.js
  source/renderer/app/components/wallet/backup-recovery/WalletRecoveryPhraseEntryDialog.js
  source/renderer/app/containers/wallet/dialogs/WalletBackupDialogContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: :hourglass_flowing_sand:release-vNext, bug

#2033 [DDW-267]: Fix data displayed outside component on transaction list screen
  CHANGELOG.md
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseVerificationWidget.scss
  source/renderer/app/components/wallet/transactions/render-strategies/VirtualTransactionList.js
Labels: :hourglass_flowing_sand:release-vNext, WIP, bug

#2037 [DDW-280] Update copy for Shelley Testnet
  CHANGELOG.md
  source/renderer/app/components/layout/TopBar.js
  source/renderer/app/components/notifications/LegacyBadge.js
  source/renderer/app/components/notifications/LegacyNotification.js
  source/renderer/app/components/notifications/LegacyNotification.scss
  source/renderer/app/components/staking/delegation-center/DelegationCenterHeader.js
  source/renderer/app/components/staking/delegation-center/DelegationCenterNoWallets.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsConfirmationDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsNotAvailableDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsSuccessDialog.js
  source/renderer/app/components/staking/rewards/StakingRewards.js
  source/renderer/app/components/wallet/WalletAdd.js
  source/renderer/app/components/wallet/WalletCreateDialog.js
  source/renderer/app/components/wallet/transfer-funds/TransferFundsStep1Dialog.js
  source/renderer/app/components/wallet/transfer-funds/TransferFundsStep2Dialog.js
  source/renderer/app/components/wallet/wallet-restore/SuccessDialog.js
  source/renderer/app/components/wallet/wallet-restore/WalletTypeDialog.js
  source/renderer/app/config/walletRestoreConfig.js
  source/renderer/app/containers/staking/DelegationCenterPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/types/walletRestoreTypes.js
  storybook/stories/staking/Staking.stories.js
  storybook/stories/wallets/index.js
  storybook/stories/wallets/legacyWallets/LegacyNotification.stories.js
  storybook/stories/wallets/legacyWallets/TransferFunds.stories.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2039 [DDW-165] Resolve electron deprecation warnings
  CHANGELOG.md
  package.json
  source/main/index.js
  source/renderer/app/components/wallet/transactions/render-strategies/VirtualTransactionList.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext, chore

#2038 [DDW-170] Password input with strength meter
  CHANGELOG.md
  package.json
  source/renderer/app/components/loading/syncing-connecting/StatusIcons.scss
  source/renderer/app/components/wallet/WalletCreateDialog.js
  source/renderer/app/components/wallet/WalletCreateDialog.scss
  source/renderer/app/components/wallet/WalletRestoreDialog.js
  source/renderer/app/components/wallet/receive/WalletReceiveDialog.scss
  source/renderer/app/components/wallet/settings/ChangeSpendingPasswordDialog.js
  source/renderer/app/components/wallet/settings/ChangeSpendingPasswordDialog.scss
  source/renderer/app/components/wallet/transactions/render-strategies/VirtualTransactionList.js
  source/renderer/app/components/wallet/wallet-restore/ConfigurationDialog.js
  source/renderer/app/components/wallet/wallet-restore/ConfigurationDialog.scss
  source/renderer/app/components/widgets/Dialog.scss
  source/renderer/app/components/widgets/forms/PasswordInput.js
  source/renderer/app/components/widgets/forms/PasswordInput.scss
  source/renderer/app/i18n/global-messages.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/themes/daedalus.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/shelley-testnet.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/overrides/TooltipOverrides.scss
  source/renderer/app/themes/utils/createTheme.js
  source/renderer/app/utils/validations.js
  storybook/stories/wallets/setPassword/SetWalletPassword.stories.js
  tests/wallets/unit/features/spending-password-validation.feature
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext, feature

#2048 bump wallet/node versions
  nix/sources.json
Labels: :hourglass_flowing_sand:release-vNext, chore
