Repository input-output-hk/daedalus, pull requests merged in 2020-12, with the labels that each got.

#2258 Fix empty disk space calculation for some Linux distributions
  CHANGELOG.md
  source/main/config.js
  source/main/utils/handleDiskSpace.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2250 [DDW-486] Close Newsfeed on Blur
  .eslintrc
  CHANGELOG.md
  source/renderer/app/actions/app-actions.js
  source/renderer/app/components/news/NewsFeed.js
  source/renderer/app/components/widgets/BigButtonForDialogs.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: :hourglass_flowing_sand:release-vNext, feature

#2220 [DDW-427] Issues on redeem rewards screen
  CHANGELOG.md
  source/common/utils/logging.js
  source/renderer/app/actions/staking-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/assets/images/circle-bg-faded.inline.svg
  source/renderer/app/assets/images/sand-clock-small.inline.svg
  source/renderer/app/assets/images/untada.inline.svg
  source/renderer/app/components/staking/redeem-itn-rewards/Step1ConfigurationDialog.js
  source/renderer/app/components/staking/redeem-itn-rewards/Step1ConfigurationDialog.scss
  source/renderer/app/components/staking/redeem-itn-rewards/Step2ConfirmationDialog.js
  source/renderer/app/config/stakingConfig.js
  source/renderer/app/containers/Root.js
  source/renderer/app/containers/staking/RedeemItnRewardsContainer.js
  source/renderer/app/containers/staking/dialogs/redeem-itn-rewards/Step1ConfigurationContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/utils/formatters.js
  storybook/stories/staking/RedeemItnWallets.stories.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2262 [DDW-323|DDW-499] Updates maximum delegation amount calculation and cardano-wallet version
  CHANGELOG.md
  nix/sources.json
  source/renderer/app/components/sidebar/Sidebar.js
  source/renderer/app/components/staking/epochs/StakingEpochs.js
  source/renderer/app/components/staking/epochs/StakingEpochsCurrentEpochData.js
  source/renderer/app/components/staking/epochs/StakingEpochsPreviousEpochData.js
  source/renderer/app/components/staking/stake-pools/StakePools.js
  source/renderer/app/components/staking/stake-pools/StakePoolsRanking.js
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseVerificationWidget.js
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/config/stakingConfig.js
  source/renderer/app/containers/settings/categories/GeneralSettingsPage.js
  source/renderer/app/containers/staking/StakePoolsListPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/stores/AppUpdateStore.js
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/themes/utils/findUpdates.js
  source/renderer/app/themes/utils/updateThemes.js
  storybook/stories/staking/StakePools.stories.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2264 [DDW-197] Enable hardware wallets for Testnet network
  CHANGELOG.md
  source/renderer/app/config/hardwareWalletsConfig.js
  source/renderer/app/stores/HardwareWalletsStore.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2263 [DDW-509] Remove delisted pools
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/api/staking/types.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2260 [DEVOPS] Reduce the size of Linux installers
  CHANGELOG.md
  nix/cardano-bridge.nix
  yarn2nix.nix
Labels: :hourglass_flowing_sand:release-vNext, WIP, chore

#2266 Merge release/2.6.0 into master
  .eslintrc
  CHANGELOG.md
  nix/sources.json
  package.json
  source/common/utils/logging.js
  source/main/config.js
  source/main/utils/handleDiskSpace.js
  source/renderer/app/actions/app-actions.js
  source/renderer/app/actions/staking-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/api/staking/types.js
  source/renderer/app/assets/images/circle-bg-faded.inline.svg
  source/renderer/app/assets/images/sand-clock-small.inline.svg
  source/renderer/app/assets/images/untada.inline.svg
  source/renderer/app/components/news/NewsFeed.js
  source/renderer/app/components/sidebar/Sidebar.js
  source/renderer/app/components/staking/epochs/StakingEpochs.js
  source/renderer/app/components/staking/epochs/StakingEpochsCurrentEpochData.js
  source/renderer/app/components/staking/epochs/StakingEpochsPreviousEpochData.js
  source/renderer/app/components/staking/redeem-itn-rewards/Step1ConfigurationDialog.js
  source/renderer/app/components/staking/redeem-itn-rewards/Step1ConfigurationDialog.scss
  source/renderer/app/components/staking/redeem-itn-rewards/Step2ConfirmationDialog.js
  source/renderer/app/components/staking/stake-pools/StakePools.js
  source/renderer/app/components/staking/stake-pools/StakePoolsRanking.js
  source/renderer/app/components/staking/stake-pools/StakePoolsSearch.scss
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseVerificationWidget.js
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/components/widgets/BigButtonForDialogs.js
  source/renderer/app/config/stakingConfig.js
  source/renderer/app/containers/Root.js
  source/renderer/app/containers/settings/categories/GeneralSettingsPage.js
  source/renderer/app/containers/staking/RedeemItnRewardsContainer.js
  source/renderer/app/containers/staking/StakePoolsListPage.js
  source/renderer/app/containers/staking/dialogs/redeem-itn-rewards/Step1ConfigurationContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/AppUpdateStore.js
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/themes/utils/findUpdates.js
  source/renderer/app/themes/utils/updateThemes.js
  source/renderer/app/utils/formatters.js
  storybook/stories/staking/RedeemItnWallets.stories.js
  storybook/stories/staking/StakePools.stories.js
Labels: chore, release-2.6.0

#2267 Merge release/2.6.0 and release/3.0.0-FC4 into develop
  CHANGELOG.md
Labels: :airplane: release-3.0.0-FC4, chore, release-2.6.0

#2261 [DDW-505] Overlapping Data on Transactions
  CHANGELOG.md
  source/renderer/app/components/wallet/transactions/WalletTransactionsList.js
  source/renderer/app/components/wallet/transactions/render-strategies/VirtualTransactionList.js
  source/renderer/app/i18n/locales/defaultMessages.json
Labels: :hourglass_flowing_sand:release-vNext, bug

#2269 [DDW-197] Fix remaining Ledger hardware wallet issues
  CHANGELOG.md
  source/main/index.js
  source/main/ipc/getHardwareWalletChannel.js
  source/main/webpack.config.js
  source/renderer/app/components/hardware-wallet/HardwareWalletStatus.js
  source/renderer/app/components/staking/stake-pools/StakePoolsRanking.scss
  source/renderer/app/stores/HardwareWalletsStore.js
Labels: bug, release-3.0.0

#2272 Transaction expired status
  CHANGELOG.md
  nix/sources.json
  source/renderer/app/api/api.js
  source/renderer/app/api/transactions/types.js
  source/renderer/app/components/wallet/transactions/CancelTransactionButton.js
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/components/wallet/transactions/Transaction.scss
  source/renderer/app/components/wallet/transactions/TransactionTypeIcon.js
  source/renderer/app/components/wallet/transactions/TransactionTypeIcon.scss
  source/renderer/app/domains/WalletTransaction.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/shelley-testnet.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/wallets/_utils/WalletsTransactionsWrapper.js
Labels: bug, release-3.0.0

#2276 Merge release/3.0.0 into develop
  CHANGELOG.md
  nix/sources.json
  source/main/environment.js
  source/renderer/app/api/api.js
  source/renderer/app/api/transactions/types.js
  source/renderer/app/components/wallet/transactions/CancelTransactionButton.js
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/components/wallet/transactions/Transaction.scss
  source/renderer/app/components/wallet/transactions/TransactionTypeIcon.js
  source/renderer/app/components/wallet/transactions/TransactionTypeIcon.scss
  source/renderer/app/domains/WalletTransaction.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/shelley-testnet.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/wallets/_utils/WalletsTransactionsWrapper.js
Labels: chore, release-3.0.0

#2278 [DDW-526] Updates ini dependency
  CHANGELOG.md
  package.json
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext, chore

#2265 [DDW-492] Add initial loading state to UTXO screen
  CHANGELOG.md
  source/renderer/app/components/wallet/utxo/WalletUtxo.js
  source/renderer/app/containers/wallet/WalletUtxoPage.js
  source/renderer/app/stores/WalletSettingsStore.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2279 [DDW-513] Update ledgerjs-hw-app-cardano package version to 2.1.0
  CHANGELOG.md
  package.json
  source/main/ipc/getHardwareWalletChannel.js
  source/renderer/app/utils/hardwareWalletUtils.js
  source/renderer/app/utils/shelleyLedger.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext, chore

#2283 [DEVOPS] Update iohk-nix
  CHANGELOG.md
  nix/sources.json
Labels: :hourglass_flowing_sand:release-vNext, chore

#2281 [DDW-503] Show stake pool ID on the "Confirmation" step of the "Delegation" wizard
  CHANGELOG.md
  gulpfile.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsConfirmationDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsConfirmationDialog.scss
  source/renderer/app/components/staking/stake-pools/helpers.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: :hourglass_flowing_sand:release-vNext, chore

#2239 [DDW-410] Cancel running fee estimation api requests once new request is made
  CHANGELOG.md
  source/renderer/app/components/wallet/WalletSendForm.js
  source/renderer/app/stores/TransactionsStore.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2271 [DDW-438] View wallet public key
  CHANGELOG.md
  source/renderer/app/actions/wallets-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/api/wallets/requests/getWalletPublicKey.js
  source/renderer/app/api/wallets/types.js
  source/renderer/app/assets/images/copy.inline.svg
  source/renderer/app/components/wallet/settings/WalletPublicKeyField.js
  source/renderer/app/components/wallet/settings/WalletPublicKeyField.scss
  source/renderer/app/components/wallet/settings/WalletPublicKeyFieldSkin.js
  source/renderer/app/components/wallet/settings/WalletPublicKeyQRCodeDialog.js
  source/renderer/app/components/wallet/settings/WalletPublicKeyQRCodeDialog.scss
  source/renderer/app/components/wallet/settings/WalletSettings.js
  source/renderer/app/components/wallet/settings/WalletSettings.scss
  source/renderer/app/config/walletsConfig.js
  source/renderer/app/containers/notifications/NotificationsContainer.js
  source/renderer/app/containers/wallet/WalletSettingsPage.js
  source/renderer/app/containers/wallet/dialogs/settings/WalletPublicKeyQRCodeDialogContainer.js
  source/renderer/app/i18n/global-messages.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/types/notificationTypes.js
  storybook/stories/wallets/settings/WalletPublicKeyQRCode.stories.js
  storybook/stories/wallets/settings/WalletSettings.stories.js
  storybook/stories/wallets/settings/WalletSettingsScreen.stories.js
Labels: :hourglass_flowing_sand:release-vNext, feature
