Repository input-output-hk/daedalus, pull requests merged in 2020-04, with the labels that each got.

#1940 Merge release/1.0.0-FC1 into develop
  default.nix
  installers/common/MacInstaller.hs
  nix/launcher-config.nix
  release-build.nix
  source/renderer/app/components/splash/SplashNetworkFlight.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#1941 [DDW-98] - Fix Cardano Node version shown on the About screen
  CHANGELOG.md
  source/main/environment.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#1943 [DDW-100] Generate an address after creating a Byron wallet
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/stores/WalletsStore.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#1946 [DDW-101] - Disable "Force resync" feature for Byron builds
  CHANGELOG.md
  source/renderer/app/components/wallet/settings/WalletSettings.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#1945 [DEVOPS] Fix OSX installer to contain genesis/secrets for itn_selfnode build
  installers/common/MacInstaller.hs
  scripts/build-installer-unix.sh
Labels: :hourglass_flowing_sand:release-vNext, bug

#1944 [DDW-116] Fix electron-storage implementation
  CHANGELOG.md
  source/main/cardano/CardanoNode.js
  source/main/cardano/CardanoWalletLauncher.js
  source/main/preload.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#1827 [DDW-927] Implement Custom Scrollbars for Each Daedalus Theme
  CHANGELOG.md
  package.json
  source/renderer/app/components/settings/SettingsLayout.scss
  source/renderer/app/components/sidebar/wallets/SidebarWalletsMenu.scss
  source/renderer/app/components/widgets/forms/InlineEditingInput.js
  source/renderer/app/components/widgets/forms/InlineEditingInput.scss
  source/renderer/app/themes/daedalus.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/index.global.scss
  source/renderer/app/themes/overrides/ScrollbarOverrides.scss
  source/renderer/app/themes/overrides/index.js
  source/renderer/app/themes/utils/createTheme.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#1949 [DDW-117] - Hide counter if we have only one newsfeed alert to show
  CHANGELOG.md
  package.json
  source/renderer/app/components/news/AlertsOverlay.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#1951 [DDW-114] Fix restoration validation
  CHANGELOG.md
  source/renderer/app/components/wallet/wallet-restore/WalletTypeDialog.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#1952 [DDW-102] Remove "Syncing" screen
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/components/loading/syncing-connecting/ReportIssue.js
  source/renderer/app/components/loading/syncing-connecting/ReportIssue.scss
  source/renderer/app/components/loading/syncing-connecting/StatusIcons.js
  source/renderer/app/components/loading/syncing-connecting/SyncingConnecting.js
  source/renderer/app/components/loading/syncing-connecting/SyncingConnectingStatus.js
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/components/widgets/NodeSyncStatusIcon.js
  source/renderer/app/config/timingConfig.js
  source/renderer/app/containers/MainLayout.js
  source/renderer/app/containers/Root.js
  source/renderer/app/containers/TopBarContainer.js
  source/renderer/app/containers/loading/SyncingConnectingPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/_support/StoryLayout.js
  storybook/stories/nodes/environment/TopBarEnvironment.stories.js
  storybook/stories/nodes/syncing/Syncing.stories.js
  storybook/stories/nodes/syncing/SyncingConnecting.stories.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#1954 [SRE] cardano-wallet: bump to 563c28f05c1f38c9741277f480a8983d37b05a68
  nix/sources.json
Labels: :airplane: release-1.0.0-FC2, bug

#1955 Merge release/1.0.0-FC2 into develop
  nix/sources.json
Labels: :airplane: release-1.0.0-FC2, chore

#1953 [DDW-92] Update README
  CHANGELOG.md
  README.md
Labels: :hourglass_flowing_sand:release-vNext, chore

#1912 [DDW-74] Fix Tests
  CHANGELOG.md
  nix/sources.json
  package.json
  source/common/types/environment.types.js
  source/common/utils/environmentCheckers.js
  source/main/cardano/utils.js
  source/main/environment.js
  source/renderer/app/actions/wallets-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/containers/wallet/WalletReceivePage.js
  source/renderer/app/stores/AddressesStore.js
  source/renderer/app/stores/WalletsStore.js
  tests/addresses/e2e/features/receive-money.feature
  tests/addresses/e2e/steps/addresses.js
  tests/common/e2e/steps/config.js
  tests/common/e2e/steps/helpers.js
  tests/delegation/e2e/features/delegation-pending.feature
  tests/delegation/e2e/features/delegation.feature
  tests/delegation/e2e/features/rewards.feature
  tests/delegation/e2e/features/stake-pools.feature
  tests/navigation/e2e/features/navigate-general-settings-menu.feature
  tests/navigation/e2e/features/navigate-sidebar-categories.feature
  tests/navigation/e2e/features/navigate-wallet-tabs.feature
  tests/navigation/e2e/features/switching-between-wallets.feature
  tests/navigation/e2e/features/toggle-sidebar-submenus.feature
  tests/nodes/e2e/features/data-layer-migration.feature
  tests/nodes/e2e/features/wallet-settings-recovery-phrase-verification.feature
  tests/paper-wallets/e2e/features/paper-wallets-certificate.feature
  tests/settings/e2e/features/custom-formats.feature
  tests/settings/e2e/features/wallet-settings.feature
  tests/setup-e2e.js
  tests/transactions/e2e/features/send-money-to-receiver.feature
  tests/transactions/e2e/features/transactions-display.feature
  tests/transactions/e2e/features/wallet-utxos.feature
  tests/transactions/e2e/steps/transactions.js
  tests/wallets/e2e/features/balance-wallets-notification.feature
  tests/wallets/e2e/features/create-wallet.feature
  tests/wallets/e2e/features/delete-wallet.feature
  tests/wallets/e2e/features/import-wallet.feature
  tests/wallets/e2e/features/restore-wallet/restore-daedalus-wallet.feature
  tests/wallets/e2e/features/restore-wallet/restore-hardware-wallet.feature
  tests/wallets/e2e/features/restore-wallet/restore-yoroi-wallet.feature
  tests/wallets/e2e/features/transfer-funds-wizard.feature
  tests/wallets/e2e/features/wallet-not-responding.feature
  tests/wallets/e2e/features/wallets-limit.feature
  tests/wallets/e2e/features/wallets-ordering.feature
  tests/wallets/e2e/steps/helpers.js
  tests/wallets/e2e/steps/wallets-limit.js
  tests/wallets/e2e/steps/wallets.js
  utils/api-importer/byron-wallet-importer.js
  utils/cardano/selfnode/genesis.json
Labels: :hourglass_flowing_sand:release-vNext, bug

#1959 [SRE] Bump cardano-wallet: supports cardano-node 1.10.0
  nix/sources.json
Labels: :hourglass_flowing_sand:release-vNext, feature

#1960 [DDW-150, DDW-90] Bump cardano-wallet, cardano-node and cardano-launcher versions
  CHANGELOG.md
  nix/sources.json
  package.json
  source/main/cardano/CardanoNode.js
  source/main/cardano/CardanoWalletLauncher.js
  source/main/config.js
  source/main/environment.js
  source/renderer/app/containers/status/DaedalusDiagnosticsDialog.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext, chore

#1961 [DDW-123] Disable address generation for Yoroi wallets
  CHANGELOG.md
  README.md
  nix/sources.json
  package.json
  source/renderer/app/api/api.js
  source/renderer/app/api/wallets/types.js
  source/renderer/app/components/wallet/receive/Address.js
  source/renderer/app/components/wallet/receive/Address.scss
  source/renderer/app/components/wallet/receive/AddressActions.js
  source/renderer/app/components/wallet/receive/AddressActions.scss
  source/renderer/app/components/wallet/receive/AddressRandom.js
  source/renderer/app/components/wallet/receive/AddressRandom.scss
  source/renderer/app/components/wallet/receive/AddressSequential.js
  source/renderer/app/components/wallet/receive/AddressSequential.scss
  source/renderer/app/components/wallet/receive/VirtualAddressesList.js
  source/renderer/app/components/wallet/receive/WalletReceiveRandom.js
  source/renderer/app/components/wallet/receive/WalletReceiveRandom.scss
  source/renderer/app/components/wallet/receive/WalletReceiveSequential.js
  source/renderer/app/components/wallet/receive/WalletReceiveSequential.scss
  source/renderer/app/containers/wallet/WalletReceivePage.js
  source/renderer/app/domains/Wallet.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  storybook/stories/_support/utils.js
  storybook/stories/staking/DelegationCenter.stories.js
  storybook/stories/wallets/receive/WalletReceive.stories.js
  utils/api-importer/byron-wallet-importer.js
  utils/api-importer/itn-byron-wallet-importer.js
  utils/api-importer/itn-shelley-wallet-importer.js
  utils/api-importer/yoroi-wallet-importer.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#1957 [DDW-105] Force setting password on passwordless wallets
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/assets/images/insecure-wallet.inline.svg
  source/renderer/app/components/wallet/layouts/WalletWithNavigation.js
  source/renderer/app/components/wallet/settings/ChangeSpendingPasswordDialog.js
  source/renderer/app/components/wallet/settings/SetWalletPassword.js
  source/renderer/app/components/wallet/settings/SetWalletPassword.scss
  source/renderer/app/containers/wallet/Wallet.js
  source/renderer/app/containers/wallet/WalletSummaryPage.js
  source/renderer/app/containers/wallet/dialogs/settings/ChangeSpendingPasswordDialogContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/_support/StoryLayout.js
  storybook/stories/_support/StoryProvider.js
  storybook/stories/_support/utils.js
  storybook/stories/wallets/_utils/WalletWithNavigationLayout.js
  storybook/stories/wallets/_utils/WalletsWrapper.js
  storybook/stories/wallets/_utils/defaultWalletProps.js
  storybook/stories/wallets/index.js
  storybook/stories/wallets/setPassword/SetWalletPassword.stories.js
  storybook/stories/wallets/settings/WalletSettingsScreen.stories.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#1962 [DDW-115] Implement smart error handler
  CHANGELOG.md
  source/renderer/app/api/addresses/errors.js
  source/renderer/app/api/api.js
  source/renderer/app/api/common/errors.js
  source/renderer/app/api/common/types.js
  source/renderer/app/api/errors.js
  source/renderer/app/api/network/errors.js
  source/renderer/app/api/transactions/errors.js
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/api/wallets/errors.js
  source/renderer/app/components/wallet/WalletSendForm.js
  source/renderer/app/domains/ApiError.js
  source/renderer/app/i18n/global-messages.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: :hourglass_flowing_sand:release-vNext, chore

#1956 [DDW-106] Wallet import feature
  CHANGELOG.md
  nix/launcher-config.nix
  nix/sources.json
  package.json
  source/common/ipc/api.js
  source/common/types/logging.types.js
  source/main/cardano/setup.js
  source/main/cardano/utils.js
  source/main/config.js
  source/main/preload.js
  source/renderer/app/actions/index.js
  source/renderer/app/actions/wallet-migration-actions.js
  source/renderer/app/actions/wallet-settings-actions.js
  source/renderer/app/assets/images/arrow-right.inline.svg
  source/renderer/app/assets/images/info-icon.inline.svg
  source/renderer/app/assets/images/pen.inline.svg
  source/renderer/app/components/wallet/WalletAdd.js
  source/renderer/app/components/wallet/settings/SetWalletPassword.scss
  source/renderer/app/components/wallet/wallet-import/WalletImportFileDialog.js
  source/renderer/app/components/wallet/wallet-import/WalletImportFileDialog.scss
  source/renderer/app/components/wallet/wallet-import/WalletSelectImportDialog.js
  source/renderer/app/components/wallet/wallet-import/WalletSelectImportDialog.scss
  source/renderer/app/components/widgets/BigButtonForDialogs.scss
  source/renderer/app/components/widgets/forms/InlineEditingSmallInput.js
  source/renderer/app/components/widgets/forms/InlineEditingSmallInput.scss
  source/renderer/app/config/numbersConfig.js
  source/renderer/app/containers/Root.js
  source/renderer/app/containers/wallet/WalletAddPage.js
  source/renderer/app/containers/wallet/dialogs/WalletImportDialogContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/WalletMigrationStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  source/renderer/app/types/walletExportTypes.js
  storybook/stories/wallets/addWallet/Add.stories.js
  storybook/stories/wallets/export/WalletExportToFile.stories.js
  storybook/stories/wallets/import/WalletImportFile.stories.js
  storybook/stories/wallets/index.js
  tests/addresses/e2e/steps/addresses.js
  tests/common/e2e/steps/config.js
  tests/wallets/e2e/features/wallets-ordering.feature
  tests/wallets/e2e/steps/wallets.js
  utils/api-importer/byron-wallet-importer.js
  utils/cardano/selfnode/genesis.json
Labels: :hourglass_flowing_sand:release-vNext, feature

#1965 Merge release/1.0.0-FC3 into develop
  CHANGELOG.md
  nix/sources.json
Labels: :hourglass_flowing_sand:release-vNext, chore

#1887 [DDW-853] Update electron
  CHANGELOG.md
  default.nix
  installers/common/MacInstaller.hs
  installers/nix/electron.nix
  installers/nix/linux.nix
  nix/sources.json
  package.json
  release.nix
  shell.nix
  source/common/ipc/api.js
  source/common/ipc/lib/IpcConversation.js
  source/common/types/file-dialog.types.js
  source/common/types/logging.types.js
  source/main/cardano/utils.js
  source/main/index.js
  source/main/ipc/electronStoreConversation.js
  source/main/ipc/index.js
  source/main/ipc/lib/MainIpcConversation.js
  source/main/ipc/show-file-dialog-channels.js
  source/main/preload.js
  source/main/utils/buildAppMenus.js
  source/main/windows/main.js
  source/renderer/app/api/utils/localStorage.js
  source/renderer/app/components/status/DaedalusDiagnostics.scss
  source/renderer/app/components/wallet/settings/ExportWalletToFileDialog.js
  source/renderer/app/components/widgets/forms/FileUploadWidget.js
  source/renderer/app/containers/staking/StakingRewardsPage.js
  source/renderer/app/containers/wallet/WalletReceivePage.js
  source/renderer/app/containers/wallet/dialogs/paper-wallet-certificate/InstructionsDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/settings/ExportWalletToFileDialogContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/ipc/electronStoreConversation.js
  source/renderer/app/ipc/lib/RendererIpcConversation.js
  source/renderer/app/ipc/show-file-dialog-channels.js
  source/renderer/app/stores/AppStore.js
  source/renderer/app/stores/WalletMigrationStore.js
  source/renderer/app/utils/logging.js
  tests/settings/e2e/features/wallet-settings.feature
  tests/settings/e2e/steps/settings.js
  yarn.lock
  yarn2nix.nix
Labels: :hourglass_flowing_sand:release-vNext, dependencies

#1967 [DDW-159] Restore the "wallet migration" paragraph on the Daedalus Flight "Splash" screen
  CHANGELOG.md
  source/renderer/app/components/splash/SplashNetworkFlight.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#1970 Merge release/1.0.0-FC4 into develop
  CHANGELOG.md
  package.json
  source/renderer/app/stores/WalletsStore.js
Labels: :airplane: release-1.0.0-FC4, chore

#1968 [DDW-162, DDW-163] Fix 'Wallet import' UI/UX issues
  CHANGELOG.md
  source/common/ipc/api.js
  source/main/cardano/setup.js
  source/main/index.js
  source/main/ipc/getDesktopDirectoryPathChannel.js
  source/renderer/app/actions/wallet-migration-actions.js
  source/renderer/app/components/wallet/WalletAdd.js
  source/renderer/app/components/wallet/layouts/WalletWithNavigation.scss
  source/renderer/app/components/wallet/settings/WalletSettings.js
  source/renderer/app/components/wallet/settings/WalletSettings.scss
  source/renderer/app/components/wallet/wallet-import/WalletImportFileDialog.js
  source/renderer/app/components/wallet/wallet-import/WalletImportFileDialog.scss
  source/renderer/app/components/wallet/wallet-import/WalletSelectImportDialog.scss
  source/renderer/app/components/widgets/forms/InlineEditingInput.js
  source/renderer/app/components/widgets/forms/InlineEditingInput.scss
  source/renderer/app/containers/staking/StakingRewardsPage.js
  source/renderer/app/containers/wallet/WalletReceivePage.js
  source/renderer/app/containers/wallet/dialogs/WalletImportDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/paper-wallet-certificate/InstructionsDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/settings/ExportWalletToFileDialogContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/ipc/getDesktopDirectoryPathChannel.js
  source/renderer/app/stores/AppStore.js
  source/renderer/app/stores/ProfileStore.js
  source/renderer/app/stores/WalletMigrationStore.js
  storybook/stories/wallets/import/WalletImportFile.stories.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#1972 [DDW-156] Track cardano-node/jormungandr process instead of cardano-wallet
  CHANGELOG.md
  source/common/types/cardano-node.types.js
  source/main/cardano/CardanoNode.js
  source/main/cardano/setup.js
  source/main/cardano/utils.js
  source/main/index.js
  source/renderer/app/components/status/DaedalusDiagnostics.js
  tests/news/e2e/features/newsfeed.feature
  tests/nodes/e2e/features/data-layer-migration.feature
  tests/nodes/e2e/features/node-restart.feature
  tests/nodes/e2e/steps/daedalus-process.js
  tests/nodes/e2e/steps/node-restart.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#1979 [DDW-155] Persist "Blank screen fix" / "--safe-mode" flag between Daedalus restarts
  CHANGELOG.md
  nix/sources.json
Labels: :hourglass_flowing_sand:release-vNext, bug

#1971 [DDW-157] Update Daedalus installer file name
  CHANGELOG.md
  default.nix
  installers/common/Types.hs
  scripts/build-cross-windows.sh
Labels: :hourglass_flowing_sand:release-vNext, chore

#1980 [DDW-158] Update Cardano node / Cardano wallet info shown on the "Diagnostics" screen
  CHANGELOG.md
  source/common/types/cardano-node.types.js
  source/common/types/logging.types.js
  source/common/utils/environmentCheckers.js
  source/main/cardano/CardanoNode.js
  source/main/config.js
  source/main/index.js
  source/main/utils/setupLogging.js
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/containers/status/DaedalusDiagnosticsDialog.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/ProfileStore.js
  source/renderer/app/types/coreSystemInfoTypes.js
  storybook/stories/nodes/status/Diagnostics.stories.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#1984 [DDW-171] Treat wallets with 100% syncing progress as synced wallets
  CHANGELOG.md
  source/renderer/app/domains/Wallet.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#1985 [DDW-172] Handle duplicate wallets in import process
  CHANGELOG.md
  nix/sources.json
  source/renderer/app/actions/wallet-migration-actions.js
  source/renderer/app/components/wallet/wallet-import/WalletSelectImportDialog.js
  source/renderer/app/components/wallet/wallet-import/WalletSelectImportDialog.scss
  source/renderer/app/containers/wallet/dialogs/WalletImportDialogContainer.js
  source/renderer/app/stores/WalletMigrationStore.js
  source/renderer/app/types/walletExportTypes.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#1982 [DDW-168] Fix lock filename
  installers/common/WindowsInstaller.hs
  nix/sources.json
Labels: :hourglass_flowing_sand:release-vNext, bug

#1989 [DDW-172] Order exported wallets by ID
  CHANGELOG.md
  source/renderer/app/stores/WalletMigrationStore.js
Labels: :airplane: release-1.0.0-FC5, bug

#1991 [DDW-172] Improve wallet import
  CHANGELOG.md
  installers/common/WindowsInstaller.hs
  nix/sources.json
  source/main/cardano/utils.js
  source/renderer/app/actions/wallet-migration-actions.js
  source/renderer/app/components/wallet/wallet-import/WalletImportFileDialog.js
  source/renderer/app/components/wallet/wallet-import/WalletImportFileDialog.scss
  source/renderer/app/components/wallet/wallet-import/WalletSelectImportDialog.js
  source/renderer/app/components/wallet/wallet-import/WalletSelectImportDialog.scss
  source/renderer/app/containers/wallet/dialogs/WalletImportDialogContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/WalletMigrationStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  source/renderer/app/types/walletExportTypes.js
  storybook/stories/wallets/import/WalletImportFile.stories.js
Labels: :airplane: release-1.0.0-FC5, chore

#1993 Merge release/1.0.0-FC5 into develop
  CHANGELOG.md
  source/main/cardano/utils.js
  source/renderer/app/actions/wallet-migration-actions.js
  source/renderer/app/components/wallet/wallet-import/WalletImportFileDialog.js
  source/renderer/app/components/wallet/wallet-import/WalletImportFileDialog.scss
  source/renderer/app/components/wallet/wallet-import/WalletSelectImportDialog.js
  source/renderer/app/components/wallet/wallet-import/WalletSelectImportDialog.scss
  source/renderer/app/containers/wallet/dialogs/WalletImportDialogContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/WalletMigrationStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  source/renderer/app/types/walletExportTypes.js
  storybook/stories/wallets/import/WalletImportFile.stories.js
Labels: :airplane: release-1.0.0-FC5, chore

#1986 mac/windows: rename install/data dir to contain Mainnet
  CHANGELOG.md
  default.nix
  installers/common/MacInstaller.hs
  installers/common/WindowsInstaller.hs
  nix/cardano-bridge.nix
  nix/launcher-config.nix
  package.json
  release.nix
  source/common/utils/environmentCheckers.js
  source/main/cardano/utils.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#1983 [DDW-161] Fix theming issues on the wallet import overlays
  CHANGELOG.md
  source/renderer/app/components/settings/categories/DisplaySettings.js
  source/renderer/app/components/wallet/receive/WalletReceiveRandom.js
  source/renderer/app/components/wallet/receive/WalletReceiveRandom.scss
  source/renderer/app/components/wallet/wallet-import/WalletImportFileDialog.js
  source/renderer/app/components/wallet/wallet-import/WalletImportFileDialog.scss
  source/renderer/app/components/wallet/wallet-import/WalletSelectImportDialog.js
  source/renderer/app/components/wallet/wallet-import/WalletSelectImportDialog.scss
  source/renderer/app/components/widgets/forms/InlineEditingSmallInput.js
  source/renderer/app/components/widgets/forms/InlineEditingSmallInput.scss
  source/renderer/app/containers/wallet/WalletAddPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/stores/ProfileStore.js
  source/renderer/app/stores/WalletMigrationStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/overrides/CheckboxOverrides.scss
  source/renderer/app/themes/utils/createTheme.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#1996 [DDW] Implement NTP force check
  CHANGELOG.md
  nix/sources.json
  source/renderer/app/actions/network-status-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/api/network/requests/getNetworkClock.js
  source/renderer/app/api/utils/localStorage.js
  source/renderer/app/components/loading/system-time-error/SystemTimeError.scss
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/components/status/DaedalusDiagnostics.scss
  source/renderer/app/components/wallet/WalletSendConfirmationDialog.js
  source/renderer/app/containers/loading/SystemTimeErrorPage.js
  source/renderer/app/containers/status/DaedalusDiagnosticsDialog.js
  source/renderer/app/containers/wallet/dialogs/WalletSendConfirmationDialogContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/NetworkStatusStore.js
  storybook/stories/nodes/status/Diagnostics.stories.js
Labels: feature, release-1.0.0

#1997 Merge master into develop branch
  CHANGELOG.md
  nix/sources.json
  source/renderer/app/actions/network-status-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/api/network/requests/getNetworkClock.js
  source/renderer/app/api/utils/localStorage.js
  source/renderer/app/components/loading/system-time-error/SystemTimeError.scss
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/components/status/DaedalusDiagnostics.scss
  source/renderer/app/components/wallet/WalletSendConfirmationDialog.js
  source/renderer/app/containers/loading/SystemTimeErrorPage.js
  source/renderer/app/containers/status/DaedalusDiagnosticsDialog.js
  source/renderer/app/containers/wallet/dialogs/WalletSendConfirmationDialogContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/NetworkStatusStore.js
  storybook/stories/nodes/status/Diagnostics.stories.js
Labels: chore, release-1.0.0

#1990 Fix typos
  BESTPRACTICES.md
  default.nix
  gulpfile.js
  installers/common/WindowsInstaller.hs
  installers/data/scripts/dockutil
  installers/nix/nix-installer.nix
  installers/nsis_plugins/liteFirewall/src/ReadMe.txt
  source/common/ipc/api.js
  source/common/ipc/lib/IpcChannel.js
  source/common/ipc/lib/IpcConversation.js
  source/main/cardano/CardanoNode.js
  source/main/cardano/CardanoWalletLauncher.js
  source/main/config.js
  source/main/utils/setupLogging.js
  source/main/webpack.config.js
  source/renderer/app/App.js
  source/renderer/app/api/api.js
  source/renderer/app/components/notifications/Notification.js
  source/renderer/app/components/staking/delegation-center/UndelegateConfirmationDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsConfirmationDialog.js
  source/renderer/app/domains/News.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/AddressesStore.js
  source/renderer/app/stores/NewsFeedStore.js
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/utils/network.js
  source/renderer/app/utils/routing.js
  source/renderer/app/utils/validations.js
  utils/create-news-verification-hashes/index.js
  utils/jormungandr/selfnode/genesis.yaml
Labels: :hourglass_flowing_sand:release-vNext, chore

#2001 [DDW-175] Improve wallet import dialog state handling
  CHANGELOG.md
  source/renderer/app/components/wallet/wallet-import/WalletImportFileDialog.js
  source/renderer/app/containers/wallet/dialogs/WalletImportDialogContainer.js
  source/renderer/app/stores/WalletMigrationStore.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#1999 [SRE] cardano-wallet: fix git revision
  CHANGELOG.md
  nix/cardano-bridge.nix
Labels: :hourglass_flowing_sand:release-vNext, chore

#2002 [DDW-176] Improve delegation fee calculation
  CHANGELOG.md
  source/renderer/app/components/staking/delegation-center/UndelegateConfirmationDialog.js
  source/renderer/app/components/staking/delegation-center/UndelegateConfirmationDialog.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsConfirmationDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsConfirmationDialog.scss
  source/renderer/app/containers/staking/DelegationCenterPage.js
  source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
  source/renderer/app/containers/staking/dialogs/UndelegateDialogContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/StakingStore.js
  tests/delegation/e2e/steps/delegation.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#1947 [SRE-86] Block installing on anything older than Windows 8.1
  CHANGELOG.md
  installers/common/WindowsInstaller.hs
Labels: :hourglass_flowing_sand:release-vNext, chore

#2004 [DDW-184] Updates cardano-wallet and cardano-node versions
  CHANGELOG.md
  nix/cardano-bridge.nix
  nix/sources.json
  source/main/environment.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2005 [DDW-177] Fixed Daedalus logo animation display on macOS
  CHANGELOG.md
  source/renderer/app/components/loading/syncing-connecting/LogosDisplay.scss
  source/renderer/app/components/loading/syncing-connecting/SyncingConnecting.js
  source/renderer/app/components/loading/syncing-connecting/SyncingConnecting.scss
  source/renderer/app/components/loading/syncing-connecting/SyncingConnectingStatus.scss
  source/renderer/app/components/notifications/LegacyNotification.scss
  source/renderer/app/components/staking/delegation-center/UndelegateConfirmationDialog.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsConfirmationDialog.scss
  source/renderer/app/components/staking/epochs/StakingEpochs.scss
  source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.scss
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/stores/NodeUpdateStore.js
Labels: :hourglass_flowing_sand:release-vNext, bug
