Repository input-output-hk/daedalus, pull requests merged in 2021-02, with the labels that each got.

#2325 [DDW-557] Update cardano-wallet
  CHANGELOG.md
  nix/sources.json
  source/main/environment.js
  source/renderer/app/api/api.js
  source/renderer/app/api/network/types.js
  source/renderer/app/components/layout/TopBar.js
  source/renderer/app/components/staking/redeem-itn-rewards/Step1ConfigurationDialog.scss
  source/renderer/app/config/walletsConfig.js
  source/renderer/app/containers/staking/StakingRewardsPage.js
  source/renderer/app/containers/staking/dialogs/redeem-itn-rewards/Step3ResultContainer.js
  source/renderer/app/stores/StakingStore.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2313 [DDW-504] Number format for syncing percentage and stake pools
  CHANGELOG.md
  source/renderer/app/components/notifications/RestoreNotification.js
  source/renderer/app/components/staking/stake-pools/StakePools.js
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/components/widgets/NodeSyncStatusIcon.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/utils/formatters.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2330 [DDW-507] Closing delegation wizard while transaction fees are being calculated throws error in the console
  CHANGELOG.md
  source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2335 [DDW-545] Remove step counter from the wallet restoration "success" dialog step
  CHANGELOG.md
  source/renderer/app/components/wallet/wallet-restore/widgets/WalletRestoreDialog.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2333 [DDW-551] Adjust sorting on rewards screen
  CHANGELOG.md
  source/renderer/app/components/staking/rewards/StakingRewards.js
  source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/utils/sortComparators.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2334 [DDW-548] Update recovery phrase input placeholder
  CHANGELOG.md
  source/renderer/app/components/wallet/WalletRestoreDialog.js
  source/renderer/app/components/wallet/backup-recovery/WalletRecoveryPhraseEntryDialog.js
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseStep2Dialog.js
  source/renderer/app/components/wallet/wallet-restore/MnemonicsDialog.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: :hourglass_flowing_sand:release-vNext, chore

#2337 [DDW-528] Spacing issues with "i" icon on "Set password" dialog
  CHANGELOG.md
  source/renderer/app/components/wallet/settings/ChangeSpendingPasswordDialog.js
  source/renderer/app/components/wallet/settings/ChangeSpendingPasswordDialog.scss
Labels: :hourglass_flowing_sand:release-vNext, bug

#2336 [DDW-533] Add "Fix connection Issues" link to the hardware wallet pairing dialog
  CHANGELOG.md
  source/renderer/app/components/wallet/WalletConnectDialog.js
  source/renderer/app/components/wallet/WalletConnectDialog.scss
  source/renderer/app/containers/wallet/dialogs/WalletConnectDialogContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: :hourglass_flowing_sand:release-vNext, chore

#2331 [DDW-512] Implement dynamic TTL for HW transactions
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/api/network/types.js
  source/renderer/app/api/utils/patchAdaApi.js
  source/renderer/app/config/txnsConfig.js
  source/renderer/app/stores/HardwareWalletsStore.js
  storybook/stories/nodes/status/Diagnostics.stories.js
  storybook/stories/staking/DelegationCenter.stories.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2332 [DDW-559] Implement delegation deposit from coin selection
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/api/transactions/types.js
  source/renderer/app/config/stakingConfig.js
  source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2339 [DDW-522] Display fee and deposit on transaction details and delegation modal
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/api/staking/types.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationSetupWizardDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsConfirmationDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsConfirmationDialog.scss
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/components/wallet/transactions/Transaction.scss
  source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
  source/renderer/app/domains/WalletTransaction.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/shelley-testnet.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/_support/utils.js
  storybook/stories/wallets/_utils/WalletsTransactionsWrapper.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2338 [DDW-521] Display Transaction Metadata
  CHANGELOG.md
  package.json
  source/renderer/app/api/api.js
  source/renderer/app/api/transactions/types.js
  source/renderer/app/api/utils/request.js
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/components/wallet/transactions/Transaction.scss
  source/renderer/app/components/wallet/transactions/WalletTransactionsList.js
  source/renderer/app/components/wallet/transactions/metadata/MetadataValueView.js
  source/renderer/app/components/wallet/transactions/metadata/TransactionMetadataView.js
  source/renderer/app/components/wallet/transactions/metadata/TransactionMetadataView.scss
  source/renderer/app/components/wallet/transactions/render-strategies/VirtualTransactionList.js
  source/renderer/app/domains/WalletTransaction.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/types/TransactionMetadata.js
  source/renderer/app/utils/transaction.js
  storybook/stories/_support/utils.js
  storybook/stories/wallets/index.js
  storybook/stories/wallets/transactions/TransactionMetadata.stories.js
  storybook/stories/wallets/transactions/TransactionsList.stories.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext, feature

#2341 [DDW-562] Fix the count of packed cardano-wallet logs
  CHANGELOG.md
  source/main/config.js
  source/main/ipc/get-logs.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2353 [VIT-895] Fix Catalyst Android app download link
  CHANGELOG.md
  source/renderer/app/components/voting/VotingInfo.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: bug, release-3.3.0

#2354 [DDW-541] Updates voting minimum registration amount
  CHANGELOG.md
  source/renderer/app/config/votingConfig.js
Labels: chore, release-3.3.0

#2308 [DDW-563] Re-enable wallet import feature
  CHANGELOG.md
  source/main/cardano/utils.js
  source/main/config.js
  source/main/utils/restoreKeystore.js
  source/renderer/app/components/wallet/WalletAdd.js
  source/renderer/app/components/wallet/wallet-import/WalletSelectImportDialog.js
  source/renderer/app/components/wallet/wallet-import/WalletSelectImportDialog.scss
  source/renderer/app/config/walletsConfig.js
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/WalletMigrationStore.js
  source/renderer/app/types/walletExportTypes.js
Labels: feature, release-3.3.0

#2342 [DDW-553] Hardware Wallets - Force Public Key export
  CHANGELOG.md
  source/renderer/app/stores/HardwareWalletsStore.js
Labels: chore, release-3.3.0

#2356 [DDW-568] Update cardano-wallet
  CHANGELOG.md
  nix/sources.json
  source/renderer/app/api/api.js
  source/renderer/app/stores/StakingStore.js
Labels: chore, release-3.3.0

#2290 [DDW-452] Show ada amounts in other currencies
  CHANGELOG.md
  source/common/config/electron-store.config.js
  source/common/types/electron-store.types.js
  source/renderer/app/Routes.js
  source/renderer/app/actions/wallets-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/api/utils/localStorage.js
  source/renderer/app/api/wallets/requests/getCurrencyList.js
  source/renderer/app/api/wallets/requests/getCurrencyRate.js
  source/renderer/app/api/wallets/types.js
  source/renderer/app/assets/images/currency-settings-ic.inline.svg
  source/renderer/app/components/settings/categories/WalletsSettings.js
  source/renderer/app/components/settings/categories/WalletsSettings.scss
  source/renderer/app/components/settings/menu/SettingsMenu.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsConfirmationDialog.js
  source/renderer/app/components/wallet/summary/WalletSummary.js
  source/renderer/app/components/wallet/summary/WalletSummary.scss
  source/renderer/app/config/currenciesList.json
  source/renderer/app/config/currencyConfig.coinapi.js
  source/renderer/app/config/currencyConfig.coingecko.js
  source/renderer/app/config/currencyConfig.js
  source/renderer/app/config/currencyConfig.nomics.js
  source/renderer/app/config/urlsConfig.js
  source/renderer/app/config/walletsConfigCurrenciesList.dummy.json
  source/renderer/app/containers/settings/categories/WalletsSettingsPage.js
  source/renderer/app/containers/wallet/WalletSummaryPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/routes-config.js
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/types/currencyTypes.js
  source/renderer/app/utils/formatters.js
  storybook/stories/settings/general/General.stories.js
  storybook/stories/wallets/_utils/currencies.json
  storybook/stories/wallets/summary/WalletSummary.stories.js
Labels: feature, release-3.3.0

#2352 [DDW-527] Fixes the automatic update failure
  CHANGELOG.md
  source/renderer/app/stores/AppUpdateStore.js
Labels: bug, release-3.3.0

#2361 Merge release/3.3.0-FC1 into develop
  CHANGELOG.md
  package.json
  source/renderer/app/stores/SidebarStore.js
Labels: :airplane: release-3.3.0-FC1, chore

#2355 [DDW-555] Improve URL validation on Stake Pools
  CHANGELOG.md
  source/renderer/app/components/settings/categories/StakePoolsSettings.js
  source/renderer/app/components/widgets/forms/InlineEditingInput.js
  source/renderer/app/config/stakingConfig.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/utils/staking.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2358 [DDW-568] Update cardano-wallet to v2021-02-12
  CHANGELOG.md
  nix/sources.json
Labels: :hourglass_flowing_sand:release-vNext, chore

#2363 [DDW-574] Update cardano-wallet and cardano-launcher
  CHANGELOG.md
  README.md
  default.nix
  nix/sources.json
  package.json
  shell.nix
  source/main/cardano/CardanoWalletLauncher.js
  source/main/config.js
  source/main/webpack.config.js
  utils/cardano/native-tokens/registry.json
  yarn.lock
Labels: chore, release-3.3.0

#2369 Fix Hardware Wallets delegation
  CHANGELOG.md
  source/renderer/app/stores/HardwareWalletsStore.js
Labels: bug, release-3.3.0

#2376 Merge release/3.3.0 into develop
  CHANGELOG.md
  package.json
  source/renderer/app/stores/HardwareWalletsStore.js
  source/renderer/app/stores/SidebarStore.js
Labels: chore, release-3.3.0

#2379 [DDW-578] Wallet send form does not work with certain amounts
  CHANGELOG.md
  source/renderer/app/components/wallet/WalletSendForm.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2371 [DDW-544] Fix broken stake pool tooltip stories
  CHANGELOG.md
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsConfirmationDialog.js
  source/renderer/app/components/staking/widgets/TooltipPool.js
  source/renderer/app/utils/formatters.js
  storybook/stories/staking/DelegationSteps.stories.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2372 [DDW-564] Update link based on net on app update overlay
  CHANGELOG.md
  source/renderer/app/components/appUpdate/AppUpdateOverlay.js
  source/renderer/app/containers/appUpdate/AppUpdateContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  storybook/stories/news/AppUpdateOverlay.stories.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2380 [DDW-456] Add missing space for amount + "ADA" [Japanese]
  CHANGELOG.md
  source/renderer/app/config/urlsConfig.js
  source/renderer/app/i18n/locales/ja-JP.json
Labels: :hourglass_flowing_sand:release-vNext, chore

#2370 [DDW-546] Select whole addresses and ids when selecting them to copy
  CHANGELOG.md
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/components/widgets/WholeSelectionText.js
  source/renderer/app/i18n/locales/defaultMessages.json
Labels: :hourglass_flowing_sand:release-vNext, chore

#2387 [DDW-556] The calendar is displayed inside the "Filter" modal
  CHANGELOG.md
  source/renderer/app/components/wallet/transactions/FilterDialog.scss
Labels: :hourglass_flowing_sand:release-vNext, bug

#2351 [DDW-149] Undelegating a wallet
  CHANGELOG.md
  source/renderer/app/actions/wallets-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/api/staking/types.js
  source/renderer/app/api/transactions/types.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsConfirmationDialog.js
  source/renderer/app/components/wallet/settings/DelegateWalletButton.js
  source/renderer/app/components/wallet/settings/DelegateWalletButton.scss
  source/renderer/app/components/wallet/settings/UndelegateWalletButton.js
  source/renderer/app/components/wallet/settings/UndelegateWalletButton.scss
  source/renderer/app/components/wallet/settings/UndelegateWalletConfirmationDialog.js
  source/renderer/app/components/wallet/settings/UndelegateWalletConfirmationDialog.scss
  source/renderer/app/components/wallet/settings/UndelegateWalletSuccessDialog.js
  source/renderer/app/components/wallet/settings/UndelegateWalletSuccessDialog.scss
  source/renderer/app/components/wallet/settings/WalletSettings.js
  source/renderer/app/components/wallet/settings/WalletSettings.scss
  source/renderer/app/components/widgets/forms/WalletsDropdown.js
  source/renderer/app/config/stakingConfig.js
  source/renderer/app/config/walletsConfig.js
  source/renderer/app/containers/staking/DelegationCenterPage.js
  source/renderer/app/containers/staking/Staking.js
  source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
  source/renderer/app/containers/staking/dialogs/UndelegateDialogContainer.js
  source/renderer/app/containers/wallet/WalletSettingsPage.js
  source/renderer/app/containers/wallet/dialogs/settings/UndelegateWalletDialogContainer.js
  source/renderer/app/domains/Wallet.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/shelley-testnet.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/_support/utils.js
  storybook/stories/staking/DelegationSteps.stories.js
  storybook/stories/staking/Staking.stories.js
  storybook/stories/staking/Undelegate.stories.js
  storybook/stories/wallets/settings/WalletSettingsScreen.stories.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2381 [DDW-573] Update Ledger and Trezor JS libraries
  CHANGELOG.md
  installers/common/MacInstaller.hs
  netlify.toml
  package.json
  source/common/types/hardware-wallets.types.js
  source/main/ipc/getHardwareWalletChannel.js
  source/renderer/app/api/transactions/types.js
  source/renderer/app/config/hardwareWalletsConfig.js
  source/renderer/app/stores/HardwareWalletsStore.js
  source/renderer/app/utils/shelleyLedger.js
  source/renderer/app/utils/shelleyTrezor.js
  yarn.lock
  yarn2nix.nix
Labels: :hourglass_flowing_sand:release-vNext, chore

#2386 [DDW-550] Hover not working properly on the first tile in the delegation center
  CHANGELOG.md
  package.json
  source/renderer/app/components/staking/delegation-center/WalletRow.js
  source/renderer/app/components/staking/delegation-center/WalletRow.scss
  source/renderer/app/components/staking/delegation-center/WalletRowPopOverOverrides.scss
  source/renderer/app/i18n/locales/defaultMessages.json
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext, chore

#2406 Merge release/3.3.1 into develop
  CHANGELOG.md
  package.json
Labels: chore, release-3.3.1

#2404 [DDW-579] Undelegated wallet shown as delegated on "Delegation center" screen
  CHANGELOG.md
  source/renderer/app/components/staking/delegation-center/WalletRow.js
  source/renderer/app/i18n/locales/defaultMessages.json
Labels: :hourglass_flowing_sand:release-vNext, chore

#2400 launcher-config: remove socketFile
  CHANGELOG.md
  nix/launcher-config.nix
Labels: :hourglass_flowing_sand:release-vNext, chore

#2409 [DDW-560] Red outlining in "Wallet Name" input
  CHANGELOG.md
  source/renderer/app/components/widgets/forms/InlineEditingInput.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2408 [DDW-584] Apply withdrawals to Hardware Wallets
  CHANGELOG.md
  nix/sources.json
  source/common/types/hardware-wallets.types.js
  source/main/ipc/getHardwareWalletChannel.js
  source/renderer/app/api/api.js
  source/renderer/app/api/transactions/requests/selectCoins.js
  source/renderer/app/api/transactions/types.js
  source/renderer/app/stores/HardwareWalletsStore.js
  source/renderer/app/utils/shelleyLedger.js
  source/renderer/app/utils/shelleyTrezor.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2401 [DDW-569] Move ITN redemption to Daedalus application menu
  CHANGELOG.md
  source/common/ipc/api.js
  source/common/ipc/constants.js
  source/main/index.js
  source/main/locales/en-US.json
  source/main/locales/ja-JP.json
  source/main/menus/MenuActions.types.js
  source/main/menus/osx.js
  source/main/menus/win-linux.js
  source/main/utils/buildAppMenus.js
  source/renderer/app/assets/images/sidebar/redeem-itn-rewards-ic.inline.svg
  source/renderer/app/config/sidebarConfig.js
  source/renderer/app/containers/MainLayout.js
  source/renderer/app/containers/profile/InitialSettingsPage.js
  source/renderer/app/containers/settings/categories/GeneralSettingsPage.js
  source/renderer/app/containers/staking/RedeemItnRewardsContainer.js
  source/renderer/app/stores/AppStore.js
  source/renderer/app/stores/AppUpdateStore.js
  source/renderer/app/stores/SidebarStore.js
Labels: :hourglass_flowing_sand:release-vNext, chore
