Repository input-output-hk/daedalus, pull requests merged in 2021-04, with the labels that each got.

#2495 [DDW-634] Update Catalyst Fund4 dates
  CHANGELOG.md
  nix/sources.json
  source/renderer/app/config/votingConfig.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2499 Merge release/4.0.4 into develop
  CHANGELOG.md
  package.json
  source/renderer/app/config/stakingConfig.js
Labels: chore, release-4.0.4

#2500 Merge release/4.0.4 into master
  CHANGELOG.md
  package.json
  source/renderer/app/api/staking/types.js
  source/renderer/app/components/staking/rewards/StakingRewards.js
  source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.js
  source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.scss
  source/renderer/app/config/stakingConfig.js
  source/renderer/app/config/stakingRewards.dummy.json
  source/renderer/app/containers/staking/StakingRewardsPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/AddressesStore.js
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/stores/VotingStore.js
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/utils/crypto.js
  storybook/stories/staking/RewardsForIncentivizedTestnet.stories.js
  tls/client/ca.crt
  tls/client/client.crt
  tls/client/client.key
  tls/client/client.pem
  tls/server/ca.crt
  tls/server/server.crt
  tls/server/server.key
  tls/server/server.pem
Labels: release-4.0.4

#2503 [DDW-638] Handle empty strings in tx metadata
  CHANGELOG.md
  source/renderer/app/components/wallet/transactions/metadata/TransactionMetadataView.js
  storybook/stories/_support/utils.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2510 [DDW-636] Reduce the clock drift tolerance to 4,5 seconds
  CHANGELOG.md
  source/renderer/app/config/timingConfig.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2509 [DDW-453] Earned delegation rewards "export CSV" button update styles
  CHANGELOG.md
  source/renderer/app/components/staking/layouts/StakingWithNavigation.js
  source/renderer/app/components/staking/layouts/StakingWithNavigation.scss
  source/renderer/app/components/staking/rewards/StakingRewards.js
  source/renderer/app/components/staking/rewards/StakingRewards.scss
  source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.js
  source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.scss
  source/renderer/app/i18n/locales/defaultMessages.json
Labels: :hourglass_flowing_sand:release-vNext, chore

#2501 [DDW-613] Fix "Send form" fee calculation edge-cases
  CHANGELOG.md
  source/renderer/app/components/wallet/WalletSendForm.js
  source/renderer/app/utils/formatters.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2517 [DDW-648] Fix stake pools list cutting off items
  CHANGELOG.md
  package.json
  source/renderer/app/components/staking/stake-pools/StakePoolsList.js
  source/renderer/app/components/staking/stake-pools/StakePoolsList.scss
Labels: :hourglass_flowing_sand:release-vNext, bug

#2497 [DDW-621] Improve currency Japanese translations
  CHANGELOG.md
  source/renderer/app/actions/wallets-actions.js
  source/renderer/app/api/wallets/types.js
  source/renderer/app/components/settings/categories/WalletsSettings.js
  source/renderer/app/components/wallet/send-form/WalletSendAssetsConfirmationDialog.js
  source/renderer/app/components/wallet/send-form/WalletSendConfirmationDialog.js
  source/renderer/app/components/wallet/summary/WalletSummaryCurrency.js
  source/renderer/app/components/wallet/summary/WalletSummaryHeader.js
  source/renderer/app/config/currenciesList.json
  source/renderer/app/config/currencyConfig.coinapi.js
  source/renderer/app/config/currencyConfig.coingecko.js
  source/renderer/app/config/currencyConfig.js
  source/renderer/app/config/currencyConfig.nomics.js
  source/renderer/app/containers/settings/categories/WalletsSettingsPage.js
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/types/currencyTypes.js
  source/renderer/app/utils/formatters.js
  storybook/stories/settings/general/General.stories.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2518 [DDW-651] Implement 'Voting registration unavailable' screen
  CHANGELOG.md
  source/renderer/app/components/voting/VotingUnavailable.js
  source/renderer/app/components/voting/VotingUnavailable.scss
  source/renderer/app/config/votingConfig.js
  source/renderer/app/containers/voting/VotingRegistrationPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: feature, release-4.0.5

#2520 [DDW-652] Hardware Wallets spending password issue with Trezor
  CHANGELOG.md
  source/renderer/app/api/api.js
  source/renderer/app/stores/HardwareWalletsStore.js
  source/renderer/app/stores/WalletsStore.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2521 Merge release/4.0.5 into master
  CHANGELOG.md
  nix/sources.json
  package.json
  source/renderer/app/actions/wallets-actions.js
  source/renderer/app/api/wallets/types.js
  source/renderer/app/components/settings/categories/WalletsSettings.js
  source/renderer/app/components/staking/layouts/StakingWithNavigation.js
  source/renderer/app/components/staking/layouts/StakingWithNavigation.scss
  source/renderer/app/components/staking/rewards/StakingRewards.js
  source/renderer/app/components/staking/rewards/StakingRewards.scss
  source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.js
  source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsList.js
  source/renderer/app/components/staking/stake-pools/StakePoolsList.scss
  source/renderer/app/components/voting/VotingInfo.js
  source/renderer/app/components/voting/VotingNoWallets.js
  source/renderer/app/components/voting/VotingUnavailable.js
  source/renderer/app/components/voting/VotingUnavailable.scss
  source/renderer/app/components/voting/voting-registration-wizard-steps/VotingRegistrationStepsEnterPinCode.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/VotingRegistrationStepsQrCode.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/VotingRegistrationStepsRegister.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/widgets/ConfirmationDialog.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/widgets/VotingRegistrationDialog.js
  source/renderer/app/components/wallet/WalletSendForm.js
  source/renderer/app/components/wallet/send-form/WalletSendAssetsConfirmationDialog.js
  source/renderer/app/components/wallet/send-form/WalletSendConfirmationDialog.js
  source/renderer/app/components/wallet/summary/WalletSummaryCurrency.js
  source/renderer/app/components/wallet/summary/WalletSummaryHeader.js
  source/renderer/app/components/wallet/transactions/metadata/TransactionMetadataView.js
  source/renderer/app/config/currenciesList.json
  source/renderer/app/config/currencyConfig.coinapi.js
  source/renderer/app/config/currencyConfig.coingecko.js
  source/renderer/app/config/currencyConfig.js
  source/renderer/app/config/currencyConfig.nomics.js
  source/renderer/app/config/timingConfig.js
  source/renderer/app/config/votingConfig.js
  source/renderer/app/containers/settings/categories/WalletsSettingsPage.js
  source/renderer/app/containers/voting/VotingRegistrationPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/types/currencyTypes.js
  source/renderer/app/utils/formatters.js
  storybook/stories/_support/utils.js
  storybook/stories/settings/general/General.stories.js
Labels: release-4.0.5

#2525 [DDW-577] Daedalus confirmation for HW crashes after unlocking the device for inactivity
  CHANGELOG.md
  source/renderer/app/stores/HardwareWalletsStore.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2529 [DDW-657] Fix blank currency selection after updating to 4.0.5
  CHANGELOG.md
  source/renderer/app/api/utils/localStorage.js
  source/renderer/app/config/currencyConfig.js
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/types/currencyTypes.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2530 [DDW-655] Update and migrate Ledger JS library to version 3.0.0.
  CHANGELOG.md
  package.json
  source/common/types/hardware-wallets.types.js
  source/main/ipc/getHardwareWalletChannel.js
  source/renderer/app/stores/HardwareWalletsStore.js
  source/renderer/app/utils/shelleyLedger.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext, chore

#2534 [DDW-658] Update trezor-connect dependency to version 8.1.26
  CHANGELOG.md
  package.json
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext, chore

#2459 [DDW-603] Enable pasting of wallet recovery phrase
  CHANGELOG.md
  package.json
  source/renderer/app/components/wallet/wallet-restore/MnemonicsDialog.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext, feature

#2512 [DDW-645] Update react-polymorph and implement the search style variables
  CHANGELOG.md
  package.json
  source/renderer/app/components/settings/categories/WalletsSettings.js
  source/renderer/app/components/settings/categories/WalletsSettings.scss
  source/renderer/app/containers/settings/categories/WalletsSettingsPage.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/shelley-testnet.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/overrides/OptionsOverrides.scss
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/settings/general/General.stories.js
  storybook/stories/wallets/_utils/currencies.json
  storybook/stories/wallets/summary/WalletSummary.stories.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext, feature

#2506 [DDW-595] Warn user when pasting an address of the same wallet
  CHANGELOG.md
  package.json
  source/renderer/app/components/wallet/WalletSendForm.js
  source/renderer/app/components/wallet/WalletSendForm.scss
  source/renderer/app/components/wallet/send-form/AssetInput.js
  source/renderer/app/components/wallet/send-form/messages.js
  source/renderer/app/containers/wallet/WalletSendPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/themes/overrides/OptionsOverrides.scss
  storybook/stories/wallets/send/WalletSend.stories.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext, DO NOT MERGE, feature
