Repository input-output-hk/daedalus, pull requests merged in 2021-07, with the labels that each got.

#2609 [DDW-711] Fix asset search in Japanese
  CHANGELOG.md
  source/renderer/app/components/wallet/summary/WalletSummaryAssets.scss
Labels: :airplane: release-4.2.0-FC1, bug

#2614 Merge release/4.2.0-FC1 into develop
  CHANGELOG.md
  package.json
  source/renderer/app/components/wallet/summary/WalletSummaryAssets.scss
Labels: :airplane: release-4.2.0-FC1, chore

#2538 [DDW-639] Fund5 voting registration with Ledger
  CHANGELOG.md
  package.json
  source/common/types/hardware-wallets.types.js
  source/main/ipc/getHardwareWalletChannel.js
  source/renderer/app/actions/voting-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/api/transactions/requests/selectCoins.js
  source/renderer/app/api/transactions/types.js
  source/renderer/app/components/voting/VotingRegistrationDialogWizard.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/VotingRegistrationStepsChooseWallet.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/VotingRegistrationStepsRegister.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/VotingRegistrationStepsRegister.scss
  source/renderer/app/config/hardwareWalletsConfig.js
  source/renderer/app/config/votingConfig.js
  source/renderer/app/containers/voting/dialogs/VotingRegistrationDialogContainer.js
  source/renderer/app/stores/HardwareWalletsStore.js
  source/renderer/app/stores/SidebarStore.js
  source/renderer/app/stores/VotingStore.js
  source/renderer/app/utils/hardwareWalletUtils.js
  source/renderer/app/utils/shelleyLedger.js
  storybook/stories/voting/Voting.stories.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext, feature

#2615 [DDW-640] Fund5 voting registration with Trezor
  CHANGELOG.md
  package.json
  source/common/types/hardware-wallets.types.js
  source/main/ipc/getHardwareWalletChannel.js
  source/renderer/app/components/voting/VotingRegistrationDialogWizard.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/VotingRegistrationStepsChooseWallet.js
  source/renderer/app/config/hardwareWalletsConfig.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/HardwareWalletsStore.js
  source/renderer/app/utils/shelleyTrezor.js
  storybook/stories/voting/Voting.stories.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext, feature

#2619 Merge release/4.2.0 into develop
  CHANGELOG.md
  package.json
  source/renderer/app/stores/SidebarStore.js
Labels: chore, release-4.2.0

#2621 [DDW-715] Enter key not working on send
  CHANGELOG.md
  source/renderer/app/components/wallet/WalletSendForm.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2625 [DDW-713] Remove "Decentralization countdown" tada icon and info tab
  CHANGELOG.md
  source/renderer/app/components/staking/navigation/StakingNavigation.js
  source/renderer/app/containers/TopBarContainer.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2617 [DDW-706] Emptying wallet - warning
  .babelrc
  .flowconfig
  CHANGELOG.md
  source/renderer/app/api/assets/types.js
  source/renderer/app/components/wallet/WalletSendForm.js
  source/renderer/app/components/wallet/WalletSendForm.scss
  source/renderer/app/components/wallet/send-form/WalletSendAssetsConfirmationDialog.js
  source/renderer/app/components/wallet/send-form/WalletSendAssetsConfirmationDialog.messages.js
  source/renderer/app/components/wallet/send-form/WalletSendAssetsConfirmationDialog.scss
  source/renderer/app/components/wallet/send-form/WalletSendConfirmationDialog.js
  source/renderer/app/components/wallet/send-form/WalletSendConfirmationDialog.messages.js
  source/renderer/app/components/wallet/send-form/WalletSendConfirmationDialog.scss
  source/renderer/app/components/wallet/settings/WalletSettings.js
  source/renderer/app/containers/wallet/WalletSettingsPage.js
  source/renderer/app/containers/wallet/dialogs/WalletSendConfirmationDialogContainer.js
  source/renderer/app/domains/Wallet.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/utils/assets.js
  source/renderer/app/utils/walletUtils.js
  storybook/stories/wallets/send/WalletSend.stories.js
  storybook/stories/wallets/settings/WalletSettingsScreen.stories.js
Labels: :hourglass_flowing_sand:release-vNext, feature
