Repository input-output-hk/daedalus, pull requests merged in 2021-06, with the labels that each got.

#2580 [DDW-697] "An error occurred" is displayed when trying to reveal the public key
  CHANGELOG.md
  source/renderer/app/api/wallets/requests/getAccountPublicKey.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2581 Merge release/4.1.0-FC1 into develop
  CHANGELOG.md
  source/renderer/app/api/wallets/requests/getAccountPublicKey.js
  source/renderer/app/config/votingConfig.js
  source/renderer/app/stores/SidebarStore.js
Labels: :airplane: release-4.1.0-FC1, chore

#2586 Merge release/4.1.0 into develop
  CHANGELOG.md
  package.json
  source/renderer/app/config/votingConfig.js
  source/renderer/app/stores/SidebarStore.js
Labels: chore, release-4.1.0

#2582 [DDW-698] Can't insert notes on "Share Wallet Address" dialog for software wallets
  CHANGELOG.md
  source/renderer/app/components/wallet/receive/WalletReceiveDialog.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2594 [DDW-699] Fix Trezor transaction native tokens grouping issue
  CHANGELOG.md
  source/renderer/app/utils/hardwareWalletUtils.js
  source/renderer/app/utils/shelleyLedger.js
  source/renderer/app/utils/shelleyTrezor.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2595 [DDW-692] Property error when delegating on shelley qa
  CHANGELOG.md
  source/renderer/app/components/staking/stake-pools/StakePoolsList.js
Labels: bug

#2593 [DDW-659] Review and fix incorrect :global instances in scss files
  CHANGELOG.md
  source/renderer/app/components/appUpdate/AppUpdateOverlay.scss
  source/renderer/app/components/assets/Asset.js
  source/renderer/app/components/assets/Asset.scss
  source/renderer/app/components/loading/syncing-connecting/SyncingConnecting.scss
  source/renderer/app/components/navigation/NavDropdown.scss
  source/renderer/app/components/notifications/Notification.scss
  source/renderer/app/components/profile/terms-of-use/TermsOfUseForm.scss
  source/renderer/app/components/settings/categories/StakePoolsSettings.scss
  source/renderer/app/components/sidebar/wallets/SidebarWalletMenuItem.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.scss
  source/renderer/app/components/staking/epochs/StakingEpochs.scss
  source/renderer/app/components/staking/info/StakingInfo.scss
  source/renderer/app/components/staking/info/StakingInfoCountdown.scss
  source/renderer/app/components/staking/legacy/StakingChart.scss
  source/renderer/app/components/staking/redeem-itn-rewards/NoWalletsDialog.js
  source/renderer/app/components/staking/redeem-itn-rewards/NoWalletsDialog.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsList.scss
  source/renderer/app/components/status/DaedalusDiagnostics.scss
  source/renderer/app/components/voting/VotingInfo.scss
  source/renderer/app/components/voting/voting-registration-wizard-steps/VotingRegistrationStepsConfirm.js
  source/renderer/app/components/wallet/receive/AddressSequential.scss
  source/renderer/app/components/wallet/receive/WalletReceiveDialog.scss
  source/renderer/app/components/wallet/receive/WalletReceiveRandom.scss
  source/renderer/app/components/wallet/transactions/FilterDialog.scss
  source/renderer/app/components/wallet/transactions/WalletTransactionsList.scss
  source/renderer/app/components/wallet/transactions/render-strategies/VirtualTransactionList.scss
  source/renderer/app/components/wallet/utxo/WalletUtxo.scss
  source/renderer/app/components/widgets/NewsFeedIcon.scss
  source/renderer/app/components/widgets/NodeSyncStatusIcon.scss
  source/renderer/app/components/widgets/Slider.scss
  source/renderer/app/components/widgets/forms/InlineEditingInput.scss
  source/renderer/app/components/widgets/forms/TinyDatePicker.scss
  source/renderer/app/containers/static/AboutDialog.scss
  source/renderer/app/themes/index.global.scss
Labels: :hourglass_flowing_sand:release-vNext, bug

#2589 [DDW-587] Implement expandable Token view
  CHANGELOG.md
  source/renderer/app/assets/images/collapse-arrow-small.inline.svg
  source/renderer/app/components/assets/Asset.js
  source/renderer/app/components/assets/Asset.scss
  source/renderer/app/components/assets/AssetAmount.js
  source/renderer/app/components/assets/AssetContent.js
  source/renderer/app/components/assets/AssetContent.scss
  source/renderer/app/components/wallet/summary/WalletSummary.js
  source/renderer/app/components/wallet/summary/WalletSummaryAsset.js
  source/renderer/app/components/wallet/summary/WalletSummaryAsset.scss
  source/renderer/app/components/wallet/summary/WalletSummaryAssets.js
  source/renderer/app/components/wallet/summary/WalletSummaryAssets.scss
  source/renderer/app/components/widgets/forms/AssetsDropdown.js
  source/renderer/app/containers/wallet/WalletSummaryPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/utils/formatters.js
  storybook/stories/wallets/summary/WalletSummary.stories.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2472 [DDW-618] Fix asset amount validation
  CHANGELOG.md
  source/renderer/app/api/utils/request.js
  source/renderer/app/components/wallet/WalletSendForm.js
  source/renderer/app/containers/wallet/WalletSendPage.js
  source/renderer/app/stores/TransactionsStore.js
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/utils/validations.js
  storybook/stories/wallets/send/WalletSend.stories.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2608 [DDW-708] Set up Fund5 voting registration
  CHANGELOG.md
  source/renderer/app/components/voting/VotingInfo.js
  source/renderer/app/components/voting/VotingNoWallets.js
  source/renderer/app/components/voting/VotingUnavailable.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/VotingRegistrationStepsConfirm.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/VotingRegistrationStepsEnterPinCode.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/VotingRegistrationStepsQrCode.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/VotingRegistrationStepsRegister.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/widgets/ConfirmationDialog.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/widgets/VotingRegistrationDialog.js
  source/renderer/app/config/votingConfig.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: :hourglass_flowing_sand:release-vNext, chore
