Repository input-output-hk/daedalus, pull requests merged in 2021-12, with the labels that each got.

#2766 [DDW-683] Prevent stake pools list reloading when slide didn't change position
  CHANGELOG.md
  source/renderer/app/components/staking/stake-pools/StakePoolsRanking.js
  source/renderer/app/components/widgets/Slider.js
Labels: feature, :hourglass_flowing_sand:release-vNext

#2759 [DDW-824] Fix app update on specific platform
  CHANGELOG.md
  source/renderer/app/config/newsfeed-files/news-automatic-update.dummy.json
  source/renderer/app/domains/News.js
  source/renderer/app/stores/NewsFeedStore.js
Labels: bug, :hourglass_flowing_sand:release-vNext

#2751 [DDW-811] [DEBT] - Checkmark alignment on react-polymorph Checkbox.
  CHANGELOG.md
  source/renderer/app/components/appUpdate/AppUpdateOverlay.scss
  source/renderer/app/components/voting/voting-info/RegisterToVote.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/VotingRegistrationStepsQrCode.js
  source/renderer/app/components/voting/widgets/PatchCheckbox.js
  source/renderer/app/components/voting/widgets/PatchCheckbox.scss
  source/renderer/app/themes/overrides/CheckboxOverrides.scss
Labels: feature, :hourglass_flowing_sand:release-vNext

#2765 [DDW-847] Bump CWB to v2021-11-11
  CHANGELOG.md
  nix/sources.json
Labels: chore, :hourglass_flowing_sand:release-vNext

#2771 [DDW-796] Implement catalyst state snapshot phase
  .gitignore
  source/renderer/app/components/staking/delegation-center/WalletRow.js
  source/renderer/app/components/voting/VotingUnavailable.js
  source/renderer/app/components/voting/voting-info/CurrentFund.js
  source/renderer/app/components/voting/voting-info/CurrentFund.messages.js
  source/renderer/app/components/voting/voting-info/CurrentPhase.scss
  source/renderer/app/components/voting/voting-info/RegisterToVote.js
  source/renderer/app/components/voting/voting-info/RegisterToVote.messages.js
  source/renderer/app/components/voting/voting-info/RegisterToVote.scss
  source/renderer/app/components/voting/voting-info/ResultsPhase.js
  source/renderer/app/components/voting/voting-info/ResultsPhase.messages.js
  source/renderer/app/components/voting/voting-info/SnapshotPhase.js
  source/renderer/app/components/voting/voting-info/SnapshotPhase.messages.js
  source/renderer/app/components/voting/voting-info/TallyingPhase.js
  source/renderer/app/components/voting/voting-info/TallyingPhase.messages.js
  source/renderer/app/components/voting/voting-info/VotingInfo.js
  source/renderer/app/components/voting/voting-info/VotingInfo.messages.js
  source/renderer/app/components/voting/voting-info/VotingInfo.scss
  source/renderer/app/components/voting/voting-info/VotingPhase.js
  source/renderer/app/components/voting/voting-info/VotingPhase.messages.js
  source/renderer/app/config/votingConfig.js
  source/renderer/app/containers/voting/VotingRegistrationPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/VotingStore.js
  source/renderer/app/stores/VotingStore.spec.js
  source/renderer/app/utils/formatters.js
  storybook/stories/voting/Voting.stories.js
Labels: feature, :hourglass_flowing_sand:release-vNext

#2770 [DDW-854] Improve startup and shutdown messages
  CHANGELOG.md
  source/renderer/app/components/loading/syncing-connecting/StatusIcons.scss
  source/renderer/app/components/loading/syncing-connecting/SyncingConnectingStatus.js
  source/renderer/app/components/loading/syncing-connecting/SyncingConnectingStatus.scss
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/shelley-testnet.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
Labels: feature, :hourglass_flowing_sand:release-vNext

#2769 [DDW-821] Update packages with vulnerabilities
  .babelrc
  .eslintrc
  CHANGELOG.md
  installers/nix/electron.nix
  package.json
  utils/create-news-verification-hashes/index.js
  yarn.lock
  yarn2nix.nix
Labels: chore, :hourglass_flowing_sand:release-vNext

#2792 [DDW-874] Update README with nix.conf for Apple M1 (only for development purposes)
  README.md
Labels: chore, experimental

#2781 [DDW-742] Fix receiver address validation (disallow rewards address)
  CHANGELOG.md
  nix/sources.json
  package.json
  source/common/types/address-introspection.types.js
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/utils/hardwareWalletUtils.js
  yarn.lock
Labels: bug, :hourglass_flowing_sand:release-vNext
