Repository input-output-hk/daedalus, pull requests merged in 2021-09, with the labels that each got.

#2663 [DDW-739] Enable hardware wallet support in Alonzo era
  CHANGELOG.md
  nix/sources.json
Labels: bug, :hourglass_flowing_sand:release-vNext

#2629 [DDW-717] Update Trezor logic to cover upcoming breaking changes
  CHANGELOG.md
  installers/common/MacInstaller.hs
  netlify.toml
  package.json
  source/common/types/hardware-wallets.types.js
  source/main/ipc/getHardwareWalletChannel.js
  source/renderer/app/stores/HardwareWalletsStore.js
  source/renderer/app/utils/shelleyLedger.js
  source/renderer/app/utils/shelleyTrezor.js
  yarn.lock
  yarn2nix.nix
Labels: chore, :hourglass_flowing_sand:release-vNext

#2667 [DDW-740] Fix Japanese copy
  CHANGELOG.md
  source/renderer/app/i18n/locales/ja-JP.json
Labels: bug, :hourglass_flowing_sand:release-vNext

#2668 Merge release/4.3.1 into develop
  CHANGELOG.md
  nix/sources.json
  package.json
Labels: chore, release-4.3.1

#2206 [DDW-414] Bump electron and related packages
  .eslintrc
  .flowconfig
  .gitignore
  CHANGELOG.md
  default.nix
  gulpfile.js
  installers/common/MacInstaller.hs
  installers/nix/electron.nix
  installers/nix/linux.nix
  netlify.toml
  nix/windows-usb-libs.zip
  package.json
  scripts/package.js
  shell.nix
  source/common/ipc/api.js
  source/common/types/cardano-node.types.js
  source/common/types/file-dialog.types.js
  source/common/types/logging.types.js
  source/common/utils/helper.js
  source/common/utils/logging.js
  source/main/cardano/CardanoNode.js
  source/main/cardano/setup.js
  source/main/environment.js
  source/main/index.js
  source/main/ipc/electronStoreConversation.js
  source/main/ipc/getHardwareWalletChannel.js
  source/main/ipc/manageAppUpdateChannel.js
  source/main/ipc/open-local-directory.js
  source/main/utils/safeExitWithCode.js
  source/main/windows/main.js
  source/renderer/app/api/utils/index.js
  source/renderer/app/api/utils/localStorage.js
  source/renderer/app/components/widgets/forms/FileUploadWidget.js
  source/renderer/app/containers/wallet/WalletReceivePage.js
  source/renderer/app/containers/wallet/dialogs/paper-wallet-certificate/InstructionsDialogContainer.js
  source/renderer/app/domains/ApiError.js
  source/renderer/app/stores/AppStore.js
  source/renderer/app/stores/HardwareWalletsStore.js
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/ProfileStore.js
  source/renderer/app/stores/WalletMigrationStore.js
  source/renderer/app/types/walletExportTypes.js
  tests/lint.nix
  utils/lockfile-checker/index.js
  yarn.lock
  yarn2nix.nix
Labels: chore, :hourglass_flowing_sand:release-vNext

#2673 [DDW-561] Fix crashes when Yubikey is connected
  CHANGELOG.md
  nix/windows-usb-libs.zip
Labels: bug, :hourglass_flowing_sand:release-vNext

#2675 [DDW-743] Update trezor-connect dependency to version 8.2.0
  CHANGELOG.md
  package.json
  yarn.lock
Labels: chore, :hourglass_flowing_sand:release-vNext

#2680 [DDW-744] Adjust font for Delegation Center info message
  CHANGELOG.md
  source/renderer/app/components/staking/_stakingConfig.scss
Labels: bug, WIP, :hourglass_flowing_sand:release-vNext
