Repository input-output-hk/daedalus, pull requests merged in 2021-05, with the labels that each got.

#2545 [DDW-669] Fix hardware wallets transactions with native tokens grouping issue
  CHANGELOG.md
  source/renderer/app/utils/shelleyLedger.js
Labels: :airplane: release-4.1.0-FC1, bug

#2547 Merge release/4.1.0-FC1 into develop
  CHANGELOG.md
  package.json
  source/renderer/app/stores/HardwareWalletsStore.js
  source/renderer/app/utils/shelleyLedger.js
Labels: :airplane: release-4.1.0-FC1, chore

#2546 [DDW-622] Move currency related code into a dedicated store
  CHANGELOG.md
  source/renderer/app/actions/currency-actions.js
  source/renderer/app/actions/index.js
  source/renderer/app/actions/wallets-actions.js
  source/renderer/app/containers/settings/categories/WalletsSettingsPage.js
  source/renderer/app/containers/wallet/WalletSummaryPage.js
  source/renderer/app/stores/CurrencyStore.js
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/stores/index.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2550 [DDW-661] Replace payment with stake address in Catalyst voting registration
  CHANGELOG.md
  source/renderer/app/stores/VotingStore.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2551 [DDW-668] Bump cardano-wallet version
  CHANGELOG.md
  default.nix
  nix/sources.json
  source/main/environment.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2282 [DDW-491] Verify HW wallet receiving address - Ledger
  CHANGELOG.md
  source/common/ipc/api.js
  source/common/types/hardware-wallets.types.js
  source/main/ipc/getHardwareWalletChannel.js
  source/renderer/app/api/addresses/types.js
  source/renderer/app/api/api.js
  source/renderer/app/components/hardware-wallet/HardwareWalletStatus.js
  source/renderer/app/components/wallet/receive/WalletReceiveDialog.js
  source/renderer/app/components/wallet/receive/WalletReceiveDialog.scss
  source/renderer/app/config/hardwareWalletsConfig.js
  source/renderer/app/containers/wallet/WalletReceivePage.js
  source/renderer/app/domains/Wallet.js
  source/renderer/app/domains/WalletAddress.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/ipc/getHardwareWalletChannel.js
  source/renderer/app/stores/HardwareWalletsStore.js
  source/renderer/app/utils/hardwareWalletUtils.js
  storybook/stories/_support/utils.js
  storybook/stories/wallets/receive/WalletReceive.stories.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2549 [DDW-674] Integrate react-polymorph 1.0.0 release
  CHANGELOG.md
  package.json
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext, chore

#2558 [DDW-529] Verify HW wallet receiving address - Trezor
  CHANGELOG.md
  source/common/ipc/api.js
  source/main/ipc/getHardwareWalletChannel.js
  source/renderer/app/components/hardware-wallet/HardwareWalletStatus.js
  source/renderer/app/components/wallet/receive/WalletReceiveDialog.js
  source/renderer/app/containers/wallet/WalletReceivePage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/HardwareWalletsStore.js
  source/renderer/app/utils/shelleyLedger.js
  storybook/stories/wallets/receive/WalletReceive.stories.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2561 cardano-cli: default to version from cardano-wallet
  CHANGELOG.md
  default.nix
Labels: :hourglass_flowing_sand:release-vNext, chore

#2556 [DDW-629] Fix external currencies not appearing when not connected
  CHANGELOG.md
  source/renderer/app/components/wallet/summary/WalletSummary.js
  source/renderer/app/components/wallet/summary/WalletSummaryCurrency.js
  source/renderer/app/components/wallet/summary/WalletSummaryCurrency.scss
  source/renderer/app/containers/wallet/WalletSummaryPage.js
  source/renderer/app/stores/CurrencyStore.js
  storybook/stories/wallets/summary/WalletSummary.stories.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2552 [DDW-641] Include wallet names in dialog windows
  CHANGELOG.md
  source/renderer/app/components/assets/AssetSettingsDialog.scss
  source/renderer/app/components/assets/AssetToken.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationSteps.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsIntroDialog.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsNotAvailableDialog.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsSuccessDialog.scss
  source/renderer/app/components/voting/voting-registration-wizard-steps/widgets/VotingRegistrationDialog.scss
  source/renderer/app/components/wallet/WalletRestoreDialog.scss
  source/renderer/app/components/wallet/receive/WalletReceiveDialog.js
  source/renderer/app/components/wallet/receive/WalletReceiveDialog.scss
  source/renderer/app/components/wallet/send-form/WalletSendAssetsConfirmationDialog.js
  source/renderer/app/components/wallet/send-form/WalletSendAssetsConfirmationDialog.scss
  source/renderer/app/components/wallet/send-form/WalletSendConfirmationDialog.js
  source/renderer/app/components/wallet/send-form/WalletSendConfirmationDialog.scss
  source/renderer/app/components/wallet/settings/ChangeSpendingPasswordDialog.js
  source/renderer/app/components/wallet/settings/DeleteWalletConfirmationDialog.js
  source/renderer/app/components/wallet/settings/DeleteWalletConfirmationDialog.scss
  source/renderer/app/components/wallet/settings/UndelegateWalletConfirmationDialog.js
  source/renderer/app/components/wallet/settings/UndelegateWalletSuccessDialog.js
  source/renderer/app/components/wallet/settings/UndelegateWalletSuccessDialog.scss
  source/renderer/app/components/wallet/settings/WalletPublicKeyDialog.js
  source/renderer/app/components/wallet/settings/WalletPublicKeyQRCodeDialog.js
  source/renderer/app/components/wallet/settings/WalletPublicKeyQRCodeDialog.scss
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseStep1Dialog.js
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseStep2Dialog.js
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseStep3Dialog.js
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseStep4Dialog.js
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseStepDialogs.scss
  source/renderer/app/components/wallet/summary/WalletSummaryCurrency.js
  source/renderer/app/components/wallet/wallet-restore/SuccessDialog.scss
  source/renderer/app/components/wallet/wallet-restore/widgets/WalletRestoreDialog.scss
  source/renderer/app/components/wallet/wallet-restore/widgets/WalletRestoreSteps.scss
  source/renderer/app/components/widgets/Dialog.scss
  source/renderer/app/containers/wallet/WalletReceivePage.js
  source/renderer/app/containers/wallet/dialogs/settings/WalletPublicKeyDialogContainer.js
  source/renderer/app/containers/wallet/dialogs/settings/WalletRecoveryPhraseContainer.js
  storybook/stories/wallets/_utils/defaultWalletProps.js
  storybook/stories/wallets/settings/WalletPublicKey.stories.js
  storybook/stories/wallets/settings/WalletSettingsScreen.stories.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2564 [DDW-635] Fix pool description scrolling and styling
  CHANGELOG.md
  source/renderer/app/components/staking/stake-pools/StakePoolsList.js
  source/renderer/app/components/staking/widgets/TooltipPool.scss
  source/renderer/app/config/stakingStakePools.dummy.json
Labels: bug

#2540 [DDW-665] Make the Wallets Dropdown agnostic
  CHANGELOG.md
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.scss
  source/renderer/app/components/staking/redeem-itn-rewards/Step1ConfigurationDialog.js
  source/renderer/app/components/staking/redeem-itn-rewards/Step1ConfigurationDialog.scss
  source/renderer/app/components/staking/stake-pools/StakePools.js
  source/renderer/app/components/staking/stake-pools/StakePools.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsRanking.js
  source/renderer/app/components/staking/stake-pools/StakePoolsRanking.scss
  source/renderer/app/components/wallet/send-form/AssetInput.js
  source/renderer/app/components/wallet/send-form/AssetInput.scss
  source/renderer/app/components/wallet/send-form/messages.js
  source/renderer/app/components/wallet/transfer-funds/TransferFundsStep1Dialog.js
  source/renderer/app/components/widgets/DialogFullSizeOverride.scss
  source/renderer/app/components/widgets/forms/AssetsDropdown.js
  source/renderer/app/components/widgets/forms/AssetsDropdown.scss
  source/renderer/app/components/widgets/forms/ItemDropdownOption.js
  source/renderer/app/components/widgets/forms/ItemDropdownOption.scss
  source/renderer/app/components/widgets/forms/ItemsDropdown.js
  source/renderer/app/components/widgets/forms/ItemsDropdown.scss
  source/renderer/app/components/widgets/forms/WalletsDropdown.js
  source/renderer/app/components/widgets/forms/WalletsDropdown.scss
  source/renderer/app/components/widgets/forms/WalletsDropdownLabel.js
  source/renderer/app/components/widgets/forms/WalletsDropdownLabel.scss
  source/renderer/app/components/widgets/forms/WalletsDropdownOption.js
  source/renderer/app/components/widgets/forms/WalletsDropdownOption.scss
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/shelley-testnet.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  storybook/stories/_support/utils.js
  storybook/stories/common/ItemsDropdown.stories.js
  storybook/stories/index.js
  storybook/stories/staking/RedeemItnWallets.stories.js
  storybook/stories/staking/StakePools.stories.js
  storybook/stories/voting/Voting.stories.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2568 [DDW-684] Fix stake pools pop over description scrollbar
  CHANGELOG.md
  source/renderer/app/components/staking/widgets/TooltipPool.scss
Labels: bug

#2562 [DDW-663] Use asset policyId+name as unique identifier instead of the fingerprint
  CHANGELOG.md
  source/renderer/app/actions/assets-actions.js
  source/renderer/app/actions/wallets-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/api/assets/requests/getAssets.js
  source/renderer/app/api/assets/types.js
  source/renderer/app/api/transactions/types.js
  source/renderer/app/api/utils/localStorage.js
  source/renderer/app/api/wallets/types.js
  source/renderer/app/components/assets/Asset.js
  source/renderer/app/components/assets/Asset.scss
  source/renderer/app/components/assets/AssetAmount.js
  source/renderer/app/components/assets/AssetSettingsDialog.js
  source/renderer/app/components/wallet/WalletSendForm.js
  source/renderer/app/components/wallet/send-form/AssetInput.js
  source/renderer/app/components/wallet/send-form/AssetInput.scss
  source/renderer/app/components/wallet/send-form/WalletSendAssetsConfirmationDialog.js
  source/renderer/app/components/wallet/summary/WalletSummary.js
  source/renderer/app/components/wallet/summary/WalletSummaryAssets.js
  source/renderer/app/components/wallet/transactions/Transaction.js
  source/renderer/app/components/wallet/transactions/WalletTransactions.js
  source/renderer/app/components/wallet/transactions/WalletTransactionsList.js
  source/renderer/app/components/widgets/forms/AssetsDropdown.js
  source/renderer/app/config/assetsConfig.js
  source/renderer/app/containers/assets/AssetSettingsDialogContainer.js
  source/renderer/app/containers/wallet/WalletSendPage.js
  source/renderer/app/containers/wallet/WalletSummaryPage.js
  source/renderer/app/containers/wallet/WalletTransactionsPage.js
  source/renderer/app/containers/wallet/dialogs/WalletSendConfirmationDialogContainer.js
  source/renderer/app/domains/Asset.js
  source/renderer/app/domains/Wallet.js
  source/renderer/app/domains/WalletTransaction.js
  source/renderer/app/stores/AssetsStore.js
  source/renderer/app/stores/TransactionsStore.js
  source/renderer/app/stores/WalletsStore.js
  source/renderer/app/utils/assets.js
  source/renderer/app/utils/transactionsCsvGenerator.js
  storybook/stories/_support/utils.js
  storybook/stories/assets/Asset.stories.js
  storybook/stories/assets/AssetSettingsDialog.stories.js
  storybook/stories/assets/AssetToken.stories.js
  storybook/stories/common/ItemsDropdown.stories.js
  storybook/stories/index.js
  storybook/stories/wallets/send/WalletSend.stories.js
  storybook/stories/wallets/summary/WalletSummary.stories.js
  storybook/stories/wallets/transactions/Transaction.stories.js
  storybook/stories/wallets/transactions/TransactionsList.stories.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2570 [DDW-686] Validate search for native tokens and conversion currency
  package.json
  source/renderer/app/components/settings/categories/WalletsSettings.js
  source/renderer/app/components/wallet/WalletSendForm.js
  source/renderer/app/components/widgets/forms/ItemsDropdown.js
  source/renderer/app/containers/settings/categories/WalletsSettingsPage.js
  source/renderer/app/i18n/global-messages.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  storybook/stories/settings/general/General.stories.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext, bug

#2445 restoreKeystore extensions
  CHANGELOG.md
  source/main/utils/restoreKeystore.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2577 [DDW-667] Use token decimal places info from the cardano-wallet Api
  CHANGELOG.md
  nix/sources.json
  source/renderer/app/api/api.js
  source/renderer/app/api/assets/types.js
  source/renderer/app/components/assets/Asset.scss
  source/renderer/app/components/assets/AssetSettingsDialog.js
  source/renderer/app/config/assetsConfig.js
  source/renderer/app/config/assetsPredefinedDecimals-testnet.json
  source/renderer/app/config/assetsPredefinedDecimals.json
  source/renderer/app/domains/Asset.js
Labels: :hourglass_flowing_sand:release-vNext, feature
