Repository input-output-hk/daedalus, pull requests merged in 2021-11, with the labels that each got.

#2727 [DDW-778] Add solution for the nix SSL issue to the README
  CHANGELOG.md
  README.md
Labels: chore, :hourglass_flowing_sand:release-vNext

#2721 [DDW-754] Update Catalyst links
  CHANGELOG.md
  package.json
  source/renderer/app/components/staking/delegation-center/DelegationCenterNoWallets.scss
  source/renderer/app/components/staking/widgets/TooltipPool.scss
  source/renderer/app/components/voting/VotingFooterLinks.js
  source/renderer/app/components/voting/VotingFooterLinks.scss
  source/renderer/app/components/voting/VotingInfo.scss
  source/renderer/app/components/voting/VotingNoWallets.scss
  source/renderer/app/components/voting/VotingUnavailable.scss
  source/renderer/app/containers/voting/VotingRegistrationPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/shelley-testnet.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  storybook/stories/voting/Voting.stories.js
  yarn.lock
Labels: feature, :hourglass_flowing_sand:release-vNext

#2733 [DDW-759] Over-saturation warning
  CHANGELOG.md
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationSetupWizardDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.messages.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsConfirmationDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsConfirmationDialog.messages.js
  source/renderer/app/components/staking/delegation-setup-wizard/OversaturationText.js
  source/renderer/app/components/staking/delegation-setup-wizard/OversaturationText.scss
  source/renderer/app/components/staking/stake-pools/helpers.js
  source/renderer/app/config/stakingConfig.js
  source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/themes/overrides/ModalOverrides.scss
  storybook/stories/staking/DelegationSteps.stories.js
  storybook/stories/staking/Staking.stories.js
Labels: feature, :hourglass_flowing_sand:release-vNext

#2732 [DDW-794] Implement the Catalysts Fund7 screen
  CHANGELOG.md
  source/renderer/app/assets/images/external-link-ic.inline.svg
  source/renderer/app/components/voting/VotingInfo.js
  source/renderer/app/components/voting/VotingInfo.scss
  source/renderer/app/components/voting/VotingNoWallets.js
  source/renderer/app/components/voting/VotingUnavailable.js
  source/renderer/app/components/voting/voting-info/AppStore.js
  source/renderer/app/components/voting/voting-info/AppStore.messages.js
  source/renderer/app/components/voting/voting-info/AppStore.scss
  source/renderer/app/components/voting/voting-info/CurrentFund.js
  source/renderer/app/components/voting/voting-info/CurrentFund.messages.js
  source/renderer/app/components/voting/voting-info/CurrentFund.scss
  source/renderer/app/components/voting/voting-info/Headline.js
  source/renderer/app/components/voting/voting-info/Headline.messages.js
  source/renderer/app/components/voting/voting-info/Headline.scss
  source/renderer/app/components/voting/voting-info/RegisterToVote.js
  source/renderer/app/components/voting/voting-info/RegisterToVote.messages.js
  source/renderer/app/components/voting/voting-info/RegisterToVote.scss
  source/renderer/app/components/voting/voting-info/VotingInfo.js
  source/renderer/app/components/voting/voting-info/VotingInfo.scss
  source/renderer/app/components/voting/voting-registration-wizard-steps/VotingRegistrationStepsEnterPinCode.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/VotingRegistrationStepsQrCode.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/VotingRegistrationStepsRegister.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/widgets/ConfirmationDialog.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/widgets/VotingRegistrationDialog.js
  source/renderer/app/components/voting/widgets/PatchCheckbox.js
  source/renderer/app/components/voting/widgets/PatchCheckbox.scss
  source/renderer/app/components/widgets/ExternalLinkButton.js
  source/renderer/app/components/widgets/ExternalLinkButton.scss
  source/renderer/app/config/profileConfig.js
  source/renderer/app/config/votingConfig.js
  source/renderer/app/containers/voting/VotingRegistrationPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/VotingStore.js
  source/renderer/app/types/i18nTypes.js
  source/renderer/app/utils/formatters.js
  source/renderer/app/utils/votingPDFGenerator.js
  storybook/stories/voting/Voting.stories.js
Labels: feature, :hourglass_flowing_sand:release-vNext

#2735 [DDW-808] Update cardano-launcher and introduce Cardano Node RTS flags
  CHANGELOG.md
  default.nix
  installers/daedalus-installer.nix
  installers/dhall-haskell.nix
  installers/dhall-json.nix
  installers/nix/electron.nix
  installers/overlays/dhall-json.nix
  installers/overlays/dhall.nix
  installers/overlays/nsis.nix
  installers/overlays/universum.nix
  nix/darwin-launcher.nix
  nix/nsis-inner.nix
  nix/sources.json
  nix/sources.nix
  package.json
  source/main/cardano/CardanoWalletLauncher.js
  source/main/config.js
  yarn.lock
  yarn2nix.nix
Labels: chore, :hourglass_flowing_sand:release-vNext

#2716 [DDW-780] Daedalus start impovement
  .nonsense
  CHANGELOG.md
  source/common/types/no-disk-space.types.js
  source/main/cardano/CardanoNode.js
  source/main/cardano/setup.js
  source/main/config.js
  source/main/index.js
  source/main/utils/handleDiskSpace.js
  source/main/utils/logging.js
Labels: chore, :hourglass_flowing_sand:release-vNext

#2724 [DDW-785] Discreet mode - Create the Discreet Mode variables
  CHANGELOG.md
  source/common/config/electron-store.config.js
  source/common/types/electron-store.types.js
  source/main/ipc/electronStoreConversation.js
  source/renderer/app/actions/app-actions.js
  source/renderer/app/api/utils/localStorage.js
  source/renderer/app/stores/AppStore.js
Labels: feature, WIP, :hourglass_flowing_sand:release-vNext

#2738 [DDW-759] Fixed hardware wallet delegation
  CHANGELOG.md
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationSetupWizardDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.js
  source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/stores/StakingStore.js
Labels: bug, :hourglass_flowing_sand:release-vNext

#2741 [DDW-815] Fix broken Ledger support on Linux
  CHANGELOG.md
  default.nix
  installers/nix/electron.nix
  installers/overlays/required.nix
  nix/sources.json
  shell.nix
Labels: bug, release-4.5.0

#2744 Fix wallet restore dialog and continue disable check
  CHANGELOG.md
  source/renderer/app/containers/wallet/dialogs/wallet-restore/StepConfigurationContainer.js
  source/renderer/app/containers/wallet/dialogs/wallet-restore/StepSuccessContainer.js
  source/renderer/app/stores/WalletsStore.js
Labels: bug, release-4.5.0

#2745 Fix wallet restore dialog and continue disable check
  CHANGELOG.md
  source/renderer/app/containers/wallet/dialogs/wallet-restore/StepConfigurationContainer.js
  source/renderer/app/containers/wallet/dialogs/wallet-restore/StepSuccessContainer.js
  source/renderer/app/stores/WalletsStore.js
Labels: bug, release-4.5.0

#2725 [DDW-786] Discreet mode - Create the TopBar icon
  CHANGELOG.md
  source/renderer/app/components/layout/TopBar.scss
  source/renderer/app/components/widgets/NodeSyncStatusIcon.scss
  source/renderer/app/components/widgets/discreet-mode/DiscreetToggle.js
  source/renderer/app/components/widgets/discreet-mode/DiscreetToggle.messages.js
  source/renderer/app/components/widgets/discreet-mode/DiscreetToggle.scss
  source/renderer/app/containers/TopBarContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  storybook/stories/_support/StoryLayout.js
  storybook/stories/common/Widgets.stories.js
  storybook/stories/nodes/environment/TopBarEnvironment.stories.js
Labels: feature, WIP, :hourglass_flowing_sand:release-vNext

#2633 [DDW-771] Add jest and couple of unit tests
  .eslintrc
  .github/workflows/run_tests_on_pr.yml
  CHANGELOG.md
  flow-typed/npm/jest_v27.x.x.js
  jest.config.js
  package.json
  tests/assets/unit/assets.spec.js
  tests/common/unit/networks.spec.js
  tests/wallets/unit/wallet-utils.spec.js
  yarn.lock
Labels: chore, :hourglass_flowing_sand:release-vNext

#2740 [DDW-787] Discreet mode - Implement the Settings option
  CHANGELOG.md
  source/common/config/electron-store.config.js
  source/common/types/electron-store.types.js
  source/main/ipc/electronStoreConversation.js
  source/renderer/app/Routes.js
  source/renderer/app/components/layout/TopBar.scss
  source/renderer/app/components/settings/categories/SecuritySettings.js
  source/renderer/app/components/settings/categories/SecuritySettings.messages.js
  source/renderer/app/components/settings/categories/SecuritySettings.scss
  source/renderer/app/components/settings/menu/SecurityMenuItem.js
  source/renderer/app/components/settings/menu/SettingsMenu.js
  source/renderer/app/components/settings/menu/SettingsMenu.messages.js
  source/renderer/app/components/settings/menu/SettingsMenu.scss
  source/renderer/app/components/settings/menu/hooks.js
  source/renderer/app/components/sidebar/Sidebar.js
  source/renderer/app/components/sidebar/SidebarCategoryWrapper.js
  source/renderer/app/components/sidebar/SidebarCategoryWrapper.messages.js
  source/renderer/app/components/sidebar/SidebarCategoryWrapper.scss
  source/renderer/app/components/sidebar/helpers.js
  source/renderer/app/components/sidebar/types.js
  source/renderer/app/components/staking/stake-pools/StakePoolsList.js
  source/renderer/app/components/staking/widgets/PoolPopOver.js
  source/renderer/app/components/widgets/notification-dot/NotificationDot.js
  source/renderer/app/components/widgets/notification-dot/NotificationDot.scss
  source/renderer/app/containers/settings/Settings.js
  source/renderer/app/containers/settings/categories/SecuritySettingsPage.js
  source/renderer/app/features/discreet-mode/api/index.js
  source/renderer/app/features/discreet-mode/feature.js
  source/renderer/app/features/discreet-mode/index.js
  source/renderer/app/features/discreet-mode/ui/DiscreetModeFeatureInject.js
  source/renderer/app/features/discreet-mode/ui/discreet-toggle-top-bar/DiscreetToggleTopBar.js
  source/renderer/app/features/discreet-mode/ui/discreet-toggle-top-bar/DiscreetToggleTopBar.messages.js
  source/renderer/app/features/discreet-mode/ui/discreet-toggle-top-bar/DiscreetToggleTopBar.scss
  source/renderer/app/features/discreet-mode/ui/discreet-toggle/DiscreetModeToggle.scss
  source/renderer/app/features/discreet-mode/ui/index.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/routes-config.js
  storybook/stories/_support/StoryLayout.js
  storybook/stories/settings/general/General.stories.js
Labels: feature, WIP, :hourglass_flowing_sand:release-vNext
