Repository input-output-hk/daedalus, pull requests merged in 2021-08, with the labels that each got.

#2611 [DDW-690] Maintain window size and position
  CHANGELOG.md
  source/common/config/electron-store.config.js
  source/common/types/electron-store.types.js
  source/main/config.js
  source/main/index.js
  source/main/ipc/electronStoreConversation.js
  source/main/utils/getContentMinimumSize.js
  source/main/windows/main.js
  source/main/windows/windowBounds.js
  source/renderer/app/components/widgets/forms/TinyDatePicker.js
  source/renderer/app/components/widgets/forms/TinyDatePicker.scss
  source/renderer/app/components/widgets/forms/TinyInput.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2638 [DDW-724] Fixes Alonzo Purple build issues, removes raw network
  CHANGELOG.md
  source/common/types/environment.types.js
  source/common/utils/environmentCheckers.js
  source/main/environment.js
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/components/wallet/paper-wallet-certificate/InstructionsDialog.js
  source/renderer/app/containers/status/DaedalusDiagnosticsDialog.js
  source/renderer/app/containers/wallet/dialogs/paper-wallet-certificate/InstructionsDialogContainer.js
  source/renderer/app/types/coreSystemInfoTypes.js
Labels: chore, :hourglass_flowing_sand:release-vNext

#2640 [DDW-731] Prepare Catalyst Fund6 voting registration
  CHANGELOG.md
  source/renderer/app/components/voting/VotingInfo.js
  source/renderer/app/components/voting/VotingNoWallets.js
  source/renderer/app/components/voting/VotingUnavailable.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/VotingRegistrationStepsEnterPinCode.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/VotingRegistrationStepsQrCode.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/VotingRegistrationStepsRegister.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/widgets/ConfirmationDialog.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/widgets/VotingRegistrationDialog.js
  source/renderer/app/config/votingConfig.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: chore, :hourglass_flowing_sand:release-vNext

#2642 Merge release/4.2.1 into develop
  CHANGELOG.md
  package.json
  source/renderer/app/components/voting/VotingInfo.js
  source/renderer/app/components/voting/VotingNoWallets.js
  source/renderer/app/components/voting/VotingUnavailable.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/VotingRegistrationStepsEnterPinCode.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/VotingRegistrationStepsQrCode.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/VotingRegistrationStepsRegister.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/widgets/ConfirmationDialog.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/widgets/VotingRegistrationDialog.js
  source/renderer/app/config/votingConfig.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: chore, release-4.2.1

#2643 Merge release/4.2.0 into master
  CHANGELOG.md
  package.json
  source/renderer/app/components/voting/VotingInfo.js
  source/renderer/app/components/voting/VotingNoWallets.js
  source/renderer/app/components/voting/VotingUnavailable.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/VotingRegistrationStepsEnterPinCode.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/VotingRegistrationStepsQrCode.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/VotingRegistrationStepsRegister.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/widgets/ConfirmationDialog.js
  source/renderer/app/components/voting/voting-registration-wizard-steps/widgets/VotingRegistrationDialog.js
  source/renderer/app/config/votingConfig.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: release-4.2.1

#2646 [DDW-733] Fix ‘Stakepool Metadata Aggregation Server (SMASH)’ link url
  CHANGELOG.md
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: bug, :hourglass_flowing_sand:release-vNext

#2641 [DDW-724] Bumps CWB and fix address validation on Alonzo Purple builds
  CHANGELOG.md
  nix/sources.json
  source/common/types/cardano-node.types.js
  source/common/types/environment.types.js
  source/common/utils/environmentCheckers.js
  source/main/environment.js
  source/renderer/app/stores/WalletsStore.js
Labels: chore, :hourglass_flowing_sand:release-vNext
