Repository input-output-hk/daedalus, pull requests merged in 2021-01, with the labels that each got.

#2294 Merge release/3.1.0 into develop
  CHANGELOG.md
  package.json
Labels: chore, release-3.1.0

#2295 Merge release/3.1.0 into master
  CHANGELOG.md
  gulpfile.js
  nix/sources.json
  package.json
  source/main/ipc/getHardwareWalletChannel.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsConfirmationDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsConfirmationDialog.scss
  source/renderer/app/components/staking/stake-pools/helpers.js
  source/renderer/app/components/wallet/WalletSendForm.js
  source/renderer/app/components/wallet/utxo/WalletUtxo.js
  source/renderer/app/containers/wallet/WalletUtxoPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/TransactionsStore.js
  source/renderer/app/stores/WalletSettingsStore.js
  source/renderer/app/utils/hardwareWalletUtils.js
  source/renderer/app/utils/shelleyLedger.js
  yarn.lock
Labels: release-3.1.0

#2289 [DDW-531] Fix Daedalus development environment issues on OSX Big Sur
  CHANGELOG.md
  installers/overlays/required.nix
  nix/sources.json
Labels: :hourglass_flowing_sand:release-vNext, bug

#2280 [DDW-497] Improve Mnemonic Phrase Input UX
  CHANGELOG.md
  package.json
  source/renderer/app/components/staking/redeem-itn-rewards/Step1ConfigurationDialog.js
  source/renderer/app/components/wallet/WalletRestoreDialog.js
  source/renderer/app/components/wallet/backup-recovery/WalletRecoveryPhraseEntryDialog.js
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseStep2Dialog.js
  source/renderer/app/components/wallet/wallet-restore/MnemonicsDialog.js
  source/renderer/app/i18n/global-messages.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/themes/README.md
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/shelley-testnet.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/utils/createTheme.js
  source/renderer/app/themes/utils/writeThemeUpdate.js
  source/renderer/app/utils/validations.js
  storybook/stories/wallets/addWallet/Restore.stories.js
  tests/common/unit/features/mnemonics-form-validation.feature
  tests/common/unit/steps/mnemonics-form-validation.steps.js
  tests/setup-common.js
  tests/wallets/unit/features/spending-password-validation.feature
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext, feature

#2287 [DDW-502] Spending password should not be longer than 255 characters
  CHANGELOG.md
  package.json
  source/renderer/app/i18n/global-messages.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/utils/validations.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext, chore

#2300 [DDW-501] Hide copy and paste context menu items on some scenarios
  CHANGELOG.md
  source/main/windows/main.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2285 [DDW-496] Scrollable dialogs improvement
  CHANGELOG.md
  source/renderer/app/components/layout/SidebarLayout.scss
  source/renderer/app/components/layout/VerticalFlexContainer.scss
  source/renderer/app/components/news/NewsFeed.scss
  source/renderer/app/components/profile/terms-of-use/TermsOfUseForm.scss
  source/renderer/app/components/settings/SettingsLayout.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsIntroDialog.scss
  source/renderer/app/components/staking/rewards/StakingRewardsForIncentivizedTestnet.scss
  source/renderer/app/components/status/DaedalusDiagnostics.scss
  source/renderer/app/components/wallet/receive/VirtualAddressesList.scss
  source/renderer/app/components/wallet/receive/WalletReceiveRandom.scss
  source/renderer/app/components/wallet/receive/WalletReceiveSequential.scss
  source/renderer/app/components/wallet/settings/ChangeSpendingPasswordDialog.scss
  source/renderer/app/components/wallet/transactions/render-strategies/VirtualTransactionList.scss
  source/renderer/app/components/wallet/utxo/WalletUtxo.scss
  source/renderer/app/components/wallet/wallet-create/WalletCreateDialog.scss
  source/renderer/app/components/wallet/wallet-restore/widgets/WalletRestoreDialog.js
  source/renderer/app/components/wallet/wallet-restore/widgets/WalletRestoreSteps.js
  source/renderer/app/components/wallet/wallet-restore/widgets/WalletRestoreSteps.scss
  source/renderer/app/components/widgets/Dialog.js
  source/renderer/app/components/widgets/Dialog.scss
  source/renderer/app/containers/static/AboutDialog.scss
  source/renderer/app/containers/status/DaedalusDiagnosticsDialog.scss
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/themes/index.global.scss
Labels: :hourglass_flowing_sand:release-vNext, chore

#2302 [DDW] Improve "Settings" screen scrolling actions
  CHANGELOG.md
  source/renderer/app/components/settings/SettingsLayout.js
  source/renderer/app/components/wallet/transactions/WalletTransactionsList.scss
  source/renderer/app/containers/settings/Settings.js
  storybook/stories/settings/utils/SettingsWrapper.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2299 [DDW-534] Fix Ledger TXs to Byron addresses
  CHANGELOG.md
  source/common/types/hardware-wallets.types.js
  source/renderer/app/api/addresses/requests/inspectAddress.js
  source/renderer/app/api/addresses/types.js
  source/renderer/app/api/api.js
  source/renderer/app/components/settings/SettingsLayout.js
  source/renderer/app/config/hardwareWalletsConfig.js
  source/renderer/app/domains/WalletAddress.js
  source/renderer/app/stores/AddressesStore.js
  source/renderer/app/stores/HardwareWalletsStore.js
  source/renderer/app/utils/shelleyLedger.js
Labels: :hourglass_flowing_sand:release-vNext, bug

#2303 [DDW-540] Update cardano-wallet version
  CHANGELOG.md
  nix/sources.json
  source/renderer/app/api/api.js
  source/renderer/app/api/network/types.js
  source/renderer/app/api/transactions/requests/selectCoins.js
  source/renderer/app/api/transactions/types.js
  source/renderer/app/api/wallets/types.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2275 [DDW-480] Tile view in the delegation center
  CHANGELOG.md
  source/renderer/app/components/staking/_stakingConfig.scss
  source/renderer/app/components/staking/delegation-center/DelegationCenter.js
  source/renderer/app/components/staking/delegation-center/DelegationCenterBody.js
  source/renderer/app/components/staking/delegation-center/DelegationCenterBody.scss
  source/renderer/app/components/staking/delegation-center/DelegationCenterHeader.scss
  source/renderer/app/components/staking/delegation-center/WalletColumn.js
  source/renderer/app/components/staking/delegation-center/WalletRow.js
  source/renderer/app/components/staking/delegation-center/WalletRow.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsTableBody.js
  source/renderer/app/components/staking/widgets/ThumbPool.js
  source/renderer/app/components/staking/widgets/TooltipPool.js
  source/renderer/app/components/staking/widgets/TooltipPool.scss
  source/renderer/app/config/stakingStakePools.dummy.js
  source/renderer/app/containers/staking/DelegationCenterPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/shelley-testnet.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/themes/overrides/PopOverOverrides.scss
  source/renderer/app/themes/utils/createTheme.js
  storybook/stories/staking/DelegationCenter.stories.js
  tests/common/unit/steps/mnemonics-form-validation.steps.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2311 Merge release/3.2.0-FC1 into develop
  CHANGELOG.md
  package.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: :airplane: release-3.2.0-FC1, chore

#2304 [DDW-536] Service agreement can be skipped by accessing to Settings
  CHANGELOG.md
  source/common/ipc/api.js
  source/main/index.js
  source/main/ipc/enableApplicationMenuNavigationChannel.js
  source/main/menus/osx.js
  source/main/menus/win-linux.js
  source/main/utils/buildAppMenus.js
  source/renderer/app/containers/profile/InitialSettingsPage.js
  source/renderer/app/containers/settings/categories/GeneralSettingsPage.js
  source/renderer/app/ipc/enableApplicationMenuNavigationChannel.js
  source/renderer/app/stores/ProfileStore.js
Labels: :hourglass_flowing_sand:release-vNext, chore

#2305 [DDW-543] Update bignumber.js from v5 to v9
  CHANGELOG.md
  installers/common/MacInstaller.hs
  package.json
  source/renderer/app/api/api.js
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseWalletDialog.js
  source/renderer/app/components/staking/redeem-itn-rewards/Step2ConfirmationDialog.js
  source/renderer/app/components/wallet/WalletSendForm.js
  source/renderer/app/containers/staking/dialogs/DelegationSetupWizardDialogContainer.js
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/utils/formatters.js
  source/renderer/app/utils/transaction.js
  source/renderer/app/utils/walletsForStakePoolsRanking.js
  tests/transactions/e2e/steps/transactions.js
  tests/wallets/e2e/steps/transfer-funds-wizard.js
  yarn.lock
  yarn2nix.nix
Labels: :hourglass_flowing_sand:release-vNext, chore

#2321 Merge release/3.2.0 into develop
  CHANGELOG.md
  package.json
Labels: chore, release-3.2.0

#2322 Merge release/3.2.0 into master
  CHANGELOG.md
  package.json
Labels: release-3.2.0

#2259 [DDW-481] Switching SMASH servers
  CHANGELOG.md
  source/common/config/electron-store.config.js
  source/common/types/electron-store.types.js
  source/main/cardano/CardanoNode.js
  source/main/cardano/CardanoWalletLauncher.js
  source/main/cardano/setup.js
  source/main/config.js
  source/main/preload.js
  source/renderer/app/Routes.js
  source/renderer/app/actions/staking-actions.js
  source/renderer/app/api/api.js
  source/renderer/app/api/errors.js
  source/renderer/app/api/staking/requests/checkSmashServerHealth.js
  source/renderer/app/api/staking/requests/getSmashSettings.js
  source/renderer/app/api/staking/requests/updateSmashSettings.js
  source/renderer/app/api/staking/types.js
  source/renderer/app/api/utils/localStorage.js
  source/renderer/app/assets/images/smash-settings-ic.inline.svg
  source/renderer/app/assets/images/spinner-ic.inline.svg
  source/renderer/app/assets/images/spinner-tiny.inline.svg
  source/renderer/app/components/settings/categories/StakePoolsSettings.js
  source/renderer/app/components/settings/categories/StakePoolsSettings.scss
  source/renderer/app/components/settings/menu/SettingsMenu.js
  source/renderer/app/components/staking/stake-pools/StakePools.js
  source/renderer/app/components/staking/stake-pools/StakePools.scss
  source/renderer/app/components/wallet/settings/WalletSettings.js
  source/renderer/app/components/widgets/forms/InlineEditingInput.js
  source/renderer/app/components/widgets/forms/InlineEditingInput.scss
  source/renderer/app/config/numbersConfig.js
  source/renderer/app/config/stakingConfig.js
  source/renderer/app/containers/settings/Settings.js
  source/renderer/app/containers/settings/categories/StakePoolsSettingsPage.js
  source/renderer/app/containers/staking/StakePoolsListPage.js
  source/renderer/app/containers/wallet/WalletSettingsPage.js
  source/renderer/app/domains/ApiError.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/routes-config.js
  source/renderer/app/stores/StakingStore.js
  source/renderer/app/types/stakingTypes.js
  source/renderer/app/utils/staking.js
  storybook/stories/common/Widgets.stories.js
  storybook/stories/settings/general/General.stories.js
  storybook/stories/settings/utils/SettingsWrapper.js
  storybook/stories/staking/StakePools.stories.js
  storybook/stories/wallets/settings/WalletSettingsScreen.stories.js
Labels: :hourglass_flowing_sand:release-vNext, feature

#2318 [DDW-543] Integrate improved numeric input
  CHANGELOG.md
  package.json
  source/renderer/app/components/wallet/WalletSendForm.js
  source/renderer/app/components/wallet/transactions/FilterDialog.js
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext, feature
