Repository input-output-hk/daedalus, pull requests merged in 2021-10, with the labels that each got.

#2683 Changes to make aarch64-darwin build
  installers/daedalus-installer.nix
  installers/dhall-haskell.nix
  installers/dhall-json.nix
  installers/nix/electron.nix
  installers/overlays/dhall-json.nix
  installers/overlays/dhall.nix
  installers/overlays/nsis.nix
  installers/overlays/required.nix
  installers/overlays/universum.nix
  nix/nsis-inner.nix
  nix/sources.json
  nix/sources.nix
  release.nix
Labels: WIP, :hourglass_flowing_sand:release-vNext

#2690 Merge release/4.3.2 into develop
  CHANGELOG.md
  nix/sources.json
  package.json
  source/main/environment.js
Labels: chore, release-4.3.2

#2703 [DDW-694] Fix: Buttons missing in Tokens footer
  CHANGELOG.md
  source/renderer/app/components/wallet/tokens/WalletToken.js
Labels: bug, :hourglass_flowing_sand:release-vNext

#2704 Merge release/4.4.0 into develop
  CHANGELOG.md
  package.json
  source/renderer/app/components/wallet/tokens/WalletToken.js
Labels: chore, release-4.4.0

#2702 [DDW-747] Fix transaction localization
  CHANGELOG.md
  source/renderer/app/components/wallet/transactions/Transaction.js
Labels: bug, :hourglass_flowing_sand:release-vNext
