Repository input-output-hk/daedalus, pull requests merged in 2022-07, with the labels that each got.

#2962 [DDW-1076] Incorrect amount of tokens is sent
  CHANGELOG.md
  source/renderer/app/components/wallet/WalletSendForm.spec.tsx
  source/renderer/app/components/wallet/WalletSendForm.tsx
  source/renderer/app/containers/wallet/WalletSendPage.tsx
  source/renderer/app/stores/HardwareWalletsStore.ts
  source/renderer/mobx-react-form.d.ts
Labels: bug, :hourglass_flowing_sand:release-vNext

#3001 [DDW-1110] Use Vasil-supported `cardano-wallet`
  CHANGELOG.md
  default.nix
  installers/common/WindowsInstaller.hs
  nix/cardano-wallet--enable-aarch64-darwin.patch
  nix/sources.json
  source/main/environment.ts
Labels: chore, infrastructure, :hourglass_flowing_sand:release-vNext, cardano-node

#2941 [DDW-1061] Downloaded installer being left behind after wallet is updated to latest version
  CHANGELOG.md
  source/renderer/app/stores/AppUpdateStore.ts
Labels: bug, :hourglass_flowing_sand:release-vNext

#3007 [DDW-1111] Non-recommended decimal place setting alert is not displayed before 1st change of settings
  CHANGELOG.md
  source/common/types/logging.types.ts
  source/renderer/app/api/api.ts
  source/renderer/app/api/utils/localStorage.ts
  source/renderer/app/components/assets/AssetSettingsDialog.tsx
  source/renderer/app/components/wallet/tokens/wallet-token/WalletToken.tsx
  source/renderer/app/components/wallet/tokens/wallet-token/helpers.spec.ts
  source/renderer/app/components/wallet/tokens/wallet-token/helpers.ts
  source/renderer/app/containers/wallet/WalletReceivePage.tsx
  source/renderer/app/stores/HardwareWalletsStore.ts
  source/renderer/app/stores/WalletSettingsStore.ts
  source/renderer/app/stores/WalletsLocalStore.ts
  source/renderer/app/types/localDataTypes.ts
Labels: bug, :hourglass_flowing_sand:release-vNext

#3009 [DDW-1095] Update Terms of Service
  CHANGELOG.md
  source/renderer/app/i18n/locales/terms-of-use/en-US.md
  source/renderer/app/i18n/locales/terms-of-use/ja-JP.md
Labels: feature, :hourglass_flowing_sand:release-vNext

#2998 [DDW-1109] Allow specifying Node.js version; patch `electron-rebuild` forcing proper Electron-Node.js headers; fix M1 CI
  default.nix
  installers/nix/electron.nix
  nix/yarn-nix-shell.sh
  package.json
  release.nix
  scripts/postinstall.sh
  shell.nix
  yarn2nix.nix
Labels: chore, infrastructure, :hourglass_flowing_sand:release-vNext

#3010 Update `cardano-node` to 1.35.1
  default.nix
  nix/cardano-wallet--node-1.35.1.patch
  nix/sources.json
  source/main/environment.ts
Labels: chore, cardano-node

#3013 Update `cardano-node` to 1.35.1 via `cardano-wallet` PR `.patch`
  default.nix
  nix/cardano-wallet--node-1.35.1.patch
Labels: chore, cardano-node

#3012 Update `cardano-node` to 1.35.1 via `cardano-wallet` PR `.patch`
  CHANGELOG.md
  default.nix
  nix/sources.json
  source/main/environment.ts
Labels: chore, cardano-node

#3016 Add OS+architecture tuple to installer file names
  CHANGELOG.md
  default.nix
  installers/common/Types.hs
Labels: bug, infrastructure

#2952 [DDW-1034] Refactor error handling for reward only wallets
  source/renderer/app/api/api.ts
  source/renderer/app/api/errors.ts
Labels: :hourglass_flowing_sand:release-vNext

#3023 [DDW-1122] Fix `darwin-launcher.go` to replace its process image with `cardano-launcher` (binary), and not swallow `stdout`
  CHANGELOG.md
  nix/darwin-launcher.go
Labels: chore, infrastructure, :hourglass_flowing_sand:release-vNext
