Repository input-output-hk/daedalus, pull requests merged in 2022-02, with the labels that each got.

#2848 [DDW-920] Missing Japanese translations for RTS flags
  source/renderer/app/i18n/locales/ja-JP.json
Labels: WIP, release-4.8.0

#2849 [DDW-934] Available disk space takes a long time to show
  CHANGELOG.md
  source/renderer/app/stores/NetworkStatusStore.ts
Labels: bug, :hourglass_flowing_sand:release-vNext

#2824 [DDW-844] Fix Storybook knobs
  .github/pull_request_template.md
  .github/workflows/chromatic.yml
  source/renderer/app/i18n/locales/ja-JP.json
  storybook/config.tsx
  storybook/monkeyPatchDateTime.ts
  storybook/webpack.config.js
Labels: bug, :hourglass_flowing_sand:release-vNext, run Chromatic

#2862 Merge Release/4.8.0 into Develop
  .eslintrc
  CHANGELOG.md
  flow-typed/npm/jest_v27.x.x.js
  package.json
  source/common/ipc/api.ts
  source/common/ipc/constants.ts
  source/common/types/cardano-node.types.ts
  source/common/types/environment.types.ts
  source/main/cardano/CardanoNode.ts
  source/main/environment.ts
  source/main/index.ts
  source/main/ipc/get-block-replay-progress.ts
  source/main/ipc/get-block-sync-progress.ts
  source/main/ipc/toggleRTSFlagsModeChannel.ts
  source/main/menus/MenuActions.types.ts
  source/main/menus/osx.ts
  source/main/menus/submenuBuilders.ts
  source/main/menus/win-linux.ts
  source/main/utils/buildAppMenus.ts
  source/main/utils/containsRTSFlags.ts
  source/main/utils/handleCheckBlockReplayProgress.ts
  source/main/utils/rtsFlags.ts
  source/main/utils/rtsFlagsSettings.ts
  source/main/webpack.config.js
  source/main/windows/main.ts
  source/renderer/app/App.tsx
  source/renderer/app/actions/app-actions.ts
  source/renderer/app/actions/network-status-actions.ts
  source/renderer/app/actions/profile-actions.ts
  source/renderer/app/components/knownIssues/RTSFlagsRecommendationOverlay/RTSFlagsRecommendationOverlay.scss
  source/renderer/app/components/knownIssues/RTSFlagsRecommendationOverlay/RTSFlagsRecommendationOverlay.tsx
  source/renderer/app/components/knownIssues/ToggleRTSFlagsDialog/ToggleRTSFlagsDialog.scss
  source/renderer/app/components/knownIssues/ToggleRTSFlagsDialog/ToggleRTSFlagsDialog.tsx
  source/renderer/app/components/loading/syncing-connecting/SyncingConnecting.tsx
  source/renderer/app/components/loading/syncing-connecting/SyncingConnectingStatus.tsx
  source/renderer/app/components/status/DaedalusDiagnostics.tsx
  source/renderer/app/containers/knownIssues/RTSFlagsRecommendationOverlayContainer.tsx
  source/renderer/app/containers/knownIssues/ToggleRTSFlagsDialogContainer.tsx
  source/renderer/app/containers/loading/SyncingConnectingPage.tsx
  source/renderer/app/containers/status/DaedalusDiagnosticsDialog.tsx
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/ipc/getBlockReplayChannel.ts
  source/renderer/app/ipc/getBlockSyncChannel.ts
  source/renderer/app/ipc/toggleRTSFlagsModeChannel.ts
  source/renderer/app/stores/AppStore.ts
  source/renderer/app/stores/NetworkStatusStore.ts
  source/renderer/app/stores/ProfileStore.ts
  source/renderer/app/types/applicationDialogTypes.ts
  source/renderer/app/types/systemInfoTypes.ts
  source/renderer/app/utils/buildSystemInfo.ts
  source/renderer/app/utils/formatters.ts
  storybook/stories/assets/Asset.stories.tsx
  storybook/stories/navigation/Sidebar.stories.tsx
  storybook/stories/nodes/status/Diagnostics.stories.tsx
  storybook/stories/nodes/syncing/SyncingConnecting.stories.tsx
  utils/lockfile-checker/index.ts
  yarn.lock
Labels: release-4.8.0

#2850 [DDW-844] Override default font-size for all links
  source/renderer/app/themes/overrides/LinkOverrides.scss
Labels: bug

#2852 [DDW-921] Remove Discreet mode notification
  CHANGELOG.md
  source/common/config/electron-store.config.ts
  source/common/types/electron-store.types.ts
  source/main/ipc/electronStoreConversation.ts
  source/renderer/app/components/settings/menu/SecurityMenuItem.tsx
  source/renderer/app/components/settings/menu/SettingsMenu.scss
  source/renderer/app/components/settings/menu/SettingsMenu.tsx
  source/renderer/app/components/sidebar/Sidebar.tsx
  source/renderer/app/components/sidebar/SidebarCategoryWrapper.messages.ts
  source/renderer/app/components/sidebar/SidebarCategoryWrapper.scss
  source/renderer/app/components/sidebar/SidebarCategoryWrapper.tsx
  source/renderer/app/features/discreet-mode/api/index.ts
  source/renderer/app/features/discreet-mode/feature.ts
  source/renderer/app/features/discreet-mode/ui/discreet-toggle-top-bar/DiscreetToggleTopBar.tsx
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  storybook/stories/_support/DiscreetModeNotificationKnob.ts
  storybook/stories/_support/StoryProvider.tsx
Labels: feature, :hourglass_flowing_sand:release-vNext

#2841 [DDW-880] Forward data attributes to input field components
  package.json
  source/renderer/app/components/wallet/WalletSendForm.spec.tsx
  source/renderer/app/components/wallet/send-form/AssetInput.tsx
  yarn.lock
Labels: chore, :hourglass_flowing_sand:release-vNext

#2837 [DDW-592] Stake pool list consistency
  CHANGELOG.md
  source/renderer/app/components/staking/stake-pools/StakePools.tsx
Labels: feature, :hourglass_flowing_sand:release-vNext

#2867 Merge Release/4.8.0 into Develop
  source/renderer/app/containers/wallet/WalletSendPage.tsx
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/ProfileStore.ts
Labels: release-4.8.0

#2872 [DDW-968] Missing baseline screenshots for Chromatic
  .github/workflows/chromatic.yml
Labels: chore

#2871 [DDW-937] Cleanup unit tests from ts ignores
  source/renderer/app/containers/MenuUpdater/useMenuUpdater.spec.tsx
Labels: chore, :hourglass_flowing_sand:release-vNext

#2856 [DDW-675] Catalyst dynamic content
  CHANGELOG.md
  source/renderer/app/api/api.ts
  source/renderer/app/api/voting/requests/getCatalystFund.ts
  source/renderer/app/api/voting/types.ts
  source/renderer/app/components/voting/VotingNoWallets.tsx
  source/renderer/app/components/voting/VotingRegistrationDialogWizard.tsx
  source/renderer/app/components/voting/voting-info/ApiError.messages.ts
  source/renderer/app/components/voting/voting-info/ApiError.scss
  source/renderer/app/components/voting/voting-info/ApiError.tsx
  source/renderer/app/components/voting/voting-info/CurrentPhase.scss
  source/renderer/app/components/voting/voting-info/Headline.scss
  source/renderer/app/components/voting/voting-info/RegisterToVote.scss
  source/renderer/app/components/voting/voting-info/RegisterToVote.tsx
  source/renderer/app/components/voting/voting-info/ResultsPhase.tsx
  source/renderer/app/components/voting/voting-info/SnapshotPhase.tsx
  source/renderer/app/components/voting/voting-info/TallyingPhase.tsx
  source/renderer/app/components/voting/voting-info/VotingInfo.tsx
  source/renderer/app/components/voting/voting-info/VotingPhase.tsx
  source/renderer/app/components/voting/voting-info/types.ts
  source/renderer/app/components/voting/voting-registration-wizard-steps/VotingRegistrationStepsChooseWallet.tsx
  source/renderer/app/components/voting/voting-registration-wizard-steps/VotingRegistrationStepsConfirm.tsx
  source/renderer/app/components/voting/voting-registration-wizard-steps/VotingRegistrationStepsEnterPinCode.tsx
  source/renderer/app/components/voting/voting-registration-wizard-steps/VotingRegistrationStepsQrCode.tsx
  source/renderer/app/components/voting/voting-registration-wizard-steps/VotingRegistrationStepsRegister.tsx
  source/renderer/app/components/voting/voting-registration-wizard-steps/widgets/ConfirmationDialog.tsx
  source/renderer/app/components/voting/voting-registration-wizard-steps/widgets/VotingRegistrationDialog.tsx
  source/renderer/app/config/urlsConfig.ts
  source/renderer/app/config/votingConfig.ts
  source/renderer/app/containers/voting/VotingRegistrationPage.tsx
  source/renderer/app/containers/voting/dialogs/VotingRegistrationDialogContainer.tsx
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/VotingStore.spec.ts
  source/renderer/app/stores/VotingStore.ts
  storybook/stories/voting/Voting.stories.tsx
Labels: feature, :hourglass_flowing_sand:release-vNext, run Chromatic

#2863 [DDW-939] Fix Stake Pools tooltip z-index
  CHANGELOG.md
  source/renderer/app/components/layout/SidebarLayout.scss
  source/renderer/app/components/staking/layouts/StakingWithNavigation.scss
  source/renderer/app/components/staking/layouts/StakingWithNavigation.tsx
  source/renderer/app/components/staking/stake-pools/StakePoolsRanking.tsx
  source/renderer/app/components/staking/stake-pools/StakePoolsSearch.tsx
  source/renderer/app/components/staking/stake-pools/StakePoolsSearchListViewButton.tsx
  source/renderer/app/components/widgets/Slider.tsx
  source/renderer/app/i18n/locales/defaultMessages.json
Labels: bug, :hourglass_flowing_sand:release-vNext

#2881 [DDW-983][BUG] - Fix the RAM Splash Screen | Main UI overlap
  CHANGELOG.md
  source/renderer/app/components/appUpdate/AppUpdateOverlay.scss
  source/renderer/app/components/knownIssues/RTSFlagsRecommendationOverlay/RTSFlagsRecommendationOverlay.scss
  source/renderer/app/components/news/AlertsOverlay.scss
  source/renderer/app/components/news/IncidentOverlay.scss
  source/renderer/app/components/news/NewsFeed.scss
  source/renderer/app/themes/mixins/layers.scss
Labels: bug, :hourglass_flowing_sand:release-vNext, run Chromatic

#2886 [DDW-984] Fix storybook Daedalus menu (theme + language selection)
  CHANGELOG.md
  package.json
  storybook/addons.ts
  storybook/presets.ts
  storybook/ts-preset.ts
  yarn.lock
Labels: chore, :hourglass_flowing_sand:release-vNext

#2877 [DDW-964] Showing progress of all three sync types at once on loading screen
  .eslintrc
  CHANGELOG.md
  source/common/ipc/api.ts
  source/common/types/cardano-node.types.ts
  source/main/ipc/get-block-sync-progress.ts
  source/main/utils/blockSyncProgressHelpers.spec.ts
  source/main/utils/blockSyncProgressHelpers.ts
  source/main/utils/handleCheckBlockReplayProgress.ts
  source/renderer/app/assets/images/check-mark-universal.inline.svg
  source/renderer/app/assets/images/question-mark-universal.inline.svg
  source/renderer/app/assets/images/spinner-universal.inline.svg
  source/renderer/app/components/loading/syncing-connecting/SyncingConnecting.tsx
  source/renderer/app/components/loading/syncing-connecting/SyncingConnectingStatus.scss
  source/renderer/app/components/loading/syncing-connecting/SyncingConnectingStatus.tsx
  source/renderer/app/components/loading/syncing-connecting/SyncingProgress/SyncingProgress.messages.ts
  source/renderer/app/components/loading/syncing-connecting/SyncingProgress/SyncingProgress.scss
  source/renderer/app/components/loading/syncing-connecting/SyncingProgress/SyncingProgress.tsx
  source/renderer/app/components/loading/syncing-connecting/SyncingProgress/index.ts
  source/renderer/app/components/loading/syncing-connecting/SyncingProgress/utils.ts
  source/renderer/app/containers/loading/SyncingConnectingPage.tsx
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/ipc/getBlockSyncChannel.ts
  source/renderer/app/stores/NetworkStatusStore.ts
  source/renderer/app/themes/daedalus/cardano.ts
  source/renderer/app/themes/daedalus/dark-blue.ts
  source/renderer/app/themes/daedalus/dark-cardano.ts
  source/renderer/app/themes/daedalus/flight-candidate.ts
  source/renderer/app/themes/daedalus/incentivized-testnet.ts
  source/renderer/app/themes/daedalus/light-blue.ts
  source/renderer/app/themes/daedalus/shelley-testnet.ts
  source/renderer/app/themes/daedalus/white.ts
  source/renderer/app/themes/daedalus/yellow.ts
  source/renderer/app/types/i18nTypes.ts
  storybook/stories/nodes/syncing/SyncingConnecting.stories.tsx
  yarn.lock
Labels: feature, :hourglass_flowing_sand:release-vNext, run Chromatic

#2803 [DDW-614] Show unspent ADA amount in rewards table
  CHANGELOG.md
  package.json
  source/renderer/app/api/staking/types.ts
  source/renderer/app/components/staking/rewards/StakingRewards.scss
  source/renderer/app/components/staking/rewards/StakingRewards.tsx
  source/renderer/app/components/wallet/summary/WalletSummary.tsx
  source/renderer/app/components/wallet/summary/WalletSummaryCurrency.scss
  source/renderer/app/components/wallet/summary/WalletSummaryHeader.scss
  source/renderer/app/components/wallet/summary/WalletSummaryHeader.tsx
  source/renderer/app/components/wallet/summary/WalletSummaryHeaderRewards.scss
  source/renderer/app/components/wallet/summary/WalletSummaryHeaderRewards.spec.ts
  source/renderer/app/components/wallet/summary/WalletSummaryHeaderRewards.tsx
  source/renderer/app/config/stakingRewards.dummy.json
  source/renderer/app/containers/wallet/WalletSummaryPage.tsx
  source/renderer/app/features/discreet-mode/feature.ts
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/StakingStore.ts
  source/renderer/app/utils/formatters.ts
  storybook/stories/_support/utils.ts
  storybook/stories/staking/Rewards.stories.tsx
  storybook/stories/wallets/index.ts
  storybook/stories/wallets/summary/WalletSummary.stories.tsx
  storybook/stories/wallets/summary/WalletSummaryHeader.stories.tsx
  yarn.lock
Labels: feature

#2891 DDW-981 Fix incorrect design of disabled inputs
  CHANGELOG.md
  package.json
  source/renderer/app/components/staking/redeem-itn-rewards/Step1ConfigurationDialog.scss
  source/renderer/app/components/staking/redeem-itn-rewards/Step1ConfigurationDialog.tsx
  source/renderer/app/components/widgets/DialogFullSizeOverride.scss
  source/renderer/app/components/widgets/forms/ItemsDropdown.tsx
  source/renderer/app/themes/daedalus/cardano.ts
  source/renderer/app/themes/daedalus/dark-blue.ts
  source/renderer/app/themes/daedalus/dark-cardano.ts
  source/renderer/app/themes/daedalus/flight-candidate.ts
  source/renderer/app/themes/daedalus/incentivized-testnet.ts
  source/renderer/app/themes/daedalus/light-blue.ts
  source/renderer/app/themes/daedalus/shelley-testnet.ts
  source/renderer/app/themes/daedalus/white.ts
  source/renderer/app/themes/daedalus/yellow.ts
  yarn.lock
Labels: bug, :hourglass_flowing_sand:release-vNext

#2783 [DDW-827] Show helpful message when trying to empty wallet containing native tokens
  CHANGELOG.md
  source/common/types/logging.types.ts
  source/main/ipc/downloadManagerChannel.ts
  source/renderer/app/actions/lib/Action.ts
  source/renderer/app/actions/wallets-actions.ts
  source/renderer/app/api/api.ts
  source/renderer/app/api/errors.ts
  source/renderer/app/api/utils/apiHelpers.spec.ts
  source/renderer/app/api/utils/apiHelpers.ts
  source/renderer/app/components/status/DaedalusDiagnostics.tsx
  source/renderer/app/components/wallet/send-form/WalletSendAssetsConfirmationDialog.tsx
  source/renderer/app/components/wallet/send-form/WalletSendConfirmationDialog.tsx
  source/renderer/app/domains/ApiError.ts
  source/renderer/app/i18n/LocalizableError.ts
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/StakingStore.ts
  source/renderer/app/stores/WalletsStore.ts
Labels: feature, WIP, :hourglass_flowing_sand:release-vNext

#2893 [DDW-987] Debug the main process
  CHANGELOG.md
  README.md
  gulpfile.js
Labels: chore, :hourglass_flowing_sand:release-vNext
