Repository input-output-hk/daedalus, pull requests merged in 2022-09, with the labels that each got.

#3003 [DDW-809] Analytics - part 3 - detailed tracking
  CHANGELOG.md
  source/main/environment.ts
  source/renderer/app/App.tsx
  source/renderer/app/actions/wallets-actions.ts
  source/renderer/app/analytics/MatomoAnalyticsTracker.ts
  source/renderer/app/analytics/MatomoClient.ts
  source/renderer/app/analytics/NoopAnalyticsTracker.ts
  source/renderer/app/analytics/TrackedRoute.tsx
  source/renderer/app/analytics/index.ts
  source/renderer/app/analytics/types.ts
  source/renderer/app/analytics/utils/getEventNameFromWallet.ts
  source/renderer/app/api/index.ts
  source/renderer/app/components/profile/analytics/AnalyticsConsentForm.messages.ts
  source/renderer/app/components/profile/analytics/AnalyticsConsentForm.scss
  source/renderer/app/components/profile/analytics/AnalyticsConsentForm.tsx
  source/renderer/app/components/settings/categories/SupportSettings.messages.ts
  source/renderer/app/components/settings/categories/SupportSettings.tsx
  source/renderer/app/components/staking/stake-pools/StakePools.tsx
  source/renderer/app/components/wallet/WalletSendForm.spec.tsx
  source/renderer/app/components/wallet/WalletSendForm.tsx
  source/renderer/app/components/wallet/send-form/AssetInput.tsx
  source/renderer/app/components/wallet/transactions/WalletTransactionsList.tsx
  source/renderer/app/components/wallet/widgets/VerticalSeparator.tsx
  source/renderer/app/config/analyticsConfig.ts
  source/renderer/app/containers/MenuUpdater/useMenuUpdater.ts
  source/renderer/app/containers/settings/categories/SupportSettingsPage.tsx
  source/renderer/app/containers/wallet/WalletReceivePage.tsx
  source/renderer/app/containers/wallet/WalletSendPage.tsx
  source/renderer/app/containers/wallet/WalletSummaryPage.tsx
  source/renderer/app/features/discreet-mode/context.tsx
  source/renderer/app/features/discreet-mode/feature.ts
  source/renderer/app/features/discreet-mode/integration-tests.spec.tsx
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/index.tsx
  source/renderer/app/stores/AppStore.ts
  source/renderer/app/stores/AssetsStore.ts
  source/renderer/app/stores/CurrencyStore.ts
  source/renderer/app/stores/HardwareWalletsStore.ts
  source/renderer/app/stores/NetworkStatusStore.ts
  source/renderer/app/stores/ProfileStore.ts
  source/renderer/app/stores/SidebarStore.spec.ts
  source/renderer/app/stores/SidebarStore.ts
  source/renderer/app/stores/StakingStore.ts
  source/renderer/app/stores/TransactionsStore.ts
  source/renderer/app/stores/UiDialogsStore.ts
  source/renderer/app/stores/VotingStore.spec.ts
  source/renderer/app/stores/VotingStore.ts
  source/renderer/app/stores/WalletMigrationStore.ts
  source/renderer/app/stores/WalletSettingsStore.ts
  source/renderer/app/stores/WalletsStore.ts
  storybook/stories/common/Widgets.stories.tsx
  storybook/stories/wallets/send/WalletSend.stories.tsx
  translations/messages.json
Labels: feature, DO NOT MERGE, :hourglass_flowing_sand:release-vNext

#3036 [DDW-1140] Update LedgerJS to 5.1.0 version
  CHANGELOG.md
  package.json
  yarn.lock
Labels: chore

#3038 [DDW-1139] Update trezor-connect to v9
  CHANGELOG.md
  installers/common/MacInstaller.hs
  package.json
  source/common/ipc/api.ts
  source/common/types/hardware-wallets.types.ts
  source/main/ipc/getHardwareWalletChannel.ts
  source/main/trezor/connection.ts
  source/main/trezor/manifest.ts
  source/main/webpack.config.js
  yarn.lock
  yarn2nix.nix
Labels: chore, :hourglass_flowing_sand:release-vNext
