Repository input-output-hk/daedalus, pull requests merged in 2022-01, with the labels that each got.

#2726 [DDW-779] Update trezor-connect dependency to version v8.2.4
  CHANGELOG.md
  installers/common/MacInstaller.hs
  package.json
  yarn.lock
  yarn2nix.nix
Labels: chore, :hourglass_flowing_sand:release-vNext

#2799 [DDW-882] Update cardano-wallet and cardano-node
  CHANGELOG.md
  nix/sources.json
  source/main/environment.js
  source/renderer/app/components/status/DaedalusDiagnostics.js
Labels: chore, :hourglass_flowing_sand:release-vNext

#2812 [DDW-894] Update catalyst dates
  CHANGELOG.md
  source/renderer/app/config/votingConfig.js
  source/renderer/app/stores/SidebarStore.js
  yarn.lock
Labels: feature, release-4.7.0

#2776 [DDW-857][DEBT] Integrate Chromatic
  .github/workflows/chromatic.yml
  CHANGELOG.md
  package.json
  source/renderer/app/components/loading/syncing-connecting/LogosDisplay.js
  source/renderer/app/components/wallet/settings/ICOPublicKeyQRCodeDialog.js
  source/renderer/app/components/wallet/settings/ICOPublicKeyQRCodeDialog.messages.js
  source/renderer/app/containers/wallet/dialogs/settings/PublicKeyQRCodeDialogContainer.js
  source/renderer/app/i18n/locales/defaultMessages.json
  storybook/config.js
  storybook/stories/_support/utils.js
  yarn.lock
Labels: chore, :hourglass_flowing_sand:release-vNext

#2811 [DDW-893] Update the PR checklist
  .github/pull_request_template.md
Labels: chore, :hourglass_flowing_sand:release-vNext

#2813 [DDW-892] Use fresh locale while rebuilding the application menu
  CHANGELOG.md
  source/main/index.js
Labels: bug, :hourglass_flowing_sand:release-vNext

#2827 [DDW-916] Change the message for syncing the blockchain
  CHANGELOG.md
  source/renderer/app/components/loading/syncing-connecting/SyncingConnectingStatus.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: feature, :hourglass_flowing_sand:release-vNext

#2831 [DDW-916] Update second message on the initial screen to in include part regarding the waiting time
  CHANGELOG.md
  source/renderer/app/components/loading/syncing-connecting/SyncingConnectingStatus.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: feature, :hourglass_flowing_sand:release-vNext

#2758 [DDW-862] Enable dynamic RTS flags setting
  CHANGELOG.md
  source/main/cardano/CardanoNode.js
  source/main/cardano/CardanoWalletLauncher.js
  source/main/cardano/setup.js
  source/main/config.js
  source/main/index.js
  source/main/locales/en-US.json
  source/main/locales/ja-JP.json
  source/main/menus/MenuActions.types.js
  source/main/menus/osx.js
  source/main/menus/win-linux.js
  source/main/utils/buildAppMenus.js
  source/main/utils/rtsFlags.js
  source/main/utils/safeExitWithCode.js
  source/main/windows/main.js
Labels: feature, :hourglass_flowing_sand:release-vNext

#2775 [DDW-741] Implement Wallet sorting
  CHANGELOG.md
  jest.config.js
  package.json
  source/renderer/app/actions/sidebar-actions.js
  source/renderer/app/assets/images/sort-arrow.inline.svg
  source/renderer/app/components/sidebar/Sidebar.js
  source/renderer/app/components/sidebar/SidebarMenu.scss
  source/renderer/app/components/sidebar/types.js
  source/renderer/app/components/sidebar/wallets/SidebarWalletMenuItem.js
  source/renderer/app/components/sidebar/wallets/SidebarWalletMenuItem.scss
  source/renderer/app/components/sidebar/wallets/SidebarWalletsMenu.js
  source/renderer/app/components/sidebar/wallets/SidebarWalletsMenu.scss
  source/renderer/app/components/sidebar/wallets/SidebarWalletsMenu.spec.js
  source/renderer/app/components/sidebar/wallets/WalletSearch.js
  source/renderer/app/components/sidebar/wallets/WalletSearch.scss
  source/renderer/app/components/sidebar/wallets/WalletSortButton.js
  source/renderer/app/components/sidebar/wallets/WalletSortButton.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsSearch.scss
  source/renderer/app/components/wallet/tokens/wallet-tokens-search/WalletTokensSearch.js
  source/renderer/app/components/wallet/tokens/wallet-tokens-search/WalletTokensSearch.scss
  source/renderer/app/config/sidebarConfig.js
  source/renderer/app/containers/MainLayout.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/SidebarStore.js
  source/renderer/app/stores/SidebarStore.spec.js
  source/renderer/app/themes/daedalus/cardano.js
  source/renderer/app/themes/daedalus/dark-blue.js
  source/renderer/app/themes/daedalus/dark-cardano.js
  source/renderer/app/themes/daedalus/flight-candidate.js
  source/renderer/app/themes/daedalus/incentivized-testnet.js
  source/renderer/app/themes/daedalus/light-blue.js
  source/renderer/app/themes/daedalus/shelley-testnet.js
  source/renderer/app/themes/daedalus/white.js
  source/renderer/app/themes/daedalus/yellow.js
  source/renderer/app/types/sidebarTypes.js
  source/renderer/app/utils/walletSorting.js
  source/renderer/app/utils/walletSorting.spec.js
  storybook/stories/_support/StoryLayout.js
  storybook/stories/navigation/SidebarWalletsMenu.stories.js
  yarn.lock
Labels: feature, :hourglass_flowing_sand:release-vNext

#2818 [DDW-737] Unify CPU info in diagnostics dialog
  CHANGELOG.md
  source/common/types/environment.types.js
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/containers/status/DaedalusDiagnosticsDialog.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/stores/ProfileStore.js
  source/renderer/app/utils/formatCpuInfo.js
  source/renderer/app/utils/formatCpuInfo.spec.js
  source/renderer/app/utils/formatters.js
Labels: feature, :hourglass_flowing_sand:release-vNext

#2805 [DDW-870] Update the team member list
  CHANGELOG.md
  source/renderer/app/components/staking/stake-pools/StakePoolsSearch.scss
  source/renderer/app/components/static/About.js
  source/renderer/app/components/wallet/tokens/wallet-tokens-search/WalletTokensSearch.scss
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: chore, :hourglass_flowing_sand:release-vNext

#2828 [DDW-917] Fix quality checks
  .github/pull_request_template.md
  .github/workflows/chromatic.yml
  .github/workflows/linter.yml
  bors.toml
Labels: chore

#2791 [DDW-860] Implement new Send screen
  .github/workflows/run_tests_on_pr.yml
  CHANGELOG.md
  source/renderer/app/components/wallet/WalletSendForm.js
  source/renderer/app/components/wallet/WalletSendForm.scss
  source/renderer/app/components/wallet/WalletSendForm.spec.js
  source/renderer/app/components/wallet/send-form/AssetInput.js
  source/renderer/app/components/wallet/send-form/messages.js
  source/renderer/app/components/wallet/tokens/wallet-token-picker/WalletTokenPicker.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  tests/_utils/TestDecorator.js
Labels: feature, :hourglass_flowing_sand:release-vNext

#2840 [DDW-918] Update blockchain verification progress
  CHANGELOG.md
  source/common/ipc/api.js
  source/common/types/cardano-node.types.js
  source/main/index.js
  source/main/ipc/get-block-replay-progress.js
  source/main/ipc/get-block-sync-progress.js
  source/main/utils/handleCheckBlockReplayProgress.js
  source/renderer/app/components/loading/syncing-connecting/SyncingConnecting.js
  source/renderer/app/components/loading/syncing-connecting/SyncingConnectingStatus.js
  source/renderer/app/containers/loading/SyncingConnectingPage.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/ipc/getBlockReplayChannel.js
  source/renderer/app/ipc/getBlockSyncChannel.js
  source/renderer/app/stores/NetworkStatusStore.js
  storybook/stories/nodes/syncing/SyncingConnecting.stories.js
Labels: feature, :hourglass_flowing_sand:release-vNext, release-4.8.0

#2842 [DDW-920] RTS flags UI/UX improvements
  CHANGELOG.md
  source/common/ipc/api.js
  source/common/ipc/constants.js
  source/common/types/cardano-node.types.js
  source/common/types/environment.types.js
  source/main/cardano/CardanoNode.js
  source/main/config.js
  source/main/environment.js
  source/main/index.js
  source/main/ipc/toggleRTSFlagsModeChannel.js
  source/main/menus/MenuActions.types.js
  source/main/menus/osx.js
  source/main/menus/submenuBuilders.js
  source/main/menus/win-linux.js
  source/main/utils/buildAppMenus.js
  source/main/utils/containsRTSFlags.js
  source/main/utils/rtsFlags.js
  source/main/utils/rtsFlagsSettings.js
  source/main/windows/main.js
  source/renderer/app/App.js
  source/renderer/app/actions/app-actions.js
  source/renderer/app/actions/network-status-actions.js
  source/renderer/app/actions/profile-actions.js
  source/renderer/app/components/knownIssues/RTSFlagsRecommendationOverlay/RTSFlagsRecommendationOverlay.js
  source/renderer/app/components/knownIssues/RTSFlagsRecommendationOverlay/RTSFlagsRecommendationOverlay.scss
  source/renderer/app/components/knownIssues/ToggleRTSFlagsDialog/ToggleRTSFlagsDialog.js
  source/renderer/app/components/knownIssues/ToggleRTSFlagsDialog/ToggleRTSFlagsDialog.scss
  source/renderer/app/components/status/DaedalusDiagnostics.js
  source/renderer/app/containers/knownIssues/RTSFlagsRecommendationOverlayContainer.js
  source/renderer/app/containers/knownIssues/ToggleRTSFlagsDialogContainer.js
  source/renderer/app/containers/status/DaedalusDiagnosticsDialog.js
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/ipc/toggleRTSFlagsModeChannel.js
  source/renderer/app/stores/AppStore.js
  source/renderer/app/stores/NetworkStatusStore.js
  source/renderer/app/stores/ProfileStore.js
  source/renderer/app/types/applicationDialogTypes.js
  source/renderer/app/types/systemInfoTypes.js
  source/renderer/app/utils/buildSystemInfo.js
  storybook/stories/nodes/status/Diagnostics.stories.js
Labels: feature, release-4.8.0

#2845 [DDW-867] Check disk space (release ver)
  CHANGELOG.md
  package.json
  source/main/webpack.config.js
  yarn.lock
Labels: release-4.8.0

#2846 [DDW-920] Reduce the RAM threshold for RTS mode recommendation
  CHANGELOG.md
  source/main/environment.js
Labels: bug, release-4.8.0
