Repository input-output-hk/daedalus, pull requests merged in 2022-10, with the labels that each got.

#3044 [DDW-1147] Added new jp translations
  CHANGELOG.md
  source/renderer/app/i18n/locales/ja-JP.json
Labels: bug, :hourglass_flowing_sand:release-vNext

#3045 [DDW-1150] Integrate `cardano-wallet` v2022-10-06
  CHANGELOG.md
  default.nix
  nix/sources.json
Labels: chore

#3050 [DDW-1158] Remove unused Dhall code
  default.nix
  installers/README.md
  installers/Spec.hs
  installers/common/Config.hs
  installers/dhall-haskell.nix
  installers/dhall-json.nix
  installers/dhall/cluster.type
  installers/dhall/demo.dhall
  installers/dhall/installer.dhall
  installers/dhall/launcher.dhall
  installers/dhall/linux64.dhall
  installers/dhall/macos64.dhall
  installers/dhall/mainnet.dhall
  installers/dhall/os.type
  installers/dhall/shell.nix
  installers/dhall/staging.dhall
  installers/dhall/testnet.dhall
  installers/dhall/topology.dhall
  installers/dhall/win64.dhall
  installers/overlays/dhall-json.nix
  installers/overlays/dhall.nix
  installers/overlays/required.nix
  installers/stack.yaml
  lib.nix
Labels: chore, :hourglass_flowing_sand:release-vNext

#3062 [DDW-1142] Fix the locale passed to the stories
  CHANGELOG.md
  storybook/stories/common/Widgets.stories.tsx
  storybook/stories/navigation/Sidebar.stories.tsx
  storybook/stories/news/AlertsOverlay.stories.tsx
  storybook/stories/news/AppUpdateOverlay.stories.tsx
  storybook/stories/news/NewsFeed.stories.tsx
  storybook/stories/nodes/errors/Errors.stories.tsx
  storybook/stories/settings/general/General.stories.tsx
  storybook/stories/settings/language/Language.stories.tsx
  storybook/stories/staking/Staking.stories.tsx
  storybook/stories/wallets/settings/WalletRecoveryPhraseVerification.stories.tsx
  storybook/stories/wallets/settings/WalletSettings.stories.tsx
  storybook/stories/wallets/transactions/TransactionsList.stories.tsx
Labels: chore, :hourglass_flowing_sand:release-vNext

#3047 [DDW-1145] Fix for props in stories regarding Send component
  CHANGELOG.md
  storybook/stories/_support/StoryProvider.tsx
  storybook/stories/wallets/send/WalletSend.stories.tsx
Labels: chore, :hourglass_flowing_sand:release-vNext

#3070 [DDW-1165] Update configs for Preprod respin
  CHANGELOG.md
  nix/sources.json
Labels: chore, infrastructure, :hourglass_flowing_sand:release-vNext, cardano-node

#3060 [DDW-1151] Use `hydraJobs` in `flake.nix` instead of `release.nix` – Cicero instead of deprecated Hydra
  CHANGELOG.md
  README.md
  default.nix
  flake.lock
  flake.nix
  iohk-nix.json
  lib.nix
  nix/sources.json
  nix/tullia.nix
  release.nix
  shell.nix
Labels: chore, infrastructure, :hourglass_flowing_sand:release-vNext

#3063 [DDW-1143] Fix languages stories
  CHANGELOG.md
  storybook/stories/settings/language/Language.stories.tsx
Labels: chore, :hourglass_flowing_sand:release-vNext

#3071 [DDW-1167] Increased minumum free disk space from 2gb to 4gb
  CHANGELOG.md
  source/main/config.ts
Labels: chore, :hourglass_flowing_sand:release-vNext

#3064 [DDW-1152] Fix general stories
  CHANGELOG.md
  storybook/stories/settings/general/General.stories.tsx
  storybook/stories/settings/language/Language.stories.tsx
  storybook/stories/settings/utils/helpers.tsx
Labels: chore, :hourglass_flowing_sand:release-vNext
