Repository input-output-hk/daedalus, pull requests merged in 2022-03, with the labels that each got.

#2898 [DDW-982] Ensure uppercase stake pool tickers
  source/renderer/app/components/staking/_stakingConfig.scss
  source/renderer/app/components/staking/delegation-center/WalletRow.scss
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.messages.ts
  source/renderer/app/components/staking/delegation-setup-wizard/DelegationStepsChooseStakePoolDialog.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsTable.scss
  source/renderer/app/components/staking/widgets/ThumbPoolContent.scss
  source/renderer/app/components/staking/widgets/ThumbSelectedPool.scss
  source/renderer/app/components/staking/widgets/TooltipPool.scss
  source/renderer/app/components/wallet/send-form/AssetInput.scss
  source/renderer/app/config/stakingStakePools.dummy.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: bug

#2884 [DDW-957] Fix random Buildkite failures and improve CI
  .github/workflows/linter.yml
  .github/workflows/run_tests_on_pr.yml
  .github/workflows/verify_pr.yml
  default.nix
  package.json
  scripts/build-cross-windows.sh
  scripts/build-installer-nix.sh
  scripts/build-installer-unix.sh
  scripts/postinstall.sh
  scripts/utils.sh
  tests/lint.nix
  tests/shellcheck.nix
  tests/tsc.nix
  utils/lockfile-checker/index.ts
Labels: bug, :hourglass_flowing_sand:release-vNext

#2902 [DDW-936] Fixes discreet tooltip appearing behind loading overlay
  CHANGELOG.md
  source/renderer/app/components/staking/stake-pools/StakePoolsRankingLoader.scss
Labels: bug

#2901 [DDW-966] Improve RTS splash message
  CHANGELOG.md
  source/renderer/app/components/knownIssues/RTSFlagsRecommendationOverlay/RTSFlagsRecommendationOverlay.scss
  source/renderer/app/components/knownIssues/RTSFlagsRecommendationOverlay/RTSFlagsRecommendationOverlay.tsx
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  storybook/stories/news/AlertsOverlay.stories.tsx
Labels: feature, :hourglass_flowing_sand:release-vNext

#2905 [DDW-911]: Fix warning sign displayed when recommend decimals is zero
  CHANGELOG.md
  jest.config.js
  source/renderer/app/components/assets/Asset.tsx
  source/renderer/app/components/assets/AssetSettingsDialog.spec.tsx
  source/renderer/app/components/assets/AssetSettingsDialog.tsx
  source/renderer/app/components/wallet/tokens/wallet-token/WalletToken.spec.tsx
  source/renderer/app/components/wallet/tokens/wallet-token/WalletToken.tsx
  source/renderer/app/components/wallet/tokens/wallet-token/WalletTokenFooter.tsx
  source/renderer/app/components/wallet/tokens/wallet-token/WalletTokenHeader.tsx
  source/renderer/app/components/wallet/tokens/wallet-token/helpers.ts
  source/renderer/app/i18n/locales/defaultMessages.json
  storybook/stories/assets/AssetSettingsDialog.stories.tsx
  tests/_utils/TestBed.tsx
  tests/mocks/asset.ts
  tsconfig.json
Labels: bug, :hourglass_flowing_sand:release-vNext

#2907 [DDW-844] Fix redeem ITN rewards wallet dropdown / introduce disabled state to the Select component
  CHANGELOG.md
  package.json
  source/renderer/app/components/staking/redeem-itn-rewards/Step1ConfigurationDialog.scss
  source/renderer/app/components/staking/redeem-itn-rewards/Step1ConfigurationDialog.tsx
  source/renderer/app/components/wallet/WalletSendForm.scss
  source/renderer/app/components/widgets/DialogFullSizeOverride.scss
  source/renderer/app/components/widgets/forms/ItemsDropdown.tsx
  source/renderer/app/themes/daedalus/cardano.ts
  source/renderer/app/themes/daedalus/dark-blue.ts
  source/renderer/app/themes/daedalus/dark-cardano.ts
  source/renderer/app/themes/daedalus/flight-candidate.ts
  source/renderer/app/themes/daedalus/incentivized-testnet.ts
  source/renderer/app/themes/daedalus/light-blue.ts
  source/renderer/app/themes/daedalus/shelley-testnet.ts
  source/renderer/app/themes/daedalus/white.ts
  source/renderer/app/themes/daedalus/yellow.ts
  yarn.lock
Labels: bug, :hourglass_flowing_sand:release-vNext

#2918 [DDW-1007] [BUG] Fix wrong message when updating min ada required
  CHANGELOG.md
  source/renderer/app/components/wallet/WalletSendForm.spec.tsx
  source/renderer/app/components/wallet/WalletSendForm.tsx
Labels: bug, :hourglass_flowing_sand:release-vNext

#2909 [DDW-927] Restore opacity for search icon in focus
  CHANGELOG.md
  source/renderer/app/components/settings/categories/WalletsSettings.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsSearch.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsSearch.tsx
  source/renderer/app/components/wallet/tokens/wallet-tokens-search/WalletTokensSearch.scss
  source/renderer/app/components/wallet/tokens/wallet-tokens-search/WalletTokensSearch.tsx
  source/renderer/app/themes/daedalus/cardano.ts
  source/renderer/app/themes/daedalus/dark-blue.ts
  source/renderer/app/themes/daedalus/light-blue.ts
Labels: bug, :hourglass_flowing_sand:release-vNext

#2904 [DDW-942] Design ASCII display for when a token doesn't have a name
  CHANGELOG.md
  source/renderer/app/components/assets/Asset.scss
  source/renderer/app/components/assets/Asset.spec.tsx
  source/renderer/app/components/assets/Asset.tsx
  source/renderer/app/components/wallet/tokens/wallet-token/WalletTokenHeader.scss
  storybook/stories/wallets/tokens/WalletTokens.stories.tsx
Labels: feature, :hourglass_flowing_sand:release-vNext, run Chromatic

#2917 [DDW-1011] fix stake pool list view overlapping news feed
  CHANGELOG.md
  source/renderer/app/components/staking/stake-pools/StakePoolsRankingLoader.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsTable.scss
  source/renderer/app/components/widgets/BackToTopButton.scss
  source/renderer/app/containers/staking/RedeemItnRewardsContainer.tsx
  source/renderer/app/containers/static/AboutDialog.scss
  source/renderer/app/containers/status/DaedalusDiagnosticsDialog.scss
  source/renderer/app/stores/AppStore.ts
  source/renderer/app/themes/mixins/layers.scss
  source/renderer/app/themes/overrides/ModalOverrides.scss
Labels: bug, :hourglass_flowing_sand:release-vNext

#2925 [DDW-985] Missing character when copying address from PDF
  CHANGELOG.md
  source/common/assets/pdf/NotoSansMono-Regular.ttf
  source/common/assets/pdf/RobotoMono-Regular.ttf
  source/common/assets/pdf/fonts.d.ts
  source/main/ipc/generateAddressPDFChannel.ts
Labels: bug, :hourglass_flowing_sand:release-vNext

#2855 [DDW-940] Use the new faker.js npm module
  CHANGELOG.md
  package.json
  source/renderer/app/components/wallet/WalletSendForm.spec.tsx
  source/renderer/app/config/generateStakePoolFakeData.ts
  storybook/stories/_support/StoryProvider.tsx
  storybook/stories/_support/utils.ts
  storybook/webpack.config.js
  yarn.lock
Labels: chore, :hourglass_flowing_sand:release-vNext

#2922 [DDW-952] Improve UI regarding the Hardware Wallet public key export error
  CHANGELOG.md
  source/renderer/app/components/hardware-wallet/HardwareWalletStatus.scss
  source/renderer/app/components/hardware-wallet/HardwareWalletStatus.tsx
Labels: feature, :hourglass_flowing_sand:release-vNext, run Chromatic

#2940 Update expired certificates
  tls/client/ca.crt
  tls/client/client.crt
  tls/client/client.key
  tls/client/client.pem
  tls/server/ca.crt
  tls/server/server.crt
  tls/server/server.key
  tls/server/server.pem
Labels: chore
