Repository input-output-hk/daedalus, pull requests merged in 2022-04, with the labels that each got.

#2942 [DDW-1065] Added new script to start Daedalus in dev mode in Windows …
  README.md
  package.json
Labels: :hourglass_flowing_sand:release-vNext

#2946 [DDW-1068] Wrong fund title
  CHANGELOG.md
  source/renderer/app/api/api.ts
Labels: bug, :hourglass_flowing_sand:release-vNext, run Chromatic

#2924 [DDW-1012][BUG] - Stake Pool List slow
  CHANGELOG.md
  package.json
  source/renderer/app/components/staking/stake-pools/StakePoolsTable.messages.tsx
  source/renderer/app/components/staking/stake-pools/StakePoolsTable.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsTable.tsx
  source/renderer/app/components/staking/stake-pools/StakePoolsTableBody.tsx
  source/renderer/app/components/staking/stake-pools/StakePoolsTableHeader.tsx
  source/renderer/app/components/staking/stake-pools/StakePoolsTableHeaderCell.tsx
  source/renderer/app/components/staking/stake-pools/hooks/index.ts
  source/renderer/app/components/staking/stake-pools/hooks/types.ts
  source/renderer/app/components/staking/stake-pools/hooks/useCreateColumns.tsx
  source/renderer/app/components/staking/stake-pools/hooks/useSortedStakePoolList.tsx
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/types/i18nTypes.ts
  storybook/stories/staking/StakePoolsTable.stories.tsx
  yarn.lock
Labels: bug, :hourglass_flowing_sand:release-vNext

#2945 [DDW-1014]: fix stake pool search paddings
  CHANGELOG.md
  source/renderer/app/components/staking/stake-pools/StakePoolsSearch.scss
Labels: :hourglass_flowing_sand:release-vNext

#2955 [DDW-1080] Add storybook:build pre-push check
  CHANGELOG.md
  package.json
Labels: chore, :hourglass_flowing_sand:release-vNext

#2960 Fix yarn.lock after release
  yarn.lock
Labels: chore, infrastructure

#2954 [DDW-756] Fix popover overlap
  CHANGELOG.md
  README.md
  package.json
  yarn.lock
  yarn2nix.nix
Labels: bug, :hourglass_flowing_sand:release-vNext, run Chromatic

#2938 [DDW-1028] Hover tooltips for menu
  CHANGELOG.md
  source/renderer/app/components/sidebar/SidebarCategory.messages.ts
  source/renderer/app/components/sidebar/SidebarCategory.tsx
  source/renderer/app/components/widgets/NewsFeedIcon.scss
  source/renderer/app/components/widgets/NewsFeedIcon.tsx
  source/renderer/app/components/widgets/NodeSyncStatusIcon.tsx
  source/renderer/app/config/sidebarConfig.ts
  source/renderer/app/config/timingConfig.ts
  source/renderer/app/features/discreet-mode/ui/discreet-toggle-top-bar/DiscreetToggleTopBar.scss
  source/renderer/app/features/discreet-mode/ui/discreet-toggle-top-bar/DiscreetToggleTopBar.tsx
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  storybook/stories/navigation/SidebarCategory.stories.tsx
Labels: feature, :hourglass_flowing_sand:release-vNext, run Chromatic

#2920 [DDW-923] Stake pool list table view adjustments
  CHANGELOG.md
  source/renderer/app/components/staking/stake-pools/StakePoolsTable.scss
  source/renderer/app/components/staking/stake-pools/StakePoolsTable.tsx
  source/renderer/app/components/staking/stake-pools/StakePoolsTableHeader.tsx
  source/renderer/app/components/staking/stake-pools/hooks/index.ts
  source/renderer/app/components/staking/stake-pools/hooks/useInViewPort.tsx
  source/renderer/app/themes/daedalus/cardano.ts
  source/renderer/app/themes/daedalus/dark-blue.ts
  source/renderer/app/themes/daedalus/dark-cardano.ts
  source/renderer/app/themes/daedalus/flight-candidate.ts
  source/renderer/app/themes/daedalus/incentivized-testnet.ts
  source/renderer/app/themes/daedalus/light-blue.ts
  source/renderer/app/themes/daedalus/shelley-testnet.ts
  source/renderer/app/themes/daedalus/white.ts
  source/renderer/app/themes/daedalus/yellow.ts
Labels: bug, :hourglass_flowing_sand:release-vNext, run Chromatic

#2900 [DDW-722] Hardware wallet Ledger Nano S - Windows pairing issue
  .eslintrc
  .prettierignore
  CHANGELOG.md
  hardware-wallet-tests/cardano-app-already-launched.ts
  hardware-wallet-tests/cardano-app-not-started.ts
  hardware-wallet-tests/connect-multiple-hardware-wallets.ts
  hardware-wallet-tests/disconnect-multiple-hardware-wallets.ts
  hardware-wallet-tests/disconnect-single-hardware-wallet.ts
  hardware-wallet-tests/index.ts
  hardware-wallet-tests/utils.ts
  installers/common/MacInstaller.hs
  nix/windows-usb-libs.zip
  package.json
  shell.nix
  source/common/ipc/api.ts
  source/common/ipc/lib/IpcChannel.ts
  source/common/types/hardware-wallets.types.ts
  source/main/ipc/createHardwareWalletIPCChannels.ts
  source/main/ipc/getHardwareWalletChannel.ts
  source/main/ipc/hardwareWallets/ledger/deviceDetection/deviceDetection.ts
  source/main/ipc/hardwareWallets/ledger/deviceDetection/deviceTracker.ts
  source/main/ipc/hardwareWallets/ledger/deviceDetection/eventDrivenDetection.ts
  source/main/ipc/hardwareWallets/ledger/deviceDetection/index.ts
  source/main/ipc/hardwareWallets/ledger/deviceDetection/pollingDrivenDetection.ts
  source/main/ipc/hardwareWallets/ledger/deviceDetection/types.ts
  source/main/ipc/index.ts
  source/renderer/app/api/utils/localStorage.ts
  source/renderer/app/containers/wallet/WalletAddPage.tsx
  source/renderer/app/containers/wallet/WalletReceivePage.tsx
  source/renderer/app/ipc/getHardwareWalletChannel.ts
  source/renderer/app/stores/HardwareWalletsStore.address-verification.uml
  source/renderer/app/stores/HardwareWalletsStore.transaction.uml
  source/renderer/app/stores/HardwareWalletsStore.ts
  source/renderer/app/stores/HardwareWalletsStore.wallet-pairing.uml
  utils/lockfile-checker/index.ts
  yarn.lock
  yarn2nix.nix
Labels: bug, DO NOT MERGE, :hourglass_flowing_sand:release-vNext

#2967 [DDW-1088] Fix no progress shown on loading screen on Windows
  CHANGELOG.md
  source/common/ipc/api.ts
  source/common/types/cardano-node.types.ts
  source/main/utils/handleCheckBlockReplayProgress.ts
  source/renderer/app/components/loading/syncing-connecting/SyncingProgress/SyncingProgress.tsx
  source/renderer/app/stores/NetworkStatusStore.ts
  storybook/stories/nodes/syncing/SyncingConnecting.stories.tsx
Labels: bug, :hourglass_flowing_sand:release-vNext

#2965 [DDW-783] Fixed dialogs being closed after receiving address shared
  CHANGELOG.md
  source/renderer/app/containers/wallet/WalletReceivePage.tsx
Labels: :hourglass_flowing_sand:release-vNext

#2839 [DDW-895] Solving ipv6 Issues by updating cardano-launcher
  CHANGELOG.md
  package.json
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext
