Repository input-output-hk/daedalus, pull requests merged in 2022-08, with the labels that each got.

#3021 [DDW-1121] Update `cardano-node` to 1.35.2
  CHANGELOG.md
  default.nix
  nix/cardano-wallet--pr-3382--ledger-bug.patch
  nix/sources.json
  source/main/environment.ts
Labels: chore, :hourglass_flowing_sand:release-vNext, cardano-node

#2979 [DDW-409] New mnemonic input
  CHANGELOG.md
  source/renderer/app/components/staking/redeem-itn-rewards/Step1ConfigurationDialog.scss
  source/renderer/app/components/staking/redeem-itn-rewards/Step1ConfigurationDialog.tsx
  source/renderer/app/components/wallet/WalletBackupDialog.tsx
  source/renderer/app/components/wallet/WalletRestoreDialog.tsx
  source/renderer/app/components/wallet/backup-recovery/WalletRecoveryPhraseDisplayDialog.tsx
  source/renderer/app/components/wallet/backup-recovery/WalletRecoveryPhraseEntryDialog.tsx
  source/renderer/app/components/wallet/mnemonic-input/MnemonicAutocompleteContainer.tsx
  source/renderer/app/components/wallet/mnemonic-input/MnemonicAutocompleteLayout.scss
  source/renderer/app/components/wallet/mnemonic-input/MnemonicAutocompleteLayout.tsx
  source/renderer/app/components/wallet/mnemonic-input/MnemonicInput.scss
  source/renderer/app/components/wallet/mnemonic-input/MnemonicInput.tsx
  source/renderer/app/components/wallet/mnemonic-input/constants.ts
  source/renderer/app/components/wallet/mnemonic-input/index.ts
  source/renderer/app/components/wallet/paper-wallet-certificate/VerificationDialog.scss
  source/renderer/app/components/wallet/paper-wallet-certificate/VerificationDialog.tsx
  source/renderer/app/components/wallet/settings/WalletRecoveryPhraseStep2Dialog.tsx
  source/renderer/app/components/wallet/wallet-restore/MnemonicsDialog.tsx
  source/renderer/app/components/widgets/forms/MnemonicInputWidget.scss
  source/renderer/app/components/widgets/forms/MnemonicInputWidget.tsx
  source/renderer/app/components/widgets/forms/PinCode.tsx
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/utils/validations.ts
  source/renderer/mobx-react-form.d.ts
  storybook/stories/common/Widgets.stories.tsx
  translations/messages.json
Labels: feature, :hourglass_flowing_sand:release-vNext

#3030 [DDW-1130] Fix blank screen when opening ITN rewards
  CHANGELOG.md
  source/renderer/app/components/staking/redeem-itn-rewards/Step1ConfigurationDialog.tsx
  source/renderer/app/components/widgets/DialogFullSizeOverride.scss
Labels: bug, :hourglass_flowing_sand:release-vNext, run Chromatic

#3031 [DDW-1134] Fix Catalyst registration with hardware wallets
  source/renderer/app/containers/voting/dialogs/VotingRegistrationDialogContainer.tsx
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/VotingStore.ts
  source/renderer/app/utils/votingPDFGenerator.ts
Labels: bug, :hourglass_flowing_sand:release-vNext
