Repository input-output-hk/daedalus, pull requests merged in 2022-05, with the labels that each got.

#2956 [DDW-723] Refactor to remove duplicated code
  CHANGELOG.md
  source/renderer/app/components/sidebar/SidebarCategoryNetworkInfo.tsx
  source/renderer/app/components/wallet/WalletSendForm.tsx
  source/renderer/app/components/wallet/send-form/AssetInput.tsx
  source/renderer/app/components/wallet/send-form/WalletSendAssetsConfirmationDialog.messages.ts
  source/renderer/app/components/wallet/send-form/WalletSendAssetsConfirmationDialog.tsx
  source/renderer/app/components/wallet/send-form/WalletSendConfirmationDialog.messages.ts
  source/renderer/app/components/wallet/send-form/WalletSendConfirmationDialog.tsx
  source/renderer/app/components/wallet/send-form/helpers.ts
  source/renderer/app/components/widgets/WalletTestEnvironmentLabel.tsx
  source/renderer/app/config/walletsConfig.ts
  source/renderer/app/containers/appUpdate/AppUpdateContainer.tsx
  source/renderer/app/containers/settings/Settings.tsx
  source/renderer/app/containers/wallet/WalletSendPage.tsx
  source/renderer/app/containers/wallet/dialogs/WalletSendConfirmationDialogContainer.tsx
  source/renderer/app/containers/wallet/dialogs/send-confirmation/DialogContentWithAssets.scss
  source/renderer/app/containers/wallet/dialogs/send-confirmation/DialogContentWithAssets.tsx
  source/renderer/app/containers/wallet/dialogs/send-confirmation/DialogContentWithoutAssets.scss
  source/renderer/app/containers/wallet/dialogs/send-confirmation/DialogContentWithoutAssets.tsx
  source/renderer/app/containers/wallet/dialogs/send-confirmation/Error.tsx
  source/renderer/app/containers/wallet/dialogs/send-confirmation/PasswordInput.tsx
  source/renderer/app/containers/wallet/dialogs/send-confirmation/SendConfirmation.container.tsx
  source/renderer/app/containers/wallet/dialogs/send-confirmation/SendConfirmation.view.tsx
  source/renderer/app/containers/wallet/dialogs/send-confirmation/helpers.ts
  source/renderer/app/containers/wallet/dialogs/send-confirmation/hooks.ts
  source/renderer/app/containers/wallet/dialogs/send-confirmation/messages.ts
  source/renderer/app/containers/wallet/dialogs/send-confirmation/styles.scss
  source/renderer/app/containers/wallet/dialogs/send-confirmation/types.ts
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/NetworkStatusStore.ts
  source/renderer/declaration.d.ts
  storybook/stories/wallets/send/WalletSend.stories.tsx
Labels: chore, :hourglass_flowing_sand:release-vNext, run Chromatic

#2951 [DDW-1082] Bump cardano-wallet to master and cardano-node to 1.34.1
  CHANGELOG.md
  default.nix
  installers/common/WindowsInstaller.hs
  nix/cardano-bridge.nix
  nix/launcher-config.nix
  nix/sources.json
  source/main/environment.ts
  source/renderer/app/api/api.ts
  source/renderer/app/api/transactions/requests/selectCoins.ts
  source/renderer/app/api/transactions/types.ts
  source/renderer/app/api/wallets/types.ts
  source/renderer/app/domains/Wallet.ts
Labels: chore, infrastructure, cardano-node

#2977 [release-4.10.0] Sign remaining macOS binaries
  installers/common/MacInstaller.hs
Labels: bug, chore, infrastructure

#2860 [DDW-926] Improve error handling for incorrect passphrase / incorrect hardware wallet device
  CHANGELOG.md
  gulpfile.js
  source/main/ipc/getHardwareWalletChannel.ts
  source/main/trezor/connection.ts
  source/main/trezor/manifest.ts
  source/main/utils/buildTrezorDeviceParams.ts
  source/renderer/app/components/hardware-wallet/HardwareWalletStatus.scss
  source/renderer/app/components/hardware-wallet/HardwareWalletStatus.tsx
  source/renderer/app/domains/Wallet.ts
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/HardwareWalletsStore.ts
  yarn.lock
Labels: bug, :hourglass_flowing_sand:release-vNext, run Chromatic

#2975 [DDW-1092] Support for Ledger Nano S Plus
  CHANGELOG.md
  hardware-wallet-tests/connect-multiple-hardware-wallets.ts
  hardware-wallet-tests/disconnect-multiple-hardware-wallets.ts
  package.json
  source/common/types/hardware-wallets.types.ts
  source/main/ipc/getHardwareWalletChannel.ts
  source/main/ipc/hardwareWallets/ledger/deviceDetection/deviceDetection.ts
  source/main/ipc/hardwareWallets/ledger/deviceDetection/deviceTracker.ts
  source/main/ipc/hardwareWallets/ledger/deviceDetection/types.ts
  source/renderer/app/assets/images/hardware-wallet/ledgerSP-cropped.inline.svg
  source/renderer/app/components/wallet/WalletConnectDialog.scss
  source/renderer/app/components/wallet/WalletConnectDialog.tsx
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/HardwareWalletsStore.ts
  yarn.lock
Labels: :hourglass_flowing_sand:release-vNext

#2966 [DDW-1086] Fix phrasing of insufficient funds for tokens message
  CHANGELOG.md
  source/renderer/app/api/api.ts
  source/renderer/app/api/errors.ts
  source/renderer/app/api/utils/apiHelpers.spec.ts
  source/renderer/app/api/utils/apiHelpers.ts
  source/renderer/app/containers/wallet/dialogs/send-confirmation/helpers.spec.ts
  source/renderer/app/containers/wallet/dialogs/send-confirmation/helpers.ts
  source/renderer/app/containers/wallet/dialogs/send-confirmation/hooks.ts
  source/renderer/app/containers/wallet/dialogs/send-confirmation/types.ts
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
Labels: bug, :hourglass_flowing_sand:release-vNext, run Chromatic

#2939 [DDW-1062] Showcase filtering `Daedalus.json` logs with `jq`
  .gitignore
  CHANGELOG.md
  scripts/filter-logs.sh
Labels: WIP, infrastructure

#2971 [DDW-1081] Publish selfnode installers for all 3 platforms
  CHANGELOG.md
  README.md
  default.nix
  installer-clusters.cfg
  installers/common/MacInstaller.hs
  installers/common/WindowsInstaller.hs
  nix/cardano-bridge.nix
  package.json
  source/main/cardano/CardanoNode.ts
  source/main/cardano/CardanoSelfnodeLauncher.ts
  source/main/utils/processes.ts
  source/renderer/app/containers/knownIssues/RTSFlagsRecommendationOverlayContainer.tsx
Labels: chore, infrastructure

#2948 [DDW-1069] Add linking steps to external packages in readme
  .gitignore
  CHANGELOG.md
  README.md
Labels: chore

#2990 Update README.md with new nix.conf setup
  README.md
Labels: chore

#2906 [DDW-970] Prevent creation of new wallet during address verification
  .eslintrc
  CHANGELOG.md
  source/renderer/app/domains/Wallet.ts
  source/renderer/app/stores/HardwareWalletsStore.ts
Labels: bug, :hourglass_flowing_sand:release-vNext

#2684 [DDW-745] Daedalus aarch64 (a.k.a M1) native support
  .buildkite/pipeline.yml
  CHANGELOG.md
  README.md
  default.nix
  installers/Installer.hs
  installers/Spec.hs
  installers/common/MacInstaller.hs
  installers/common/WindowsInstaller.hs
  installers/daedalus-installer.nix
  installers/nix/electron.nix
  installers/overlays/add-test-stubs.nix
  installers/overlays/github.nix
  installers/overlays/required.nix
  nix/cardano-bridge.nix
  nix/launcher-config.nix
  nix/sources.json
  package.json
  release.nix
  scripts/build-installer-unix.sh
  scripts/build-installer-unix.sh--nix-2.5
  shell.nix
  yarn.lock
  yarn2nix.nix
Labels: feature, :hourglass_flowing_sand:release-vNext
