Repository input-output-hk/daedalus, pull requests merged in 2023-06, with the labels that each got.

#3124 [DDW-1213] Upgrade Electron to 24.2, and Node.js to 18.×
  CHANGELOG.md
  installers/common/WindowsInstaller.hs
  nix/any-darwin.nix
  nix/libsystemd--device-monitor.patch
  nix/new-common.nix
  nix/old-default.nix
  nix/windows-usb-libs.zip
  nix/x86_64-linux.nix
  nix/x86_64-windows.nix
  package.json
  scripts/rebuild-native-modules.sh
  source/main/cardano/CardanoNode.ts
  source/main/cardano/CardanoSelfnodeLauncher.ts
  source/main/config.ts
  source/main/index.ts
  source/main/windows/main.ts
  source/renderer/app/api/index.ts
  yarn.lock
Labels: chore, :hourglass_flowing_sand:release-vNext

#3126 [DDW-1221] Remove Chromatic from project
  .github/pull_request_template.md
  .github/workflows/chromatic.yml
  CHANGELOG.md
  package.json
  source/renderer/app/components/loading/syncing-connecting/LogosDisplay.tsx
  storybook/monkeyPatchDateTime.ts
  storybook/stories/settings/general/General.stories.tsx
Labels: chore

#3092 ❤️ Add members of Cardano Wallet team to the "About Daedalus" screen.
  CHANGELOG.md
  source/renderer/app/components/static/About.tsx
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  translations/messages.json
Labels: chore, :hourglass_flowing_sand:release-vNext

#3127 [DDW-1211] Update @trezor/connect to v9.0.8
  CHANGELOG.md
  installers/common/MacInstaller.hs
  nix/x86_64-linux.nix
  nix/x86_64-windows.nix
  package.json
  source/main/trezor/connection.ts
  source/renderer/app/utils/shelleyTrezor.ts
  yarn.lock
Labels: chore

#3129 [DDW-1216] Use new Catalyst API
  CHANGELOG.md
  source/renderer/app/api/voting/requests/getCatalystFund.ts
  source/renderer/app/config/urlsConfig.ts
Labels: feature, :hourglass_flowing_sand:release-vNext

#3131 [DDW-1217] Change voting registration reward address to a payment address
  CHANGELOG.md
  source/renderer/app/api/transactions/types.ts
  source/renderer/app/stores/HardwareWalletsStore.ts
  source/renderer/app/stores/VotingStore.ts
  source/renderer/app/utils/shelleyLedger.ts
  source/renderer/app/utils/shelleyTrezor.ts
Labels: chore, :hourglass_flowing_sand:release-vNext

#3105 [DDW-1186] Shows 'To be defined' if date of the next fund is in the past
  CHANGELOG.md
  source/common/types/environment.types.ts
  source/main/environment.ts
  source/renderer/app/api/voting/requests/getCatalystFund.ts
  source/renderer/app/components/voting/voting-info/RegisterToVote.messages.ts
  source/renderer/app/components/voting/voting-info/RegisterToVote.tsx
  source/renderer/app/config/urlsConfig.ts
  source/renderer/app/containers/voting/VotingRegistrationPage.tsx
  source/renderer/app/i18n/locales/defaultMessages.json
  source/renderer/app/i18n/locales/en-US.json
  source/renderer/app/i18n/locales/ja-JP.json
  source/renderer/app/stores/SidebarStore.ts
  source/renderer/app/utils/PersistentTimeMachine.ts
  source/renderer/app/utils/index.ts
  translations/messages.json
Labels: feature, :hourglass_flowing_sand:release-vNext
