Repository input-output-hk/daedalus, pull requests merged in 2023-01, with the labels that each got.

#3091 [DDW-1174] Add custom dimension to track legacy and hardware wallets
  CHANGELOG.md
  source/renderer/app/analytics/MatomoAnalyticsTracker.ts
  source/renderer/app/analytics/MatomoClient.ts
  source/renderer/app/analytics/getCustomDimensions.ts
  source/renderer/app/config/analyticsConfig.ts
  source/renderer/app/index.tsx
Labels: feature, :hourglass_flowing_sand:release-vNext

#3082 [DDW-1169] Update `cardano-node` to 1.35.4 for the Preview network respin
  CHANGELOG.md
  nix/sources.json
  source/main/environment.ts
  source/renderer/app/api/api.ts
Labels: chore, DO NOT MERGE, :hourglass_flowing_sand:release-vNext

#3074 Create CODE-OF-CONDUCT.md
  CODE-OF-CONDUCT.md
Labels: chore, :hourglass_flowing_sand:release-vNext

#3094 [DDW-1180] Trigger Darwin builds manually
  .buildkite/pipeline.yml
Labels: chore, infrastructure, :hourglass_flowing_sand:release-vNext
