Repository input-output-hk/daedalus, pull requests merged in 2024-08, with the labels that each got.

#3215 [LW-10808] Update HW dependencies
  .github/workflows/verify_pr.yml
  Brewfile.netlify
  CHANGELOG.md
  installers/common/MacInstaller.hs
  netlify.toml
  nix/devshells.nix
  nix/internal/any-darwin.nix
  nix/internal/x86_64-linux.nix
  nix/internal/x86_64-windows.nix
  package.json
  scripts/darwin-no-x-compile.sh
  scripts/rebuild-native-modules.sh
  source/main/trezor/connection.ts
  source/main/utils/config.ts
  source/renderer/app/components/loading/syncing-connecting/SyncingConnectingStatus.tsx
  source/renderer/app/components/notifications/LegacyNotification.tsx
  source/renderer/app/utils/shelleyLedger.ts
  yarn.lock
Labels: chore, dependencies

#3207 [LW-10649] Fix installing & running with strict AppArmor
  CHANGELOG.md
  flake.lock
  flake.nix
  installers/nix/linux.nix
  installers/nix/nix-installer.nix
  nix/devshells.nix
  nix/internal/common.nix
  nix/internal/glibc-electron-loader.patch
  nix/internal/launcher-config.nix
  nix/internal/linux-self-extracting-archive.sh
  nix/internal/x86_64-linux.nix
  source/main/cardano/setup.ts
  source/main/index.ts
  source/main/ipc/manageAppUpdateChannel.ts
  source/main/utils/buildAppMenus.ts
Labels: chore, :hourglass_flowing_sand:release-vNext

#3212 [LW-10808] Update cardano-node to 9.1.0
  CHANGELOG.md
  flake.lock
  flake.nix
  installers/common/MacInstaller.hs
  installers/common/WindowsInstaller.hs
  nix/internal/launcher-config.nix
Labels: chore, :hourglass_flowing_sand:release-vNext, cardano-node

#3218 Merge `main` with 6.0.0 into `develop`
  CHANGELOG.md
  installers/common/MacInstaller.hs
  nix/internal/x86_64-linux.nix
  nix/internal/x86_64-windows.nix
  package.json
Labels: chore

#3219 [LW-10649] Unset `LD_LIBRARY_PATH` on Linux
  CHANGELOG.md
  nix/internal/x86_64-linux.nix
Labels: chore, :hourglass_flowing_sand:release-vNext
